changed save buttons from `tertiary` to `primary`
keycloak/keycloak-admin-ui pull request #1000
Opened 2021-08-12 09:15 UTC by edewit

fixes: #959

2021-08-12 09:24 UTC, jonkoops approved these changes

2021-08-12 09:29 UTC, agagancarczyk approved these changes

2021-08-12 12:47 UTC, mfrances17 approved these changes
LGTM

2021-08-16 08:08 UTC, yih-wang requested changes
The issue is requested to change to the secondary style, not primary. 

![image](https://user-images.githubusercontent.com/23331885/129531958-a95ecedf-7c2e-40aa-adf4-0c6e8b6fa26e.png)

2021-08-16 09:19 UTC, yih-wang approved these changes
LGTM!

2021-08-16 09:22 UTC, merged