made realm name editable
keycloak/keycloak-admin-ui pull request #1001
Opened 2021-08-12 14:53 UTC by edewit

fixes: #941

2021-08-16 09:42 UTC, jonkoops commented on src/context/realm-context/RealmContext.tsx
> +          await adminClient.keycloak?.updateToken(Number.MAX_VALUE);
That's interesting :thinking:

2021-08-16 12:16 UTC, jonkoops requested changes

2021-08-16 12:16 UTC, jonkoops commented on src/realm-settings/RealmSettingsSection.tsx
> +                  <KeysListTab realmComponents={realmComponents!} />
If the aforementioned statement is changed there is no need to use a non-null assertion here.
```suggestion
                  <KeysListTab realmComponents={realmComponents} />
```

2021-08-16 12:16 UTC, jonkoops commented on src/realm-settings/RealmSettingsSection.tsx
> +                    realmComponents={realmComponents!}
If the aforementioned statement is changed there is no need to use a non-null assertion here.
```suggestion
                    realmComponents={realmComponents}
```

2021-08-16 12:16 UTC, jonkoops commented on src/realm-settings/RealmSettingsSection.tsx
> +                realm={realm!}
If the aforementioned statement is changed there is no need to use a non-null assertion here.
```suggestion
                realm={realm}
```

2021-08-16 12:16 UTC, jonkoops commented on src/realm-settings/RealmSettingsSection.tsx
> +                realm={realm!}
If the aforementioned statement is changed there is no need to use a non-null assertion here.
```suggestion
                realm={realm}
```

2021-08-16 12:16 UTC, jonkoops commented on src/realm-settings/TokensTab.tsx
> +  const control = form.control;
You can use destructuring to shorten this statement. In fact we might actually want to create an ESLint rule for this (that's for another time).

```suggestion
  const { control } = form;
```

2021-08-17 06:49 UTC, edewit commented on src/context/realm-context/RealmContext.tsx
> +          await adminClient.keycloak?.updateToken(Number.MAX_VALUE);
The token contains realm and access information if we don't refresh it after a realm has been created you get errors

2021-08-17 08:51 UTC, jonkoops approved these changes

2021-08-17 13:20 UTC, ssilvert commented
13 Realm Settings tests are failing.  I'm re-running the tests but that probably won't fix the problem.

2021-08-17 13:32 UTC, jonkoops commented
@stianst This is a known issue, looks like some of the review suggestions have broken the tests.

2021-08-18 13:33 UTC, edewit commented
@ssilvert I thought I fixed it yesterday, but guess it's not enough I'll have another look

2021-08-18 16:45 UTC, jenny-s51 commented on src/realm-settings/TokensTab.tsx
> -    Object.entries(realm).map((entry) => {
This was needed here in order to populate the last four fields of the form

2021-08-18 16:47 UTC, jenny-s51 reviewed
Looks and works great @edewit! However removing the `setupForm` from the TokensTab causes the last four fields of the tokens settings to not be populated with the data from the server

2021-08-18 20:49 UTC, mfrances17 approved these changes
LGTM - code looks fine, and testing worked as expected

2021-08-19 06:12 UTC, edewit commented on src/realm-settings/TokensTab.tsx
> -    Object.entries(realm).map((entry) => {
I moved it to the `RealmSettingsSection.tsx`

2021-08-20 15:27 UTC, jonkoops commented
@edewit Looks like the tests are still failing? I've ran it a couple of times, but always seems to fail.

2021-08-21 06:30 UTC, edewit commented
yes it seems that it doesn't save the `IdP account email verification` token is not saved, but it's also broken on master

2021-08-23 18:34 UTC, jenny-s51 approved these changes
Looks great!

2021-08-23 19:00 UTC, jonkoops approved these changes

2021-08-23 19:00 UTC, merged