initial version of config settings for executions
keycloak/keycloak-admin-ui pull request #1015
Opened 2021-08-17 13:40 UTC by edewit

still needs to render different controls based on the types

## Verification Steps
Go to authentication section click on one of the flows some executions can have settings indicated by a cog wheel on the right side
clicking it will open a modal dialog to add the settings or clear / update existing onces.

TODO is rendering different inputs based on the type of the field
The fields are dynamic based off a backend call

2021-08-20 16:11 UTC, jonkoops requested changes
Still need to look at more of the code but here is a preliminary review.

2021-08-20 16:11 UTC, jonkoops commented on src/authentication/components/ExecutionConfigModal.tsx
> +      }
You can probably use a ternary here.
```suggestion
      const config = execution.authenticationConfig
        ? await adminClient.authenticationManagement.getConfig({
            id: execution.authenticationConfig,
          })
        : undefined;
```

2021-08-20 16:11 UTC, jonkoops commented on src/authentication/components/ExecutionConfigModal.tsx
> +  });
This effect has no dependencies, which means it will run after each render. Is that the intended behavior?

2021-08-20 16:11 UTC, jonkoops commented on src/authentication/components/ExecutionConfigModal.tsx
> +    configDescription.properties.map(
This `map()` operation does not actually get assigned to anything, perhaps you meant to do a `forEach()`?
```suggestion
    configDescription.properties.forEach(
```

2021-08-20 16:11 UTC, jonkoops commented on src/authentication/components/ExecutionConfigModal.tsx
> +          config?.config?.[property.name!] || property.defaultValue || ""
Note that this will use values that are empty strings from the config. If you want to explicitly check if it is a nullish value then the [nullish coalescing operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator) might be a better option.
```suggestion
          config?.config?.[property.name!] ?? property.defaultValue ?? ""
```

2021-08-20 16:11 UTC, jonkoops commented on src/authentication/components/ExecutionConfigModal.tsx
> +  const { register, errors, setValue, handleSubmit } = useForm();
You can provide a generic type here to make the fields inside this form strictly typed.
```suggestion
  const { register, errors, setValue, handleSubmit } = useForm<MyFormFields>();
```

2021-08-20 16:11 UTC, jonkoops commented on src/authentication/components/ExecutionConfigModal.tsx
> +    if (configDescription) setupForm(configDescription, config), [open];
There seems to be an array literal here that doesn't do anything, I think it can be removed.
```suggestion
    if (configDescription) setupForm(configDescription, config);
```

2021-08-20 16:27 UTC, edewit commented on src/authentication/components/ExecutionConfigModal.tsx
> +      }
I don't think this is better

2021-08-20 16:45 UTC, edewit commented on src/authentication/components/ExecutionConfigModal.tsx
> +  });
oops... that seems like a weird little refactor error

2021-08-20 16:49 UTC, edewit commented on src/authentication/components/ExecutionConfigModal.tsx
> +          config?.config?.[property.name!] || property.defaultValue || ""
do we really care about the difference between ?? and ||

2021-08-20 16:49 UTC, edewit commented on src/authentication/components/ExecutionConfigModal.tsx
> +    if (configDescription) setupForm(configDescription, config), [open];
it's the useEffect dependency I fixed it

2021-08-24 10:37 UTC, jonkoops commented on src/authentication/components/ExecutionConfigModal.tsx
> +      }
I guess it's a matter of opinion, I prefer the ternary because it allows us to use a constant and because the type can be inferred automatically.

2021-08-24 11:05 UTC, edewit commented on src/authentication/components/ExecutionConfigModal.tsx
> +      }
Yes that is true, but I feel it's a lot more difficult to read

2021-08-25 08:42 UTC, jonkoops commented on src/authentication/components/ExecutionConfigModal.tsx
> +      }
I think that's valid, let's consider this resolved :ok_hand:

2021-08-25 08:43 UTC, jonkoops commented on src/authentication/components/ExecutionConfigModal.tsx
> +          config?.config?.[property.name!] || property.defaultValue || ""
Depends if you want to allow empty strings here (if they are values that could occur).

2021-08-25 08:53 UTC, jonkoops approved these changes

2021-08-25 08:53 UTC, jonkoops commented on src/authentication/components/FlowHeader.tsx
> +            <DataListCell key="config"></DataListCell>,
This cell `DataListCell` doesn't need to have text like the others?

2021-08-25 13:35 UTC, edewit commented on src/authentication/components/FlowHeader.tsx
> +            <DataListCell key="config"></DataListCell>,
No it doesn't have a label according to the design it only contains icons buttons

2021-08-25 13:36 UTC, merged