changed to append to url, for client role details
keycloak/keycloak-admin-ui pull request #1048
Opened 2021-08-24 06:02 UTC by edewit

fixes: #1041

2021-08-24 10:43 UTC, jonkoops requested changes

2021-08-24 10:43 UTC, jonkoops commented on src/realm-roles/routes/RealmRole.ts
> +    pathname: `${url}/${params.id}/details`,
This is only true if you are navigating from a route which is already on the correct path. If this function is called in any other location the result will be an invalid URL.

2021-08-24 10:59 UTC, edewit commented on src/realm-roles/routes/RealmRole.ts
> +    pathname: `${url}/${params.id}/details`,
To be honest I don't know what the correct way is to solve it but this function should append `${id}/details` as it is also used in client details just going to realm roles is wrong

2021-08-25 13:22 UTC, jonkoops commented on src/realm-roles/routes/RealmRole.ts
> +    pathname: `${url}/${params.id}/details`,
@edewit Let's merge this for now, can you create an issue to resolve this?

2021-08-25 13:22 UTC, jonkoops approved these changes

2021-08-25 13:22 UTC, merged