fixed flow name
keycloak/keycloak-admin-ui pull request #1049
Opened 2021-08-24 06:53 UTC by edewit

fixes: #1045

2021-08-24 10:41 UTC, jonkoops requested changes

2021-08-24 10:41 UTC, jonkoops commented on src/authentication/DuplicateFlowModal.tsx
> +        ).find((flow) => flow.alias === form.alias)!;
We should not be using the non-null assertion operator here as the result from a `find()` operation could possibly be `undefined`.
```suggestion
        ).find((flow) => flow.alias === form.alias);
```

2021-08-24 11:02 UTC, edewit commented on src/authentication/DuplicateFlowModal.tsx
> +        ).find((flow) => flow.alias === form.alias)!;
how can it not be found as it's just been created 1 line above

2021-08-24 12:34 UTC, jonkoops commented on src/authentication/DuplicateFlowModal.tsx
> +        ).find((flow) => flow.alias === form.alias)!;
Of course, but there are no guarantees.

2021-08-24 12:34 UTC, jonkoops approved these changes
Looks good enough :+1:

2021-08-25 12:33 UTC, ssilvert approved these changes
Tested and it's working now.  Approved.

2021-08-25 12:33 UTC, merged