Identity Providers(SAML): Adds data table for SAML mappers
keycloak/keycloak-admin-ui pull request #1058
Opened 2021-08-24 19:02 UTC by jenny-s51

## Motivation

https://issues.redhat.com/browse/CLUX-223

## Brief Description

Adds data table for mappers of SAML Identity Providers

## Verification Steps

1. In the old console, go to Identity Providers -> Add Provider -> SAML v2.0
2. Save the new provider and scroll up to the Mappers tab.
3. Click the mappers tab and create a few mappers with different names and mapper types.
4. Now in the new console, go to Identity Providers and click on the SAML provider you created.
5. Click the Mappers tab and verify the data matches the table in the old console 

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

## Additional Notes

2021-08-25 15:27 UTC, jonkoops commented on src/identity-providers/add/DetailSettings.tsx
> +    },
Since this is an arrow function you can return the value implicitly to shorten this function.
```suggestion
    () =>
      Promise.all([
        adminClient.identityProviders.findOne({ alias: id }),
        adminClient.identityProviders.findMappers({ alias: id }),
        adminClient.identityProviders.findMapperTypes({ alias: id }),
      ]),
```

2021-08-25 15:29 UTC, jonkoops commented on src/identity-providers/add/DetailSettings.tsx
>      (provider) => {
Instead of using an index to access the provider you can de-structure the array and get the fist item.
```suggestion
    ([provider]) => {
```

2021-08-25 15:34 UTC, jonkoops commented on src/identity-providers/add/DetailSettings.tsx
> +        );
If you destructure the entry this code can be simplified.
```suggestion
        Object.entries(provider).map(([key, value) =>
          setValue(key], value)
        );
```

I think you can even use `reset()` instead.
```suggestion
        reset(provider);
```

2021-08-25 15:36 UTC, jonkoops commented on src/identity-providers/add/DetailSettings.tsx
> +    const components = (loaderMappers as IdPWithMapperAttributes[])?.map(
The `loaderMappers` variable already has a type associated with it, why does it need to be cast to another type?

2021-08-25 15:37 UTC, jonkoops commented on src/identity-providers/add/DetailSettings.tsx
> +    const components = (loaderMappers as IdPWithMapperAttributes[])?.map(
There should be no need to use an optional chain here as according to the types this is always an array.
```suggestion
    const components = (loaderMappers as IdPWithMapperAttributes[]).map(
```

2021-08-25 15:38 UTC, jonkoops commented on src/identity-providers/add/DetailSettings.tsx
> +        const provider = Object.values(loaderMapperTypes)?.filter(
`Object.values()` always returns an array, so there is no need to use an optional chain here.
```suggestion
        const provider = Object.values(loaderMapperTypes).filter(
```

2021-08-25 15:39 UTC, jonkoops commented on src/identity-providers/add/DetailSettings.tsx
> +              loaderMapper.identityProviderMapper! === loaderMapperType?.id!
The `loaderMapperType` variable is always defined so there is no need to optional chain this.
```suggestion
              loaderMapper.identityProviderMapper! === loaderMapperType.id!
```

2021-08-25 15:41 UTC, jonkoops commented on src/identity-providers/add/DetailSettings.tsx
> +          name: loaderMapper?.name,
The `loaderMapper` variable is always defined so there is no need to use optional chaining  here.
```suggestion
          name: loaderMapper.name,
```

2021-08-25 15:41 UTC, jonkoops commented on src/identity-providers/add/DetailSettings.tsx
> +                    //   onPrimaryAction={() => setAddDialogOpen(true)}
Commented out code.

2021-08-25 15:42 UTC, jonkoops commented on src/identity-providers/add/DetailSettings.tsx
> +                loader={loader as any}
There should be no need to cast this.
```suggestion
                loader={loader}
```

2021-08-25 15:42 UTC, jonkoops commented on src/identity-providers/add/DetailSettings.tsx
> +                  <>
This fragment can be removed.

2021-08-25 15:42 UTC, jonkoops commented on src/identity-providers/add/DetailSettings.tsx
> +                      {/* <Button to={toAddIdentityProviderMapperTab({ realm })}>
Why is this not implemented?

2021-09-01 17:09 UTC, jonkoops commented
@jenny-s51 Looks like the tests are failing, you might want to rebase on `master`.

2021-09-03 19:00 UTC, ssilvert approved these changes
Looks like a good start.

@jenny-s51 Why is there no Marvel for this?

2021-09-03 19:03 UTC, jenny-s51 commented
@ssilvert thank you! yes good question - I asked at one of our recent team meetings and @mfrances17 @yih-wang mentioned that the new implementation should just match the old console

2021-09-06 02:23 UTC, yih-wang commented
@ssilvert The mappers of IdP follow the designs of the old console.

2021-09-06 09:11 UTC, jonkoops requested changes

2021-09-06 09:11 UTC, jonkoops commented on src/identity-providers/add/DetailSettings.tsx
> +      const provider = Object.values(loaderMapperTypes).filter(
I believe `Object.values` can be removed here and the result will still be the same.
```suggestion
      const provider = loaderMapperTypes.filter(
```

2021-09-06 09:11 UTC, jonkoops commented on src/identity-providers/add/DetailSettings.tsx
> +      ) as unknown as IdPWithMapperAttributes[];
I believe you could use a `Array#find()` here to get the result you are looking for (as only the first index is ever used).

```suggestion
      const mapperType = loaderMapperTypes.find(
        (loaderMapperType) =>
          loaderMapper.identityProviderMapper! === loaderMapperType.id!
      );
```

2021-09-06 09:11 UTC, jonkoops commented on src/identity-providers/add/DetailSettings.tsx
> +      } as IdPWithMapperAttributes;
Casting the value to a type using `as` might allow fields to be missed in the type check at compile time. It's better to use the type annotation at the front:

```ts
const result: IdPWithMapperAttributes = {
  ...provider[0],
  name: loaderMapper.name,
  type: provider[0]?.name,
}
```

2021-09-07 14:41 UTC, jenny-s51 commented on src/identity-providers/add/DetailSettings.tsx
> +      const provider = Object.values(loaderMapperTypes).filter(
A `.filter is not a function` error gets thrown here unless `Object.values` is used

2021-09-07 14:42 UTC, jenny-s51 commented
@jonkoops Thank you for your helpful and insightful feedback - I've addressed all your comments.

2021-09-08 08:55 UTC, jonkoops commented on src/identity-providers/add/DetailSettings.tsx
>        }
This can be reduced/improved a bit by making the following changes:

1. There is no need to wrap the call in `Promise.resolve()` as it already returns a Promise
2. There is no need to make the callback `async` as there is no `await` used inside of the function.
3. There is no need to destructure the result as it's only a single value.
4. There is no need to check the value of the result before assignment (according to the return type it's value is always present). 
5. `forEach()` should be used instead of `.map()` as there is no resulting value from the map operation.

With these changes you'll end up with the following:
```suggestion
    () => adminClient.identityProviders.findOne({ alias: alias }),
    (provider) => {
      Object.entries(provider).forEach(([key, value]) => setValue(key, value));
    },
```

2021-09-08 09:16 UTC, jonkoops requested changes

2021-09-08 09:16 UTC, jonkoops commented on src/identity-providers/add/DetailSettings.tsx
> +        (loaderMapperType) =>
@jenny-s51 You are correct that this `Object.values()` call in required, however it looks like the Admin Client is giving us a faulty type here. We are expecting a type of `Record<string, IdentityProviderMapperRepresentation>`, but the admin client is giving us a `IdentityProviderMapperRepresentation[]` type instead.

2021-09-08 09:16 UTC, jonkoops commented on src/identity-providers/add/DetailSettings.tsx
> +        (loaderMapperType) =>
I've created a PR (https://github.com/keycloak/keycloak-nodejs-admin-client/pull/248) on the Admin Client to correct this issue.

2021-09-08 13:56 UTC, jenny-s51 commented on src/identity-providers/add/DetailSettings.tsx
> +        (loaderMapperType) =>
That makes sense - thank you

2021-09-08 13:58 UTC, jonkoops approved these changes
LGTM :heavy_check_mark:

2021-09-08 13:58 UTC, jenny-s51 commented on src/identity-providers/add/DetailSettings.tsx
> +        );
good call, thank you

2021-09-08 14:33 UTC, merged