Make filtering of client scopes same for clients and client scope section
keycloak/keycloak-admin-ui pull request #1064
Opened 2021-08-25 13:53 UTC by edewit

fixes: #1027

2021-08-25 15:07 UTC, jonkoops commented on src/client-scopes/ClientScopesSection.tsx
> +    AllClientScopes.none
Enums values are supposed to start with a capital letter like [the TypeScript documentation](https://www.typescriptlang.org/docs/handbook/enums.html). But this is a separate issue from this PR.

2021-08-25 15:20 UTC, jonkoops requested changes

2021-08-25 15:20 UTC, jonkoops commented on src/client-scopes/ClientScopesSection.tsx
> +        } as Row;
Instead of casting this value to a different type it might be better to create a variable and use a proper type to catch type-errors.

```ts
const row: Row = {
 ...
}

return row;
```

2021-08-25 15:20 UTC, jonkoops commented on src/client-scopes/details/SearchFilter.tsx
> +}
Enums values are supposed to start with a capital letter like in [the TypeScript documentation](https://www.typescriptlang.org/docs/handbook/enums.html).
```suggestion
export enum ProtocolType {
  All = "all",
  Saml = "saml",
  Openid = "openid-connect",
}
```

2021-08-25 15:20 UTC, jonkoops commented on src/client-scopes/details/SearchFilter.tsx
> +export type SearchType = "name" | "type" | "protocol";
Why not make this an enum as well?

2021-08-25 15:20 UTC, jonkoops commented on src/client-scopes/details/SearchFilter.tsx
> +  (search: string = "") =>
No need to specify the type if a default is provided from which the type can be inferred.
```suggestion
  (search = "") =>
```

2021-08-25 15:20 UTC, jonkoops commented on src/client-scopes/details/SearchFilter.tsx
> +                console.log(value);
Stray console log

2021-09-02 20:18 UTC, ssilvert commented
@edewit The test that's failing here is not one of the usual suspects.  Maybe worth a look?

2021-09-03 08:52 UTC, edewit commented
uhhh `realm_settings_test.spec.ts` deleteProviders seems to be one of the usal suspects though

2021-09-03 15:02 UTC, mfrances17 submitted a review, later dismissed
The issue requested that the layout of the toolbars look the same, but i'm seeing a 'Change type' command from the vertical ellipsis in the Client Scopes toolbar, and a 'Change type to' dropdown from the Clients > Client details > Client scopes tab.

![client-scopes](https://user-images.githubusercontent.com/39063664/132026737-36fec4d7-3ea7-49c6-a547-0b37647f2e07.png)


![client](https://user-images.githubusercontent.com/39063664/132026718-71539e2c-9fd7-436d-8020-e02cd99f879a.png)

2021-09-06 14:52 UTC, jonkoops approved these changes

2021-09-13 07:17 UTC, edewit commented
@mfrances17 now both pages have the same dropdown to change the type

2021-09-13 08:23 UTC, jonkoops commented
@edewit build is failing now.

2021-09-14 09:59 UTC, jonkoops requested changes

2021-09-14 09:59 UTC, jonkoops commented on src/client-scopes/details/SearchFilter.tsx
> +      aria-label="Select Input"
This label needs to be translated.

2021-09-14 09:59 UTC, jonkoops commented on src/client-scopes/details/SearchFilter.tsx
> +export const Protocols = ["all", "saml", "openid-connect"];
Since this is variable it should start with a lower case.

```suggestion
export const protocols = ["all", "saml", "openid-connect"];
```

Or if you want to use a constant case:
```suggestion
export const PROTOCOLS = ["all", "saml", "openid-connect"];
```

2021-09-14 09:59 UTC, jonkoops commented on src/client-scopes/details/SearchFilter.tsx
> +export const Protocols = ["all", "saml", "openid-connect"];
Note that you can also tell the TypeScript compiler that the type is a readonly tuple. So instead of having a type of `string[]` it will become `readonly ["all", "saml", "openid-connect"]`.

This also will reflects down to `ProtocolType` which will be of type `"all" | "saml" | "openid-connect"` instead of type `string`.

```suggestion
export const protocols = ["all", "saml", "openid-connect"] as const;
```

2021-09-14 09:59 UTC, jonkoops commented on src/components/table-toolbar/KeycloakDataTable.tsx
> +        emptyState}
This statement is getting very complex. Perhaps it could be extracted into a function.

2021-09-14 13:03 UTC, jonkoops approved these changes

2021-09-14 13:10 UTC, edewit commented on src/components/table-toolbar/KeycloakDataTable.tsx
> +        emptyState}
I'll add that to another PR

2021-09-14 15:48 UTC, merged