Group page
keycloak/keycloak-admin-ui pull request #108
Opened 2020-09-21 15:42 UTC by christiemolloy

Implemented first page in the Groups Section.

**Notes:**
-  I haven't added actual data yet so I had to add a new component called GroupsSectionData which passes in the data as a prop, that was the only way I could immediately set the data. I plan to add the data in the next round of changes.
- I updated TableToolbar component so that you can pass in the input group now instead of having one there... this is because all the pages require different input groups. I also updated client section to reflect this change.
- There's quite a few TS errors - I plan to fix those once I actully add the data because I haven't looked at the models yet from the old Keycloak code - so that will probably fix all of the errors.
- Commented out the DataLoader component for now as it was refreshing all the current states on the page on every re-render so I need to investigate that further.

**Functionality to test:**
1) Filter on groups
2) Select items in the table
3) Select multiple items in the table and click on Toolbar kebab > "Delete" to delete rows in the table.
4) Select Table kebab > "Delete" to delete individual row in the table.

2020-09-21 18:35 UTC, ssilvert requested changes
@christiemolloy Nice to see a first PR.  A few things to get this going:
- Please fix conflicts
- You will need to clean up the TS errors before it will let you merge
- We are using camelCase for resource bundle keys.
i.e. `"Create group": "Create group"` should be `"createGroup": "Create group"`

2020-09-21 20:49 UTC, dlabaj requested changes

2020-09-21 20:49 UTC, dlabaj commented on src/groups/GroupsList.tsx
> +      title: t("Delete"),
Can we call this something other than t.  t has no meaning when you look at it without looking the useTranslate above.

2020-09-21 20:49 UTC, dlabaj commented on src/groups/GroupsSection.tsx
> +type GroupsSectionProps = {
Shouldn't this be an interface instead of a type?

2020-09-21 20:49 UTC, dlabaj commented on src/groups/GroupsSection.tsx
> +    if (rowId === -1) {
Can we use a constant instead of -1

2020-09-21 20:49 UTC, dlabaj commented on src/groups/GroupsSection.tsx
> +      {/* <DataLoader loader={loader}>
Can we remove the commented out code.

2020-09-21 20:49 UTC, dlabaj commented on src/groups/GroupsSection.tsx
> +            onPerPageSelect={(f,m) => {
what's f and m.  We should use full names instead of a single letter.

2020-09-21 20:49 UTC, dlabaj commented on src/groups/GroupsSection.tsx
> +      </DataLoader> */}
Remove dead code.

2020-09-21 21:24 UTC, ssilvert commented on src/groups/GroupsList.tsx
> +      title: t("Delete"),
@dlabaj That a convention commonly used with the i18next package.

2020-09-21 21:41 UTC, ssilvert commented on src/groups/GroupsSection.tsx
> +type GroupsSectionProps = {
I've done some reading on this, and while you could use either, `type` is probably a better choice here.  `type` is a little more flexible.  In our codebase, we are only using interfaces for data transfer definitions (representations).

2020-09-22 17:58 UTC, srambach commented on src/groups/GroupsSection.css
> +}
We decided to prefix all CSS classes using the pattern `.keycloak-admin--block[__element][--modifier][--state][--breakpoint][--pseudo-element]` so maybe instead of `.pf-icon-group-members`, something more like `.keycloak-admin--groups__member-count`? 
Since this is used twice already, is it worth making that a component? Especially if there are going to be variations in color or icon. I can't find where it is in the Groups mockups so IDK if there are or not?

2020-09-22 19:57 UTC, dlabaj commented on src/groups/GroupsList.tsx
> +      title: t("Delete"),
We can leave this since that's how it's being provided by the library.

2020-09-22 19:57 UTC, dlabaj commented on src/groups/GroupsSection.tsx
> +type GroupsSectionProps = {
That's opposite of the way it is on other projects.  What's the convention then we use type for all Props?

2020-09-22 20:25 UTC, ssilvert commented on src/groups/GroupsSection.tsx
> +type GroupsSectionProps = {
Yes, I think we should use `type`.  The main place it might come in handy for props is the ability to do unions, which you can't do with interfaces.

BTW, I'm getting my info from O'Reily book "Effective TypeScript".  Really good read.

We use interfaces for the representations because the tool we use to generate them from Java code uses interfaces.  See Realm.ts for an example.

2020-09-23 08:16 UTC, edewit requested changes

2020-09-23 08:16 UTC, edewit commented on src/clients/ClientsSection.tsx
> +            inputGroup={
I think there might be a way to make this a bit more re-usable? I mean now every user of this will need to create this same piece of components just to make the search work. Maybe we can have the field and button still be in the `TableToolbar` and only expose the "action"?

2020-09-23 10:41 UTC, dlabaj commented on src/groups/GroupsSection.tsx
> +type GroupsSectionProps = {
Thanks stan

2020-09-23 15:44 UTC, christiemolloy commented on src/groups/GroupsSection.tsx
> +    if (rowId === -1) {
I got this straight from PatternFly. I can update it though to be undefined

2020-09-23 15:45 UTC, christiemolloy commented on src/groups/GroupsSection.tsx
> +            onPerPageSelect={(f,m) => {
I think these were from @edewit 's implementation. Erik would you be ok with changing these to full names?

2020-09-23 15:50 UTC, christiemolloy commented on src/groups/GroupsSection.css
> +}
I refactored the code so that class only appears once now. I don't think we need it as a separate component unless another comes up! which it might, so I can add that in the future. I updated the naming of the class thanks for that feedback!

2020-09-23 17:45 UTC, christiemolloy commented on src/clients/ClientsSection.tsx
> +            inputGroup={
Agreed. I updated it so that now the Input Group and Button are in the TableToolbar, and you pass in the name, placeholder, and onChange event

2020-09-23 19:07 UTC, christiemolloy commented on src/groups/GroupsSection.tsx
> +    const groupsData = groups.data;
@edewit do you mind taking a look at the TS errors that I'm getting in this block. The `<HTTPResponse>` is unknown and when I try to map it its throwing an error because its unknown. I've been reading up on async/await functions and TS  https://www.carlrippon.com/type-safe-data-fetching-with-unknown/  but I'm still struggling so wondering if you could help me out :)

2020-09-24 13:43 UTC, edewit commented on src/groups/GroupsSection.tsx
> +    const groupsData = groups.data;
right add the type on the `doGet` like this:
```javascript
const groups = await httpClient.doGet<GroupRepresentation[]>("/admin/realms/master/groups", { params: { first, max } });
```

2020-09-24 18:49 UTC, christiemolloy commented
@ssilvert @edewit @dlabaj @srambach @jenny-s51  checks finally all passed if you want to take another look :)

2020-09-25 06:28 UTC, edewit commented on src/groups/GroupsSection.tsx
> +    if (rowId === -1) {
I think we shouldn't create constants for something like `-1` see: https://www.codereadability.com/magic-numbers/

2020-09-25 06:30 UTC, edewit commented on src/groups/GroupsSection.tsx
> +            onPerPageSelect={(f,m) => {
I'll do that in another PR we can rename them to `first` and `max` still pretty short

2020-09-25 06:39 UTC, edewit approved these changes

2020-09-25 06:39 UTC, edewit commented
I get an error in the console about the inline property:
```
Warning: React does not recognize the `isInline` prop on a DOM element.
```
Other then that :+1: looks great

2020-09-25 06:41 UTC, edewit commented
Oh one more comment, this is more general and not specific to your implementation but fetching the members of a group is limited to 100 @ssilvert should we remove the column? I guess without it the whole thing also looks dumb

2020-09-25 13:19 UTC, dlabaj commented on src/groups/GroupsSection.tsx
> +    if (rowId === -1) {
okay i've been on projects where I seen it used a constant instead of -1.  We can leave it then.  Thanks.

2020-09-25 13:26 UTC, christiemolloy commented
> Oh one more comment, this is more general and not specific to your implementation but fetching the members of a group is limited to 100 @ssilvert should we remove the column? I guess without it the whole thing also looks dumb

Could we limit the number of groups using pagination and then on every new page fetch the members by all the groupIDs on the page?

2020-09-25 14:00 UTC, dlabaj approved these changes
LGTM

2020-09-25 17:00 UTC, ssilvert requested changes
@christiemolloy It looks like you ran prettier against some files that you didn't actually change?

2020-09-25 17:13 UTC, christiemolloy commented on tsconfig.json
> +    "module": "esnext" /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', or 'ESNext'. */,
@ssilvert yep thats because I ran `prettier --write .` I probably shouldn't have committed those files too, so I can revert those changes, and next time just make sure that I only use `prettier` for the files that have formatting errors, do you know if there is a short cut using prettier for formatting certain files ?

2020-09-25 18:07 UTC, ssilvert commented on tsconfig.json
> +    "module": "esnext" /* Specify module code generation: 'none', 'commonjs', 'amd', 'system', 'umd', 'es2015', or 'ESNext'. */,
@christiemolloy I set up VSCode to "format on save", with prettier as my default formatter.  That way, it only tries to format the files I've worked on.

I'm a little distressed about what prettier did to tsconfig.json.  That's a nasty-looking change.

2020-09-25 19:23 UTC, christiemolloy commented
@ssilvert do you mind taking a look again? some of the files didnt update but its only slight formatting and i fixed tsconfig.json

2020-09-28 11:43 UTC, ssilvert commented
@srambach Can you look at the changes you requested on this one and approve or disapprove ASAP?  This one is at the 7 day limit.

2020-09-28 11:49 UTC, ssilvert requested changes

2020-09-28 11:49 UTC, ssilvert commented on src/groups/GroupsList.tsx
> +      title: t("moveTo"),
Missing key.  Please fix ASAP.

2020-09-28 11:49 UTC, ssilvert commented on src/groups/GroupsList.tsx
> +      title: t("delete"),
Missing key.  Should be `"common:delete"`.  Please fix ASAP.

2020-09-28 13:28 UTC, srambach commented on src/clients/ClientsSection.tsx
> +              inputGroupPlaceholder="Search for client"
Does this need a translation?

2020-09-28 13:30 UTC, srambach commented on src/groups/GroupsList.tsx
> +          aria-label="Selectable Table"
Does this need a translation?

2020-09-28 13:43 UTC, christiemolloy commented on src/groups/GroupsList.tsx
> +      title: t("moveTo"),
There is a "moveTo" key that exists in the messages file. Are you referring to something else?

2020-09-28 13:57 UTC, christiemolloy commented
@srambach @ssilvert updated

2020-09-28 15:57 UTC, ssilvert approved these changes

2020-09-28 15:58 UTC, merged