add action menu to delete current user
keycloak/keycloak-admin-ui pull request #1094
Opened 2021-08-30 13:20 UTC by edewit

2021-09-01 14:05 UTC, mfrances17 requested changes
Code looks fine, a couple string suggestions. Delete and impersonate tested ok, although other than logging you out and going to the account console, not sure exactly what impersonate is supposed to do (no description or testing steps provided).

2021-09-01 14:05 UTC, mfrances17 commented on src/user/messages.ts
> +      "Are you sure you want to login as this user? If this user is in the same realm with you, your current login session will be logged out before you log in as this user",
Should be: "Are you sure you want to log in..." not "Are you sure you want to login..."
Also it's a full sentence so should end in a period.

2021-09-01 18:47 UTC, ssilvert requested changes
This all looks good except "Impersonate" isn't actually working.  It takes me to the account console but I am logged out.

What should happen is that I go to the account console and it appears that I am logged in as the user I am impersonating.

2021-09-02 05:28 UTC, edewit commented
@ssilvert Right, I should have mentioned that on the PR it only works when keycloak is serving the page.

2021-09-02 13:41 UTC, ssilvert commented
> @ssilvert Right, I should have mentioned that on the PR it only works when keycloak is serving the page.

@edewit OK.  So if the plan is to fix that in a future PR I can approve this one.  Is that what you want to do?

2021-09-02 15:46 UTC, edewit commented
@ssilvert no need to fix it later. It already works just not in dev mode, only when the admin client is installed.

2021-09-02 17:34 UTC, ssilvert commented
> @ssilvert no need to fix it later. It already works just not in dev mode, only when the admin client is installed.

Oh, I see.  I'll give it a try running as a theme then.

2021-09-02 17:50 UTC, ssilvert commented
@edewit Running as a theme works as you said.  I'm ready to approve except that the test failures are not ones I recognize.  Running the tests again.

2021-09-02 18:21 UTC, ssilvert approved these changes

2021-09-03 13:51 UTC, mfrances17 approved these changes
LGTM, thanks for updating

2021-09-03 13:54 UTC, merged