WIP: initial version client scopes
keycloak/keycloak-admin-ui pull request #111
Opened 2020-09-22 12:17 UTC by edewit

2020-09-24 18:18 UTC, ssilvert requested changes
These screens have the header and breadcrumbs missing.  Are the components for that ready to integrate?

2020-09-24 18:18 UTC, ssilvert commented on src/client-scopes/add/NewClientScopeForm.tsx
> +          }
Protocol is a required field.  Default should be openid-connect.

2020-09-24 18:18 UTC, ssilvert commented on src/client-scopes/add/NewClientScopeForm.tsx
> +          />
Add validation.  Must be an integer.

2020-09-24 18:18 UTC, ssilvert commented on src/client-scopes/add/NewClientScopeForm.tsx
> +          fieldId="kc-display.on.consent.screen"
Help icon missing.

2020-09-24 18:23 UTC, ssilvert commented
> These screens have the header and breadcrumbs missing. Are the components for that ready to integrate?

Nevermind.  Didn't see your other PR.  I guess we are just missing breadcrumbs.

2020-09-25 07:18 UTC, edewit commented on src/client-scopes/add/NewClientScopeForm.tsx
> +          />
Guess that is a bug in the old console, there you can save a text as well... changed the type to `number` way nicer then validation.

2020-09-25 07:20 UTC, edewit commented on src/client-scopes/add/NewClientScopeForm.tsx
> +          }
yes fetching the protocols is done with this `server-info` call, guess we need your PR that initializes the console

2020-09-25 17:08 UTC, ssilvert commented on src/client-scopes/add/NewClientScopeForm.tsx
> +          }
Yes, you are right.

Actually, I'm working whoami right now.  But I guess serverinfo needs to be next on the list.

2020-09-25 17:11 UTC, ssilvert approved these changes

2020-09-25 17:11 UTC, merged

2020-09-25 17:53 UTC, srambach commented
@edewit and @ssilvert FYI, I'm looking into the tooltips - as it was yesterday anyway, it doesn't quite match PF recommendations and isn't accessible. I made myself an issue. https://github.com/keycloak/keycloak-admin-ui/issues/120

2020-09-25 18:10 UTC, ssilvert commented
@srambach Sounds good.