Identity Providers(Mappers): Implement "Add Mapper" Screen/Functionality for OIDC and SAML IdPs
keycloak/keycloak-admin-ui pull request #1118
Opened 2021-09-02 20:00 UTC by jenny-s51

## Motivation

https://issues.redhat.com/browse/CLUX-230
https://issues.redhat.com/browse/CLUX-231

## Verification Steps

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

## Additional Notes

2021-09-08 09:48 UTC, jonkoops requested changes
I am seeing a lot of the same changes in this PR as in #1058. I am guessing they are dependent on each other so I'd like to merge #1058 first before reviewing this PR any further.

2021-09-08 09:48 UTC, jonkoops commented on src/components/attribute-form/AttributeForm.tsx
> +    <FormAccess role="manage-realm" onSubmit={handleSubmit(save!)}>
Using a non-null assertion here might cause errors at runtime. Instead you can check the value before assigning it:
```suggestion
    <FormAccess role="manage-realm" onSubmit={save ? handleSubmit(save) : undefined}>
```

2021-09-08 09:48 UTC, jonkoops commented on src/identity-providers/add/AddIdentityProvider.tsx
> +      history.push(toIdentityProviderTab({ realm, providerId: id, alias: id }));
Nice improvement!

2021-09-08 09:48 UTC, jonkoops commented on src/identity-providers/add/DetailSettings.tsx
> +        adminClient.identityProviders.findMapperTypes({ alias: alias }),
The values from these calls are not being used so I think they can be removed. Looks like this is a change from #1058?

2021-09-08 09:48 UTC, jonkoops commented on src/identity-providers/add/SamlConnectSettings.tsx
> +          // isRequired
Commented out code.

2021-09-08 09:48 UTC, jonkoops commented on src/identity-providers/add/SamlConnectSettings.tsx
> +        // isRequired
Commented out code.

2021-09-08 09:48 UTC, jonkoops commented on src/identity-providers/routes/AddMapper.ts
> +  id?: string;
The `id` parameter does not exist in the path of the route so it can be removed.

2021-09-08 09:48 UTC, jonkoops commented on src/identity-providers/routes/AddMapper.ts
> +  tab?: IdentityProviderTab;
The `tab` parameter does not exist in the path of the route so it can be removed.

2021-09-08 09:48 UTC, jonkoops commented on src/identity-providers/routes/AddMapper.ts
> +  alias?: string;
The `alias` parameter is required in the path of the route so it should be here too.
```suggestion
  alias: string;
```

2021-09-08 09:48 UTC, jonkoops commented on src/identity-providers/routes/AddMapper.ts
> +  providerId?: string;
The `providerId` parameter is required in the path of the route so it should be here too.
```suggestion
  providerId: string;
```

2021-09-08 09:48 UTC, jonkoops commented on src/identity-providers/routes/AddMapper.ts
> +export const toAddIdentityProviderMapperTab = (
The name of this function should correspond with the name of the route.
```suggestion
export const toIdentityProviderAddMapper = (
```

2021-09-08 09:48 UTC, jonkoops commented on src/identity-providers/routes/IdentityProviderTab.ts
> +  path: "/:realm/identity-providers/:providerId?/:alias/:tab?",
Nice, this was incorrect before so good catch!

2021-09-08 14:05 UTC, jenny-s51 commented
@jonkoops thank you - sounds good, I will address your comments above in the meantime. yes this PR is dependent on #1058 - once it's merged I'll rebase on this branch and this PR will get smaller and easier to review 🙂

2021-09-09 11:53 UTC, jonkoops commented
@jenny-s51 Looks like there are some compilation errors coming from the upgrade of the Admin Client that will have to be fixed.

2021-09-09 16:02 UTC, jonkoops requested changes

2021-09-09 16:02 UTC, jonkoops commented on src/identity-providers/routes/EditMapper.ts
> +  // editMode: string;
All parameters here are required in the route, so they should be in this type as well. Also, it looks like some can be removed as they are not present in the route.

```suggestion
  realm: string;
  providerId: string;
  alias: string;
  id: string;
```

2021-09-09 16:02 UTC, jonkoops commented on src/identity-providers/routes/EditMapper.ts
> +export const toEditIdentityProviderMapperTab = (
The name of the link function should match that of the route.
```suggestion
export const toIdentityProviderEditMapper = (
```

2021-09-09 17:34 UTC, jenny-s51 commented on src/components/attribute-form/AttributeForm.tsx
> +  noSaveCancelButtons,
cool idea 👍

2021-09-09 18:33 UTC, jenny-s51 commented on src/identity-providers/add/SamlConnectSettings.tsx
> +      );
Yes but it was implemented for URL imports only: https://github.com/keycloak/keycloak-nodejs-admin-client/pull/163/files

Was this intentional @edewit?

2021-09-10 16:11 UTC, jonkoops approved these changes

2021-09-13 06:48 UTC, edewit commented on src/identity-providers/add/SamlConnectSettings.tsx
> +      );
Yes it's was intentional, the admin client is build around JSON and this request needs to be form data. So the choice was to make this call outside of the admin client or refactor the admin client to not only use JSON.

2021-09-13 09:17 UTC, merged