Process UXD feedback for client revocation
keycloak/keycloak-admin-ui pull request #1139
Opened 2021-09-08 12:29 UTC by jonkoops

Closes #958

2021-09-09 01:44 UTC, yih-wang requested changes
@jonkoops Thanks for the updates, that looks great!

Only one minor issue that hasn't been addressed.

- For the third point I mentioned in the original issue, I meant to change the tooltip of the "Not before" label to "Revoke any tokens issued before this time for this client. To push the policy, you should set an effective admin URL in the Settings tab first". That hasn't been addressed in this commit.

2021-09-09 13:37 UTC, jonkoops commented
@yih-wang Ahh, I see. I misunderstood the intention there. I've updated the tooltip to reflect this, can you take another look?

2021-09-10 02:33 UTC, yih-wang approved these changes
LGTM, thanks!

2021-09-10 13:09 UTC, agagancarczyk approved these changes

2021-09-10 13:25 UTC, merged