Create realm role page
keycloak/keycloak-admin-ui pull request #114
Opened 2020-09-22 18:49 UTC by jenny-s51

This is a branch from #11.

2020-09-25 17:23 UTC, ssilvert requested changes

2020-09-25 17:23 UTC, ssilvert commented on src/realm-roles/messages.json
> +      "create" : "Create",
Something this generic probably belongs in `common-messages.json`

2020-09-25 17:23 UTC, ssilvert commented on src/realm-roles/add/NewRoleForm.tsx
> +      await httpClient.doPost(`/auth/admin/realms/${realm}/roles`, role);
Looks like this didn't actually work.

Your payload is wrong.  You are sending `{"role", "newrole"}`.  Should be `{"name", "newrole"}`

Easy way to double-check is to look at what the old console does.

2020-09-28 14:07 UTC, jenny-s51 commented
@edewit @ssilvert do you guys have any ideas as to why the HTTP post doesn't work with this route?

2020-09-28 14:12 UTC, edewit commented
> @edewit @ssilvert do you guys have any ideas as to why the HTTP post doesn't work with this route?

@ssilvert suspected that the payload is wrong, is that not the case?

2020-09-28 19:31 UTC, ssilvert reviewed
@jenny-s51 The Create roll function is working now.  Just a few minor things to fix and we can merge.

2020-09-28 19:33 UTC, ssilvert requested changes

2020-09-28 19:33 UTC, ssilvert commented on src/realm-roles/add/NewRoleForm.tsx
> +      add(`${t("Could not create role:")} '${error}'`, AlertVariant.danger);
Use camel Case

```suggestion
      add(`${t("couldNotCreateRole")} '${error}'`, AlertVariant.danger);
```

2020-09-28 23:14 UTC, dlabaj approved these changes

2020-09-28 23:14 UTC, dlabaj commented on src/realm-roles/add/NewRoleForm.tsx
> +            <TextInput
Did you create a PR against pattern fly for the TextArea failure?

2020-09-29 13:02 UTC, jenny-s51 commented on src/realm-roles/add/NewRoleForm.tsx
> +            <TextInput
yes - https://github.com/patternfly/patternfly-react/issues/4894

2020-09-29 13:15 UTC, edewit approved these changes

2020-09-29 13:15 UTC, dlabaj approved these changes

2020-09-29 17:54 UTC, ssilvert approved these changes

2020-09-29 17:54 UTC, merged