Saml edit mappers
keycloak/keycloak-admin-ui pull request #1140
Opened 2021-09-08 20:04 UTC by jenny-s51

## Motivation

## Brief Description

## Verification Steps

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

## Additional Notes

2021-09-14 13:39 UTC, ssilvert commented
@jenny-s51 The failing test looks legit.  I think it will need to be fixed before we merge.

2021-09-14 16:33 UTC, jonkoops requested changes

2021-09-14 16:33 UTC, jonkoops commented on src/identity-providers/add/AddMapper.tsx
> +  }
It's [not allowed](https://reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level) to render hooks conditionally, so this has to be a single `useFetch` with any conditional logic inside the function body. The calls to the Admin Client in this function are also not dependent on each other, which means they can be ran in parallel using [`Promise.all()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all).

I tried to refactor this code a little and this is what I ended up with (untested):
```ts
useFetch(
  () =>
    Promise.all([
      id ? adminClient.identityProviders.findOneMapper({ alias, id }) : null,
      adminClient.identityProviders.findMapperTypes({ alias }),
      !id ? adminClient.roles.find() : null,
    ]),
  ([mapper, mapperTypes, roles]) => {
    if (mapper) {
      setCurrentMapper(mapper);
      setupForm(mapper);
    }

    setMapperTypes(mapperTypes);

    if (roles) {
      setRoles(roles);
    }
  },
  []
);
```

2021-09-14 16:33 UTC, jonkoops commented on src/identity-providers/add/DetailSettings.tsx
> +        alias: alias!,
The `alias` prop is of type `string` and thus cannot be `undefined`, this means the non-null assertion can be removed.
```suggestion
        alias,
```

2021-09-14 16:33 UTC, jonkoops commented on src/identity-providers/add/DetailSettings.tsx
> +        providerId: providerId,
If the key and value share the same name the part after the colon can be removed.
```suggestion
        providerId,
```

2021-09-14 16:33 UTC, jonkoops commented on src/identity-providers/routes/EditMapper.ts
> +  providerId?: string;
All these fields are required in the route path, so they should be required in this type as well. The `tab` field is never used in the path, so it can be removed. It is also a good idea to keep the order of these fields the same as they appear in the route path.

```suggestion
  providerId: string;
  alias: string;
  id: string;
```

2021-09-14 16:33 UTC, jonkoops commented on src/realm-roles/AssociatedRolesModal.tsx
> +  const { id } = useParams<RealmRoleParams>();
Nice, thanks for cleaning that up!

2021-09-14 16:33 UTC, jonkoops commented on src/realm-roles/AssociatedRolesModal.tsx
> +  }
It's [not allowed](https://reactjs.org/docs/hooks-rules.html#only-call-hooks-at-the-top-level) to render hooks conditionally, so this has to be a single `useFetch` with any conditional logic inside the function body.
```suggestion
  useFetch(
    () =>
      props.isMapperId
        ? adminClient.roles.findOneById({ id })
        : Promise.resolve(null),
    (role) => setName(role ? role.name! : t("createRole")),
    []
  );
```

2021-09-15 18:29 UTC, jenny-s51 commented on src/identity-providers/add/AddMapper.tsx
> +  }
great idea! thank you

2021-09-20 09:02 UTC, jonkoops requested changes

2021-09-20 09:02 UTC, jonkoops commented on src/identity-providers/routes/IdentityProvider.ts
> +  tab: IdentityProviderTabs;
Each route should have no dependencies on other routes, and neither should their types. The reason for this is to prevent accidentally introducing new params when editing another route.
```suggestion
export type IdentityProviderParams = {
  realm: string;
  providerId: string;
  alias: string;
  tab: IdentityProviderTabs;
```

2021-09-20 09:02 UTC, jonkoops commented on src/user/UserIdentityProviderLinks.tsx
> +          // providerId: idp.identityProvider!,
Some commented out code here, but this field should be passed to create a valid link,

2021-09-21 18:07 UTC, jenny-s51 commented on src/identity-providers/routes/IdentityProvider.ts
> +  providerId?: string;
An error is thrown at https://github.com/keycloak/keycloak-admin-ui/pull/1140#discussion_r711979977 unless the `providerId` is made optional here.

2021-09-22 08:15 UTC, jonkoops commented on src/identity-providers/routes/IdentityProvider.ts
> +  providerId?: string;
In that case the `providerId` should be checked or more likely use a non-null assertion as it is coming from a field that is always present in the responses from the API. So for example:

```ts
providerId: providerId!,
```

2021-09-22 08:26 UTC, jonkoops requested changes

2021-09-22 08:26 UTC, jonkoops commented on src/identity-providers/routes/IdentityProviderCreate.ts
> +  providerId?: string;
The `providerId` field here should be made required like in the path of the route.
```suggestion
  providerId: string;
```

2021-09-22 08:26 UTC, jonkoops commented on src/user/UserIdentityProviderLinks.tsx
> +          providerId: idp.identityProvider,
If the `providerId` field is made required in the route you can use the non-null assertion operator to force this value to be interpreted as defined.
```suggestion
          providerId: idp.identityProvider!,
```

2021-09-22 08:26 UTC, jonkoops commented on src/identity-providers/routes/IdentityProvider.ts
> +  path: "/:realm/identity-providers/:providerId?/:alias/:tab",
Once `providerId` is made required it should be made required here as well. 
```suggestion
  path: "/:realm/identity-providers/:providerId/:alias/:tab",
```

2021-09-22 08:26 UTC, jonkoops commented on src/identity-providers/routes/IdentityProvider.ts
>  type IdentityProviderTabs = "settings" | "mappers";
Like in other places in the name of a type is generally singular.
```suggestion
type IdentityProviderTab = "settings" | "mappers";
```

2021-09-22 08:26 UTC, jonkoops commented on src/identity-providers/add/AddMapper.tsx
> +                  providerId,
Once `providerId` is required you can use the non-null assertion operator here.
```suggestion
                  providerId: providerId!,
```

2021-09-22 08:26 UTC, jonkoops commented on src/identity-providers/add/AddIdentityProvider.tsx
> +          providerId,
Once `providerId` is required you can use the non-null assertion operator here.
```suggestion
          providerId: providerId!,
```

2021-09-22 08:26 UTC, jonkoops commented on src/identity-providers/IdentityProvidersSection.tsx
> +                  providerId: provider.id,
Once `providerId` is required you can use the non-null assertion operator here.
```suggestion
                  providerId: providerId!,
```

2021-09-22 19:37 UTC, ssilvert commented
@jenny-s51 This only works for Hardcoded User Session Attribute.  Are you planning to implement the other mapper types in a subsequent PR?

2021-09-22 19:42 UTC, ssilvert requested changes
Help text is incorrect for Name and Mapper type.  Note that in the old console, the help text for Mapper type changes based on which one you select.

2021-09-22 19:54 UTC, jenny-s51 commented
@ssilvert would you mind providing some more info? I am not able to replicate this -- currently I can edit mappers for all mapper types.

2021-09-22 19:56 UTC, jenny-s51 commented
> Help text is incorrect for Name and Mapper type. Note that in the old console, the help text for Mapper type changes based on which one you select.

@ssilvert Nice catch - I'm on it

2021-09-22 20:27 UTC, merged