Realm setting profiles
keycloak/keycloak-admin-ui pull request #1149
Opened 2021-09-13 13:29 UTC by agagancarczyk

## Motivation
1. Add radio button switch between "fromView" and "JSON editor" as per https://marvelapp.com/prototype/h11728e/screen/81529504 and https://marvelapp.com/prototype/h11728e/screen/81529214

2. Add "Delete profile?" dialog as per https://marvelapp.com/prototype/h11728e/screen/81529212

## Verification Steps
Navigate to /realm-settings page, select "Client policies" tab, and verify that the above exist. 

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

2021-09-13 20:07 UTC, jenny-s51 requested changes
Nice work @agagancarczyk! Profiles are looking good. 

Left some comments and suggestions below 🙂

2021-09-13 20:07 UTC, jenny-s51 commented on src/realm-settings/ProfilesTab.tsx
> +    return clientProfiles.globalProfiles;
If I try to make a new custom profile in the old console, it doesn't show up in the data table because this is only returning the `globalProfiles`; we should be returning both `profiles` and `globalProfiles`.

2021-09-13 20:07 UTC, jenny-s51 commented on src/realm-settings/ProfilesTab.tsx
> +            {name}
If I try to create a new custom profile in the old console, this renders the name in the data list twice:

<img width="1329" alt="Screen Shot 2021-09-13 at 4 04 06 PM" src="https://user-images.githubusercontent.com/32821331/133149274-814cd80f-fb9f-4bae-a6c3-ad8502dad817.png">

2021-09-14 09:01 UTC, agagancarczyk commented on src/realm-settings/ProfilesTab.tsx
> +              transforms: [cellWidth(10)],
Fixed - thank you @jenny-s51 !

2021-09-14 09:03 UTC, agagancarczyk commented on src/realm-settings/messages.ts
> +      fromView: "From view",
Fixed - thank you @jenny-s51 !

2021-09-14 09:05 UTC, agagancarczyk commented on src/realm-settings/RealmSettingsSection.css
>  }
Fixed - thank you @jenny-s51 !

2021-09-14 09:12 UTC, agagancarczyk commented on src/realm-settings/ProfilesTab.tsx
> +              name="jsonEditor"
Fixed - thank you @jenny-s51 !

2021-09-14 09:12 UTC, agagancarczyk commented on src/realm-settings/ProfilesTab.tsx
> +              name="fromView"
Fixed - thank you @jenny-s51 !

2021-09-14 11:26 UTC, agagancarczyk commented on src/realm-settings/ProfilesTab.tsx
> +    return clientProfiles.globalProfiles;
Fixed - thanks @jenny-s51

2021-09-14 11:33 UTC, agagancarczyk commented on src/realm-settings/ProfilesTab.tsx
> +            {name}
Fixed - thanks @jenny-s51

2021-09-14 13:06 UTC, jonkoops commented on package-lock.json
> -      "bin": {
Hmmm, strange this was removed but seems to be fine :man_shrugging:

2021-09-14 13:26 UTC, jenny-s51 requested changes
Looking awesome @agagancarczyk ! Thank you for making those updates.

One more thing:

<img width="238" alt="Screen Shot 2021-09-14 at 9 22 58 AM" src="https://user-images.githubusercontent.com/32821331/133265570-f3ba221f-9d34-4d31-9452-bc8781d72615.png">

According to the mock it looks like custom profiles should not have the "Global" label rendered next to them: https://marvelapp.com/prototype/h11728e/screen/81529211

Will you be adding tests to this PR? Once those are done looks good to merge 🙂

2021-09-14 13:35 UTC, agagancarczyk commented
> Looking awesome @agagancarczyk ! Thank you for making those updates.
> 
> One more thing:
> 
> <img alt="Screen Shot 2021-09-14 at 9 22 58 AM" width="238" src="https://user-images.githubusercontent.com/32821331/133265570-f3ba221f-9d34-4d31-9452-bc8781d72615.png">
> 
> According to the mock it looks like custom profiles should not have the "Global" label rendered next to them: https://marvelapp.com/prototype/h11728e/screen/81529211
> 
> Will you be adding tests to this PR? Once those are done looks good to merge 🙂

Thank you @jenny-s51 I'll fix this issue and add some tests :)

2021-09-15 08:51 UTC, jonkoops requested changes

2021-09-15 08:51 UTC, jonkoops commented on src/realm-settings/ProfilesTab.tsx
> +  }
Since this function is basically just a wrapped call to `setShow()` with the same arguments perhaps we can use `setShow()` directly here.

2021-09-15 08:51 UTC, jonkoops commented on src/realm-settings/ProfilesTab.tsx
> +    continueButtonLabel: "delete",
This string will have to be translated.

2021-09-15 08:51 UTC, jonkoops commented on src/realm-settings/ProfilesTab.tsx
> +  });
Since the delete functionality is not implemented on the API level I think it's better to leave out this code, otherwise we might ship a product with a button that does not work.

2021-09-15 08:51 UTC, jonkoops commented on src/realm-settings/ProfilesTab.tsx
> +        <Link to={""} key={`link-${name}`}>
This link is missing a route, but I am assuming this will come later.

2021-09-15 08:51 UTC, jonkoops commented on src/realm-settings/ProfilesTab.tsx
> +        {profiles?.globalProfiles?.length! > 0 && (
Using the non-null assertion operator here can cause issues at run-time. Make sure to check the value first.
```suggestion
        {profiles?.globalProfiles && profiles.globalProfiles.length > 0 && (
```

2021-09-15 08:51 UTC, jonkoops commented on src/realm-settings/ProfilesTab.tsx
> +              >
This button should probably use a link later on instead of using `onClick` to navigate.

2021-09-15 08:51 UTC, jonkoops commented on src/realm-settings/ProfilesTab.tsx
> +              code={JSON.stringify(profiles, null, 2)}
Calling `JSON.stringify()` on every render can be quite expensive. It is better to memoize this value so it is not recalculated every time.

```ts
const code = useMemo(() => JSON.stringify(profiles, null, 2), [profiles]);
```

2021-09-15 08:51 UTC, jonkoops commented on src/realm-settings/ProfilesTab.tsx
> +              height={"30rem"}
Strings can be passed directly,
```suggestion
              height="30rem"
```

2021-09-15 08:51 UTC, jonkoops commented on src/realm-settings/ProfilesTab.tsx
> +              Save
This string will have to be translated.

2021-09-15 08:51 UTC, jonkoops commented on src/realm-settings/ProfilesTab.tsx
> +            <Button variant={ButtonVariant.secondary}>Reload</Button>
This string will have to be translated.

2021-09-15 08:51 UTC, jonkoops commented on src/realm-settings/RealmSettingsSection.css
> +  transform: scale(1.6);
Do we want to use a `scale` for this? It's not possible to set the height and width?

2021-09-15 09:26 UTC, agagancarczyk commented on src/realm-settings/ProfilesTab.tsx
> +  });
Actually, when I investigated this again yesterday, I have noticed that in the old console they are using PUT request for deleting non-global profiles. I can try to implement it in the same way. wdyt?

2021-09-15 09:27 UTC, agagancarczyk commented on src/realm-settings/ProfilesTab.tsx
> +        <Link to={""} key={`link-${name}`}>
Yes, this will come later :)

2021-09-15 09:42 UTC, agagancarczyk commented on src/realm-settings/ProfilesTab.tsx
> +              >
yes, you are correct. I'll be working on this next.

2021-09-15 13:41 UTC, agagancarczyk commented
> > Looking awesome @agagancarczyk ! Thank you for making those updates.
> > One more thing:
> > <img alt="Screen Shot 2021-09-14 at 9 22 58 AM" width="238" src="https://user-images.githubusercontent.com/32821331/133265570-f3ba221f-9d34-4d31-9452-bc8781d72615.png">
> > According to the mock it looks like custom profiles should not have the "Global" label rendered next to them: https://marvelapp.com/prototype/h11728e/screen/81529211
> > Will you be adding tests to this PR? Once those are done looks good to merge 🙂
> 
> Thank you @jenny-s51 I'll fix this issue and add some tests :)

Fixed

2021-09-15 13:42 UTC, agagancarczyk commented on src/realm-settings/RealmSettingsSection.css
> +  transform: scale(1.6);
I think it's ok, let's leave it.

2021-09-15 14:17 UTC, jonkoops commented on src/realm-settings/ProfilesTab.tsx
> +  });
Oh wow, that sounds like a hack on the API side hahah. Yeah, if you can get that to work, why not :man_shrugging:

2021-09-15 14:19 UTC, jonkoops commented on src/realm-settings/RealmSettingsSection.css
> +  transform: scale(1.6);
Aight, I am no CSS magician like y'all so let's roll with it :smile:

2021-09-15 14:30 UTC, jonkoops requested changes

2021-09-15 14:30 UTC, jonkoops commented on src/realm-settings/ProfilesTab.tsx
> +  global?: boolean;
Looking at the code in the loader I think you can make this field required as it is always added to the object before `setProfiles()` is called.
```suggestion
  global: boolean;
```

2021-09-15 14:30 UTC, jonkoops commented on src/realm-settings/ProfilesTab.tsx
> +    const allClientProfiles = globalProfiles?.concat(profiles!);
Since `profiles` theoretically could be `undefined` it might be better to fall back to default here rather than using the non-null assertion operator.
```suggestion
    const allClientProfiles = globalProfiles?.concat(profiles ?? []);
```

2021-09-15 14:30 UTC, jonkoops commented on src/realm-settings/ProfilesTab.tsx
> +    <Link to={""} key={`label-${row.name}`}>
When providing a `key` prop it only has to be unique within the context it is used. I think you can pass `row.name` directly to achieve the same result.
```suggestion
    <Link to={""} key={row.name}>
```

2021-09-15 14:30 UTC, jonkoops commented on src/realm-settings/ProfilesTab.tsx
> +      )}
Since the `Label` component is shown conditionally and not in a `.map()` I believe there is no need to provide a `key` prop here. Also since the else condition is rendering an empty string perhaps it can be omitted?

```suggestion
      {row.global && <Label color="blue">{t("global")}</Label>}
```

2021-09-15 14:34 UTC, agagancarczyk commented on src/realm-settings/ProfilesTab.tsx
> +  global?: boolean;
You're right! thanks @jonkoops

2021-09-15 14:43 UTC, agagancarczyk commented on src/realm-settings/ProfilesTab.tsx
> +      )}
like this idea - nice catch! ty

2021-09-16 16:47 UTC, agagancarczyk commented
Great work @jonkoops !

2021-09-17 09:51 UTC, agagancarczyk commented
> > Looking awesome @agagancarczyk ! Thank you for making those updates.
> > One more thing:
> > <img alt="Screen Shot 2021-09-14 at 9 22 58 AM" width="238" src="https://user-images.githubusercontent.com/32821331/133265570-f3ba221f-9d34-4d31-9452-bc8781d72615.png">
> > According to the mock it looks like custom profiles should not have the "Global" label rendered next to them: https://marvelapp.com/prototype/h11728e/screen/81529211
> > Will you be adding tests to this PR? Once those are done looks good to merge 🙂
> 
> Thank you @jenny-s51 I'll fix this issue and add some tests :)

@jenny-s51 I'll need to merge this without tests because all tests are still failing. I'll add tests for all client profiles in my next PR - hope that's ok.

2021-09-17 10:45 UTC, jonkoops requested changes

2021-09-17 10:45 UTC, jonkoops commented on package-lock.json
> -      "name": "keycloak-admin-ui",
This change is generated by older versions of NPM. Make sure you are running the latest version of NPM (`npm install -g npm@latest`). After running `npm install` this should be removed automatically.

2021-09-17 10:45 UTC, jonkoops commented on src/realm-settings/routes/NewClientProfile.ts
> +export const NewClientProfileRoute: RouteDef = {
Can you also create a `toNewClientProfile()` function to accompany this route?

2021-09-17 10:45 UTC, jonkoops commented on src/realm-settings/ProfilesTab.tsx
> +                }
Make sure to use a link here and use a function for the route.

```tsx
<Button component={Link} to={toNewClientProfile({ realm })}></Button>
```

2021-09-17 10:45 UTC, jonkoops commented on src/realm-settings/ProfilesTab.tsx
> +    <Link to={""} key={row.name}>
We don't have a link for this page yet?

2021-09-17 10:45 UTC, jonkoops commented on src/realm-settings/NewClientProfileForm.tsx
> +    //TODO
This still needs to be implemented? Do you want to do that in this PR or the next?

2021-09-17 10:45 UTC, jonkoops commented on src/realm-settings/NewClientProfileForm.tsx
> +            >
Make sure to use a Link button here that actually renders an `a` element that is styled like a button.

2021-09-17 11:17 UTC, agagancarczyk commented on src/realm-settings/routes/NewClientProfile.ts
> +export const NewClientProfileRoute: RouteDef = {
Sure @jonkoops!

2021-09-17 11:25 UTC, agagancarczyk commented on src/realm-settings/ProfilesTab.tsx
> +                }
I have added this, but typescript is complaining about having "to=", would you know why this is working fine for other buttons but not mine?

2021-09-17 11:27 UTC, agagancarczyk commented on src/realm-settings/ProfilesTab.tsx
> +    <Link to={""} key={row.name}>
No, but I'll need to implement this next. It seems to be included in the designs.

2021-09-17 11:30 UTC, agagancarczyk commented on src/realm-settings/NewClientProfileForm.tsx
> +    //TODO
I'll work on this next. I'd prefer to include it in the next PR, if that's ok.

2021-09-17 16:29 UTC, jonkoops commented on src/realm-settings/ProfilesTab.tsx
> +                }
Yeah, this is a known issue in PatternFly. It can be resolved by adding a `// @ts-ignore`. I've pushed a commit to make the build pass again.

2021-09-17 16:30 UTC, jonkoops commented on src/realm-settings/ProfilesTab.tsx
> +    <Link to={""} key={row.name}>
Then consider this issue resolved.

2021-09-17 16:30 UTC, jonkoops commented on src/realm-settings/NewClientProfileForm.tsx
> +    //TODO
:ok: :+1:

2021-09-20 10:10 UTC, jonkoops requested changes

2021-09-20 10:10 UTC, jonkoops commented on src/realm-settings/NewClientProfileForm.tsx
> +              onClick={() =>
This can still be a link component:

```
component={Link}
to={`/${realm}/realm-settings/clientPolicies`}
```

2021-09-20 12:40 UTC, jonkoops approved these changes
LGTM :heavy_check_mark:

2021-09-20 12:42 UTC, merged