Generic view header
keycloak/keycloak-admin-ui pull request #115
Opened 2020-09-23 06:50 UTC by edewit

Can be used as a header for a from or view as well as a specific item with actions

2020-09-24 18:31 UTC, ssilvert requested changes

2020-09-24 18:31 UTC, ssilvert commented on src/realm/messages.json
> +    "realmExplain": "A realm is something",
You can use this text: `A realm manages a set of users, credentials, roles, and groups. A user belongs to and logs into a realm. Realms are isolated from one another and can only manage and authenticate the users that they control.`

2020-09-24 23:53 UTC, dlabaj reviewed
One minor comment otherwise looks great.

2020-09-24 23:53 UTC, dlabaj commented on src/clients/ClientsSection.tsx
> +              onPerPageSelect={(f, m) => {
Change to something other then f and m

2020-09-25 14:03 UTC, dlabaj approved these changes
LGTM

2020-09-25 17:28 UTC, ssilvert approved these changes

2020-09-25 17:29 UTC, merged