fixes some issue on the events tab
keycloak/keycloak-admin-ui pull request #1150
Opened 2021-09-14 07:41 UTC by edewit

* user details can be empty
* fix the number of rows displayed with collapse

2021-09-14 10:20 UTC, jonkoops requested changes

2021-09-14 10:20 UTC, jonkoops commented on src/components/table-toolbar/KeycloakDataTable.tsx
> +            isOpen: detailColumns?.[0]?.enabled?.(value) ? false : undefined,
If I get this correctly `isOpen` is `false` if `enabled()` is `true`? Otherwise it's also a falsy value, is that correct behavior? I was expecting something like:

```suggestion
            isOpen: detailColumns?.[0]?.enabled?.(value) ?? false,
```

2021-09-14 10:20 UTC, jonkoops commented on src/components/table-toolbar/KeycloakDataTable.tsx
> +            isOpen: detailColumns?.[0]?.enabled?.(value) ? false : undefined,
Since this logic is used twice in this function perhaps it can be extracted into a separate variable?

```ts
const isColumnEnabled = detailColumns?.[0]?.enabled?.(value) ?? false;
```

2021-09-21 09:41 UTC, edewit commented on src/components/table-toolbar/KeycloakDataTable.tsx
> +            isOpen: detailColumns?.[0]?.enabled?.(value) ? false : undefined,
No, it should only be `false` when "detailColumns" are not undefined and enabled for that value, but your right I can make it a function

2021-09-21 12:16 UTC, edewit commented
fixes: #1156

2021-09-21 13:32 UTC, ssilvert commented
> * fix the number of rows displayed with collapse

What do you mean by this?

2021-09-21 19:09 UTC, ssilvert commented
BTW, I verified that this does fix user events where there is no user, like failed login.  That works nicely.

I'm just not sure what I should test for "fix the number of rows displayed with collapse"

2021-09-22 06:47 UTC, edewit commented
@ssilvert it does fix #1156 the problem was the collapsible rows where counted as rows so the number of rows show was always half of the actual just like you describe in issue 1156

2021-09-22 07:05 UTC, edewit commented
@ssilvert right forgot about the pagination numbers, fixed those now as well

2021-09-22 08:08 UTC, jonkoops requested changes

2021-09-22 08:08 UTC, jonkoops commented on src/components/table-toolbar/KeycloakDataTable.tsx
> +            isOpen: isDetailColumnsEnabled(value) ? false : undefined,
Is the result of this expression not always `false` or `undefined`? Perhaps you can default to `false` here?
```suggestion
            isOpen: false,
```

2021-09-22 08:08 UTC, jonkoops commented on src/components/table-toolbar/KeycloakDataTable.tsx
> +  };
Since arrow functions return the value from the last statement this code could be shortened a bit:

```suggestion
  const renderCell = (columns: (Field<T> | DetailField<T>)[], value: T) =>
    columns.map((col) => {
      if (col.cellRenderer) {
        return { title: col.cellRenderer(value) };
      }
      return _.get(value, col.name);
    });
```

You could make it even more compact if you use a ternary: 

```suggestion
  const renderCell = (columns: (Field<T> | DetailField<T>)[], value: T) =>
    columns.map((col) =>
      col.cellRenderer
        ? { title: col.cellRenderer(value) }
        : _.get(value, col.name)
    );
```

2021-09-22 08:57 UTC, edewit commented on src/components/table-toolbar/KeycloakDataTable.tsx
> +            isOpen: isDetailColumnsEnabled(value) ? false : undefined,
false is not the same as undefined when we always set it to false it will always show the collapse icon we only want that when detail columns are enabled

2021-09-22 18:37 UTC, ssilvert commented
> @ssilvert right forgot about the pagination numbers, fixed those now as well

Yes, verified that this fixes #1156

2021-09-23 15:06 UTC, jonkoops commented on src/components/table-toolbar/KeycloakDataTable.tsx
> +            isOpen: isDetailColumnsEnabled(value) ? false : undefined,
I see, thanks for clarifying.

2021-09-26 18:34 UTC, ssilvert commented
Group test should be fixed now if you rebase.

2021-09-27 08:37 UTC, jonkoops approved these changes

2021-09-27 08:52 UTC, merged