fetch and save client
keycloak/keycloak-admin-ui pull request #116
Opened 2020-09-23 12:32 UTC by edewit

2020-09-24 18:57 UTC, ssilvert requested changes

2020-09-24 18:57 UTC, ssilvert commented on src/clients/messages.json
> +    "clientSaveSuccess": "Client successful updated",
Should say either `Client successfully updated` or `Client update successful`

2020-09-24 18:57 UTC, ssilvert commented on src/clients/messages.json
>      "clientImportSuccess": "Client imported successful",
Should say either `Client import successful` or `Client imported successfully`

2020-09-24 18:57 UTC, ssilvert commented on src/clients/ClientSettings.tsx
> +  const [add, Alerts] = useAlerts();
Can we change this from `add` to `alert`?   `add` is too generic.  The code will read much nicer if we change it.

2020-09-24 23:48 UTC, dlabaj reviewed
Looks good a few minor comments.

2020-09-24 23:48 UTC, dlabaj commented on src/clients/ClientList.tsx
> +        {field.indexOf("true") === -1 && <Badge isRead>Disabled</Badge>}
Can we use a constant instead of -1

2020-09-24 23:48 UTC, dlabaj commented on src/clients/ClientList.tsx
> +      r.clientId = r.id + "#" + r.clientId + "#" + r.enabled;
Use something other then r to describe the argument.

2020-09-24 23:48 UTC, dlabaj commented on src/clients/ClientList.tsx
> +              clientCopy.clientId = clientCopy.clientId.split("#")[1];
Use a constant instead of 1

2020-09-24 23:48 UTC, dlabaj commented on src/clients/ClientSettings.tsx
> +    const func = async () => {
Can you do this with an IIFE instead of declaring a const?

2020-09-24 23:48 UTC, dlabaj commented on src/clients/messages.json
> +    "clientSaveSuccess": "Client successful updated",
Like Client successfully updated.

2020-09-24 23:48 UTC, dlabaj commented on src/components/multi-line-input/MultiLineInput.tsx
> +  return field.map((f) => {
change argument to something other then f.

2020-09-25 05:50 UTC, edewit commented on src/clients/ClientList.tsx
> +        {field.indexOf("true") === -1 && <Badge isRead>Disabled</Badge>}
I think usually people don't create constants for -1

2020-09-25 13:17 UTC, dlabaj commented on src/clients/ClientList.tsx
> +        {field.indexOf("true") === -1 && <Badge isRead>Disabled</Badge>}
okay

2020-09-25 13:17 UTC, dlabaj approved these changes

2020-09-25 17:42 UTC, ssilvert approved these changes

2020-09-25 17:42 UTC, merged