changed to use code editor
keycloak/keycloak-admin-ui pull request #1161
Opened 2021-09-15 09:44 UTC by edewit

use the `<CodeEditor` on the `<JsonFileUpload` component

2021-09-15 14:55 UTC, jonkoops requested changes

2021-09-15 14:55 UTC, jonkoops commented on src/components/json-file-upload/JsonFileUpload.tsx
> +        value: value as string,
Are you sure this value will always be a string?

2021-09-15 14:55 UTC, jonkoops commented on src/components/json-file-upload/JsonFileUpload.tsx
> +              code={fileUpload.value as string}
This is already always a string according to the type, so this type cast can be removed.
```suggestion
              code={fileUpload.value}
```

2021-09-15 14:55 UTC, jonkoops commented on src/components/json-file-upload/JsonFileUpload.tsx
> +              onChange={(value, event) =>
Would be nice if we get an actual type for this event, perhaps we can open a bug upstream?

2021-09-16 17:17 UTC, ssilvert commented on src/components/json-file-upload/JsonFileUpload.tsx
> +              onChange={(value, event) =>
+1

2021-09-22 08:35 UTC, jonkoops approved these changes

2021-09-22 08:54 UTC, merged