initial version of confirm dialog
keycloak/keycloak-admin-ui pull request #117
Opened 2020-09-23 14:47 UTC by edewit

2020-09-24 14:40 UTC, srambach commented
Should the first two stories for this display the modal?
By default, as a confirmation modal, I think this should use a primary button, and a variant added to make it a danger button.
I think we should also make the modal small by default, and allow a variant for the other sizes if needed. (unless you have mockups saying otherwise?)

2020-09-24 19:07 UTC, ssilvert requested changes

2020-09-24 19:07 UTC, ssilvert commented on src/components/confirm-dialog/ConfirmDialog.tsx
> +            if (onCancel) onCancel();
If there is no cancel handler, we shouldn't snow the cancel button.

2020-09-24 19:28 UTC, ssilvert commented
> Should the first two stories for this display the modal?
> By default, as a confirmation modal, I think this should use a primary button, and a variant added to make it a danger button.
> I think we should also make the modal small by default, and allow a variant for the other sizes if needed. (unless you have mockups saying otherwise?)

Agree with @srambach.  Otherwise, LGTM.

2020-09-24 23:34 UTC, dlabaj approved these changes
LGTM other then sarah's comment

2020-09-25 06:13 UTC, edewit commented
@srambach ahh yes it should show the dialog, fixed that now

2020-09-25 13:17 UTC, merged