SAML ID provider cleanup
keycloak/keycloak-admin-ui pull request #1170
Opened 2021-09-16 13:43 UTC by mfrances17

## Motivation
Several fields in the original SAML identity provider were not working in the first pass, to be fixed later. 

## Brief Description
This fixes it so all SAML fields should be working as expected. Any fields that are not working from here on should be filed as issues.

## Verification Steps
Verify that the following fields now work as expected in the SAML ID provider config, as they worked in the old console (set the value in the old console and verify that the new console reads the value, etc):
Single logout service URL
NameID policy format
Principal type
Principal attribute
Want AuthnRequests signed
Signature algorithm
SAML signature key name
Validating X509 certificates
Pass subject
Allowed clock skew
Comparison
AuthnContext ClassRefs
AuthnContext DeclRefs
Stored tokens readable
Hide on login page

## Checklist:
- [x] Code has been tested locally by PR requester
- [x] User-visible strings are using the react-i18next framework (useTranslation)
- [x] Help has been implemented

## Additional Notes
Cypress tests coming in separate PR.

2021-09-16 13:59 UTC, jonkoops requested changes

2021-09-16 13:59 UTC, jonkoops commented on package-lock.json
> -      "name": "keycloak-admin-ui",
This change is generated by older versions of NPM, but makes no functional difference. Make sure to update to the latest version of NPM and this change should disappear. You can upgrade NPM by running `npm install -g npm@latest`. 

Alternatively using the latest version of Node should also resolve this, if you have NVM tyou can run `nvm install 16 && nvm alias default 16`.

2021-09-16 13:59 UTC, jonkoops commented on src/identity-providers/add/AdvancedSettings.tsx
> +      setFlows(flows.filter((flow) => flow.providerId === "basic-flow")),
Nice, thanks for cleaning that up!

2021-09-16 13:59 UTC, jonkoops commented on src/identity-providers/add/DescriptorSettings.tsx
> +    control: control,
If the value has the same name as the key the part after the colon can be omitted.
```suggestion
    control,
```

2021-09-16 13:59 UTC, jonkoops commented on src/identity-providers/add/ReqAuthnConstraintsSettings.tsx
> +              onToggle={() => setComparisonOpen(!comparisonOpen)}
The `onToggle` prop provides a value in the callback to set the open state so we don't have to control this ourselves.
```suggestion
              onToggle={(isExpanded) => setComparisonOpen(isExpanded)}
```

2021-09-16 15:26 UTC, mfrances17 commented on package-lock.json
> -      "name": "keycloak-admin-ui",
hmmm, i'm already using v16.1.0 of node i'm surprised that's the issue, but i will try updating, thanks

2021-09-16 18:15 UTC, mfrances17 commented on package-lock.json
> -      "name": "keycloak-admin-ui",
i don't know why i bother questioning it, you were right - fixed when i updated to the latest npm, thanks!

2021-09-16 18:16 UTC, mfrances17 commented on src/identity-providers/add/DescriptorSettings.tsx
> +    control: control,
fixed, always forget this one - thanks

2021-09-16 18:16 UTC, mfrances17 commented on src/identity-providers/add/ReqAuthnConstraintsSettings.tsx
> +              onToggle={() => setComparisonOpen(!comparisonOpen)}
always forget this one as well - fixed, ty

2021-09-17 10:35 UTC, jonkoops commented on src/identity-providers/add/DescriptorSettings.tsx
> +    control: control,
Yeah, might be worth adding a linting rule for it.

2021-09-17 10:35 UTC, jonkoops approved these changes

2021-09-17 17:51 UTC, merged