Login tab fix
keycloak/keycloak-admin-ui pull request #1183
Opened 2021-09-16 19:17 UTC by jenny-s51

## Motivation

Closes #1158

## Verification Steps

1. Go to Realm Settings -> Login Tab
2. Verify that the all switches work as expected.

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

## Additional Notes

2021-09-17 18:29 UTC, mfrances17 requested changes
It's really odd that the changes are automatically saved when each switch changes - the old console had a save/cancel. Personally I would lob this back at design as to why it was changed  to automatically update on every switch status change. 

Aside from that, in the old console, if you turned on 'User registration', you would get another option 'Email as username' - wondering if the intent was to omit this. There is no such option in the new UI. Likewise with the 'Require SSL' dropdown - was this omitted purposely?

2021-09-20 10:07 UTC, jonkoops requested changes
Looks like the tests are failing.

2021-09-20 10:07 UTC, jonkoops commented on cypress/integration/realm_settings_test.spec.ts
> +    // sidebarPage.goToRealm(realmName);
Some commented out code, I believe this might be causing some test failures.

2021-09-21 12:37 UTC, jenny-s51 commented
> It's really odd that the changes are automatically saved when each switch changes status - the old console had a save/cancel. Personally I would lob this back at design as to why it was changed to automatically update on every switch status change.

@mfrances17 certainly valid points! We had a team discussion about this in Zulip a few months ago -- [here is the link to the thread](https://keycloak.zulipchat.com/#narrow/stream/251649-dev-new-admin/topic/Realm.20settings.20login.20screen)! 

Based on Haley's response it was decided to proceed with the implementation without the save/cancel buttons. 

> Aside from that, in the old console, the enable/disable of the 'Email as username' switch was controlled by the 'User registration' switch. In the new implementation, 'Email as username' is always enabled regardless of the status of 'User registration' - wondering if this was the intent? Also, the old console had a 'Require SSL' dropdown - was this omitted purposely?

Good questions. @yih-wang could you kindly speak to this?

2021-09-22 13:21 UTC, yih-wang commented
@mfrances17 @jenny-s51 

> Aside from that, in the old console, the enable/disable of the 'Email as username' switch was controlled by the 'User registration' switch. In the new implementation, 'Email as username' is always enabled regardless of the status of 'User registration' - wondering if this was the intent?

Yes. The email could be used as a username no matter whether we allow the users self-registration. It's not correct in the old console. So we changed that in the new one.

> Also, the old console had a 'Require SSL' dropdown - was this omitted purposely?

This one is moved to the General tab.

2021-09-22 19:27 UTC, mfrances17 approved these changes

2021-09-22 19:28 UTC, mfrances17 commented
thanks @yih-wang and @jenny-s51, your responses addressed my only concerns. LGTM.

2021-09-22 20:34 UTC, jenny-s51 commented
@ssilvert nice catch, looking into this. Thank you @mfrances17

2021-09-23 08:35 UTC, jonkoops approved these changes
LGTM

2021-09-27 09:55 UTC, jonkoops requested changes

2021-09-27 09:55 UTC, jonkoops commented on src/realm-settings/RealmSettingsSection.tsx
> +    setTimeout(update, 1000);
What is the reason there is a `setTimeout` here with a hardcoded value?

2021-09-27 09:55 UTC, jonkoops commented on src/realm-settings/RealmSettingsSection.tsx
> +    setKey(new Date().getTime());
Instead of using a date this value could also be incremented.
```suggestion
    setKey(key + 1);
```

2021-09-27 12:40 UTC, ssilvert requested changes

2021-09-27 12:40 UTC, ssilvert commented on src/realm-settings/LoginTab.tsx
> +                    onChange(value);
Do you need a call to refresh() here?

2021-09-27 12:40 UTC, ssilvert commented on src/realm-settings/LoginTab.tsx
> +                    refresh();
These three lines are repeated over and over.  Suggest you factor it out into a function.

2021-09-27 13:10 UTC, jenny-s51 commented on src/realm-settings/RealmSettingsSection.tsx
> +    setTimeout(update, 1000);
@jonkoops Using the `setTimeout` here was suggested by @edewit, due to the bug @ssilvert noticed above. There is a server-side bug that causes the re-fetching to happen too quickly, and therefore the switches are not updated correctly. @edewit suggested to use `setTimeout` to delay the fetching which solved this.

2021-09-27 14:52 UTC, jonkoops commented on src/realm-settings/RealmSettingsSection.tsx
> +    setTimeout(update, 1000);
Oh wow, that is really strange. Perhaps you could add a comment to explain this in the code so people do not get confused in the future?

2021-09-27 14:53 UTC, jonkoops approved these changes
LGTM

2021-09-27 14:56 UTC, jenny-s51 commented on src/realm-settings/RealmSettingsSection.tsx
> +    setTimeout(update, 1000);
Good idea. Done :)

2021-09-27 17:15 UTC, ssilvert approved these changes

2021-09-27 17:15 UTC, merged