deleted original screens,  works like old console
keycloak/keycloak-admin-ui pull request #1187
Opened 2021-09-17 13:39 UTC by edewit

These mapper screens are dyanmic
so introduced components that make up the form

fixes: #1099

2021-09-17 14:34 UTC, jonkoops requested changes

2021-09-17 14:34 UTC, jonkoops commented on src/client-scopes/routes/Mapper.ts
> +  type: string;
Let's keep the order in the interface the same as the path.
```suggestion
  id: string;
  type: string;
  mapperId: string;
```

2021-09-17 14:34 UTC, jonkoops commented on src/client-scopes/details/MappingDetails.tsx
> +              to={toClientScope({ realm, id, type, tab: "mappers" })}
Nice! Great that this is a link now!

2021-09-17 14:34 UTC, jonkoops commented on src/client-scopes/add/components/components.ts
> +];
You can give this one a constant type so that it can be narrowed down further.
```suggestion
export const ComponentTypes = [
  "String",
  "boolean",
  "List",
  "Role",
  "Script",
] as const;
```

2021-09-17 14:34 UTC, jonkoops commented on src/client-scopes/add/components/components.ts
> +export const COMPONENTS: { [index in Components]: FC<ComponentProps> } = {
We're using `FunctionComponent` in other places, let's keep that consistent.
```suggestion
export const COMPONENTS: {
  [index in Components]: FunctionComponent<ComponentProps>;
} = {
```

2021-09-17 14:34 UTC, jonkoops commented on src/client-scopes/details/MappingDetails.tsx
> +              } else {
Instead of using `includes()` with a type-cast you could write a function that uses a [type-guard](https://www.typescriptlang.org/docs/handbook/advanced-types.html#user-defined-type-guards) to narrow down the type. For example:

```ts
const isValidComponentType = (value: string): value is Components => value in COMPONENTS;
```

Now you can use this function to narrow down the type without needing to cast it.
```suggestion
              if (isValidComponentType(componentType)) {
                const Component = COMPONENTS[componentType];
                return <Component key={property.name} {...property} />;
              } else {
```

2021-09-17 14:34 UTC, jonkoops commented on src/client-scopes/details/MapperList.tsx
> +  const url = `/${realm}/client-scopes/${clientScope.id}/${type}/mappers`;
Any chance we can use a router function here instead?

2021-09-17 14:34 UTC, jonkoops commented on src/client-scopes/add/components/RoleComponent.tsx
> +                  onToggle={() => setRoleOpen(!roleOpen)}
```suggestion
                  onToggle={(isExpanded) => setRoleOpen(isExpanded)}
```

2021-09-18 12:34 UTC, edewit commented on src/client-scopes/add/components/components.ts
> +];
I tried that first, but that doesn't work when you want to do:
```typescript
const componentType = property.type!;
if (ComponentTypes.includes(componentType)) {
  // only supported compnent types
```
because in this case when you use the `as const` then `compnentType` needs to be one of the types so defies the check

2021-09-18 12:37 UTC, edewit commented on src/client-scopes/add/components/components.ts
> +export const COMPONENTS: { [index in Components]: FC<ComponentProps> } = {
`FC` is just shorthand for `FunctionComponent`, from react:
```typescript
type FC<P = {}> = FunctionComponent<P>;
```
but I'll change it

2021-09-18 14:39 UTC, jonkoops commented on src/client-scopes/add/components/components.ts
> +];
Correct, I have a utility function in [another comment](https://github.com/keycloak/keycloak-admin-ui/pull/1187#discussion_r711106658) that fixes that.

2021-09-18 15:15 UTC, edewit commented on src/client-scopes/details/MappingDetails.tsx
> +              } else {
Yes it's a cast, but it can never fail as Components are all the Components that are in ComponentTypes. And your function is also casting by specifying the return type.

2021-09-20 15:30 UTC, jonkoops approved these changes

2021-09-20 15:31 UTC, merged