initial version of the breadcrumb component
keycloak/keycloak-admin-ui pull request #119
Opened 2020-09-25 11:17 UTC by edewit

2020-09-25 17:43 UTC, ssilvert commented
@edewit Please resolve conflict.

2020-09-28 19:50 UTC, ssilvert requested changes
@edewit This looks good.  Are there any screens where I can see it in action?

2020-09-28 19:50 UTC, ssilvert commented on src/route-config.ts
> +    breadcrumb: "Users",
Please go ahead and localize these.

2020-09-28 20:35 UTC, srambach commented
Making a component `Breadcrumbs` (plural) seems to ask for mistakes since there's already the PatternFly component `Breadcrumb` - could it be something like `PageBreadcrumb` instead?

2020-09-28 23:17 UTC, dlabaj requested changes

2020-09-28 23:17 UTC, dlabaj commented on package.json
> +    "use-react-router-breadcrumbs": "^1.0.4"
We are adding a new library?  Do we really need this?

2020-09-28 23:17 UTC, dlabaj commented on src/components/bread-crumb/__tests__/__snapshots__/BreadCrumbs.test.tsx.snap
> +<BreadCrumbs>
Let's call this something else it's too close to Breadcrumb and can cause coding errors.

2020-09-29 06:36 UTC, edewit commented on package.json
> +    "use-react-router-breadcrumbs": "^1.0.4"
we don't we can copy the code this is all of the code: https://github.com/icd2k3/use-react-router-breadcrumbs/blob/master/src/index.tsx

2020-09-29 07:02 UTC, edewit commented
@srambach I made it `PageBreadcrumbs` because it renders contains multiple crumbs IMO

2020-09-29 18:05 UTC, ssilvert commented on package.json
> +    "use-react-router-breadcrumbs": "^1.0.4"
@dlabaj @edewit I'm not crazy about adding more libraries either.  But I think copying the code is even worse.  Let's just use the library.  Then at least we don't have to maintain the code.

2020-09-29 18:18 UTC, ssilvert requested changes
I can see it in action now.  Looks good except that there needs to be spacing between the breadcrumbs and the page title.

2020-09-29 18:18 UTC, ssilvert commented
@edewit Oh, and also a conflict.

2020-09-29 18:33 UTC, dlabaj commented on package.json
> +    "use-react-router-breadcrumbs": "^1.0.4"
agreed I don't want to copy the code.  Was just wondering if we really needed it or not.  It's small so we can bring it in.

2020-09-29 18:33 UTC, dlabaj approved these changes

2020-09-30 06:44 UTC, edewit commented
> I can see it in action now. Looks good except that there needs to be spacing between the breadcrumbs and the page title.

@srambach I guess just adding some padding would is not the way to go for this?

2020-09-30 16:13 UTC, srambach commented
> > I can see it in action now. Looks good except that there needs to be spacing between the breadcrumbs and the page title.
> 
> @srambach I guess just adding some padding would is not the way to go for this?

Probably not ;-) Can the breadcrumb be passed to the Page? That seems to be the way it's meant to be built now. (I think there used to be a page section variant for breadcrumbs but I don't see it now) https://www.patternfly.org/v4/components/page/react-demos

2020-10-01 14:25 UTC, ssilvert approved these changes

2020-10-01 14:25 UTC, merged