Change the way cypress tests run
keycloak/keycloak-admin-ui pull request #1210
Opened 2021-09-23 14:04 UTC by edewit

now creates a test realm before starting the tests and logs in only for the test case instead of each time

2021-09-23 14:24 UTC, jonkoops requested changes

2021-09-23 14:24 UTC, jonkoops commented on cypress/support/util/keycloak_hooks.ts
> +export const TEST_REALM = "test" as const;
Constant variables that are assigned a string literal are already a constant type by default.
```suggestion
export const TEST_REALM = "test";
```

2021-09-23 14:24 UTC, jonkoops commented on cypress/support/util/AdminClient.ts
> +    const theRealm = (await this.client.realms.findOne({ realm })) as
Looks like the return type of the `findOne()` method is incorrect, can we fix this upstream in the Admin Client?

2021-09-23 14:24 UTC, jonkoops commented on cypress/support/pages/admin_console/manage/realm_settings/RealmSettingsPage.ts
> +    const keysUrl = "/auth/admin/realms/test/keys";
Perhaps we can use the `TEST_REALM` constant here as well?

2021-09-23 14:24 UTC, jonkoops commented on cypress/support/pages/admin_console/manage/realm_roles/AssociatedRolesPage.ts
> +    const load = "/auth/admin/realms/test/clients";
Perhaps we can use the `TEST_REALM` constant here as well?

2021-09-23 14:24 UTC, jonkoops commented on cypress/support/pages/admin_console/manage/providers/ProviderPage.ts
> -    cy.wait(1000);
Nice cleanup!

2021-09-23 14:24 UTC, jonkoops commented on cypress/support/pages/admin_console/manage/events/AdminEventsTab.ts
> +    cy.intercept("/auth/admin/realms/test/admin-events*").as("eventsFetch");
Perhaps we can use the `TEST_REALM` constant here as well?

2021-09-23 14:24 UTC, jonkoops commented on cypress/support/pages/admin_console/manage/identity_providers/AddMapperPage.ts
> +    const load = "/auth/admin/realms/test/roles";
Perhaps we can use the `TEST_REALM` constant here as well?

2021-09-23 14:24 UTC, jonkoops commented on cypress/support/pages/admin_console/ListingPage.ts
> +      const searchUrl = `/auth/admin/realms/test/*${searchValue}*`;
Perhaps we can use the `TEST_REALM` constant here as well?

2021-09-24 06:39 UTC, edewit commented on cypress/support/util/AdminClient.ts
> +    const theRealm = (await this.client.realms.findOne({ realm })) as
for sure

2021-10-05 12:14 UTC, closed without merging