Added missing labels on the client scope mappers
keycloak/keycloak-admin-ui pull request #1217
Opened 2021-09-24 08:04 UTC by edewit

fixes: #1216

2021-09-24 08:05 UTC, edewit commented
formatted the help text on the Javascript mapper:
![image](https://user-images.githubusercontent.com/51133/134640376-e9517e86-f564-4ba5-909c-75e0948419a1.png)

2021-09-24 16:14 UTC, jonkoops requested changes

2021-09-24 16:14 UTC, jonkoops commented on src/client-scopes/add/components/ScriptComponent.tsx
> +                <Fragment key={key}>
Instead of using the index as a key perhaps you can use the item itself?
```suggestion
                <Fragment key={item}>
```

2021-09-24 16:14 UTC, jonkoops commented on src/client-scopes/add/components/ScriptComponent.tsx
> +          }
If you are looking to preserve the white-space, perhaps you can wrap this in a `pre` tag instead?
```suggestion
          helpText={<pre>{t(helpText!)}</pre>}
```

2021-09-26 18:32 UTC, ssilvert commented
Group test should be fixed now if you rebase.

2021-09-27 08:06 UTC, edewit commented on src/client-scopes/add/components/ScriptComponent.tsx
> +                <Fragment key={key}>
Doesn't really matter as it's a static list

2021-09-27 08:10 UTC, edewit commented on src/client-scopes/add/components/ScriptComponent.tsx
> +          }
a `<pre` will use another font and mess up the layout:
![image](https://user-images.githubusercontent.com/51133/134869530-ce6950e6-17e9-44ef-a7f4-cb1327266660.png)

2021-09-27 09:40 UTC, jonkoops commented on src/client-scopes/add/components/ScriptComponent.tsx
> +                <Fragment key={key}>
True, still better not to do it out of convention. I'd like to add an ESLint rule for this at some point as well.

2021-09-27 09:41 UTC, jonkoops commented on src/client-scopes/add/components/ScriptComponent.tsx
> +          }
Ahhh yes. We can use some styling here instead by adding `white-space: pre-wrap;` to the containing element.

2021-09-27 10:30 UTC, jonkoops approved these changes

2021-09-27 10:32 UTC, merged