Identity Providers(Mappers): Add create/edit functionality for mappers of type Username Template Importer
keycloak/keycloak-admin-ui pull request #1248
Opened 2021-09-28 15:08 UTC by jenny-s51

## Motivation

Towards #1206

## Verification Steps

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

2021-09-29 07:34 UTC, edewit requested changes
Test seems to fail

2021-09-29 07:34 UTC, edewit commented on src/identity-providers/add/AddMapper.tsx
> +
This is not needed, because this is already done in the `convertToFormValues` as well

2021-09-29 07:34 UTC, edewit commented on src/identity-providers/add/AddMapper.tsx
> +                {" "}
this space can be removed right?

2021-09-29 13:54 UTC, jonkoops requested changes

2021-09-29 13:54 UTC, jonkoops commented on src/identity-providers/add/AddMapper.tsx
> +            {form.getValues().identityProviderMapper ===
Since there are multiple calls to `form.getValues()` it might be a good idea to store this in a variable first.

```ts
const formValues = form.getValues();
```

2021-09-29 13:54 UTC, jonkoops commented on src/identity-providers/add/AddMapper.tsx
> +                </FormGroup>{" "}
Perhaps this white space can be removed?
```suggestion
                </FormGroup>
```

2021-09-29 13:54 UTC, jonkoops commented on src/identity-providers/add/AddMapper.tsx
> +            )}{" "}
Perhaps this white space can be removed?
```suggestion
            )}
```

2021-09-29 13:54 UTC, jonkoops commented on src/identity-providers/add/AddMapper.tsx
> +                "saml-role-idp-mapper") && (
You could use `.includes()` here to shorten this statement.

```ts
[
  "saml-advanced-role-idp-mapper",
  "oidc-hardcoded-role-idp-mapper",
  "saml-role-idp-mapper",
].includes(formValues.identityProviderMapper);
```

2021-09-30 09:00 UTC, jonkoops approved these changes
LGTM

2021-09-30 09:26 UTC, edewit approved these changes

2021-09-30 09:26 UTC, merged