Added client setttings header with actions
keycloak/keycloak-admin-ui pull request #125
Opened 2020-09-29 10:06 UTC by edewit

2020-09-29 14:50 UTC, srambach commented on src/clients/ClientSettings.tsx
> +            <FormGroup label={t("consentRequired")} fieldId="kc-consent">
Please add `hasNoPaddingTop` to the form group to align the switch

2020-09-29 14:50 UTC, srambach commented on src/clients/ClientSettings.tsx
> +            <FormGroup
Please add `hasNoPaddingTop` to the form group to align the switch

2020-09-29 14:59 UTC, srambach commented on src/clients/ClientSettings.tsx
> +      <PageSection>
I think this needs a `variant="light"`

2020-09-29 18:32 UTC, ssilvert requested changes
When you go to Client Settings page, the header still says `Client list`

2020-09-29 18:32 UTC, ssilvert commented on src/clients/ClientSettings.tsx
> +                    isPlaceholder={true}
`Action` should not show as a selectable value in the dropdown.

2020-09-29 18:32 UTC, ssilvert commented on src/clients/ClientSettings.tsx
> +        <Alerts />
Not something to address in this PR, but I don't understand why we need to keep adding the Alerts component over and over.  I would think that we should have only one instance of the Alerts component that all screens could add alerts to.

2020-09-30 06:35 UTC, edewit commented on src/clients/ClientSettings.tsx
> +                    isPlaceholder={true}
That is the way it is with patternfly even if you give add the `isPlaceholder` it add it to the dropdown. @srambach do you know how you can get a placeholder to not show up in the dropdown?

2020-09-30 06:36 UTC, edewit commented on src/clients/ClientSettings.tsx
> +        <Alerts />
I don't want to have a static component that we add like in the other console.

2020-09-30 06:52 UTC, edewit commented on src/clients/ClientSettings.tsx
> +        <Alerts />
created issue #132 for this.

2020-09-30 07:27 UTC, edewit commented on src/clients/ClientSettings.tsx
> +                    isPlaceholder={true}
ahhh... I see it's resolved in 37c1576

2020-09-30 18:03 UTC, ssilvert commented
@srambach If you agree that all your issues are resolved then please approve.

2020-09-30 19:26 UTC, srambach commented on src/clients/ClientSettings.tsx
> +                titleKey="clients:clientList"
Is this still the wrong page title?  
Is this the mockup, and it should be the client name and have breadcrumbs?

2020-10-01 06:33 UTC, edewit commented on src/clients/ClientSettings.tsx
> +                titleKey="clients:clientList"
Changed to use the client name and the breadcrumbs are done in #119 and yes that is the mockup

2020-10-01 19:57 UTC, srambach commented on src/clients/ClientSettings.tsx
> +                titleKey="clients:clientList"
I'm just seeing a blank now, even though there's a clientID shown in the list...?

2020-10-02 08:21 UTC, edewit commented on src/clients/ClientSettings.tsx
> +                titleKey="clients:clientList"
strange it seems to works sometimes... now I really fixed it ;)

2020-10-02 13:49 UTC, ssilvert approved these changes

2020-10-02 13:56 UTC, merged