Add tests for bearer-only client details
keycloak/keycloak-admin-ui pull request #1270
Opened 2021-09-29 13:42 UTC by jonkoops

## Motivation
I added some logic to show a tooltip for bearer-only clients that was not yet tested, this PR adds the missing tests.

2021-09-29 13:45 UTC, agagancarczyk approved these changes

2021-09-29 13:46 UTC, edewit approved these changes

2021-09-29 13:46 UTC, edewit commented on cypress/integration/clients_test.spec.ts
> +      });
great way to get a bearer only client

2021-09-29 18:44 UTC, ssilvert requested changes
I found an issue with the bearer only client.  The fix looks easy, but we need a test for the use case so you may want to include both the fix and the new test with this PR.

https://github.com/keycloak/keycloak-admin-ui/issues/1276

2021-09-30 10:04 UTC, jonkoops commented
@ssilvert I'll create some separate PR for those issues, I don't want to pull in too much logic into a single PR.

2021-09-30 10:04 UTC, merged