Updated the test ldap settings with second button
keycloak/keycloak-admin-ui pull request #1275
Opened 2021-09-29 15:46 UTC by edewit

fixes: #1114

2021-09-30 09:06 UTC, jonkoops requested changes

2021-09-30 09:06 UTC, jonkoops commented on src/client-scopes/add/MapperDialog.tsx
> +    });
This is quite an expensive operation to do on every render, I would recommend that you put it in a `useMemo()`.

2021-09-30 09:06 UTC, jonkoops commented on src/client-scopes/add/MapperDialog.tsx
> +            .map((mapper) => (
This is quite an expensive operation to do on every render, I would recommend to use `useMemo()` here as well.

2021-09-30 09:06 UTC, jonkoops commented on src/user-federation/ldap/LdapSettingsConnection.tsx
> +    settings[key] = _.isArray(value) ? value[0] : "";
You can also use [`Array.isArray()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray) here instead of lodash.
```suggestion
    settings[key] = Array.isArray(value) ? value[0] : "";
```

2021-10-04 11:07 UTC, jonkoops commented on src/client-scopes/add/MapperDialog.tsx
> +            .map((mapper) => (
@edewit this is still being done on each render.

2021-10-04 11:07 UTC, jonkoops requested changes
Looks like the tests are failing

2021-10-05 10:22 UTC, jonkoops approved these changes

2021-10-05 10:22 UTC, jonkoops commented on src/client-scopes/add/MapperDialog.test.tsx
> +import "@testing-library/jest-dom";
There is no need to import this from the testing library as this is already included in the Jest setup.

2021-10-05 10:23 UTC, jonkoops commented on src/client-scopes/add/MapperDialog.test.tsx
> +import "@testing-library/jest-dom";
Pushed a commit to fix this

2021-10-05 10:31 UTC, merged

2021-10-05 10:59 UTC, edewit commented on src/client-scopes/add/MapperDialog.test.tsx
> +import "@testing-library/jest-dom";
It didn't work for me without it