Client add executors
keycloak/keycloak-admin-ui pull request #1284
Opened 2021-09-30 18:03 UTC by agagancarczyk

## Motivation
1. Saving changed client profiles.
2. Reloading client profiles.
2. Deleting newly created client profile.
3. Adding cypress tests.

## Verification Steps
1. Go to Realm Settings > Client policies > Profiles > Json editor 
2. Change one of the existing profiles, click "Reload" btn and verify that original profiles display
2. Manually add a new profile or change one of non-global profiles, click save btn and verify that client was successfully saved in the table list (formView tab)
3. Go to Realm Settings > Client policies > Profiles >
4. Click "Create new profile" btn and complete all form fields, click "Save" and from "Action" dropdown select "Delete this client profile", select "Delete" on the delete modal and verify that the client is not listed in the clients table (formView tab)

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

2021-10-01 11:03 UTC, edewit approved these changes

2021-10-01 15:00 UTC, jonkoops requested changes

2021-10-01 15:11 UTC, agagancarczyk commented on cypress/integration/realm_settings_test.spec.ts
> +    // Test works locally but not in CI
I can try that alright! thanks @jonkoops

2021-10-01 15:15 UTC, agagancarczyk commented on src/realm-settings/NewClientProfileForm.tsx
> +    useState<ClientProfileRepresentation>({});
yeah, sounds good! ty

2021-10-01 15:22 UTC, agagancarczyk commented on src/realm-settings/ProfilesTab.tsx
> +          );
that's spot on! ty

2021-10-01 17:49 UTC, agagancarczyk commented on src/realm-settings/NewClientProfileForm.tsx
> +        history.push(`/${realm}/realm-settings/clientPolicies`);
It doesn't seem possible. I have tried to add <Link to={toClientPolicies({ realm })}></Link>, but I'm getting this error: ClientPolicies.js:5 Uncaught ReferenceError: Cannot access 'ProfilesTab' before initialization

2021-10-01 17:50 UTC, agagancarczyk commented on src/realm-settings/NewClientProfileForm.tsx
> +                        to={`/${realm}/realm-settings/clientPolicies`}
This is fixed, ty @jonkoops

2021-10-04 11:00 UTC, jonkoops commented on src/realm-settings/NewClientProfileForm.tsx
> +        history.push(`/${realm}/realm-settings/clientPolicies`);
Ok, then let's leave it for now :+1:

2021-10-04 11:01 UTC, jonkoops commented on src/realm-settings/NewClientProfileForm.tsx
> +                        to={`/${realm}/realm-settings/clientPolicies`}
No problem, we will look at this some other time

2021-10-04 11:04 UTC, jonkoops approved these changes
Besides this one comment the PR looks good to me, so I am approving it.

2021-10-04 11:04 UTC, jonkoops commented on src/realm-settings/ProfilesTab.tsx
> +  const normalizeProfile = (
You can also use this function in the delete dialog [here](https://github.com/keycloak/keycloak-admin-ui/blob/9f74584078a2472c6f22c94d6b916d4fea0044a0/src/realm-settings/ProfilesTab.tsx#L85).

2021-10-04 13:38 UTC, agagancarczyk commented on src/realm-settings/ProfilesTab.tsx
> +  const normalizeProfile = (
true, done, thanks @jonkoops

2021-10-04 13:39 UTC, merged