Identity providers(mappers): update form fields for all Social mapper types
keycloak/keycloak-admin-ui pull request #1304
Opened 2021-10-04 16:03 UTC by jenny-s51

## Motivation

Closes #1206 

## Verification Steps

1. Go to Identity Providers
2. Create a provider and select a "Social" identity provider from the . 
3. Go to the "Mappers" tab
4. Click "Create a new mapper."
5. Verify that when a new mapper type is selected in the "Mapper Type" menu, the fields in the form change corresponding to the mapper type. 
6. Create a mapper for every type and verify the save is successful.

## Checklist:

- [x] Code has been tested locally by PR requester
- [x] User-visible strings are using the react-i18next framework (useTranslation)
- [x] Help has been implemented
- [x] axe report has been run and resulting a11y issues have been resolved
- [x] Unit tests have been created/updated

## Additional Notes

2021-10-05 15:32 UTC, jonkoops requested changes

2021-10-05 15:32 UTC, jonkoops commented on src/identity-providers/add/AddMapper.tsx
> +import _ from "lodash";
Instead of including all of the Lodash functionality you can also used named imports for the individual functions. This allows the build system to more aggressively [optimize](https://webpack.js.org/guides/tree-shaking/) our code as it can understand which code can be eliminated.
```suggestion
import { groupBy } from "lodash";
```

2021-10-05 15:32 UTC, jonkoops commented on src/identity-providers/add/AddMapper.tsx
> +  );
Since this operation might possibly be intensive to do you could memoize it so it does not get recalculated each time the component is rendered.
```suggestion
  const serverInfo = useServerInfo();
  const identityProviders = useMemo(
    () => groupBy(serverInfo.identityProviders, "groupName"),
    [serverInfo]
  );
```

2021-10-05 15:32 UTC, jonkoops commented on src/identity-providers/add/AddMapper.tsx
> +    .includes(providerId.toLowerCase());
Since this operation might possibly be intensive to do you could memoize it so it does not get recalculated each time the component is rendered.
```suggestion
  const isSocialIdP = useMemo(
    () =>
      identityProviders["Social"]
        .map((item) => item.id)
        .includes(providerId.toLowerCase()),
    [identityProviders, providerId]
  );
```

2021-10-05 15:32 UTC, jonkoops commented on src/identity-providers/add/AddMapper.tsx
> +    !isSocialIdP ? "hardcodedRole" : "attributeImporter"
If you invert the order of this statement there is no need to negate the value.
```suggestion
    isSocialIdP ? "attributeImporter" : "hardcodedRole"
```

2021-10-05 15:32 UTC, jonkoops commented on src/identity-providers/add/AddMapper.tsx
> +  );
Since this operation might possibly be intensive to do you could memoize it so it does not get recalculated each time the component is rendered.
```suggestion
  const isSocialAttributeImporter = useMemo(
    () => formValues.identityProviderMapper?.includes("user-attribute-mapper"),
    [formValues.identityProviderMapper]
  );
```

2021-10-05 17:47 UTC, jenny-s51 commented on src/identity-providers/add/AddMapper.tsx
> +import _ from "lodash";
Great idea. This is cool - thank you for linking the tree shaking doc

2021-10-06 11:04 UTC, jonkoops approved these changes

2021-10-06 11:04 UTC, merged