Some pages don't support pagination
keycloak/keycloak-admin-ui pull request #134
Opened 2020-09-30 13:59 UTC by edewit

so introduced non paginating toolbar that can be used for pages like groups

2020-10-05 18:13 UTC, ssilvert commented
@edewit Please resolve conflicts

2020-10-06 17:19 UTC, srambach commented
Looks good. One axe issue noting a duplicate aria-label, but this seems to fall under an exception for pagination controls existing above and below the table. (copying below for info) 

> This section of the WAI Aria Practices actually covers that specific instance under Step 3: Label areas:
> If a specific landmark role is used more than once on a page, provide each instance of that landmark with a unique label. There is one rare circumstance where providing the same label to multiple instances of a landmark can be beneficial: the content and purpose of each instance is identical. For example, a large search results table has two sets of identical pagination controls -- one above and one below the table, so each set is in a navigation region labelled Search Results. In this case, adding extra information to the label that distinguishes the two instances may be more distracting than helpful.

2020-10-06 18:30 UTC, ssilvert requested changes

2020-10-06 18:30 UTC, ssilvert commented on src/client-scopes/ClientScopesSection.tsx
> +          <div style={{ textAlign: "center" }}>
You should be able to use PF layout components here instead of css.

2020-10-06 18:34 UTC, ssilvert commented
@christiemolloy Can you review this, please?

2020-10-07 15:46 UTC, ssilvert approved these changes

2020-10-07 15:47 UTC, merged