Added coding standards to the project.
keycloak/keycloak-admin-ui pull request #139
Opened 2020-10-01 13:34 UTC by dlabaj

Added coding standards and also updated the package json so that the scripts have consistent naming conventions.

2020-10-01 14:00 UTC, edewit commented on CODING_GUIDELINES.md
> +* Global styling should be located…?  */static/resources/style.css*.
Global styling should be in `./public/index.css` right?

2020-10-01 14:01 UTC, edewit commented on CODING_GUIDELINES.md
> +.kogito-management-console--data-table--compact--lg {
```suggestion
.keycloak-admin--data-table--compact--lg {
```

2020-10-01 14:39 UTC, jenny-s51 requested changes
Some suggestions for grammar/spelling fixes

2020-10-01 14:39 UTC, jenny-s51 commented on CODING_GUIDELINES.md
> +### Maintiaing state with types
```suggestion
### Maintaining state with types
```

2020-10-01 14:39 UTC, jenny-s51 commented on CODING_GUIDELINES.md
> +When maintaining state for a component it is recommend that you use a [type instead of an interface](https://react-typescript-cheatsheet.netlify.app/docs/basic/getting-started/types_or_interfaces).
```suggestion
When maintaining state for a component, it is recommended that you use a [type instead of an interface](https://react-typescript-cheatsheet.netlify.app/docs/basic/getting-started/types_or_interfaces).
```

2020-10-01 14:39 UTC, jenny-s51 commented on CODING_GUIDELINES.md
> +### Intefaces
```suggestion
### Interfaces
```

2020-10-01 14:39 UTC, jenny-s51 commented on CODING_GUIDELINES.md
> +This project uses function components and hooks over class components. When coding function components in typescript a developer should include any specific props that they need.
```suggestion
This project uses function components and hooks over class components. When coding function components in typescript, a developer should include any specific props that they need.
```

2020-10-01 14:39 UTC, jenny-s51 commented on CODING_GUIDELINES.md
> +When using hooks with Typescript there are few recommendations that we follow below. Additional recommendations besides the ones mention in this document can be found [here](https://react-typescript-
```suggestion
When using hooks with Typescript there are few recommendations that we follow below. Additional recommendations besides the ones mentioned in this document can be found [here](https://react-typescript-cheatsheet.netlify.app/docs/basic/getting-started/hooks).
```

2020-10-01 14:39 UTC, jenny-s51 commented on CODING_GUIDELINES.md
> +Currently we recommend using inference for the primative types booleans, numbers, and string when using useState. Anything other then these 3 types should use a declartive syntax to specify what is e
```suggestion
Currently we recommend using inference for primitive types booleans, numbers, and strings when using useState. Anything other then these 3 types should use a declarative syntax to specify what is expected. For example the following is an example of how to use inference:
```

2020-10-01 14:39 UTC, jenny-s51 commented on CODING_GUIDELINES.md
> +Here is an example how to use a declaritive syntax. When using a declearative syntax if the value can be null that will also need to be specified:
```suggestion
Here is an example how to use a declarative syntax. When using a declarative syntax, if the value can be null, that will also need to be specified:
```

2020-10-01 14:39 UTC, jenny-s51 commented on CODING_GUIDELINES.md
> +#### useReducres
```suggestion
#### useReducer
```

2020-10-01 15:44 UTC, srambach commented on CODING_GUIDELINES.md
> +The Keycloak UI projects uses best practices based off the offical [React TypeScript Cheatsheet](https://react-typescript-cheatsheet.netlify.app/), with modificiations for this project. The React Typ
typo - "modifications"

2020-10-01 15:47 UTC, srambach commented on CODING_GUIDELINES.md
> +* Should we set up SCSS? *Not for now*
Did we decide yes or no for SCSS?

2020-10-01 15:49 UTC, srambach commented on CODING_GUIDELINES.md
> +// Data tables throughout kogito that are marked as compact
Replace kogito with keycloak

2020-10-02 08:05 UTC, edewit commented on CODING_GUIDELINES.md
> +* Should we set up SCSS? *Not for now*
I think the answer was we use it when we need to? As we in the first place would like to minimize the css.

2020-10-02 19:42 UTC, ssilvert reviewed
@dlabaj Looks like everyone is pretty happy with this.  Please address the small issues mentioned and we can get this merged.

2020-10-02 19:42 UTC, ssilvert commented on CODING_GUIDELINES.md
> +* Should we set up SCSS? *Not for now*
Right.  Let's hold off until if and when we definitely need it.

2020-10-06 12:19 UTC, ssilvert commented
@dlabaj Please include the section on state management from https://docs.google.com/document/d/151A0IAV5cq0LBkkDqixweYfOyWovA_9Kz-CwPTvgD-U/edit

2020-10-06 13:38 UTC, christiemolloy approved these changes
LGTM

2020-10-06 15:19 UTC, mfrances17 requested changes
Content is great... added a few more typo suggestions, tried not to repeat those already caught by others. One bad link in there at the bottom, I don't think it was intended to jump to training.

2020-10-06 15:19 UTC, mfrances17 commented on CODING_GUIDELINES.md
> +The Keycloak UI projects uses best practices based off the offical [React TypeScript Cheatsheet](https://react-typescript-cheatsheet.netlify.app/), with modificiations for this project. The React Typ
offical - official

2020-10-06 15:19 UTC, mfrances17 commented on CODING_GUIDELINES.md
> +Additonal details around function components can be found [here](https://react-typescript-cheatsheet.netlify.app/docs/basic/getting-started/function_components).
Additional

2020-10-06 15:19 UTC, mfrances17 commented on CODING_GUIDELINES.md
> +* [PatternFly CSS utility classes](https://www.patternfly.org/v4/documentation/react/overview/react-training)
the css utility classes link looks like a copy/paste error, it goes to the generic training page

2020-10-06 18:42 UTC, dlabaj commented on CODING_GUIDELINES.md
> +import React from 'react';
Done

2020-10-06 18:42 UTC, dlabaj commented on CODING_GUIDELINES.md
> +import { X1, X2, ... Xn } from 'package-x';
Done

2020-10-06 18:42 UTC, dlabaj commented on CODING_GUIDELINES.md
> +import React, { ReactNode } from 'react'
Done

2020-10-06 18:43 UTC, dlabaj commented on CODING_GUIDELINES.md
> +import ReactDOM from 'react-dom';
Done

2020-10-06 18:43 UTC, dlabaj commented on CODING_GUIDELINES.md
> +import React, { FunctionComponent } from 'react';
Done

2020-10-06 18:46 UTC, dlabaj commented on CODING_GUIDELINES.md
> +* Global styling should be located…?  */static/resources/style.css*.
Yep let me fix it.

2020-10-06 18:47 UTC, dlabaj commented on CODING_GUIDELINES.md
> +### Maintiaing state with types
Done.

2020-10-06 18:48 UTC, dlabaj commented on CODING_GUIDELINES.md
> +When maintaining state for a component it is recommend that you use a [type instead of an interface](https://react-typescript-cheatsheet.netlify.app/docs/basic/getting-started/types_or_interfaces).
Done.

2020-10-06 18:48 UTC, dlabaj commented on CODING_GUIDELINES.md
> +### Intefaces
Done

2020-10-06 18:48 UTC, dlabaj commented on CODING_GUIDELINES.md
> +This project uses function components and hooks over class components. When coding function components in typescript a developer should include any specific props that they need.
Done

2020-10-06 18:51 UTC, dlabaj commented on CODING_GUIDELINES.md
> +Here is an example how to use a declaritive syntax. When using a declearative syntax if the value can be null that will also need to be specified:
Done

2020-10-06 19:34 UTC, dlabaj commented on CODING_GUIDELINES.md
> +#### useReducres
Done

2020-10-06 19:35 UTC, dlabaj commented on CODING_GUIDELINES.md
> +The Keycloak UI projects uses best practices based off the offical [React TypeScript Cheatsheet](https://react-typescript-cheatsheet.netlify.app/), with modificiations for this project. The React Typ
Done

2020-10-06 19:35 UTC, dlabaj commented on CODING_GUIDELINES.md
> +* Should we set up SCSS? *Not for now*
Do you want me to remove this line?

2020-10-06 19:35 UTC, dlabaj commented on CODING_GUIDELINES.md
> +// Data tables throughout kogito that are marked as compact
done

2020-10-06 19:43 UTC, dlabaj commented on CODING_GUIDELINES.md
> +Currently we recommend using inference for the primative types booleans, numbers, and string when using useState. Anything other then these 3 types should use a declartive syntax to specify what is e
Done.

2020-10-06 19:44 UTC, dlabaj commented on CODING_GUIDELINES.md
> +The second option is for createing [mutable refs](https://react-typescript-cheatsheet.netlify.app/docs/basic/getting-started/hooks#useref) that you will manage.
done

2020-10-06 19:44 UTC, dlabaj commented on CODING_GUIDELINES.md
> +Additonal details around function components can be found [here](https://react-typescript-cheatsheet.netlify.app/docs/basic/getting-started/function_components).
done

2020-10-06 19:44 UTC, dlabaj commented on CODING_GUIDELINES.md
> +
done

2020-10-06 19:48 UTC, ssilvert commented on CODING_GUIDELINES.md
> +* Should we set up SCSS? *Not for now*
Yes.  Remove it.

2020-10-06 19:49 UTC, dlabaj commented on CODING_GUIDELINES.md
> +* [PatternFly CSS utility classes](https://www.patternfly.org/v4/documentation/react/overview/react-training)
fixed

2020-10-06 19:49 UTC, dlabaj commented on CODING_GUIDELINES.md
> +For components that do not have any additonal props an empty object should be used instead:
done

2020-10-06 19:49 UTC, dlabaj commented on CODING_GUIDELINES.md
> +The Keycloak UI projects uses best practices based off the offical [React TypeScript Cheatsheet](https://react-typescript-cheatsheet.netlify.app/), with modificiations for this project. The React Typ
done

2020-10-06 19:59 UTC, srambach commented on CODING_GUIDELINES.md
> +**Using a utility class **
Something messed up in the formatting here - *s are showing up in the markdown - maybe an extra space?

2020-10-06 20:07 UTC, dlabaj commented on CODING_GUIDELINES.md
> +* Should we set up SCSS? *Not for now*
done.

2020-10-06 20:07 UTC, dlabaj commented on CODING_GUIDELINES.md
> +**Using a utility class **
fixed had extra spaces.

2020-10-06 20:14 UTC, srambach commented on CODING_GUIDELINES.md
> +**Using a utility class **
Extra space here, too, that I think is messing up the markdown. Then that's it, I swear! :)

2020-10-06 20:16 UTC, dlabaj commented on CODING_GUIDELINES.md
> +**Using a utility class **
lol thanks sarah!

2020-10-06 20:18 UTC, ssilvert requested changes

2020-10-06 20:18 UTC, ssilvert commented on CODING_GUIDELINES.md
> +
I don't think this makes sense.  Using `type` instead of `interface` is not about state management.  

Since `type instead of an interface` is already in the cheat sheet, I think we can get rid of this section altogether.

2020-10-06 20:23 UTC, dlabaj commented on CODING_GUIDELINES.md
> +
It was in this section [here](https://react-typescript-cheatsheet.netlify.app/docs/basic/getting-started/types_or_interfaces) if you need to maintain state of a component with an object, you should try to use type instead of an interface.  I can try rewording this.

2020-10-06 20:28 UTC, dlabaj commented on CODING_GUIDELINES.md
> +* If #3, is not sufficient, use a [global context](https://reactjs.org/docs/context.html).
Got it thanks.

2020-10-06 20:33 UTC, dlabaj commented on CODING_GUIDELINES.md
> +**Using a utility class **
done.

2020-10-06 20:42 UTC, ssilvert approved these changes

2020-10-06 21:13 UTC, mfrances17 approved these changes

2020-10-06 21:42 UTC, merged