Add Create Group Functionality
keycloak/keycloak-admin-ui pull request #142
Opened 2020-10-01 19:02 UTC by christiemolloy

Adds the functionality to create a group, and then updates the state so that the new group shows immediately.

**Minor fixes included in this PR, unrelated to Create Groups:**
- Added realm context for every POST and GET
- Added alerts after POST and GET
- Replaced the header I had with the common header

2020-10-01 19:03 UTC, christiemolloy commented on src/groups/GroupsCreateModal.tsx
> +            validated={errors.name ? "error" : "default"}
@edewit I don't think the "required" error is working. I copied what you had done in Clients. Is this the correct way to validate the form field?

2020-10-02 07:14 UTC, edewit commented on src/groups/GroupsCreateModal.tsx
> +            validated={errors.name ? "error" : "default"}
There are 2 ways either you submit the form and use `handleSubmit` from the `react-hook-form` or you use `trigger` to trigger the validation. Maybe here we can also add server side validation to check if the group you want to create doesn't already exists?

2020-10-05 21:20 UTC, srambach commented
If I hit return on the modal instead of the button, it reloads the page, but the group doesn't seem to have been created. 
Also, when I do use the button, I get an alert saying the group has been created, but it's not showing in the list until I reload the page.

2020-10-06 07:09 UTC, edewit commented
@srambach the reload problem is handled in #143

2020-10-06 15:38 UTC, mfrances17 commented
i need to do a hard refresh to see the group appear in the list... have you merged with the latest changes from master, namely those in 143?

2020-10-06 15:42 UTC, mfrances17 requested changes
Code looks good - two comments... Would like to see it adding the new group name row without refreshing, does not seem to be working yet, although it could just be a merge issue. Also seeing a unique key prop warning on the groups table, probably need to ensure we are using a unique key to each row as they are added.

2020-10-06 20:02 UTC, ssilvert commented
> @srambach the reload problem is handled in #143

@christiemolloy #143 is now merged.  Please update this PR to use it.

2020-10-08 12:37 UTC, ssilvert commented
Christie will fix and resubmit later.

2020-10-14 13:16 UTC, dlabaj submitted a review, later dismissed
Looks good just that one export for the type and marks comments.

2020-10-14 13:16 UTC, dlabaj commented on src/groups/GroupsList.tsx
>  type GroupsListProps = {
This should be exported since you are exporting GroupList

2020-10-14 13:20 UTC, dlabaj commented
@christiemolloy Also add some jest / unit tests or create a PR to add them.

2020-10-14 14:20 UTC, srambach commented
@christiemolloy Can you check the Axe report? There are some form labels it's complaining about, and a landmark for the page, which I don't know if that's new for this page or not.

2020-10-14 19:12 UTC, christiemolloy commented on src/groups/GroupsList.tsx
>  type GroupsListProps = {
This isn't something that is happening across the project, should we start doing that ?

2020-10-14 19:16 UTC, christiemolloy commented
@srambach looks like this is actually a problem with PatternFly. I can file an issue but I don't know that we need to worry about it for now - we can follow up if PF does something about it!

<img width="1276" alt="Screen Shot 2020-10-14 at 3 11 47 PM" src="https://user-images.githubusercontent.com/20118816/96034837-25c7c400-0e30-11eb-9ccb-7be075f30954.png">

2020-10-14 19:54 UTC, ssilvert commented on src/groups/GroupsList.tsx
>  type GroupsListProps = {
@christiemolloy I think it's probably a good idea to go ahead and export it.  I don't see any down side.

2020-10-14 20:20 UTC, mfrances17 requested changes
I'm not sure what the purpose is of the Delete command to the right of the 'Create group' button. At first I thought that if you had multiple groups selected it would be a way to perform a bulk delete but that doesn't seem to be working.

**Edit:** This feature is coming later, not part of this PR

2020-10-14 20:23 UTC, srambach commented on src/groups/GroupsCreateModal.tsx
> +            fieldId="group-id"
I think this might need to be "name" to fix the a11y error?

2020-10-14 20:28 UTC, mfrances17 commented
LGTM, just fix your conflicts :)

2020-10-14 20:28 UTC, mfrances17 approved these changes

2020-10-14 20:30 UTC, jenny-s51 approved these changes
create functionality is looking good @christiemolloy !! +1 about what @mfrances17 about bulk-delete... but it would be okay to just make a new PR for that I think 🙂

2020-10-14 20:48 UTC, christiemolloy commented on src/groups/GroupsCreateModal.tsx
> +            fieldId="group-id"
added a name - we could follow up if this doesnt fix it

2020-10-14 20:48 UTC, christiemolloy commented on src/groups/GroupsCreateModal.tsx
> +            fieldId="group-id"
a lot of the FormGroups dont have names so might be a universal issue

2020-10-14 21:18 UTC, christiemolloy commented on src/groups/GroupsList.tsx
>  type GroupsListProps = {
Going to address this in a separate issue so that we handle all of the exports in one issue and make that a requirement going ahead.

2020-10-14 21:20 UTC, merged