add ability to leave multiple groups
keycloak/keycloak-admin-ui pull request #1431
Opened 2021-10-27 13:01 UTC by edewit

fixes: #496

2021-11-01 10:33 UTC, jonkoops commented
@ssilvert can we merge this one?

2021-11-01 13:59 UTC, ssilvert commented
> @ssilvert can we merge this one?

I will retest this afternoon.  If it looks good I will merge it.

2021-11-01 17:07 UTC, ssilvert commented
> @edewit Now it looks like ability to leave multiple groups is broken.
> 
> 1. Create Group A at the root.
> 2. Create Group B at the root.
> 3. User joins both A and B
> 4. Select `Group membership` to select both A and B
> 5. Click `Leave` at the top of the table
> 6. Only A will be removed

@edewit Looks like this still doesn't work.

2021-11-01 20:53 UTC, mfrances17 requested changes
i'm getting the same results as @ssilvert during testing. also some string issues on the confirm dialog based on these changes.

2021-11-01 20:53 UTC, mfrances17 commented on src/user/UserGroups.tsx
> +      count: selectedGroups.length,
i don't think the message changes are working as expected:
![leave-group](https://user-images.githubusercontent.com/39063664/139740470-745c0b75-8ee5-46f7-954f-18d090ffe9ae.png)

2021-11-03 09:25 UTC, edewit commented
@mfrances17 @ssilvert sorry dropped the ball on this one... this time it's really fixed

2021-11-03 10:08 UTC, jonkoops approved these changes

2021-11-03 13:45 UTC, ssilvert approved these changes
Looks good now.  Merging.

2021-11-03 13:45 UTC, merged