Client policies(profiles): Add support for editing client policy data
keycloak/keycloak-admin-ui pull request #1448
Opened 2021-10-29 20:13 UTC by jenny-s51

## Motivation

https://issues.redhat.com/browse/CLUX-293

## Brief Description

## Verification Steps

1. Go to Realm Settings -> Client Policies tab
2. Click on the "policies" subtab
3. Create a policy
4. Go back to the data table and click the policy you just created
5. Change the name and/or description of the policy
6. Verify the save is successful
7. Go back to the data table and select the policy you just edited
8. Verify the data shown is correct

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

## Additional Notes

2021-11-01 11:17 UTC, jonkoops requested changes

2021-11-01 11:17 UTC, jonkoops commented on cypress/integration/realm_settings_test.spec.ts
> -  describe.skip("Realm settings client policies tab tests", () => {
Always nice to see tests get re-enabled!

2021-11-01 11:17 UTC, jonkoops commented on src/realm-settings/NewClientPolicyForm.tsx
> +    const createdForm = form.getValues();
We can't use `formValues` directly here?

2021-11-01 11:17 UTC, jonkoops commented on src/realm-settings/NewClientPolicyForm.tsx
> +      const policyNameExists = !!policies.find(
You can use [`some()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some) to get a boolean value directly.
```suggestion
      const policyNameExists = policies.some(
```

2021-11-01 11:17 UTC, jonkoops commented on src/realm-settings/NewClientPolicyForm.tsx
> +      }
Since all the branches of this `if` statement return a value you can omit the `else` clause and return directly.
```suggestion
      return policies.concat(createdForm);
```

2021-11-01 11:17 UTC, jonkoops commented on src/realm-settings/NewClientPolicyForm.tsx
> +        return res;
Seems like `res` is only used in this branch, so perhaps you can return it inline?
```suggestion
        return policies.map((policy) =>
          policy.name === createdPolicy.name ? createdPolicy : policy
        );
```

2021-11-01 13:25 UTC, jenny-s51 commented on src/realm-settings/NewClientPolicyForm.tsx
> +    const createdForm = form.getValues();
No - this doesn't save the current values that are entered into the fields

2021-11-01 15:22 UTC, jenny-s51 commented
Thank you for your review and comments @jonkoops ! I've included your suggestions - please kindly re-review when you have a moment 🙂

2021-11-02 12:56 UTC, jonkoops requested changes

2021-11-02 12:56 UTC, jonkoops commented on src/realm-settings/ClientProfileForm.tsx
> +            `/${realm}/realm-settings/clientPolicies/${profileName}/edit-profile`
Can you replace this with a route function?

2021-11-02 12:56 UTC, jonkoops commented on src/realm-settings/ExecutorForm.tsx
> +        `/${realm}/realm-settings/clientPolicies/${profileName}/edit-profile`
Can you replace this with a route function?

2021-11-02 12:56 UTC, jonkoops commented on src/realm-settings/ExecutorForm.tsx
> +                  to={`/${realm}/realm-settings/clientPolicies/${profileName}/edit-profile`}
Can you replace this with a route function?

2021-11-02 14:14 UTC, jonkoops approved these changes
Great! Looks good to me

2021-11-02 17:11 UTC, merged