IDPs: go to edit form after save()
keycloak/keycloak-admin-ui pull request #1464
Opened 2021-11-01 18:17 UTC by jenny-s51

Closes #1440

2021-11-02 10:16 UTC, jonkoops approved these changes
LGTM

2021-11-02 11:20 UTC, edewit requested changes
test seems to fail

2021-11-03 10:09 UTC, jonkoops approved these changes

2021-11-03 20:21 UTC, mfrances17 approved these changes
LGTM, changes work as expected. 

Side note... this is tagged as a Post-1.0 Issue, we should be fixing 1.0 issues first before we tackle these.

2021-11-04 06:24 UTC, edewit approved these changes

2021-11-04 06:24 UTC, merged