refactor: unecessary condition #1128
keycloak/keycloak-admin-ui pull request #1476
Opened 2021-11-02 13:42 UTC by alevid99

## Motivation

Resolve warnings for issue #1128 

## Brief Description

## Verification Steps

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

## Additional Notes

2021-11-02 14:27 UTC, jonkoops requested changes
It's hard to tell which of these changes might break the application as I don't know if the types we are using are all that correct.

2021-11-02 14:27 UTC, jonkoops commented on src/client-scopes/add/components/ClientSelectComponent.tsx
> -        params.search = true;
What is the reason this was removed? I am not seeing any warnings that this is an unnecessary condition.

2021-11-02 14:27 UTC, jonkoops commented on src/client-scopes/form/ClientScopeForm.tsx
> +          `/${realm}/client-scopes/${scope.id}/${clientScopes.type}/settings`
This will actually cause an error as `clientScopes.type` can be an empty string and thus needs a fallback. I think we should provide a default value to the form to fix this.

2021-11-02 14:27 UTC, jonkoops commented on src/clients/ClientsSection.tsx
> -      params.search = true;
Why was this removed? I don't see any warnings for this one.

2021-11-02 14:27 UTC, jonkoops commented on src/components/multi-line-input/MultiLineInput.tsx
> -              isDisabled={rest.isDisabled || !currentValues?.[index]?.value}
This might be a false positive as we have [`noUncheckedIndexedAccess`](https://www.typescriptlang.org/tsconfig#noUncheckedIndexedAccess) disabled.

2021-11-02 14:27 UTC, jonkoops commented on src/realm-roles/AssociatedRolesTab.tsx
> -      search: search,
Why were these removed? I don't see a reason to remove the filters here. Although this could be simplified.

```ts
const compositeRoles = await adminClient.roles.getCompositeRoles({
  id: parentRole.id!,
  first,
  max,
  search,
});
```

2021-11-03 10:19 UTC, alevid99 commented on src/client-scopes/add/components/ClientSelectComponent.tsx
> -        params.search = true;
@jonkoops there is an error due to the typescript type of params

2021-11-03 10:19 UTC, alevid99 commented on src/clients/ClientsSection.tsx
> -      params.search = true;
@jonkoops there is an error due to the typescript type of params

2021-11-03 10:21 UTC, alevid99 commented on src/realm-roles/AssociatedRolesTab.tsx
> -      search: search,
@jonkoops there is an error due to the typescript type. All this field are not present on the input type of the method.

2021-11-09 14:05 UTC, jonkoops commented
I'm closing this PR as we currently have to focus on other priorities (delivering the first version of the admin console) and thus cannot afford the time to test the changes right now. We intend to fix the issues with this code progressively as we refactor it over time.

@alevid99 I want to thank you a lot for contributing to the project, we appreciate your efforts a lot but we simply do not have the resources to resolve this issue at this point in time. If you are looking for issues to pick, we have a [milestone](https://github.com/keycloak/keycloak-admin-ui/milestone/1) for things we need to get in before our first release which would help us out greatly.

2021-11-09 14:05 UTC, closed without merging