Added initial "Authorisation" tabs Settings and Resources
keycloak/keycloak-admin-ui pull request #1524
Opened 2021-11-10 12:41 UTC by edewit

This tab will be shown if Client authentication is On and Authorization is on for a client.

Import is not yet implemented but save works also deleting resources but not creating them.

2021-11-10 12:41 UTC, edewit commented
see marvel https://marvelapp.com/prototype/78j1b69/screen/82976119 and https://marvelapp.com/prototype/6a7eeb2/screen/83007361

2021-11-12 12:55 UTC, jonkoops commented
@edewit The build is failing, could you give your PR a rebase?

2021-11-16 10:29 UTC, jonkoops requested changes

2021-11-16 10:29 UTC, jonkoops commented on src/clients/ClientDetails.tsx
> +  const [activeTab3, setActiveTab3] = useState(40);
Perhaps we can give this a more descriptive name like `activeAuthorizationTab`?

2021-11-16 10:29 UTC, jonkoops commented on src/clients/authorization/DetailCell.tsx
> +  );
I think these API calls can be ran in parallel:
```suggestion
  useFetch(
    () =>
      Promise.all([
        adminClient.clients.listScopesByResource({
          id: clientId,
          resourceName: id,
        }),
        adminClient.clients.listPermissionsByResource({
          id: clientId,
          resourceId: id,
        }),
      ]),
    ([scopes, permissions]) => {
      setScope(scopes);
      setPermissions(permissions);
    },
    []
  );
```

2021-11-16 10:29 UTC, jonkoops commented on src/clients/authorization/DetailCell.tsx
> +      <DescriptionListGroup>
Should this not be rendered conditionally based on the presence and length of `uris`?

2021-11-16 10:29 UTC, jonkoops commented on src/clients/authorization/DetailCell.tsx
> +      <DescriptionListGroup>
Same here, do we need a length check first?

2021-11-16 10:29 UTC, jonkoops commented on src/clients/authorization/DetailCell.tsx
> +      <DescriptionListGroup>
Same here, do we need a length check first?

2021-11-16 10:29 UTC, jonkoops commented on src/clients/authorization/detail-cell.css
> +  --pf-c-description-list--m-horizontal__term--width: 20ch;
Since this only sets a CSS variable it might be okay to use this as an inline style.

2021-11-16 10:29 UTC, jonkoops commented on src/clients/authorization/Settings.tsx
> +          }}
Some stray logging here.

2021-11-16 10:29 UTC, jonkoops commented on src/clients/authorization/Settings.tsx
> +  const setupForm = (resource: ResourceServerRepresentation) =>
Would `form.reset(resource)` not result in the same?

2021-11-16 10:29 UTC, jonkoops commented on src/clients/authorization/Settings.tsx
> +const DecisionStrategy = ["UNANIMOUS", "AFFIRMATIVE"] as const;
Can we use constant casing for these?
```suggestion
const POLICY_ENFORCEMENT_MODES = ["ENFORCING", "PERMISSIVE", "DISABLED"] as const;
const DECISION_STRATEGY = ["UNANIMOUS", "AFFIRMATIVE"] as const;
```

2021-11-16 10:29 UTC, jonkoops commented on src/clients/authorization/Resources.tsx
> +                          console.log(
Stray console log.

2021-11-16 10:29 UTC, jonkoops commented on src/clients/authorization/Resources.tsx
> +                      console.log(rows);
Stray console log

2021-11-16 10:29 UTC, jonkoops commented on src/clients/authorization/Resources.tsx
> +                      rows[rowIndex] = row;
This could also be a map operation.

```ts
const rows = resources.map((resource, index) =>
  index === rowIndex
    ? { ...resource, isExpanded: !resource.isExpanded }
    : resource
);
```

2021-11-16 10:29 UTC, jonkoops commented on src/clients/authorization/Resources.tsx
> +        <TableComposable aria-label="Expandable Table" variant="compact">
This label should have a translation.

2021-11-16 10:29 UTC, jonkoops commented on src/clients/authorization/Resources.tsx
> +        // search,
Stray comment.

2021-11-16 15:00 UTC, edewit commented on src/clients/authorization/detail-cell.css
> +  --pf-c-description-list--m-horizontal__term--width: 20ch;
no, if you do that it's no longer people can't override it anymore.

2021-11-16 16:14 UTC, jonkoops commented on src/clients/authorization/detail-cell.css
> +  --pf-c-description-list--m-horizontal__term--width: 20ch;
Fair enough

2021-11-16 16:16 UTC, jonkoops approved these changes

2021-11-17 08:27 UTC, merged