filter out unknown mappers
keycloak/keycloak-admin-ui pull request #1559
Opened 2021-11-15 14:09 UTC by edewit

fixes: #1478

2021-11-16 11:32 UTC, jonkoops requested changes

2021-11-16 11:32 UTC, jonkoops commented on src/client-scopes/details/MapperList.tsx
> +  };
I think this function could be improved a bit, what do you think of this?

```ts
const loader = async () => {
  if (!mapperList) {
    return [];
  }

  const list = mapperList.reduce<Row[]>((rows, mapper) => {
    const mapperType = mapperTypes.find(
      ({ id }) => id === mapper.protocolMapper
    );

    if (!mapperType) {
      return rows;
    }

    return rows.concat({
      ...mapper,
      category: mapperType.category,
      type: mapperType.name,
      priority: mapperType.priority,
    });
  }, []);

  return list.sort((a, b) => a.priority - b.priority);
};
```

2021-11-19 12:27 UTC, edewit commented on src/client-scopes/details/MapperList.tsx
> +  };
yep that improves it...

2021-11-22 10:32 UTC, jonkoops approved these changes

2021-11-22 10:32 UTC, merged