Initial version of the create and edit resouce screen
keycloak/keycloak-admin-ui pull request #1573
Opened 2021-11-18 14:58 UTC by edewit

2021-11-22 16:12 UTC, jonkoops requested changes

2021-11-22 16:12 UTC, jonkoops commented on src/clients/authorization/ResourceDetails.tsx
> +    },
Since the other API calls have no dependency on `client` it's call can also be done in parallel.
```suggestion
    async (): Promise<FetchResource> => {
      const [client, resource, permissions] = await Promise.all([
        adminClient.clients.findOne({ id }),
        resourceId
          ? adminClient.clients.getResource({ id, resourceId })
          : Promise.resolve(undefined),
        resourceId
          ? adminClient.clients.listPermissionsByResource({ id, resourceId })
          : Promise.resolve(undefined),
      ]);

      return { client, resource, permissions };
    },
```

2021-11-22 16:12 UTC, jonkoops commented on src/clients/authorization/ResourceDetails.tsx
> +        adminClient.clients.updateResource({ id, resourceId }, resource);
I think you are missing an `await` here.
```suggestion
        await adminClient.clients.updateResource({ id, resourceId }, resource);
```

2021-11-22 16:47 UTC, edewit commented on src/components/attribute-input/AttributeInput.tsx
> +                aria-label={`remove ${attribute.key} with value ${attribute.value} `}
ahh yes didn't see that one... copy paste action

2021-11-22 16:47 UTC, edewit commented on src/components/attribute-form/attributeConvert.test.ts
> +describe("useRequiredContext", () => {
oops

2021-11-22 16:47 UTC, edewit commented on src/components/attribute-form/attributeConvert.test.ts
> +    } = { one: ["1"], two: ["2"] };
hmm... yes

2021-11-22 16:50 UTC, edewit commented on src/clients/routes/Resource.ts
> +  resourceId?: string;
yes but it's also used for new and then it's not defined

2021-11-23 11:41 UTC, jonkoops commented on src/clients/routes/Resource.ts
> +  resourceId?: string;
Right, then it should be marked as optional in the route path as well.

2021-11-23 14:46 UTC, jonkoops commented
@edewit there are still a couple of open review comments, could you take a look at them?

2021-11-23 19:12 UTC, ssilvert requested changes
For the `Resources` table, the expanded rows don't look right compared to the design:
https://marvelapp.com/prototype/6a7eeb2/screen/83042826
This is especially a problem when there are no URLs, Scopes, and Permissions.  You will get a "flash" and then a blank row.  Suggest that we have something like a `<none>` value so that the user can see what should be there.

 Another issue:
1. Create a resource and add an authorization scope.
2. Go back to Resources list.
3. Edit the resource again.
4. `Authorization scopes` will show [object Object}

2021-11-24 03:11 UTC, xianli123 commented on src/clients/authorization/ResourceDetails.tsx
> +                />
As for the second question, I remember that Pedro has mentioned that users can't edit the owner in the current console. I can double-check this part with Pedro. As for the first question, I can ask for Pedro's suggestion. What do you think?

2021-11-24 03:12 UTC, xianli123 commented on src/clients/authorization/ResourceDetails.tsx
> +                  helpText="clients-help:displayName"
ok. I will do that and invite Andy to help us.

2021-11-24 07:37 UTC, edewit commented on src/clients/messages.ts
> +    allowRemoteResourceManagement: "Remote resource management",
help texts are in the help.ts

2021-11-24 07:46 UTC, edewit commented on src/clients/help.ts
> +    iconUri: "An URI pointing to an icon.",
do we need to log this as an issue in the old console as well?

2021-11-24 08:20 UTC, edewit commented on src/clients/authorization/ResourceDetails.tsx
> +                />
The help text comes from the old console

2021-11-24 08:26 UTC, edewit commented
> For the `Resources` table, the expanded rows don't look right compared to the design: https://marvelapp.com/prototype/6a7eeb2/screen/83042826 This is especially a problem when there are no URLs, Scopes, and Permissions. You will get a "flash" and then a blank row. Suggest that we have something like a `<none>` value so that the user can see what should be there.
> 

Introduced a loader spinner to prevent the "flash" and now shows all details with `<i>None</i>` when there is no information for that description.

2021-11-24 09:52 UTC, jonkoops requested changes
Still some threads unresolved from my original review.

2021-11-25 10:22 UTC, jonkoops approved these changes

2021-12-01 07:58 UTC, merged