Realm settings(Client policies): Update client-roles condition to match new design
keycloak/keycloak-admin-ui pull request #1575
Opened 2021-11-18 16:58 UTC by jenny-s51

## Motivation

https://marvelapp.com/prototype/2b3ghc06/screen/81619352

## Brief Description

- Adds screen, correct fields, and functionality to client policies -> add condition -> client-scopes condition type
- Supports save and edit functionality

## Verification Steps

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

## Additional Notes

Dependent on #1532  - will rebase once merged to simplify review process.

2021-11-18 21:05 UTC, jonkoops commented
@jenny-s51 Looks like there are some conflicts, can you rebase on `main`?

2021-11-22 14:53 UTC, jonkoops requested changes

2021-11-22 14:53 UTC, jonkoops commented on src/clients/scopes/AddScopeDialog.tsx
> +          { name: "protocol", displayKey: "Protocol" },
Should `displayKey` here not be translated as well?

2021-11-22 14:53 UTC, jonkoops commented on src/components/dynamic/components.ts
> -  selectedValues?: string[];
Good catch on removing this!

2021-11-22 19:09 UTC, jenny-s51 commented on src/clients/scopes/AddScopeDialog.tsx
> +          : t("addClientScopesTo", { clientId: "test" })
Yes you're right -- looks like this somehow sneaked into the component through a merged PR a while back ... fixed! 👍

2021-11-22 19:13 UTC, jenny-s51 commented on src/clients/scopes/AddScopeDialog.tsx
> +    <SelectOption key={3} value={t("protocolTypes.all")} isPlaceholder />,
Great idea - thank you for this suggestion

2021-11-22 21:44 UTC, jenny-s51 commented
Thank you for your thorough review and helpful feedback @jonkoops ! I've addressed your comments 🙂

2021-11-23 12:22 UTC, jonkoops requested changes

2021-11-23 12:22 UTC, jonkoops commented on src/clients/utils.ts
>  export const getProtocolName = (t: TFunction<"clients">, protocol: string) => {
This function was already used in other places as well, are you sure this change doesn't break the expectations there?

2021-11-23 12:22 UTC, jonkoops commented on src/clients/scopes/AddScopeDialog.tsx
> +  );
The type can be inferred since you are assigning a the enum value here , which means the generics can be omitted.
```suggestion
  const [filterType, setFilterType] = useState(FilterType.Name);
  const [protocolType, setProtocolType] = useState(ProtocolType.All);
```

2021-11-23 12:22 UTC, jonkoops commented on src/clients/scopes/AddScopeDialog.tsx
> +  };
If you make this function `async` there is no need to wrap the returns in a `Promise.resolve` call, which can reduce the code here. Also since we already have enums with string values we can compare against the enum instead.
```suggestion
  const loader = async () => {
    if (protocolType === ProtocolType.OpenIDConnect) {
      return clientScopes.filter((item) => item.protocol === "openid-connect");
    } else if (protocolType === ProtocolType.SAML) {
      return clientScopes.filter((item) => item.protocol === "saml");
    }

    return clientScopes;
  };
```

2021-11-23 12:22 UTC, jonkoops commented on src/clients/scopes/AddScopeDialog.tsx
> +  };
Here you can also compare against the enum values directly instead of string literals.
```suggestion
  const onFilterTypeDropdownSelect = (filterType: string) => {
    if (filterType === FilterType.Name) {
      setFilterType(FilterType.Protocol);
    } else if (filterType === FilterType.Protocol) {
      setFilterType(FilterType.Name);
    }

    setIsFilterTypeDropdownOpen(!isFilterTypeDropdownOpen);
  };
```

2021-11-23 12:22 UTC, jonkoops commented on src/clients/scopes/AddScopeDialog.tsx
> +  };
Also here you can compare the value directly to the enum. 

```suggestion
  const onProtocolTypeDropdownSelect = (protocolType: string) => {
    if (protocolType === ProtocolType.SAML) {
      setProtocolType(ProtocolType.SAML);
    } else if (protocolType === ProtocolType.OpenIDConnect) {
      setProtocolType(ProtocolType.OpenIDConnect);
    } else if (protocolType === ProtocolType.All) {
      setProtocolType(ProtocolType.All);
    }

    setIsProtocolTypeDropdownOpen(!isProtocolTypeDropdownOpen);
  };
```

2021-11-23 12:22 UTC, jonkoops commented on src/clients/scopes/AddScopeDialog.tsx
> +          : t("addClientScopesTo", { clientName: clientName })
This can be shortened by omitting the value.
```suggestion
          : t("addClientScopesTo", { clientName })
```

2021-11-23 12:22 UTC, jonkoops commented on src/clients/scopes/AddScopeDialog.tsx
> +                {filterType === "Name" ? t("protocol") : t("common:name")}
You can use the enum to compare here as well.
```suggestion
                {filterType === FilterType.Name
                  ? t("protocol")
                  : t("common:name")}
```

2021-11-23 12:22 UTC, jonkoops commented on src/clients/scopes/AddScopeDialog.tsx
> +          filterType === "Protocol" && (
You can use the enum to compare here as well.
```suggestion
          filterType === FilterType.Protocol && (
```

2021-11-23 14:13 UTC, jenny-s51 commented on src/clients/utils.ts
>  export const getProtocolName = (t: TFunction<"clients">, protocol: string) => {
Should be working everywhere it's used now 👍

2021-11-23 14:58 UTC, jonkoops approved these changes

2021-11-23 14:59 UTC, merged