Client groups select
keycloak/keycloak-admin-ui pull request #1577
Opened 2021-11-19 19:58 UTC by jenny-s51

**On hold for merge / review until #1532 and #1575 are merged**

2021-11-23 15:01 UTC, jenny-s51 commented
On it - thank you @jonkoops !

2021-11-24 10:28 UTC, jonkoops requested changes

2021-11-24 10:28 UTC, jonkoops commented on src/user/UserForm.tsx
> +          filterGroups={selectedGroups.map((group) => group.name) as string[]}
If you are sure that `name` is always present you can use a non-null assertion so there is no need to type-cast.
```suggestion
          filterGroups={selectedGroups.map((group) => group.name!)}
```

2021-11-24 10:28 UTC, jonkoops commented on src/components/group/GroupPickerDialog.tsx
> +    ].find((group) => group === row?.name);
This code can be cleaned up a bit by using [`.some()` ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some)instead of `.find()`.

```suggestion
    return [
      ...joinedGroups.map((item) => item.name),
      ...(filterGroups || []),
    ].some((group) => group === row?.name);
```

2021-11-24 10:28 UTC, jonkoops commented on src/components/dynamic/MultivaluedChipsComponent.tsx
> +                    console.log(value);
Stray console log

2021-11-24 14:15 UTC, jenny-s51 commented on src/components/group/GroupPickerDialog.tsx
> +    ].find((group) => group === row?.name);
Ah nice catch! It definitely makes more sense to use `.some()` here

2021-11-24 15:09 UTC, jonkoops approved these changes

2021-11-24 16:19 UTC, merged

2021-11-25 11:17 UTC, edewit commented on src/components/dynamic/DynamicComponents.tsx
> +      if (isValidComponentType(componentType) && property.name !== "scopes") {
This should not be nessary

2021-11-25 11:17 UTC, edewit commented on src/components/dynamic/MultivaluedChipsComponent.tsx
> +        name === "scopes"
why not use the "label" field?

2021-11-25 11:17 UTC, edewit commented on src/components/dynamic/MultivaluedChipsComponent.tsx
> +      id={name === "scopes" ? "expected-scopes" : "expected-groups"}
why not use the name field?

2021-11-25 11:17 UTC, edewit commented on src/components/dynamic/MultivaluedChipsComponent.tsx
> +            name === "scopes"
why not use the `helpText`

2021-11-25 11:17 UTC, edewit commented on src/components/dynamic/MultivaluedChipsComponent.tsx
> +              {open && name === "scopes" && (
let's not add a lot of extra logic based on the name of the fields, if we need extra ui logic it should use a different component type on the server side

2021-11-25 13:30 UTC, edewit commented on src/clients/scopes/AddScopeDialog.tsx
> +          { name: "protocol", displayKey: "Protocol" },
![image](https://user-images.githubusercontent.com/51133/143450242-932af25f-9461-4ec9-bc1c-cf32b3d3b81d.png)
Don't think we need two times protocol