Fix role-ldap-mapper defaults
keycloak/keycloak-admin-ui pull request #1578
Opened 2021-11-19 22:24 UTC by mfrances17

## Motivation
Fixes https://github.com/keycloak/keycloak-admin-ui/issues/1481.

## Brief Description
As noted in https://github.com/keycloak/keycloak-admin-ui/issues/1481, the `Role Object Classes` issue was fixed as part of https://github.com/keycloak/keycloak-admin-ui/pull/1511.

For the `User roles retrieve strategy` issue, fixed it so the Active Directory vendor has three possible choices vs the other 4 vendor types which only have two available choices.

During testing, noticed that the field itself was not writing/reading correctly - this is because both roles and groups both use the user-roles-retrieve-strategy API value, but have different enums. It works correctly now.

And finally, with these changes, there were just far too many IF conditions within the Select so made one check for isRole and based on that load a different Select.

## Verification Steps
1. Go to User Federation > LDAP > LDAP Mappers.
2. Create new mapper.
3. Choose `role-ldap-mapper` as mapper type.
4. Verify that `Role Object Classes` has the correct defaults for the Active Directory vendor type (`group`) vs the other vendors (`groupOfNames`), and that you can save/read correctly, using the old console if needed.
5. Verify that for the Active Directory vendor type, `User roles retrieve strategy` has three choices, vs the other vendors which  should have only two choices, and that you can save/read correctly, using the old console if needed.
6. Repeat with the `group-ldap-mapper` mapper type. See old console for comparison purposes.

## Checklist:
- [x] Code has been tested locally by PR requester
- [x] User-visible strings are using the react-i18next framework (useTranslation)
- [x] Help has been implemented
- [x] Unit tests have been created/updated

## Additional Notes
None

2021-11-22 20:34 UTC, jenny-s51 requested changes
`User roles retrieve strategy` is looking great and works as expected. 

It looks like when the vendor type is AD, and either `group-ldap-mapper` or `role-ldap-mapper` is selected, its value is initially undefined and therefore we always get `groupOfNames` in as the defaultValue (but we need `groups`). After some investigating it looks like you can rename the values in the hook to fix this (see comments)!

Otherwise LGTM 🙂

2021-11-22 20:34 UTC, jenny-s51 commented on src/user-federation/ldap/mappers/LdapMapperRoleGroup.tsx
> +                  hidden={vendor !== "ad"}
```suggestion
                  hidden={vendorType !== "ad"}
```

2021-11-22 20:34 UTC, jenny-s51 commented on src/user-federation/ldap/mappers/LdapMapperRoleGroup.tsx
> +                  hidden={vendor !== "ad"}
```suggestion
                  hidden={vendorType !== "ad"}
```

2021-11-22 20:34 UTC, jenny-s51 commented on src/user-federation/ldap/mappers/LdapMapperRoleGroup.tsx
> +        setVendor(fetchedComponent.config?.vendor[0]);
`vendor` is undefined on the initial load so the defaultValue always gets set to `groupOfNames`
```suggestion
        const vendor = fetchedComponent.config?.vendor[0];
        setVendorType(vendor);
```

2021-11-23 16:34 UTC, mfrances17 commented on src/user-federation/ldap/mappers/LdapMapperRoleGroup.tsx
> +        setVendor(fetchedComponent.config?.vendor[0]);
thanks @jenny-s51, good catch 👍  - this wouldn't have worked as originally coded, i thought i had tested that. should be fixed now.

2021-11-23 18:18 UTC, jenny-s51 approved these changes
Nice work @mfrances17 !

2021-11-24 10:34 UTC, jonkoops approved these changes

2021-11-29 14:07 UTC, merged