Realm settings(client policies): Add switches to client policies table
keycloak/keycloak-admin-ui pull request #1595
Opened 2021-11-22 21:04 UTC by jenny-s51

Closes #1388

2021-11-22 21:39 UTC, ssilvert approved these changes
LGTM

2021-11-23 12:28 UTC, jonkoops requested changes

2021-11-23 12:28 UTC, jonkoops commented on src/realm-settings/PoliciesTab.tsx
> +  const form = useForm({ mode: "onChange" });
Can you provide a type for this form's value?

2021-11-23 12:28 UTC, jonkoops commented on src/realm-settings/PoliciesTab.tsx
> +    }) as ClientPolicyRepresentation[];
Instead of using `as` (which might cast the type invalidly) you can provide a generic of the expected type to `map()`.
```suggestion
    const updatedPolicies = policies?.map<ClientPolicyRepresentation>(
      (policy) => {
        if (policy.name !== updatedPolicy.name) {
          return policy;
        }

        const enabled = switchValues[updatedPolicy.name!];

        return {
          ...policy,
          enabled: enabled,
        };
      }
    );
```

2021-11-23 12:28 UTC, jonkoops commented on src/realm-settings/PoliciesTab.tsx
> +      history.push(`/${realm}/realm-settings/clientPolicies`);
Can we use a route function here instead?

2021-11-23 18:12 UTC, jenny-s51 commented on src/realm-settings/PoliciesTab.tsx
> +  const form = useForm({ mode: "onChange" });
Yes good idea! After changing this I discovered a bug in the function that updates the switch values... investigating...

2021-11-24 10:02 UTC, jonkoops commented on src/realm-settings/PoliciesTab.tsx
> +  const form = useForm({ mode: "onChange" });
Very nice! It's always great when TypeScript helps us find possible bugs.

2021-11-24 10:08 UTC, jonkoops requested changes

2021-11-24 10:08 UTC, jonkoops commented on src/realm-settings/PoliciesTab.tsx
> +  const form = useForm<EnabledConfigPolicyForm>({ mode: "onChange" });
TypeScript has a useful type for these kind of objects called [`Record`](https://www.typescriptlang.org/docs/handbook/utility-types.html#recordkeys-type) which you could use here. Both options are equally valid though, so it comes down to personal preference.

```suggestion
  const form = useForm<Record<string, boolean>>({ mode: "onChange" });
```

2021-11-24 10:08 UTC, jonkoops commented on src/realm-settings/PoliciesTab.tsx
> +          key={key && policies.length}
I think this might break the refresh logic. If `key` is a 'truthy' value (1 or higher) the resulting value will always be `policies.length`.

2021-11-24 14:26 UTC, jenny-s51 commented on src/realm-settings/PoliciesTab.tsx
> +  const form = useForm<EnabledConfigPolicyForm>({ mode: "onChange" });
Ah yes, very cool! Thank you for suggesting this

2021-11-24 15:09 UTC, jonkoops approved these changes

2021-11-24 16:19 UTC, merged