User credentials
keycloak/keycloak-admin-ui pull request #1597
Opened 2021-11-23 10:50 UTC by agagancarczyk

## Motivation
Adding "Credentials" tab for Users section as per the following: 
1. Empty state, set password, delete password -> https://marvelapp.com/prototype/a9b33db/screen/83342134
2. Reset password -> https://marvelapp.com/prototype/a9b33db/screen/83342111
3. View data -> https://marvelapp.com/prototype/a9b33db/screen/83342116

Note: (1) Multiple credentials and (2) change user label designs haven't been implemented yet. I need to get some clarifications before proceeding. Also tests will be added in a separate PR.

## Verification Steps
1. Navigate to Users screen and add a new user. Select created user and navigate to 'Credentials" tab.
2. Verify empty state and set a new password. Complete the form. Both passwords should match (if not error should show - not implemented yet). For now, only an alert is displaying and preventing the user from setting up a new password. Once set up successfully, the password should display in a table.
3. Select "Show data" and verify that password data dialog with data in alphabetical order is displaying. Close the dialog.
4. Select "Reset Password" and proceed with the reset. 
5. Select "Delete" from the dropdown and delete the password. Verify the empty state. 

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

2021-11-23 16:13 UTC, jonkoops requested changes

2021-11-23 16:13 UTC, jonkoops commented on src/user/UserCredentials.tsx
> +        setKey(key + 1);
This might hold an older version of the `key` due to the way scoping works in JS. Perhaps we can use the callback style here?
```suggestion
        setKey((key) => key + 1);
```

2021-11-23 16:13 UTC, jonkoops commented on src/user/UserCredentials.tsx
> +          : t("savePasswordError"),
This ternary is quite hard to read.

2021-11-24 09:30 UTC, agagancarczyk commented on src/user/UserCredentials.tsx
> +  const refresh = () => setKey(new Date().getTime());
yeah, true, like your idea!

2021-11-24 11:17 UTC, agagancarczyk commented on src/user/UserCredentials.tsx
> +          : t("savePasswordError"),
thanks @jonkoops I have now cleaned it up!

2021-11-24 15:10 UTC, jonkoops approved these changes
Looks great!

2021-11-24 15:37 UTC, merged