added import dialog for authorization resources
keycloak/keycloak-admin-ui pull request #1604
Opened 2021-11-26 09:42 UTC by edewit

added only [the screen](https://marvelapp.com/prototype/78j1b69/screen/82976116) without the import logic

2021-11-30 12:27 UTC, ssilvert submitted a review, later dismissed
This breaks the partial import tests.

2021-11-30 16:05 UTC, jonkoops requested changes

2021-11-30 16:05 UTC, jonkoops commented on src/clients/authorization/ImportDialog.tsx
> +              .filter((entry) => Array.isArray(entry[1]))
You could also destructure this.
```suggestion
              .filter(([, value]) => Array.isArray(value))
```

2021-11-30 16:05 UTC, jonkoops commented on src/clients/authorization/ImportDialog.tsx
> +      title="Import"
This title will have to be translated.

2021-12-01 10:51 UTC, jonkoops approved these changes

2021-12-01 10:52 UTC, jonkoops commented
@edewit Looks good to me, but there are some merge conflicts.

2021-12-01 11:05 UTC, merged