Wait for group to be deleted before navigating
keycloak/keycloak-admin-ui pull request #1634
Opened 2021-12-01 11:58 UTC by jonkoops

Closes #1625

2021-12-01 12:01 UTC, agagancarczyk approved these changes
lgtm

2021-12-01 21:07 UTC, jenny-s51 requested changes
Looking good @jonkoops !

Can we change this line https://github.com/keycloak/keycloak-admin-ui/blob/main/src/groups/GroupsSection.tsx#L51

to `addAlert(t("groupDeleted_one"), AlertVariant.success);`? Looks like it wasn't getting the correct localized string before.

2021-12-02 10:29 UTC, jonkoops commented
@jenny-s51 Good catch! I added the change, can you take another look?

2021-12-02 14:00 UTC, jenny-s51 approved these changes

2021-12-03 11:16 UTC, merged