Changed the idP mapper form to use the new Dynamic forms
keycloak/keycloak-admin-ui pull request #1641
Opened 2021-12-02 07:58 UTC by edewit

This changes the way the idp mappers render based on the types instead of the premade form

2021-12-06 12:29 UTC, jonkoops requested changes

2021-12-06 12:29 UTC, jonkoops commented on src/components/dynamic/GroupComponent.tsx
> +      typeAheadAriaLabel="Select an action"
This label should be translated.

2021-12-06 12:29 UTC, jonkoops commented on src/components/dynamic/GroupComponent.tsx
> +                onChange(groups.map((g) => g.path)[0]);
If you are always getting this first group, can't we get rid of the map operation here? Something like:
```ts
onChange(groups[0].path);
```

2021-12-06 12:29 UTC, jonkoops commented on src/components/dynamic/GroupComponent.tsx
> +              <ChipGroup categoryName={""}>
Can the category name prop be omitted?
```suggestion
              <ChipGroup>
```

2021-12-06 12:29 UTC, jonkoops commented on src/components/dynamic/GroupComponent.tsx
> +                  <Chip onClick={() => onChange(undefined)}>{value}</Chip>
Should clicking a chip clear the value?

2021-12-06 22:20 UTC, jenny-s51 requested changes
Excellent refactor @edewit !! Left a couple comments 🙂

2021-12-06 22:20 UTC, jenny-s51 commented on src/identity-providers/add/AddMapper.tsx
>    const [mapperType, setMapperType] = useState(
Looks like these are not currently rendering the fields for the default mapper type.

Line 81: `"advancedAttributeToRole"` can be replaced with `"saml-advanced-role-idp-mapper"` and for line 82 we can use `"hardcoded-user-session-attribute-idp-mapper"` to render the correct fields by default.

The `attributeImporter` type here also cannot be used the way it was used previously since [lines 228 - 231](https://github.com/keycloak/keycloak-admin-ui/pull/1641/files#diff-99eab818b1103a8fb2fb717ae61ca05c92e919aeba6159455533f9624987469dL228-L231) were deleted

2021-12-08 15:10 UTC, edewit commented on src/components/dynamic/GroupComponent.tsx
> +              <ChipGroup categoryName={""}>
no it renders something different if you do

2021-12-08 15:10 UTC, edewit commented on src/components/dynamic/GroupComponent.tsx
> +                  <Chip onClick={() => onChange(undefined)}>{value}</Chip>
yes

2021-12-10 10:52 UTC, jonkoops approved these changes
Code looks good to me, but it looks like the tests are still failing.

2021-12-14 22:46 UTC, merged