Fix modal title in User Fed -> hardcoded-ldap-mapper
keycloak/keycloak-admin-ui pull request #1643
Opened 2021-12-02 14:40 UTC by jenny-s51

## Motivation

Closes #1483 

## Verification Steps

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

## Additional Notes

@ssilvert it looks like clients without assigned roles are no longer displayed as options in the filter dropdown, which seems to  address the filtering issue you raised - please confirm

2021-12-02 22:19 UTC, ssilvert commented
@jenny-s51 I can confirm that the clients without assigned roles are no longer displayed.  So that must have been fixed somewhere else along the way.

I assume this is just fixing the title?

2021-12-03 13:59 UTC, jenny-s51 commented
@ssilvert yes that's correct!

2021-12-06 16:05 UTC, ssilvert approved these changes
LGTM

2021-12-06 17:17 UTC, jonkoops requested changes

2021-12-06 17:17 UTC, jonkoops commented on src/groups/GroupsSection.tsx
> +                    deleteGroup({ id });
Why was this `await` removed? It is required for a bugfix, see https://github.com/keycloak/keycloak-admin-ui/pull/1634

2021-12-06 21:09 UTC, mfrances17 approved these changes
LGTM, works great - should be ok to merge once the async/await is back.

2021-12-06 21:13 UTC, jenny-s51 commented
Fixed @jonkoops @mfrances17 !

2021-12-08 10:17 UTC, jonkoops approved these changes

2021-12-08 14:16 UTC, merged