Complete partial import functionality.
keycloak/keycloak-admin-ui pull request #1644
Opened 2021-12-03 20:25 UTC by ssilvert

## Motivation
Completed Partial Import

## Brief Description
The import button is now active and it calls the REST endpoint.  Then it displays the results as per:
https://marvelapp.com/prototype/fg26f9b/screen/75624798

## Verification Steps
1. Go to `Realm settings`.
2. Select Partial import form the Action dropdown.
3. Import a previously exported Keycloak json. (Samples test data at `/cypress/fixtures/partial-import-test-data/`. kcexport.json is a good one to look at)
4. Verify that modal presents the user with options as shown in the design, plus multi-realm functionality.
5. Press import and see results.

## Checklist:

- [X] Code has been tested locally by PR requester
- [X] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented (not applicable)
- [ ] axe report has been run and resulting a11y issues have been resolved
- [X] Unit tests have been created/updated

2021-12-06 16:01 UTC, jonkoops commented on src/realm-settings/PartialImport.tsx
> +  const importModal = () => {
Technically this function is a valid React function component, perhaps we should be treating it as such. It doesn't have to leave this file but could be standalone.

```tsx
const ImportModal = () => { ... }

{!importResponse && <ImportModal />}

2021-12-06 16:07 UTC, jonkoops commented on src/realm-settings/PartialImport.tsx
> +    let last = first! + max!;
Using the [non-null assertion operator](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-0.html#non-null-assertion-operator) (`!`) here can cause exceptions at run-time as the value can be possibly `undefined`. When using this operator you are essentially saying to the compiler that it should not be catching these errors at compile time as you are 'sure' that this is fine.

A better solution here I think would be to provide some default values so that we're not disabling any compile-time checks.
```suggestion
  const loader = async (first = 0, max = 15) => {
    let last = first + max;
```

2021-12-06 16:10 UTC, jonkoops commented on src/realm-settings/PartialImport.tsx
> +  const loader = async (first?: number, max?: number) => {
You can reduce the amount of non-null assertions and optional chaining here by using an early return on the presence of `importResponse` (like already at the end of this function).

```suggestion
  const loader = async (first?: number, max?: number) => {
    // Empty state can't happen as you will get back a result record
    // for each record you submit. This is here to make Typescript happy.
    if (!importResponse) {
      return [];
    }
```

2021-12-06 16:17 UTC, jonkoops commented on src/realm-settings/PartialImport.tsx
> +    if (last > length!) last = length!;
Instead of this statement I think you could also use [`Math.min`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/min) to keep the bounds here.

```ts
const last = Math.min(first + max, importResponse.results.length);
```

2021-12-06 16:19 UTC, jonkoops commented on src/realm-settings/PartialImport.tsx
> +  };
If you take all the suggestions above you'll end up with something like this:

```ts
const loader = async (first = 0, max = 15) => {
  if (!importResponse) {
    return [];
  }

  const last = Math.min(first + max, importResponse.results.length);

  return importResponse.results.slice(first, last);
};
```

2021-12-06 16:23 UTC, jonkoops commented on src/realm-settings/PartialImport.tsx
> +  const ActionLabel = (importRecord: { action: string }) => {
You can also directly reference the original type here. It's a tad verbose as the type was not extracted in the admin client library.
```suggestion
  const ActionLabel = (importRecord: PartialImportResponse["results"][0]) => {
```

2021-12-06 16:24 UTC, jonkoops commented on src/realm-settings/PartialImport.tsx
> +    let color: "green" | "orange" | "purple" = "green";
You can reference the prop type here directly as well. 
```suggestion
    let color: LabelProps["color"] = "green";
```

2021-12-06 16:26 UTC, jonkoops commented on src/realm-settings/PartialImport.tsx
> +    if (importRecord.action === "OVERWRITTEN") {
Since these branches are mutually exclusive you might want to use `else if` here.
```suggestion
    } else if (importRecord.action === "OVERWRITTEN") {
```

2021-12-06 16:27 UTC, jonkoops commented on src/realm-settings/PartialImport.tsx
> +  const TypeRenderer = (importRecord: { resourceType: string }) => {
The original type can be referenced here as well.
```suggestion
  const TypeRenderer = (importRecord: PartialImportResponse["results"][0]) => {
```

2021-12-06 16:27 UTC, jonkoops commented on src/realm-settings/PartialImport.tsx
> +    const typeMap = new Map<string, string>([
There is no need to provide a generic type for this make as it can be inferred from the value passed into the constructor.
```suggestion
    const typeMap = new Map([
```

2021-12-06 16:29 UTC, jonkoops commented on src/realm-settings/PartialImport.tsx
> +  const importCompletedModal = () => {
This is essentially a React functional component, perhaps we should use it like such.
```tsx
const ImportCompletedModal = () => { }
  
{importResponse && <ImportCompletedModal />}
```

2021-12-07 14:28 UTC, ssilvert commented on src/realm-settings/PartialImport.tsx
> +    return (importedFile as [RealmRepresentation]).map(mapper);
That's true, but TypeScript can't figure it out without the `isArray`.  Using isMultiRealm is more clear.  

However, I do see that I've got the wrong type there.  It should be `RealmRepresentation[]`.  So I'll fix that.

2021-12-07 15:06 UTC, ssilvert commented on src/realm-settings/PartialImport.tsx
> +  }) => {
Agree.  That's much better.

2021-12-07 19:19 UTC, ssilvert commented on src/realm-settings/PartialImport.tsx
> +    return (importedFile as [RealmRepresentation]).map(mapper);
```suggestion
    return (importedFile as RealmRepresentation[]).map(mapper);
```

2021-12-07 19:28 UTC, ssilvert commented on src/realm-settings/PartialImport.tsx
> +    let color: "green" | "orange" | "purple" = "green";
That's an interesting way to do it, but unless you feel strongly, I'd rather not rewrite that section of the code.

2021-12-07 19:52 UTC, ssilvert commented on src/realm-settings/PartialImport.tsx
> +    if (importRecord.action === "OVERWRITTEN") {
I'll go one better.  How about no if statement at all?
```
  const ActionLabel = (importRecord: { action: string; id: string }) => {
    const actionLabels = new Map([
      [
        "ADDED",
        <Label key={importRecord.id} color="green">
          {t("added")}
        </Label>,
      ],
      [
        "SKIPPED",
        <Label key={importRecord.id} color="orange">
          {t("skipped")}
        </Label>,
      ],
      [
        "OVERWRITTEN",
        <Label key={importRecord.id} color="purple">
          {t("overwritten")}
        </Label>,
      ],
    ]);

    return actionLabels.get(importRecord.action);
  };
```

2021-12-07 19:59 UTC, ssilvert commented on src/realm-settings/PartialImport.tsx
> +  const TypeRenderer = (importRecord: { resourceType: string }) => {
I don't understand why I would want or need the original type here.

2021-12-08 17:54 UTC, ssilvert commented on src/realm-settings/PartialImport.tsx
> +  const importCompletedModal = () => {
I like that idea, but I found something interesting.  When I change this one to be a component, the dropdowns inside the modal only contain one item:
`{!importResponse && <ImportModal />}`

Any idea why that would be?  Somehow, the function is treated differently when used as a component.

2021-12-08 17:55 UTC, ssilvert commented on src/realm-settings/PartialImport.tsx
> +    if (importRecord.action === "OVERWRITTEN") {
BTW, I went ahead and added the above code.

2021-12-08 20:14 UTC, ssilvert commented on src/realm-settings/PartialImport.tsx
> +  const importCompleteMessage = () => {
I think that would look ugly.  I like to keep the markup compact so you can easily see its structure.

2021-12-08 20:17 UTC, ssilvert commented on src/realm-settings/PartialImport.tsx
> +  const importModal = () => {
See my reply to your same concern on [ImportCompletedModal](https://github.com/keycloak/keycloak-admin-ui/pull/1644#discussion_r765094879).  Weird behavior when I changed this.

2021-12-08 20:21 UTC, ssilvert commented on src/realm-settings/PartialImport.tsx
> +  const ActionLabel = (importRecord: { action: string }) => {
I don't understand that one.  Why would I want to do that?

2021-12-08 20:28 UTC, ssilvert commented on src/realm-settings/PartialImport.tsx
> +  };
Yes, that's much nicer.

2021-12-08 20:32 UTC, ssilvert commented on src/realm-settings/PartialImport.tsx
> +                  <Text>{t("selectRealm")}:</Text>
I'm not sure that's true in this case.  The colon is not punctuation but rather part of the layout.

2021-12-08 20:37 UTC, ssilvert commented on src/realm-settings/PartialImport.tsx
> +                <DataList aria-label="Resources to import" isCompact>
Done.

2021-12-08 20:42 UTC, ssilvert commented on src/realm-settings/PartialImport.tsx
> +          {isFileSelected && targetHasResources() && (
I think that would be overkill for this.

2021-12-09 07:20 UTC, edewit requested changes

2021-12-09 07:20 UTC, edewit commented on src/realm-settings/PartialImport.tsx
> +  const loader = async (first = 0, max = 15) => {
These defaults have no effect, maybe we should change the loader type

2021-12-09 07:20 UTC, edewit commented on src/realm-settings/PartialImport.tsx
> +  const TypeRenderer = (importRecord: { resourceType: string }) => {
you are now declaring `imported` record as a new type when you apply the suggestion by @jonkoops the type will be the same as `PartialImportResponse` and not duplicated e.g.:
```typescript
importRecord: {
    action: string;
    resourceType: string;
    resourceName: string;
    id: string;
} 
```

2021-12-09 07:20 UTC, edewit commented on src/realm-settings/messages.ts
> +      "{{added}} records added. {{skipped}} records skipped. {{overwritten}} records overwritten.",
You could split this up into separate parts:
```typescript
importSuccessRoutes_zero: "no records where added",
importSuccessRoutes_one: "one record added.",
importSuccessRoutes_other: "{{count}} records added.",
```
And then use it like this:
```typescript
t("importSuccessRoutes", {
      count: importResponse?.added,
})
```

2021-12-09 12:50 UTC, ssilvert commented on src/realm-settings/PartialImport.tsx
> +  const loader = async (first = 0, max = 15) => {
Perhaps so.

2021-12-09 13:57 UTC, jonkoops commented on src/realm-settings/PartialImport.tsx
> +  const [targetRealm, setTargetRealm] = useState<RealmRepresentation>({});
@ssilvert why was this one marked as resolved? I still see the original code.

2021-12-09 14:08 UTC, ssilvert commented on src/realm-settings/messages.ts
> +      "{{added}} records added. {{skipped}} records skipped. {{overwritten}} records overwritten.",
That's nice.  Fixed.

2021-12-09 14:18 UTC, jonkoops commented on src/realm-settings/PartialImport.tsx
> +    return (importedFile as [RealmRepresentation]).map(mapper);
I have to disagree that `isMultiRealm` is the correct solution here, for the reason that this code can compile and still produce run-time errors or other unexpected behaviour. When the `as` keyword is used a subset of the type-checking in the compiler is disabled, essentially you are telling the compiler that you know better than it what type a value is. 

TypeScript does in no way provide any runtime guarantees for these kinds of type-casts as they are simply compiled away in the translation to JavaScript.


For example, if I were to set `isMultiRealm` to `true` because I am a human that can make mistakes this code will produce a runtime exception:

![An example of such a runtime exception](https://user-images.githubusercontent.com/695720/145411797-c9b63e41-4b56-46c8-9c22-fd42b8cdb02d.png)

This is further exacerbated by the fact that  `isMultiRealm` is not a computed value, but a separate state. Which increases the possibility for errors simply by forgetting to update the state when the `importedFile` state changes. A better solution would be to derive the value of `isMultiRealm` directly from the `importedFile` state:

```ts
  const [importedFile, setImportedFile] = useState<ImportedMultiRealm>([]);
  const isMultiRealm = Array.isArray(importedFile);
```

This guarantees that the value remains correct without the need for manually setting state to do so. However this does not resolve issues of type-casting a value based on other state.

2021-12-09 14:18 UTC, ssilvert commented on src/realm-settings/PartialImport.tsx
> +  const TypeRenderer = (importRecord: { resourceType: string }) => {
I still don't see why that's better.  You have to know what `[0]` means.  Seems to me that my way is more clear to the reader.

2021-12-09 14:22 UTC, ssilvert commented on src/realm-settings/PartialImport.tsx
>      event: React.ChangeEvent<Element> | React.MouseEvent<Element, MouseEvent>,
Good idea.  Changed.

2021-12-09 14:23 UTC, jonkoops commented on src/realm-settings/PartialImport.tsx
> +          {isFileSelected && targetHasResources() && (
True, in this case it might be overkill. Consider it resolved.

2021-12-09 14:25 UTC, jonkoops commented on src/realm-settings/PartialImport.tsx
> +  const importCompleteMessage = () => {
Fair enough.

2021-12-09 14:28 UTC, jonkoops commented on src/realm-settings/PartialImport.tsx
> +  const ActionLabel = (importRecord: { action: string }) => {
It would allow you to use all the fields from this object without creating a duplicate type for it. However it's perhaps not the best option. Consider this one resolved.

2021-12-09 14:28 UTC, jonkoops commented on src/realm-settings/PartialImport.tsx
> +    let color: "green" | "orange" | "purple" = "green";
Sure I have no preference here, just a note that this is possible.

2021-12-09 14:33 UTC, jonkoops commented on src/realm-settings/PartialImport.tsx
> +    if (importRecord.action === "OVERWRITTEN") {
This is a good improvement, but you could take it a step further and remove the need to keep a `Map` around by using a `switch` statement and returning the values directly. This might also be more performant as it does not allocate the extra elements in memory and is likely more easily optimized by the JIT.

```tsx
const ActionLabel = (importRecord: { action: string; id: string }) => {
  switch (importRecord.action) {
    case "ADDED":
      return (
        <Label key={importRecord.id} color="green">
          {t("added")}
        </Label>
      );
    case "SKIPPED":
      return (
        <Label key={importRecord.id} color="green">
          {t("added")}
        </Label>
      );
    case "OVERWRITTEN":
      return (
        <Label key={importRecord.id} color="purple">
          {t("overwritten")}
        </Label>
      );
  }
};
```

2021-12-09 14:33 UTC, jonkoops commented on src/realm-settings/PartialImport.tsx
> +  const TypeRenderer = (importRecord: { resourceType: string }) => {
Exactly, however as long as they types share the same fields this should not be a problem per se.

2021-12-09 14:44 UTC, ssilvert commented on src/realm-settings/PartialImport.tsx
> +    return (importedFile as [RealmRepresentation]).map(mapper);
isMultiRealm is computed in lines 118-124 and it's just a saved value of what you are suggesting.  If that isn't set correctly you will have other problems.

`const isMultiRealm = Array.isArray(importedFile);` is not correct because a one-element array is not multi-realm.

So to do it your way I would need both:
`if (!isMultiRealm) return [];`
`if (!Array.isArray(importedFile)) {
  return [];
}`

which is redundant.  

I guess it wouldn't hurt though, so if you want me to add that redundant check just to get rid of the cast I'll do it.

2021-12-09 14:54 UTC, ssilvert commented on src/realm-settings/PartialImport.tsx
> +  const [targetRealm, setTargetRealm] = useState<RealmRepresentation>({});
Sorry.  I didn't mean to mark resolved without an explanation.  I don't see why there is a problem with setting a default value.  Then I never have to worry about doing operations on an undefined value.

2021-12-09 15:03 UTC, jonkoops commented on src/realm-settings/PartialImport.tsx
> +  const importModal = () => {
Yeah, I think we can keep things like they are for now.

2021-12-09 15:21 UTC, ssilvert commented on src/realm-settings/PartialImport.tsx
> +  const importCompletedModal = () => {
Agreed off line to leave as-is.

2021-12-09 18:41 UTC, jonkoops approved these changes

2021-12-09 23:13 UTC, jonkoops commented on src/realm-settings/PartialImport.tsx
> +                  <Text>{t("selectRealm")}:</Text>
I guess if it becomes a problem we can always add a quick fix for it. Let's consider this resolved.

2021-12-10 06:07 UTC, edewit approved these changes

2021-12-10 10:53 UTC, merged