changed to use Dynamic components instead
keycloak/keycloak-admin-ui pull request #1662
Opened 2021-12-06 11:12 UTC by edewit

Now uses thet Dynamic components based on the respone of keycloak

2021-12-06 17:29 UTC, jonkoops requested changes

2021-12-06 17:29 UTC, jonkoops commented on src/user-federation/ldap/mappers/LdapMapperDetails.tsx
> +        {}
We can get rid of the `any` here by passing a generic to the `reduce()` with the expected type.

```ts
.reduce<Record<string, string | string[]>>()
```

2021-12-10 10:56 UTC, jonkoops approved these changes

2021-12-10 10:56 UTC, jonkoops commented on src/user-federation/ldap/mappers/LdapMapperDetails.tsx
> +          `/${realm}/user-federation/ldap/${mapper!.parentId}/mappers`
Any chance we can use a route function here?

2021-12-10 10:56 UTC, jonkoops commented on src/user-federation/ldap/mappers/LdapMapperDetails.tsx
> +      ).reduce((result: any, [key, value]) => {
Instead of typing `result` as any you can provide a generic to the `reduce()` method for the result type.

2021-12-10 10:56 UTC, jonkoops commented
@edewit the tests still seem to be failing, can you take a look?

2021-12-15 16:35 UTC, mfrances17 approved these changes
LGTM - the failing test should be fixed once https://github.com/keycloak/keycloak-admin-ui/pull/1700 is merged. it's most likely caused by the max-content group label issue i posted about earlier this week. if you don't want to wait for that PR to be merged, you can fix it by removing the `.pf-c-form__group-label `style from `user-section.css `and the failing test should pass.

2021-12-16 16:24 UTC, merged