Edit message bundle values
keycloak/keycloak-admin-ui pull request #1663
Opened 2021-12-06 20:52 UTC by jenny-s51

## Motivation

https://issues.redhat.com/browse/CLUX-162
Closes #684 

## Verification Steps

1. Go to Realm Settings -> Localization
2. Enable internationalization
3. Save and add a message bundle to the data table below.
4. Click the edit icon to the right of the key/value pair you added.
5. Verify that the value can be edited, updated, and saved correctly.

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

## Additional Notes

Tests will be added in separate PR

2021-12-09 08:54 UTC, edewit requested changes
I think it's better to not use the `KeycloakDatatable` for this and instead use a custom table. We already do this in other places if we add to much edge cases to this generic component it becomes bloated.

2021-12-10 12:07 UTC, jonkoops requested changes

2021-12-10 12:07 UTC, jonkoops commented on src/realm-settings/LocalizationTab.tsx
> +    if (!invalid && type === RowEditAction.save) {
You could reduce the nesting here by escaping on the inverse of this condition.
```ts
setTableRows(newRows);

if (invalid || type !== RowEditAction.save) {
  return;
}
```

2021-12-10 12:07 UTC, jonkoops commented on src/realm-settings/LocalizationTab.tsx
> +        adminClient.realms.addLocalization(
This API call needs to be awaited.
```suggestion
        await adminClient.realms.addLocalization(
```

2021-12-10 17:03 UTC, jenny-s51 commented on src/realm-settings/LocalizationTab.tsx
> +    if (!invalid && type === RowEditAction.save) {
That is a great suggestion - though I tested this and the behavior did not work as expected, since we want to call a different function for each row edit action

2021-12-10 17:04 UTC, jenny-s51 commented on src/realm-settings/LocalizationTab.tsx
> +      return Object.entries(result).slice(first, first + max + 1);
Good idea 👍

2021-12-10 17:06 UTC, jenny-s51 commented on src/realm-settings/LocalizationTab.tsx
> +        ...params,
Done! Thank you for your approval on https://github.com/keycloak/keycloak-nodejs-admin-client/pull/326 - when you have a moment, would be great if you could kick off a rerun of the tests as I no longer have write access to this repo.

2021-12-16 16:38 UTC, edewit approved these changes

2021-12-16 17:08 UTC, mfrances17 approved these changes
LGTM, code looked good and it tested as expected.

2021-12-17 10:49 UTC, jonkoops submitted a review, later dismissed

2021-12-17 10:49 UTC, jonkoops commented on src/realm-settings/LocalizationTab.tsx
> +                  aria-label="editable-rows-table"
The `aria-label` attribute should be a human-readable string, in this case it should be localized as well.

2021-12-17 10:49 UTC, jonkoops commented on src/realm-settings/LocalizationTab.tsx
> +                  hasIcon={true}
Boolean props that are `true` can have their value omitted.
```suggestion
                  hasIcon
```

2021-12-17 10:49 UTC, jonkoops commented on src/realm-settings/LocalizationTab.tsx
> +                  isSearchVariant={true}
Boolean props that are `true` can have their value omitted.
```suggestion
                  isSearchVariant
```

2021-12-17 10:49 UTC, jonkoops commented on src/realm-settings/LocalizationTab.tsx
> +      addError("addMessageBundleError", error);
I believe the key passed here should be a full path as `addError` does  a call to get the translation from the root scope. If we leave it like this I think the message "addMessageBundleError" will be shown in the error message.

2021-12-17 10:49 UTC, jonkoops commented on src/realm-settings/LocalizationTab.tsx
> +          requestConfig: { headers: { "Content-Type": "text/plain" } },
This is not necessary anymore as the admin client should set this headers itself (see [here](https://github.com/keycloak/keycloak-nodejs-admin-client/blob/121231eaeb21be54aca9315df82f9f11d91c7742/src/resources/realms.ts#L330)).

2021-12-17 10:49 UTC, jonkoops commented on src/realm-settings/LocalizationTab.tsx
> +          selectMenuLocale || getValues("defaultLocale") || whoAmI.getLocale,
`getLocale()` is a function, it should be executed.
```suggestion
          selectMenuLocale || getValues("defaultLocale") || whoAmI.getLocale(),
```

2021-12-17 10:49 UTC, jonkoops commented on src/realm-settings/LocalizationTab.tsx
> +      const params = {
These params can be inlined into the `getRealmLocalizationTexts()` call below.

2021-12-17 16:56 UTC, jenny-s51 commented on src/realm-settings/LocalizationTab.tsx
> +          selectMenuLocale || getValues("defaultLocale") || whoAmI.getLocale,
Nice catch, thank you

2021-12-21 06:34 UTC, merged