Credentials Reset Flow
keycloak/keycloak-admin-ui pull request #1699
Opened 2021-12-13 16:31 UTC by squaremarco

## Motivation
Add credential reset flow to user credential tab

## Verification Steps
1. Go to `Users >> Select User`
2. Add an email to the user, if missing
3. Click `Credentials` tab
4. Click on `Credentials Reset`
5. Fill the form and submit

**NOTE**: for this enhancement to work you must configure a valid smtp server in the realm

## Checklist:
- [x] Code has been tested locally by PR requester
- [x] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

## Additional Notes
![User Credentials Tab](https://user-images.githubusercontent.com/8075395/145850217-101abed4-1978-4ccb-bbfb-2311bf99b96d.png)
![Credentials Reset Form](https://user-images.githubusercontent.com/8075395/145850258-1a3f3b23-a61c-47af-92de-acbd9d104826.png)
![Credentials Reset Form Fill](https://user-images.githubusercontent.com/8075395/145850366-9db96cba-6f0f-4fb9-89e4-be22a6003083.png)
![Credentials Reset Confirmation](https://user-images.githubusercontent.com/8075395/145850429-69441056-edb5-400f-955f-e4352ab3619b.png)

2021-12-13 17:11 UTC, edewit requested changes

2021-12-13 17:11 UTC, edewit commented on src/user/UserCredentials.tsx
> +const lifespanEnumToSeconds = (v: number, e: LifespanEnum) => {
couldn't you use the `TimeSelector` component for this?

2021-12-13 17:19 UTC, agagancarczyk commented
hi @squaremarco many thanks for your contribution. Could you please match your solution with these designs https://marvelapp.com/prototype/a9b33db/screen/84125109? Thanks!

2021-12-13 17:37 UTC, squaremarco commented
> hi @squaremarco many thanks for your contribution. Could you please match your solution with these designs https://marvelapp.com/prototype/a9b33db/screen/84125109 and write tests? Thanks!

Absolutely! I’ll come back to you asap

2021-12-13 18:01 UTC, squaremarco commented on src/user/UserCredentials.tsx
> +const lifespanEnumToSeconds = (v: number, e: LifespanEnum) => {
I wasn’t aware of that component. Thank you for the reply!

2021-12-14 12:36 UTC, squaremarco commented on src/user/UserCredentials.tsx
> +const lifespanEnumToSeconds = (v: number, e: LifespanEnum) => {
Hi @edewit, in my last commit I resolved this change request. I'll provide the test suite soon.

2021-12-14 16:14 UTC, squaremarco commented
Hello, I resolved all the issues you @agagancarczyk and @edewit raised. I've also implemented e2e tests as asked.

2021-12-16 10:34 UTC, edewit requested changes

2021-12-16 10:34 UTC, edewit commented on src/user/UserCredentials.tsx
> +  return (
You could also put it all in one line like this:
```suggestion
const LifespanField = ({
  form: { control },
}: {
  form: UseFormMethods<CredentialResetForm>;
}) => {
  const { t } = useTranslation("users");

  return (
```

2021-12-16 10:34 UTC, edewit commented on src/user/UserCredentials.tsx
> +          style={{ height: "20rem" }}
I'm guessing you added this to make room for the dropdown, you can use it like this:
```suggestion
          variant={ModalVariant.medium}
```
And add:
```
menuAppendTo="parent"
```
to the `CredentialsResetActionMultiSelect` => `Select` then it pops out of the dialog when there is not enough place:
https://www.patternfly.org/v4/components/modal#with-dropdown

2021-12-16 10:35 UTC, edewit commented
This is great work just a small point left

2021-12-16 14:08 UTC, jonkoops approved these changes
Aside from the feedback from Erik this LGTM

2021-12-16 14:08 UTC, jonkoops commented on cypress/support/pages/admin_console/manage/users/CredentialsPage.ts
> +  confirmationButton: string;
Note that you can use [instance fields](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Public_class_fields#public_instance_fields) to assign the value directly without the need for a constructor. Also since these fields are only used in this class and never re-asssigned they could be marked as `private readonly`.
```suggestion
  private readonly credentialsTab = "credentials";
  private readonly emptyStatePasswordBtn = "no-credentials-empty-action";
  private readonly emptyStateResetBtn = "credential-reset-empty-action";
  private readonly resetBtn = "credentialResetBtn";
  private readonly setPasswordBtn = "setPasswordBtn";
  private readonly credentialResetModal = "credential-reset-modal";
  private readonly resetModalActionsToggleBtn = "[data-testid=credential-reset-modal] #actions";
  private readonly passwordField = ".kc-password > .pf-c-input-group > .pf-c-form-control";
  private readonly passwordConfirmationField = ".kc-passwordConfirmation > .pf-c-input-group > .pf-c-form-control";
  private readonly resetActions = [
    "VERIFY_EMAIL-option",
    "UPDATE_PROFILE-option",
    "CONFIGURE_TOTP-option",
    "UPDATE_PASSWORD-option",
    "terms_and_conditions-option",
  ];
  private readonly confirmationButton = "okBtn";
```

2021-12-16 14:08 UTC, jonkoops commented on cypress/support/pages/admin_console/manage/users/CredentialsPage.ts
> +  }
By implementing the feedback above this constructor can be eliminated.

2021-12-17 08:59 UTC, squaremarco commented
Thank you for the feedback, I’ll implement all the requested changes asap.

2021-12-17 10:11 UTC, squaremarco commented
Done, thank you again for the feedback

2021-12-21 06:22 UTC, edewit approved these changes

2021-12-21 06:22 UTC, merged