Fixes for eslint and prettier
keycloak/keycloak-admin-ui pull request #175
Opened 2020-10-14 20:04 UTC by mfrances17

The linting configuration using eslint and prettier was not working with the VSCode intellisense, you could not visually see the issues as you were working, although you could force a format with keystrokes. This fix will allow you to see the issues in the IDE in real-time as you are working, and hover over them >  _Quick Fix_ > _Fix this prettier/prettier problem_.

![lint-int-found](https://user-images.githubusercontent.com/39063664/96039554-d5079980-0e36-11eb-9d58-93248fc978f3.png)

![lint-int-fix](https://user-images.githubusercontent.com/39063664/96039566-d89b2080-0e36-11eb-8e29-d4c837f35af2.png)

2020-10-15 05:49 UTC, edewit requested changes
Is this something that changed by mistake, because I only see this one change and I'm sure that we use it all over the place? And could you elaborate on what the actual problem is, because I don't have any issues with VS code

2020-10-15 05:49 UTC, edewit commented on src/client-scopes/details/MapperList.tsx
> -type Row = {
I like the type notation when it's a simple type why do we want to change that?

2020-10-15 11:09 UTC, ssilvert commented on src/client-scopes/details/MapperList.tsx
> -type Row = {
@mfrances17 We have decided to use `type` for everything except the (data transfer) Representation types.  The only reason we use `interface` for that is because many are auto-generated and the tool that generates these types uses `interface`.

According to "Effective Typescript", `type` has advantages over `interface` because it can express:
- Union types
- Mapped types
- Tuple types

The only thing an `interface` can do that a `type` can not do is "declaration merging", which is weird and tends to only be used in *.d.ts files.

2020-10-20 18:08 UTC, mfrances17 commented on src/client-scopes/details/MapperList.tsx
> -type Row = {
i removed the offending type/interface rule and reverted the related changes that were made to MapperList.tsx

2020-10-20 18:13 UTC, dlabaj approved these changes

2020-10-20 18:19 UTC, dlabaj commented
@mfrances17 You need to run prettier fix.  The build is failing.

2020-10-20 18:36 UTC, mfrances17 commented
> @mfrances17 You need to run prettier fix. The build is failing.

Yep, I noticed that earlier and am in the process of fixing them now. Thanks.

2020-10-20 21:01 UTC, mfrances17 commented
Not sure why this is still failing on the server, it passes locally. There may be a difference in versions, although nothing is flagged in the diff. We might need to hold off on this until I get some help on figuring out why the exact same files would fail on the server and pass on my local system.

2020-10-21 17:38 UTC, closed without merging