initial version of the scopes screen
keycloak/keycloak-admin-ui pull request #1750
Opened 2021-12-21 14:17 UTC by edewit

## Motivation

## Brief Description

## Verification Steps

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

## Additional Notes

2022-01-03 16:19 UTC, jonkoops requested changes

2022-01-03 16:19 UTC, jonkoops commented on src/clients/authorization/Scopes.tsx
> +      })) as ExpandableScopeRepresentation[];
This cast is not accurate as it's missing the required `isExpanded` field. Might be better to pass a generic into the `map()` down below.

2022-01-03 16:19 UTC, jonkoops commented on src/clients/authorization/Scopes.tsx
> +  resources: ResourceRepresentation[] | undefined;
The `resources` property already exists on `ScopeRepresentation`, I think this can be removed.
```suggestion
```

2022-01-03 16:19 UTC, jonkoops commented on src/clients/authorization/Scopes.tsx
> +  permissions: PolicyRepresentation[] | undefined;
If a field is optional you can use the following shorthand.
```suggestion
  permissions?: PolicyRepresentation[];
```

2022-01-03 16:19 UTC, jonkoops commented on src/clients/authorization/Scopes.tsx
> +      const params = {
These parameters should be in-lined in the call below, if they are missing in the admin client they should be added there.

2022-01-03 16:19 UTC, jonkoops commented on src/clients/authorization/Scopes.tsx
> +          s.permissions = await adminClient.clients.listAllPermissionsByScope({
These API calls should happen in parallel, now they are waiting for each other.

2022-01-03 16:19 UTC, jonkoops commented on src/clients/authorization/Scopes.tsx
> +      setScopes(scopes.map((scope) => ({ ...scope, isExpanded: false }))),
This mapping procedure should happen before in the fetching logic so that the type is immediately correct.

2022-01-03 16:19 UTC, jonkoops commented on src/clients/authorization/Scopes.tsx
> +        scopes.map(async (s) => {
```suggestion
        scopes.map<Promise<ExpandableScopeRepresentation>>(async (s) => {
```

2022-01-03 16:19 UTC, jonkoops commented on src/clients/authorization/Scopes.tsx
> +          s.resources = await adminClient.clients.listAllResourcesByScope({
This assignment mutates the object directly, in a `map()` operation a new version should be returned that does not mutate the original reference. Same goes for `permissions`.

2022-01-03 16:19 UTC, jonkoops commented on src/clients/authorization/Scopes.tsx
> +  );
If you incorporate all my suggestions from before you'll end up with this: 
```tsx
useFetch(
  async () => {
    const scopes = await adminClient.clients.listAllScopes({
      first,
      max,
      deep: false,
      id: clientId,
    });

    return await Promise.all(
      scopes.map<Promise<ExpandableScopeRepresentation>>(async (scope) => {
        const options = { id: clientId, scopeId: scope.id! };
        const [resources, permissions] = await Promise.all([
          adminClient.clients.listAllResourcesByScope(options),
          adminClient.clients.listAllPermissionsByScope(options),
        ]);

        return {
          ...scope,
          resources,
          permissions,
          isExpanded: false,
        };
      })
    );
  },
  (scopes) => setScopes(scopes),
  [key]
);
```

2022-01-03 16:19 UTC, jonkoops commented on src/clients/authorization/Scopes.tsx
> +                          onClick: async () => {
```suggestion
                          onClick () => {
```

2022-01-04 06:43 UTC, edewit commented on src/clients/authorization/Scopes.tsx
> +      setScopes(scopes.map((scope) => ({ ...scope, isExpanded: false }))),
it doesn't need to be, but it could

2022-01-04 06:46 UTC, edewit commented on src/clients/authorization/Scopes.tsx
> +          s.resources = await adminClient.clients.listAllResourcesByScope({
it doesn't matter that these objects are mutated at this point as they are not yet part of react scope, but I like your change

2022-01-04 07:49 UTC, edewit commented on src/clients/authorization/ScopeDetails.tsx
> +        await adminClient.clients.updateAuthorizationScope(
no the form still has the values that the user entered

2022-01-04 09:15 UTC, jonkoops approved these changes
One comment, otherwise LGTM

2022-01-04 09:15 UTC, jonkoops commented on src/clients/authorization/Scopes.tsx
> +      const params = {
This has not been resolved yet.

2022-01-04 09:17 UTC, edewit commented on src/clients/authorization/Scopes.tsx
> +      const params = {
that is right as the PR for changing the types is still pending, I'll change it in another PR

2022-01-04 09:17 UTC, merged