initial version of the role mapping create form
keycloak/keycloak-admin-ui pull request #177
Opened 2020-10-15 09:02 UTC by edewit

[marvel](https://marvelapp.com/prototype/f0e8fih/screen/72042619)

2020-10-19 09:04 UTC, edewit commented
now uses typeahead and new design: [marvel](https://marvelapp.com/prototype/f0e8fih/section/1103591/screen/72042619)

2020-10-19 14:58 UTC, srambach commented
@edewit How do you get to this in the interface?

2020-10-20 07:39 UTC, edewit commented
@srambach right now only through the story `RoleMappingForm.stories.tsx` still need the other PRs to get merged to do the entire flow

2020-10-20 15:46 UTC, srambach commented on src/client-scopes/add/RoleMappingForm.tsx
> +                helpText="client-scopes-help:protocolMapper"
Looks like the helpText on all these needs the translation.

2020-10-20 15:58 UTC, srambach commented on src/client-scopes/add/RoleMappingForm.tsx
> +                forID="role"
`forID` should match a `toggleId` on the select.

2020-10-20 16:00 UTC, srambach commented on src/client-scopes/add/RoleMappingForm.tsx
> +                  aria-label={t("selectASourceOfRoles")}
This looks like it's coming in blank maybe?

2020-10-20 16:02 UTC, srambach commented on src/client-scopes/add/RoleMappingForm.tsx
> +                      aria-label="Select Input"
I think this looks like it's coming in blank as well, and should be translated as well.

2020-10-20 16:08 UTC, srambach commented on src/client-scopes/add/RoleMappingForm.tsx
> +            <Gallery hasGutter>
This is probably better as a Split than a Gallery.

2020-10-21 09:43 UTC, edewit commented on src/client-scopes/add/RoleMappingForm.tsx
> +                  aria-label={t("selectASourceOfRoles")}
Yes it's not rendering it, is this a know patternfly bug?

2020-10-21 10:12 UTC, edewit commented on src/client-scopes/add/RoleMappingForm.tsx
> +                  aria-label={t("selectASourceOfRoles")}
ahh no found it should use `typeAheadAriaLabel` instead of `aria-label`

2020-10-21 16:07 UTC, srambach commented on src/client-scopes/add/RoleMappingForm.tsx
> +                  id="role"
this needs to be toggleId so that the icon can refer to it

2020-10-21 16:10 UTC, srambach commented on src/client-scopes/add/RoleMappingForm.tsx
> +                      aria-label={t("selectARole")}
And this would also be `typeAheadAriaLabel` then

2020-10-22 14:35 UTC, srambach commented
One question - if I select something in the first dropdown, then the second, then clear the first - should the second dropdown be cleared or left alone?
![image](https://user-images.githubusercontent.com/19825616/96887110-3f7d9280-1452-11eb-8a4f-465316d790bc.png)

If that's good as is, then 👍 LGTM.

2020-10-22 19:43 UTC, ssilvert commented
> [marvel](https://marvelapp.com/prototype/f0e8fih/screen/72042619)
> 
> I think this screen needs some discussion / explanation on how it's supposed to work. As I see from the screen shots the first dropdown has realm roles and clients grouped and a search that only filters clients? I think this would be very confusing for the user. Also that leaves the second dropdown to show the client roles once a client is chosen? On top of this we can't do a filter input on a one select dropdown as it's only supported on a mutli select.

So after trying this out, I really agree with your original comments.  I think this needs to go back to UXD.  It's very confusing.  Frankly, the old console has better usability for this.

2020-10-23 17:11 UTC, ssilvert commented
Closing because the UX design needs review.

2020-10-26 08:34 UTC, edewit commented
Added group and divider to make it more obvious
![image](https://user-images.githubusercontent.com/51133/97150445-67306b80-176e-11eb-92a0-ddda923c8844.png)

2020-10-26 12:17 UTC, ssilvert requested changes

2020-10-26 12:17 UTC, ssilvert commented on src/client-scopes/add/RoleMappingForm.tsx
> +          {t("realmRoles")}
I think this should be the name of the realm, such as "Master" or "Sales and Marketing".  The way this turns out is that it says "Use a realm role from: Realm roles"

2020-10-26 13:55 UTC, edewit commented on src/client-scopes/add/RoleMappingForm.tsx
> +          {t("realmRoles")}
Right missed that change... fix now

2020-10-27 11:25 UTC, ssilvert approved these changes

2020-10-27 11:25 UTC, merged