Change list view header action menu from select to dropdown
keycloak/keycloak-admin-ui pull request #179
Opened 2020-10-15 18:35 UTC by srambach

Fixes #171 
The action menu should have been a dropdown rather than select, and a dropdown allows a right alignment, so this fixes the overflow off the right side as well as correcting the semantics of the element.

To verify, look at the ViewHeader story and also the Client settings page (actions menu in the header)

2020-10-15 18:53 UTC, jenny-s51 requested changes
Looking good @srambach ! Actions menu working as expected per @mfrances17 . Just delete that comment above :)

2020-10-15 18:53 UTC, jenny-s51 commented on src/components/view-header/ViewHeader.tsx
> +                    {/* This is the dropdown to replace the select.  It operates but does not initiate the actions. See it by going to Clients and click on a client. All 3 menu actions should work bu
delete this line

2020-10-19 11:36 UTC, edewit approved these changes
:tada: so much better

2020-10-19 13:44 UTC, jenny-s51 approved these changes
👍

2020-10-19 13:44 UTC, merged