Adding Mapping list and detail screen
keycloak/keycloak-admin-ui pull request #180
Opened 2020-10-19 11:32 UTC by edewit

2020-10-20 20:25 UTC, ssilvert requested changes
Heading for detail screen always says, "Create client scope"

2020-10-20 20:42 UTC, ssilvert commented
Assume you know this, but mapper detail form varies by mapper type.  Variation not implemented yet?

2020-10-21 08:29 UTC, edewit commented
variations coming

2020-10-21 17:36 UTC, ssilvert approved these changes

2020-10-21 17:38 UTC, merged