Update Masthead tests
keycloak/keycloak-admin-ui pull request #1820
Opened 2022-01-03 15:49 UTC by Aboullos

## Motivation
Updating Masthead tests in order to make it more clear and avoid a possible failure scenario of  the`isMobileMode` method

## Brief Description
- Change the name of the method `isAdminConsole`, that could imply the return of a boolean, to `checkIsAdminConsole` to imply the assert check.
- Modify `isMobileMode` method to check the window size instead of just returning a variable (there are different scenarios where the mobile mode could change without updating the variable)

## Checklist:

- [ x] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

2022-01-03 16:23 UTC, jonkoops requested changes

2022-01-03 16:23 UTC, jonkoops commented on cypress/support/pages/admin_console/Masthead.ts
>    }
If this is always the logic to determine if we are mobile or not we can get rid of the `isMobile` field entirely and return the result of the statement instead.

```suggestion
  get isMobileMode() {
    return window.parent[0].innerWidth >= 1024;
  }
```

2022-01-04 11:52 UTC, Aboullos commented on cypress/support/pages/admin_console/Masthead.ts
>    }
Updated

2022-01-04 13:26 UTC, jonkoops approved these changes
LGTM

2022-01-05 09:56 UTC, merged