Adds the permissions tab to the Authorization screen under clients
keycloak/keycloak-admin-ui pull request #1835
Opened 2022-01-07 13:27 UTC by edewit

Permissions tab with create for resource based permssions scope-based comming in a sperate PR also search is still a work in progress

2022-01-07 16:25 UTC, mfrances17 requested changes
Functionality works great... nice job. 

Added one review comment regarding a style, and also I would expect the associated policy row to be indented under the permission, since it is a drop-down, as it is in the old console. Currently it's outdented and doesn't look quite right:
![indent](https://user-images.githubusercontent.com/39063664/148574049-abf2f106-f6ec-4b5e-a22b-54036a053f95.png)

2022-01-07 16:25 UTC, mfrances17 commented on src/clients/authorization/permissions.css
> +.pf-c-button.disabled {
is this really needed? it should probably be renamed to make it unique since styles are global.

2022-01-10 07:32 UTC, edewit commented on src/clients/authorization/permissions.css
> +.pf-c-button.disabled {
yes I can't make the buttons actually disabled as that would make the tooltip not work, but your right I should make it a unique name what was I thinking

2022-01-12 16:01 UTC, mfrances17 approved these changes
Both issues were addressed, nice work

2022-01-12 16:01 UTC, merged