Realm roles: fixes bug that prevented fields from being populated
keycloak/keycloak-admin-ui pull request #1839
Opened 2022-01-07 18:44 UTC by jenny-s51

Closes #1838 

Finishing up a PR that will add selectable functionality to [AttributeInput](https://github.com/keycloak/keycloak-admin-ui/blob/0bbd4ddad1b0fe3eeac9942b88539933f2e66c3a/src/components/attribute-input/AttributeInput.tsx) -- however while testing, I discovered the data could not be saved correctly due to this bug.

After investigating, this seems like it's a timing issue.

2022-01-10 08:05 UTC, edewit requested changes

2022-01-10 08:05 UTC, edewit commented on src/realm-roles/RealmRoleTabs.tsx
> +        if (url.includes("/attributes")) {
This seem like a workaround also the timout of 5 milliseconds I don't see why that would be needed

2022-01-10 19:28 UTC, jenny-s51 commented on src/realm-roles/RealmRoleTabs.tsx
> +        if (url.includes("/attributes")) {
Ah you're right, reordered the hook and the conditional and this seemed to resolve it.

2022-01-13 18:03 UTC, jonkoops approved these changes

2022-01-14 14:56 UTC, edewit approved these changes

2022-01-14 14:56 UTC, merged