add multiple group delete functionality
keycloak/keycloak-admin-ui pull request #185
Opened 2020-10-21 22:07 UTC by christiemolloy

## Motivation
Add multiple delete (add issue later)

## Brief Description
Add multi delete functionality from the toolbar

## Verification Steps
1. Go to Groups 
2. Select multiple table rows
3. Click on the top kebab and click 'delete'
4. This should delete all the table rows that were selected and refresh

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated
- [ ] Formatting has been performed via prettier/eslint
- [ ] Type checking has been performed via 'yarn check-types'

2020-10-22 07:01 UTC, edewit requested changes

2020-10-22 07:01 UTC, edewit commented on src/groups/GroupsSection.tsx
> +      "what is groupsData here" + groupsData + JSON.stringify(groupsData)
Guess we can remove this now that it works 😄

2020-10-22 20:12 UTC, ssilvert requested changes
Looks good.  Just a couple of small changes and it should be ready to go.

2020-10-22 20:12 UTC, ssilvert commented on src/groups/GroupsSection.tsx
> +        addAlert(`${t("clientDeleteError")} ${error}`, AlertVariant.danger);
`clientDeleteError` is missing from the resource bundle.

2020-10-23 14:55 UTC, christiemolloy commented
updated @edewit @ssilvert

2020-10-23 15:17 UTC, srambach commented on src/groups/messages.json
> +    "noGroupsInThisRealm": "No groups in this Realm",
should Realm be lower case?

2020-10-23 15:18 UTC, srambach commented on src/groups/messages.json
> +    "groupDeleteError": "Group unsuccessfully deleted"
What does that mean exactly?  🤣  So... not deleted?

2020-10-23 19:38 UTC, ssilvert commented on src/groups/messages.json
> +    "groupDeleteError": "Group unsuccessfully deleted"
@sguilhen Good catch.  How about "Error deleting group"

2020-10-23 20:28 UTC, christiemolloy commented
updated @srambach @ssilvert

2020-10-23 21:05 UTC, mfrances17 requested changes
Code looks good, one small comment to remove a console msg. 

Also worth investigating, when I originally tested, I was getting inconsistent deletes, sometimes it only deleted one of the couple I selected, sometimes neither. It was upon first startup of the server/admin UI. Once it started working, it worked flawlessly. I'm just suspicious of those first few occurrences. I saw this in the server log:

```
16:48:31,976 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (default task-1) Unique index or primary key violation: "SIBLING_NAMES_INDEX_E ON PUBLIC.KEYCLOAK_GROUP(REALM_ID, PARENT_GROUP, NAME) VALUES ('master', ' ', 'adfadf', 8)"; SQL statement:
insert into KEYCLOAK_GROUP (NAME, PARENT_GROUP, REALM_ID, ID) values (?, ?, ?, ?) [23505-197]
```

2020-10-23 21:05 UTC, mfrances17 commented on src/groups/GroupsSection.tsx
> +  console.log("what is filteredData" + filteredData);
remove this debugging message

2020-10-26 14:51 UTC, jenny-s51 requested changes
Great work @christiemolloy ! Just fix the Empty State toggle -- looking good overall!

2020-10-26 14:51 UTC, jenny-s51 commented on src/groups/GroupsSection.tsx
>            />
When I deleted all the groups to return to the empty state, the `Create Group` button didn't show the `GroupsCreateModal`. Looks like you just need to add

```  
<GroupsCreateModal
          isCreateModalOpen={isCreateModalOpen}
          handleModalToggle={handleModalToggle}
          setIsCreateModalOpen={setIsCreateModalOpen}
          createGroupName={createGroupName}
          setCreateGroupName={setCreateGroupName}
          refresh={loader}
/>
```

under `ListEmptyState` here, and wrap them in a JSX fragment for the modal to toggle.

2020-10-26 15:52 UTC, christiemolloy commented on src/groups/GroupsSection.tsx
>            />
Great catch!!!

2020-10-26 15:55 UTC, christiemolloy commented
@jenny-s51 @mfrances17 updated! @ssilvert have you seen the error message that Mark is referring to in the console of the old product ?

2020-10-27 06:42 UTC, edewit approved these changes
Don't know what that message is about, seems strange that for an delete there is an insert on the database. I think we can merge this when there is some backend problem, which I doubt btw, we can leave that for others to fix.

2020-10-27 18:08 UTC, mfrances17 commented
I was able to reproduce the issue.

1. Created 5 groups, named mark1 - mark5.
2. Selected mark4 and mark5, selected the Delete on mark4 group table row. The mark4 group was deleted, the mark5 group remained. Two notifications of group deleted appear.
3. Select any combination of the remaining group rows (mark1, mark2, mark3) along with mark5, and select the group delete, all other rows will delete but the mark5 group row will never delete. You need to select it by itself and explicitly delete it.

2020-10-27 20:42 UTC, christiemolloy commented
> I was able to reproduce the issue.
> 
> 1. Created 5 groups, named mark1 - mark5.
> 2. Selected mark4 and mark5, selected the Delete on mark4 group table row. The mark4 group was deleted, the mark5 group remained. Two notifications of group deleted appear.
> 3. Select any combination of the remaining group rows (mark1, mark2, mark3) along with mark5, and select the group delete, all other rows will delete but the mark5 group row will never delete. You need to select it by itself and explicitly delete it.

This was an awesome bug to find, thank you Mark!!!! I found the problem - after deleting an individual row I needed to reset the `tableRowSelectedArray` value back to an empty array. The problem was that the array still included the last clicked indexes which was causing the problem.

2020-10-27 21:00 UTC, mfrances17 approved these changes
LGTM... I retested and the multi-delete issue I called out is now fixed. Good job, Christie.

2020-10-27 23:44 UTC, ssilvert approved these changes

2020-10-27 23:45 UTC, ssilvert commented
> LGTM... I retested and the multi-delete issue I called out is now fixed. Good job, Christie.

Great.  Let's merge it!

2020-10-27 23:45 UTC, merged