WIP: Auth evaluate tab
keycloak/keycloak-admin-ui pull request #1861
Opened 2022-01-13 22:26 UTC by jenny-s51

2022-01-18 14:23 UTC, edewit requested changes

2022-01-18 14:23 UTC, edewit commented on package.json
> +    "react-monaco-editor": "^0.41.2",
this is not necessary right it's already part of patternfly

2022-01-18 14:23 UTC, edewit commented on src/clients/ClientDetails.tsx
> +    },
It's better to do these in parallel like this:
```suggestion
    () =>
      Promise.all([
        adminClient.clients.find(),
        adminClient.roles.find(),
        adminClient.users.find(),
      ]),
    ([clients, roles, users]) => {
      setClients(clients);
      setClientRoles(roles);
      setUsers(users);
    },
```

2022-01-18 14:23 UTC, edewit commented on src/clients/ClientDetails.tsx
> +    const allClients = await adminClient.clients.find();
why do you query all clients here again?

2022-01-18 14:23 UTC, edewit commented on src/clients/authorization/AuthorizationEvaluate.tsx
> +    },
```suggestion
    () => adminClient.clients.listResources({ id: clientId }),
```

2022-01-18 14:23 UTC, edewit commented on src/clients/authorization/AuthorizationEvaluate.tsx
> +          </Button>
instead of calling this function directly we can make it a form submit
```suggestion
          <Button data-testid="authorization-eval" type="submit">
            {t("evaluate")}
          </Button>
```

2022-01-18 14:23 UTC, edewit commented on src/clients/authorization/AuthorizationEvaluate.tsx
> +    const formValues = form.getValues();
```suggestion
  const evaluate = (formValues: ResourceEvaluation) => {
```

2022-01-18 14:23 UTC, edewit commented on src/clients/authorization/AuthorizationEvaluate.tsx
> +  const form = useForm<ResourceEvaluation>({ mode: "onChange" });
Do you really need 2 forms on this page?

2022-01-18 14:23 UTC, edewit commented on src/clients/authorization/AuthorizationEvaluate.tsx
> +        <FormAccess isHorizontal role="manage-clients">
use form submit so it only calls your `evaluate` function when the form is valid
```suggestion
        <FormAccess isHorizontal role="manage-clients" onSubmit={form.handleSubmit(evaluate)}>
```

2022-01-18 14:23 UTC, edewit commented on src/clients/authorization/AuthorizationEvaluate.tsx
> +      clientId: clients.find(
you could change your `<Select` to give you the client object instead of just the `id` so that you wouldn't have to find it here again, same goes for user.

2022-01-18 14:23 UTC, edewit commented on src/clients/authorization/Resources.tsx
> +
This can go I guess...
```suggestion
```

2022-01-18 14:23 UTC, edewit commented on src/components/attribute-input/AttributeInput.tsx
> +                          // }
don't you want to keep this?

2022-01-18 19:59 UTC, jenny-s51 commented on src/clients/authorization/AuthorizationEvaluate.tsx
> +      clientId: clients.find(
Great idea, thank you @edewit !

2022-01-19 08:18 UTC, edewit commented on cypress/support/pages/admin_console/manage/realm_settings/RealmSettingsPage.ts
> +    cy.wait(500);
it's better to wait for the request to finish then to wait a "random" amount of time:
```typescript
cy.intercept("/auth/admin/realms/master<something>").as("get");
cy.findByTestId(this.saveNewClientPolicyBtn).click();
cy.get(this.alertMessage).should("be.visible", "New client policy created");
cy.wait(["@get"]);
```

2022-01-19 19:40 UTC, jenny-s51 commented on cypress/support/pages/admin_console/manage/realm_settings/RealmSettingsPage.ts
> +    cy.wait(500);
Updated based on your suggestion though it seems to break the test! Is this the update we would expect here?

```
    cy.intercept(
      "/auth/admin/realms/master/realm-settings/clientPolicies/add-client-policy"
    ).as("get");
    cy.findByTestId(this.saveNewClientPolicyBtn).click();
    cy.get(this.alertMessage).should("be.visible", "New client policy created");
    cy.wait(["@get"]);
```

2022-01-20 10:48 UTC, jonkoops requested changes

2022-01-20 10:48 UTC, jonkoops commented on src/components/attribute-input/AttributeInput.tsx
> +      | undefined;
I think you can remove the type cast here and use an annotation instead.
```suggestion
    let attributeValues: { key: string; name: string; }[] | undefined = [];
```

2022-01-20 10:48 UTC, jonkoops commented on src/components/attribute-input/AttributeInput.tsx
> +  const [isKeyOpenArray, setIsKeyOpenArray] = useState<boolean[]>([false]);
I think Typescript can infer the type here from the assigned value.
```suggestion
  const [isKeyOpenArray, setIsKeyOpenArray] = useState([false]);
```

2022-01-20 10:48 UTC, jonkoops commented on src/components/attribute-input/AttributeInput.tsx
> +  const [isValueOpenArray, setIsValueOpenArray] = useState<boolean[]>([false]);
I think Typescript can infer the type here from the assigned value.
```suggestion
  const [isValueOpenArray, setIsValueOpenArray] = useState([false]);
```

2022-01-20 10:48 UTC, jonkoops commented on src/clients/authorization/AuthorizationEvaluate.tsx
> +      });
These API calls could be made in parallel since they have no dependencies between them.

2022-01-20 10:48 UTC, jonkoops commented on src/clients/authorization/AuthorizationEvaluate.tsx
> +              id="test"
I assume this `id` needs to be changed?

2022-01-20 13:39 UTC, edewit commented on cypress/support/pages/admin_console/manage/realm_settings/RealmSettingsPage.ts
> +    cy.wait(500);
I've created https://github.com/keycloak/keycloak-admin-ui/pull/1906 to remove those waits

2022-01-21 14:09 UTC, edewit approved these changes

2022-01-23 20:20 UTC, jonkoops approved these changes

2022-01-23 20:21 UTC, merged