Added the policy screens
keycloak/keycloak-admin-ui pull request #1884
Opened 2022-01-18 08:15 UTC by edewit

implementation of the design [marvel](https://marvelapp.com/prototype/2c39260g/screen/83080815) still missing the search / filter that
will come in a later PR, but it has all the input screens for the different policy types

2022-01-19 20:53 UTC, jenny-s51 requested changes
Awesome work on these policy type screens @edewit! 💪 Left some comments

2022-01-19 20:53 UTC, jenny-s51 commented on src/clients/authorization/policy/Role.tsx
> +              <Th>{t("common:required")}</Th>
The column title here should just be "Required" but it becomes `Required Fields` using this message bundle key, which causes it to wrap like this:

<img width="529" alt="Screen Shot 2022-01-19 at 3 17 07 PM" src="https://user-images.githubusercontent.com/32821331/150207345-b3d37e0b-f92a-4d38-aec1-660efbcb4112.png">

2022-01-19 20:53 UTC, jenny-s51 commented on src/clients/authorization/policy/PolicyDetails.tsx
> +const isValidComponentType = (value: string): boolean => value in COMPONENTS;
Currently if I try to make a policy of type `user`, an error gets thrown: `Danger alert:Not a supported user!` since `user` doesn't exist within this components object. 

According to the design `user` and `client` policy types follow the same pattern -- maybe the `Client` component can be reused here

2022-01-19 20:53 UTC, jenny-s51 commented on src/clients/authorization/policy/Role.tsx
> +      helperTextInvalid={t("requiredRoles")}
Looks like this needs a corresponding message bundle value! e.g. "Please add at least one role."

2022-01-20 07:26 UTC, edewit commented
Thanks @jenny-s51 for the thorough review

2022-01-20 15:55 UTC, jenny-s51 approved these changes

2022-01-21 14:10 UTC, merged