Removed waits from realm test
keycloak/keycloak-admin-ui pull request #1906
Opened 2022-01-20 13:38 UTC by edewit

Now uses the new faster login method + removed all wait and uses the test realm it creates

2022-01-20 14:16 UTC, jonkoops approved these changes

2022-01-20 14:57 UTC, jonkoops commented
@edewit looks like there is a test failure, is it related to your changes?

2022-01-20 16:56 UTC, jenny-s51 commented on cypress/support/pages/admin_console/manage/realm_settings/RealmSettingsPage.ts
> +      `/auth/admin/realms/${this.realmName}/client-policies/profiles*`
```suggestion
      `/auth/admin/realms/${this.realmName}/clientPolicies/profiles*`
```

2022-01-20 16:57 UTC, jenny-s51 commented on cypress/support/pages/admin_console/manage/realm_settings/RealmSettingsPage.ts
> +      `/auth/admin/realms/${this.realmName}/client-policies/policies`
```suggestion
      `/auth/admin/realms/${this.realmName}/clientPolicies/policies`
```

2022-01-21 09:29 UTC, jonkoops commented
@edewit can you rebase this one on `main`?

2022-01-21 10:22 UTC, edewit commented on cypress/support/pages/admin_console/manage/realm_settings/RealmSettingsPage.ts
> +      `/auth/admin/realms/${this.realmName}/client-policies/profiles*`
no @jenny-s51 it's `client-policies` not `clientPolicies` see: https://github.com/keycloak/keycloak-nodejs-admin-client/blob/main/src/resources/clientPolicies.ts#L13

2022-01-21 12:37 UTC, jonkoops requested changes
Still seeing some test failures

2022-01-23 20:00 UTC, jonkoops approved these changes
LGTM

2022-01-24 14:17 UTC, merged