handle error code < 500 in error handler
keycloak/keycloak-admin-ui pull request #1916
Opened 2022-01-21 08:36 UTC by edewit

also:
fixes: #378

2022-01-21 09:59 UTC, jonkoops requested changes

2022-01-21 09:59 UTC, jonkoops commented on src/context/RealmsContext.tsx
> +        }
You can use `axios.isAxiosError()` here to determine the error is indeed an `AxiosError`. You can also omit the `else` clause since the `if` branch terminates with a `return` statement. The `Error` type can also be omitted, as it's fine to re-throw a value of the type `unknown`.

```suggestion
        if (
          axios.isAxiosError(error) &&
          error.response &&
          error.response.status < 500
        ) {
          return [];
        }

        throw error;
```

2022-01-21 10:11 UTC, jonkoops approved these changes
LGMT

2022-01-25 11:25 UTC, jonkoops commented
@edewit Looks like there are still some test failures.

2022-02-03 19:37 UTC, jonkoops commented
@edewit looks like there is one more test failure in the masthead, but otherwise LGTM.

2022-02-08 22:08 UTC, mfrances17 approved these changes
LGTM

2022-02-08 22:10 UTC, merged