Added scope typed permission screen
keycloak/keycloak-admin-ui pull request #1933
Opened 2022-01-24 12:50 UTC by edewit

Prev. PR was missing ability to create scope typed permissions this PR adds that.

2022-02-07 19:03 UTC, jenny-s51 requested changes
Nice work @edewit ! New ScopeSelect is behaving as expected and scopes can be added/saved successfully. Left a few comments!

Also do you think the "Apply to Resource Type" switch can be removed from this screen? Based on the design it looks like we might not need it here after all https://marvelapp.com/prototype/161eb3e9/screen/83039203 

Otherwise this is looking great 👍

2022-02-08 07:39 UTC, edewit commented on src/clients/authorization/ResourcesPolicySelect.tsx
> +  variant = SelectVariant.typeaheadMulti,
it can be used without it it's already used here: https://github.com/edewit/keycloak-admin/blob/3736d2df9ea2d137a8457e651a0f7d74a4390693/src/clients/authorization/policy/Aggregate.tsx#L27-L31

2022-02-08 10:12 UTC, edewit commented on src/clients/authorization/ResourcesPolicySelect.tsx
>              setSearch("");
Ahh yes there is a bug fixed that.

But the scope type should be a multi select as it is also in the old console: 
![image](https://user-images.githubusercontent.com/51133/152940369-89b08208-de87-420e-9b0b-062e76f81aa8.png)
and in the new one it should remain that way.

2022-02-08 12:01 UTC, jonkoops requested changes

2022-02-09 09:50 UTC, jonkoops requested changes
There are still some open review comments.

2022-02-09 16:21 UTC, edewit commented
> There are still some open review comments.

Ooops... right now it's fine

2022-02-09 22:39 UTC, jonkoops approved these changes
LGTM!

2022-02-09 22:40 UTC, jonkoops commented
Since this PR has been open for a while should we get it merged? I see some failing tests, but they might just be flaky.

2022-02-10 08:22 UTC, edewit commented
@jonkoops agreed

2022-02-10 08:23 UTC, merged