Clients(Authentication): Adds "Export" tab
keycloak/keycloak-admin-ui pull request #1937
Opened 2022-01-24 19:23 UTC by jenny-s51

## Motivation

https://marvelapp.com/prototype/78j1b69/screen/83085244

## Brief Description

Adds "Export" subtab to Authentication settings in Clients

## Verification Steps

1. Go to Clients
2. Create a new OIDC client and make sure "Client authentication" and "Authorization" switches are both enabled
3. Save the client and go to the Authorization -> Export subtab
4. Verify that the "Download" and "Copy" buttons work as expected

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

2022-02-08 13:42 UTC, jonkoops requested changes

2022-02-08 13:42 UTC, jonkoops commented on src/clients/ClientDetails.tsx
> +                    id="Export"
Any reason this `id` is starting with a capital? Never seen that before.
```suggestion
                    id="export"
```

2022-02-08 13:42 UTC, jonkoops commented on src/clients/authorization/AuthorizationExport.tsx
> +  const { clientId } = useParams<{ clientId: string }>();
Instead of providing a new type, is there perhaps an existing type that can be used for the route params?

2022-02-08 13:42 UTC, jonkoops commented on src/clients/authorization/AuthorizationExport.tsx
> +    async () =>
The function already returns a Promise, so there is no need to mark this as `async`.
```suggestion
    () =>
```

2022-02-08 13:42 UTC, jonkoops commented on src/clients/authorization/AuthorizationExport.tsx
> +      adminClient.clients.exportResource({
This method in the admin client is missing a proper return type, can you add one there?

2022-02-08 13:42 UTC, jonkoops commented on src/clients/authorization/AuthorizationExport.tsx
> +      setAuthorizationDetails(authDetails);
Looking at your code `authorizationDetails` is already a string, so why does it need to be stringified again in `code`?

2022-02-08 13:42 UTC, jonkoops commented on src/clients/authorization/AuthorizationExport.tsx
> +              navigator.clipboard.writeText(code!);
According to the [documentation](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText) this method returns a Promise. Make sure that you await it's result and also handle any errors.

2022-02-09 15:12 UTC, jenny-s51 commented on src/clients/authorization/AuthorizationExport.tsx
> +      setAuthorizationDetails(authDetails);
It looks like `authorizationDetails` should be of type `resourceServerRepresentation`, therefore the stringify is needed here! Updated the default hook value to use the correct type.

2022-02-09 15:16 UTC, jenny-s51 commented on src/clients/ClientDetails.tsx
> +                    id="Export"
Nice catch, thanks - fixed!

2022-02-09 21:32 UTC, jonkoops approved these changes
Changes are looking good to me, @jenny-s51 could you install the latest Admin Client to see if the code is compatible with the types you added in https://github.com/keycloak/keycloak-nodejs-admin-client/pull/408?

2022-02-09 22:37 UTC, jonkoops commented
Looks like some tests are failing, but I don't think they are related to the changes in this PR. Should we merge this?

2022-02-09 22:37 UTC, merged