updated and fixed user test
keycloak/keycloak-admin-ui pull request #1956
Opened 2022-01-26 09:21 UTC by edewit

2022-01-27 21:33 UTC, jenny-s51 commented on cypress/integration/users_test.spec.ts
> +    cy.findByTestId("modalConfirm").click();
```suggestion
    cy.findByTestId("confirm").click();
```

2022-01-31 14:45 UTC, jonkoops commented
Seems like some of the tests are still failing, including unit tests as well.

2022-01-31 21:52 UTC, jonkoops requested changes
Changes look good to me, but some tests are unfortunately still failing.

2022-02-02 11:11 UTC, jonkoops approved these changes

2022-02-02 11:44 UTC, merged