## Motivation Added credentials tab [marvel](https://marvelapp.com/prototype/695h94c/screen/72265889)
keycloak/keycloak-admin-ui pull request #196
Opened 2020-10-29 07:34 UTC by edewit

## Verification Steps

1. Go to client details
1. Make the client "public"
1. The new credentials tab will appear
-->

## Checklist:

- [x] Code has been tested locally by PR requester
- [x] User-visible strings are using the react-i18next framework (useTranslation)
- [x] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated
- [x] Formatting has been performed via prettier/eslint
- [x] Type checking has been performed via 'yarn check-types'

## Additional Notes
Setting the client to see the credentials tab:

2020-10-29 15:55 UTC, srambach commented on src/clients/messages.json
> +    "confirmAccessTokenBody": "If you regenerate reiteration access token, the access data regarding the client registration service will be updated.",
Is it "reiteration" or "registration" ?

2020-10-29 16:07 UTC, srambach commented
When there is an empty footer, it creates too much space below the Save button. You can have multiple `CardBody`s so maybe adding one as needed with the client secret would be a better way?

2020-10-29 17:17 UTC, ssilvert requested changes
"Client secret" missing.  To reproduce:
1. Create a new client
2. Go to Credentials tab
3. Default value for Client Authenticator is "Client Id and Secret"
4. "Client Secret" is missing

If I change "Client Authenticator" to something else, then change it back, "Client Secret" shows up.

2020-10-29 17:22 UTC, ssilvert commented
`Client secret` has wrong help text.  You can leave this out for now since it isn't available in old console either.

2020-10-29 17:28 UTC, ssilvert commented
For `Signed Jwt`, there is a switch and two buttons that exist in the old console, but not in the wireframes.  Please double-check to make sure this is OK.

2020-10-29 17:28 UTC, ssilvert commented
`Save` button is always disabled whenever `Client Id and Secret` is selected.

2020-10-29 17:29 UTC, ssilvert commented
When you save something, there is no alert.

2020-10-29 17:42 UTC, ssilvert commented
On old console, `Signed Jwt with Client Secret` includes dropdown for `Signature Algorithm`

2020-10-30 07:16 UTC, edewit commented on src/clients/messages.json
> +    "confirmAccessTokenBody": "If you regenerate reiteration access token, the access data regarding the client registration service will be updated.",
I copied it from the old console, but I'm sure it should be registration.

2020-10-30 07:43 UTC, edewit commented
> For `Signed Jwt`, there is a switch and two buttons that exist in the old console, but not in the wireframes. Please double-check to make sure this is OK.

According to the new design these settings will be on the new "keys" tab: 
![image](https://user-images.githubusercontent.com/51133/97673355-f2ba3d00-1a8b-11eb-9c56-a09135883b57.png)

2020-10-30 18:26 UTC, ssilvert commented
> On old console, `Signed Jwt with Client Secret` includes dropdown for `Signature Algorithm`

Don't see a fix for this one?

2020-11-02 08:53 UTC, edewit commented
> > On old console, `Signed Jwt with Client Secret` includes dropdown for `Signature Algorithm`
> 
> Don't see a fix for this one?

No, see my reply above! According to the new design these fields have moved to the new "Keys" tab.

2020-11-02 20:15 UTC, ssilvert approved these changes

2020-11-02 20:15 UTC, merged