Clients(Authorization): Evaluate tab updates
keycloak/keycloak-admin-ui pull request #1961
Opened 2022-01-26 19:34 UTC by jenny-s51

## Motivation

Extends work done on #1861 - updates are necessary in order to implement results screen https://marvelapp.com/prototype/5eg9ic7/screen/83188838

## Brief Description

Fixes `evaluate` call which now POSTs successfully, adds 'revert' functionality to form, fixes bug in realm role attributes and  resolves some issues with data types in `AttributeInput`

## Verification Steps

1. Create a OIDC client with Client Authentication and Authorization switches enabled.
2. Go to the new client -> Authorization -> Evaluate
3. Fill in form data and verify that the `evaluate` call POSTs successfully

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

## Additional Notes

2022-02-08 10:55 UTC, edewit commented on src/clients/authorization/AuthorizationEvaluate.tsx
> +              <Controller
Why would you need a `<Controller` around this control, isn't it already part of the "form"

2022-02-08 11:30 UTC, jonkoops requested changes

2022-02-08 11:30 UTC, jonkoops commented on src/clients/authorization/AuthorizationEvaluate.tsx
> +  resources: { [key: string]: string }[];
You can use a [`Record`](https://www.typescriptlang.org/docs/handbook/utility-types.html#recordkeys-type) type here.
```suggestion
  context: Record<string, string>;
  resources: Record<string, string>[];
```

2022-02-08 11:30 UTC, jonkoops commented on src/clients/authorization/AuthorizationEvaluate.tsx
> +    if (await trigger()) {
You can reduce nesting here by using an [early return pattern](https://medium.com/swlh/return-early-pattern-3d18a41bba8).

```ts
if (!(await trigger())) {
  return;
}

// The rest of the code.
```

2022-02-08 11:30 UTC, jonkoops commented on src/clients/authorization/AuthorizationEvaluate.tsx
> +            .resources.map((item) => item.key)
This logic is repeated for every resource you are iterating, it might be a good idea to store it in a variable. You also should not have to call `getValues()` again as there is already a variable that contains this called `formValues` above.

```ts
const keys = formValues.resources.map(({ key }) => key);
```

2022-02-08 11:30 UTC, jonkoops commented on src/clients/authorization/AuthorizationEvaluate.tsx
> +              }
This code is very hard to parse, but looking at the type casting this seems to entirely change the type of `formValues.context`. Why does this need to happen?

I'd like to see this code without type-casting, as this disables certain compiler checks that can prevent errors during runtime.

2022-02-08 11:30 UTC, jonkoops commented on src/clients/authorization/AuthorizationEvaluate.tsx
> +                        .flat() as AttributeType[]
There is no need to call `flat()` here or to type-cast the items if you map it directly to an object instead of an array with a generic type.

```ts
resources.map<AttributeType>((item) => ({
  name: item.name!,
}))
```

According to the `AttributeType` type you will also have to provide a `key` which is missing here. Because this was being type-casted this error was suppressed by the compiler.

2022-02-08 11:30 UTC, jonkoops commented on src/clients/authorization/AuthorizationEvaluate.tsx
> +            onClick={() => reset}
You probably want to call the `reset()` function here.
```suggestion
            onClick={() => reset()}
```

2022-02-08 11:30 UTC, jonkoops commented on src/components/attribute-input/AttributeInput.tsx
> +  }, [reset]);
Why does this effect now depend on `reset`? It doesn't look like this dependency is used inside of the effect at all.

2022-02-08 16:11 UTC, jenny-s51 commented on src/clients/authorization/AuthorizationEvaluate.tsx
> +  resources: { [key: string]: string }[];
Good call - thanks @jonkoops

2022-02-08 19:55 UTC, jenny-s51 commented on src/clients/authorization/AuthorizationEvaluate.tsx
> +              }
Nice catch, I've updated this logic - the submitted types should be correct and casting is no longer necessary

2022-02-08 20:20 UTC, jenny-s51 commented on src/clients/authorization/AuthorizationEvaluate.tsx
> +              <Controller
Thanks! Removed 👍

2022-02-08 20:22 UTC, jenny-s51 commented on src/components/attribute-input/AttributeInput.tsx
> +  }, [reset]);
The reset sets `fields.length` to 0 -- if it is not a dependency, the field is removed rather than being set to empty

2022-02-09 09:27 UTC, jonkoops commented on src/clients/authorization/AuthorizationEvaluate.tsx
> +              }
Awesome, nice work!

2022-02-09 09:40 UTC, jonkoops requested changes

2022-02-09 09:40 UTC, jonkoops commented on src/clients/authorization/AuthorizationEvaluate.tsx
> +  console.log(form.getValues());
Stray console log statement here.
```suggestion
```

2022-02-09 09:40 UTC, jonkoops commented on src/clients/authorization/AuthorizationEvaluate.tsx
> +            .map(Object.values)
Not sure if this works correctly, if I split this code out then `atrributes` gets an `any` type. You might want to make this a bit more explicit.
```suggestion
            .map(({ key, value }) => [key, value])
```

2022-02-09 09:40 UTC, jonkoops commented on src/components/attribute-input/AttributeInput.tsx
> +  console.log("huh", fields.length);
Another stray console statement here.
```suggestion
```

2022-02-15 16:51 UTC, jonkoops approved these changes

2022-02-15 17:51 UTC, jenny-s51 commented
All Cypress tests passing locally ✅

2022-02-15 17:52 UTC, merged