added default group tab to user registration
keycloak/keycloak-admin-ui pull request #1965
Opened 2022-01-27 14:19 UTC by edewit

[marvel](https://marvelapp.com/prototype/7h0bjj5/screen/75047135)

2022-02-08 13:53 UTC, jonkoops requested changes

2022-02-08 13:53 UTC, jonkoops commented on src/realm-settings/DefaultGroupsTab.tsx
> +  const loader = () => Promise.resolve(defaultGroups!);
Having mechanism in place that does fetching and having multiple different states to handle stages of data loading seems rather complex. Perhaps it would be better to move the side-effect of storing the data in this loader?

```ts
const loader = async () => {
  const groups = await adminClient.realms.getDefaultGroups({ realm });
  setDefaultGroups(groups);
  return groups;
};
```

2022-02-08 13:53 UTC, jonkoops commented on src/realm-settings/DefaultGroupsTab.tsx
> +        await adminClient.realms.removeDefaultGroup({
These calls will not happen in parallel, but perhaps they can?

```ts
await Promise.all(
  selectedRows.map((group) =>
    adminClient.realms.removeDefaultGroup({
      realm,
      id: group.id!,
    })
  )
);
```

2022-02-08 13:53 UTC, jonkoops commented on src/realm-settings/DefaultGroupsTab.tsx
> +      for (const group of groups) {
Same here, I think this can be done in parallel.

2022-02-08 13:53 UTC, jonkoops commented on src/realm-settings/DefaultGroupsTab.tsx
> +              Default groups allow you...
Instead of adding text here you can also add an empty placeholder.
```suggestion
              {" "}
```

2022-02-08 13:53 UTC, jonkoops commented on src/realm-settings/DefaultGroupsTab.tsx
> +            onRowClick: async (group: GroupRepresentation) => {
Nothing `async` is happening here.
```suggestion
            onRowClick: (group: GroupRepresentation) => {
```

2022-02-08 13:53 UTC, jonkoops commented on src/realm-settings/DefaultGroupsTab.tsx
> +                Default groups allow you...
Instead of adding text here you can also add an empty placeholder.
```suggestion
                {" "}
```

2022-02-08 14:00 UTC, edewit commented on src/realm-settings/DefaultGroupsTab.tsx
> +  const loader = () => Promise.resolve(defaultGroups!);
that is not a good idea now when the component gets unmounted while the request is still going on you are then still setting state, but in a component that is unmounted and thus creating a memory leak

2022-02-08 14:06 UTC, jonkoops commented on src/realm-settings/DefaultGroupsTab.tsx
> +  const loader = () => Promise.resolve(defaultGroups!);
It's not that much of an issue, after the state is set the garbage collector will see there are no longer any references to it an clean it up.

Ideally though the Keycloak table would just allow us to pass data directly to it instead.

2022-02-08 14:22 UTC, edewit commented on src/realm-settings/DefaultGroupsTab.tsx
> +  const loader = () => Promise.resolve(defaultGroups!);
It is a big deal, you'll get an error if you do that and you application will slowly start to run less smooth. That is why we have the `useFetch` hook that will cancel the request and only set the state if the component is still mounted

2022-02-09 09:51 UTC, jonkoops commented on src/realm-settings/DefaultGroupsTab.tsx
> +  const loader = () => Promise.resolve(defaultGroups!);
Ahhh, the unmounted component state update. Yeah I forgot about that one, ok let's leave it as is.

2022-02-09 09:51 UTC, jonkoops approved these changes

2022-02-09 09:52 UTC, jonkoops commented on src/realm-settings/DefaultGroupsTab.tsx
> +              return Promise.resolve(false);
`onRowClick` expects a Promise? I wasn't expecting that.

2022-02-09 11:30 UTC, edewit commented on src/realm-settings/DefaultGroupsTab.tsx
> +              return Promise.resolve(false);
yes

2022-02-09 11:46 UTC, merged