540 user fed settings
keycloak/keycloak-admin-ui pull request #198
Opened 2020-10-29 14:54 UTC by srambach

## Motivation
APPDUX-540 https://issues.redhat.com/browse/APPDUX-540

## Brief Description
This lays out the sections in the User Federation LDAP Settings tab. It is NOT tied to data nor are controls like switches and dropdowns operational. And, it is not the entire page - this is the contents of one of the tabs. 
**This is intended to lay out the page and establish the structure for future work.**

## Verification Steps
This can only be viewed in Storybook. Find it under "User Federation LDAP Settings Tab". It can be compared to this mockup: https://marvelapp.com/prototype/ecjc94b/screen/72071065

## Checklist:

- [ x] Code has been tested locally by PR requester
- [ x] User-visible strings are using the react-i18next framework (useTranslation)
- [ x] Help has been implemented
- [ x] axe report has been run and resulting a11y issues have been resolved
- [NA] Unit tests have been created/updated
- [ x] Formatting has been performed via prettier/eslint
- [ x] Type checking has been performed via 'yarn check-types'

## Additional Notes
![image](https://user-images.githubusercontent.com/19825616/97590473-08206000-19d5-11eb-8e05-175c439a8018.png)

2020-10-29 22:30 UTC, mfrances17 requested changes
Found some typos/misspellings... easy fixes. 

Looking at the marvel spec and the storybook, it looks like there are some discrepancies that probably make sense to discuss rather than mark up. I'm not sure how closely we are trying to match the marvel spec. For example, a lot of the controls like the help icons are gray in the spec, not black, and probably should be gray so they don't stand out as much. 

Also, many of the fields have default entries that are missing in the implementation (Select a mode, LDAP user DN, etc). I'm also having trouble with storybook in that none of the fields are actionable (e.g. radios/toggles/dropdowns aren't working, so I can't verify values in the dropdown). I'm not convinced of the value for using storybook as opposed to just a screen cap.

2020-10-29 22:30 UTC, mfrances17 commented on src/user-federation/help.json
> +    "useTruststoreSpiHelp": "Specifies whether LDAP connection will use the truststore SPI with the truststore confifured in standalone.xml/domain.sml. 'Always' means that it will always use it. 'Nev
"configured"

2020-10-29 22:30 UTC, mfrances17 commented on src/user-federation/help.json
> +    "bindTypeHelp": "Type of the authentication method userd during LDAP bind operation. It is used in most of the requests sent to the LDAP server. Currently only 'none' (anonymous LDAP authenticati
"used"

2020-10-29 22:30 UTC, mfrances17 commented on src/user-federation/help.json
> +    "editModeHelp": "READ_ONLY is a read-only LDAP store. WRITABLE means data will be s ynced back to LDAP on demand. UNSYNCED means user data will be imported, but not synced back to LDAP.",
"synced"

2020-10-29 22:30 UTC, mfrances17 commented on src/user-federation/help.json
> +    "periodicFullSyncHelp": "Whether periodic full synchroniation of LDAP users to Keycloak should be enabled or not",
"synchronization"

2020-10-29 22:30 UTC, mfrances17 commented on src/user-federation/help.json
> +    "cachePolicyHelp": "Cache Policy for this storage provider.  'DEFAULT' is whatever the default settings are for the global cache.  'EVICT_DAILY' is a time of day every day that the cache will be
Search for all double spaces after period like these and make single space.

2020-10-29 22:30 UTC, mfrances17 commented on src/user-federation/messages.json
> +    "Ldap": "LDAP",
"ldap" will never be translated, it's still ldap

2020-10-30 13:14 UTC, srambach commented on src/user-federation/messages.json
> +    "Ldap": "LDAP",
Not even in languages with different alphabets or those that are non-phonetic? (I don't think this is actually the right term) Are you saying to leave "LDAP" in the code?

2020-10-30 13:47 UTC, srambach commented
@mfrances17 This is just getting the fields there with the help text. For one thing, I am assuming that the values for at least some dropdowns are probably coming from data somewhere but idk. My next step was to get placeholder text, default values, and dropdown options in.
As for the help icons, I need to contact the design team because I am using the PF help icon here. I want to check if this is a conscious choice or result of changes over the past year. Regardless, those are all using the HelpItem component, so it's one change to fix it globally if so. (in a separate PR probably)

2020-10-30 18:48 UTC, ssilvert commented on src/user-federation/messages.json
> +    "Ldap": "LDAP",
@srambach `LDAP` will never be localized.  So, yes, you can just leave it in the code.

2020-10-30 19:09 UTC, ssilvert requested changes
This looks good.  I think if you just put LDAP back in the code then we can merge.

There is one other thing that is broken though.  The scroll spy doesn't actually work.  It jumps OK, but it should always stay visible when you scroll to the bottom.  Optional if you want to fix that in this PR or just log an issue.

2020-10-30 19:14 UTC, srambach commented
> This looks good. I think if you just put LDAP back in the code then we can merge. Looks like you address all of @mfrances17 other issues, right?
So even though it's a display string, it should be "LDAP" in the code? That's what you both are saying?
> 
> There is one other thing that is broken though. The scroll spy doesn't actually work. It jumps OK, but it should always stay visible when you scroll to the bottom. Optional if you want to fix that in this PR or just log an issue.
I noticed that but it's broken elsewhere as well. I'll log an issue.

2020-10-30 19:29 UTC, srambach commented
> There is one other thing that is broken though. The scroll spy doesn't actually work. It jumps OK, but it should always stay visible when you scroll to the bottom. Optional if you want to fix that in this PR or just log an issue.

Actually, there's an issue to take the PatternFly component when it becomes available so that seems sufficient to me.

2020-10-30 19:51 UTC, mfrances17 commented
> So even though it's a display string, it should be "LDAP" in the code? That's what you both are saying?
Yes. Terms like LDAP won't not localized, they are the same in every language. So it doesn't make sense to add them.

2020-10-30 19:51 UTC, srambach commented
OK, LDAP is removed from the strings. It was actually not used after I removed the header for later anyway.
@mfrances17 @ssilvert

2020-10-30 19:56 UTC, mfrances17 commented
I noticed the scrolling issue as well. This IS actually working correctly in Client Details, when you scroll it bumps down.

![client-details](https://user-images.githubusercontent.com/39063664/97751244-5e220000-1ac8-11eb-8216-094e2a4cda50.png)

2020-10-30 20:06 UTC, mfrances17 approved these changes
LGTM - I think it's fine to just merge this in as a known WIP while work continues on it.

2020-10-30 20:15 UTC, ssilvert approved these changes

2020-10-30 20:15 UTC, merged