Add Clients tests and fix notification message
keycloak/keycloak-admin-ui pull request #1999
Opened 2022-02-02 17:51 UTC by Aboullos

## Motivation
Adds tests to Clients for the List and Initial Access Token screens and fix a notification message

## Brief Description
Adds tests to Clients for the List and Initial Access Token screens and fix the notification message when deleting an initial access token fixing issue #1936 

## Checklist:

- [ x] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

2022-02-09 09:57 UTC, jonkoops requested changes

2022-02-09 09:57 UTC, jonkoops commented on cypress/integration/realm_settings_client_policies_test.spec.ts
>    });
No need for async syntax if the returned value is a Promise.
```suggestion
  after(() => new AdminClient().deleteRealm(realmName));
```

2022-02-09 09:57 UTC, jonkoops commented on cypress/integration/realm_settings_client_policies_test.spec.ts
> +    cy.wait(2000);
Instead of waiting an arbitrary amount of time, can we wait for a specific element or request? These kind of things tend to turn flaky on the CI otherwise.

2022-02-09 10:18 UTC, Aboullos commented on cypress/support/pages/admin_console/manage/realm_settings/RealmSettingsPage.ts
> +    cy.wait(500).findByTestId(this.modalConfirm).click();
This is from the rebase that got changed back to what it was before. I'll revert it

2022-02-09 10:19 UTC, Aboullos commented on cypress/integration/realm_settings_client_policies_test.spec.ts
> +    cy.wait(200);
This is from the rebase that got changed back to what it was before. I'll revert it

2022-02-09 10:19 UTC, Aboullos commented on cypress/integration/realm_settings_client_policies_test.spec.ts
> +    cy.wait(2000);
This is from the rebase that got changed back to what it was before. I'll revert it

2022-02-09 10:19 UTC, Aboullos commented on cypress/integration/realm_settings_client_policies_test.spec.ts
>    });
This is from the rebase that got changed back to what it was before. I'll revert it

2022-02-09 10:19 UTC, Aboullos commented on cypress/integration/realm_settings_client_policies_test.spec.ts
>    });
This is from the rebase that got changed back to what it was before. I'll revert it

2022-02-15 16:28 UTC, jonkoops requested changes

2022-02-15 16:28 UTC, jonkoops commented on src/components/form-access/FormAccess.tsx
> +  fineGrainedAccess?: boolean | undefined;
This field is already optional.
```suggestion
  fineGrainedAccess?: boolean;
```

2022-02-15 16:28 UTC, jonkoops commented on src/components/form-access/FormAccess.tsx
> +  if (fineGrainedAccess !== undefined) isDisabled = !fineGrainedAccess;
This seems like it could be a tenary.
```suggestion
  const  isDisabled = fineGrainedAccess !== undefined ? !ineGrainedAccess : !hasAccess(role);
```

2022-02-15 16:50 UTC, Aboullos commented
Sorry, I just checked and some of the last 3 rebases some files were reset to a previous version:
- Authentication.ts
- Flow.ts
- Formaccess.tsx
- NewRealmForm.tsx
- AddRealm.ts
- Session.ts
I will revert these changes after the Cypress results

2022-02-16 07:54 UTC, edewit approved these changes

2022-02-16 14:34 UTC, Aboullos commented
There are just 2 test failing but they just fail here on github, locally they all pass

2022-02-16 14:41 UTC, jonkoops commented on cypress.json
> +    "pageLoadTimeout": 120000,
@edewit do we feel comfortable changing these values?

2022-02-16 14:43 UTC, jonkoops commented on cypress/support/util/keycloak_hooks.ts
> +  cy.get('[role="progressbar"]').should("not.exist");
This might be executed a lot since this hook is called pretty much everywhere, are we sure this is what we want to do?

2022-02-16 14:45 UTC, Aboullos commented on cypress/support/util/keycloak_hooks.ts
> +  cy.get('[role="progressbar"]').should("not.exist");
After doing that some recurrent errors on Github stopped appearing, I could try to remove it to see if with the 17 version is more stable or not

2022-02-16 16:30 UTC, Aboullos commented on cypress/support/util/keycloak_hooks.ts
> +  cy.get('[role="progressbar"]').should("not.exist");
I reverted it but left the last wait for the loading bar

2022-02-16 16:30 UTC, Aboullos commented on cypress.json
> +    "pageLoadTimeout": 120000,
I reverted it but left the slowTestThreshold to 3000

2022-02-16 16:33 UTC, jonkoops approved these changes

2022-02-16 16:34 UTC, merged