initial version of dedicated client scope
keycloak/keycloak-admin-ui pull request #2000
Opened 2022-02-03 08:38 UTC by edewit

2022-02-09 10:08 UTC, jonkoops requested changes

2022-02-09 10:08 UTC, jonkoops commented on src/clients/scopes/ClientScopes.tsx
> +      .slice(firstNum, Number(first) + Number(max));
You already have `firstNum` here which has been converted to a number.
```suggestion
      .slice(firstNum, firstNum + Number(max));
```

2022-02-09 10:08 UTC, jonkoops commented on src/clients/scopes/DecicatedScope.tsx
> +    const clients = await adminClient.clients.find();
I think you can also get the clients in parallel here.
```suggestion
    const [clients, assignedRoles, effectiveRoles] = await Promise.all([
      adminClient.clients.find(),
      adminClient.clients
        .listRealmScopeMappings({ id: client.id! })
        .then((roles) => roles.map((role) => ({ role }))),
      adminClient.clients
        .listCompositeRealmScopeMappings({ id: client.id! })
        .then((roles) => roles.map((role) => ({ role }))),
    ]);

```

2022-02-09 10:08 UTC, jonkoops commented on src/clients/scopes/DecicatedScope.tsx
> +  const assignRoles = async (rows: Row[]) => {
Perhaps the calls in this function can be executed in parallel?

2022-02-09 10:08 UTC, jonkoops commented on src/clients/scopes/DecicatedScope.tsx
> +  const [hide, setHide] = useState(false);
`useToggle` was giving you issues here?

2022-02-09 10:08 UTC, jonkoops commented on src/components/role-mapping/AddRoleMappingModal.tsx
> +            })) as RoleRepresentation[];
Is this type missing somewhere? Can we get rid of this type-cast?

2022-02-09 10:08 UTC, jonkoops commented on src/components/role-mapping/AddRoleMappingModal.tsx
> +    const availableRoles: RoleRepresentation[] = await castAdminClient(
Here also, why does `castAdminClient` not have this type already?

2022-02-09 10:08 UTC, jonkoops commented on src/components/role-mapping/AddRoleMappingModal.tsx
> +          const clientAvailableRoles: RoleRepresentation[] =
And here as well.

2022-02-09 10:08 UTC, jonkoops commented on src/components/role-mapping/RoleMapping.tsx
> +export const castAdminClient = (
Can we give this function a proper return type somehow?

2022-02-10 08:17 UTC, edewit commented on src/clients/scopes/DecicatedScope.tsx
> +  const [hide, setHide] = useState(false);
no this is code that has been implemented before `useToggle` was introduced, changed it now

2022-02-10 08:19 UTC, edewit commented on src/client-scopes/ClientScopesSection.tsx
>        onSelect={async (value) => {
onSelect gives us a `string | SelectOptionObject` we know it's a string and one of `AllClientScopeType`, but we can't enforce that here

2022-02-21 10:13 UTC, edewit commented on src/clients/ClientDetails.tsx
> -                data-testid="mappersTab"
done

2022-02-21 12:14 UTC, jonkoops commented
All tests are passing :heavy_check_mark: 
```log
  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  authentication_policies.spec.ts          00:15        3        3        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  authentication_test.spec.ts              01:09       15       15        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  client_authorization_test.spec.ts        00:22        9        9        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  client_scopes_test.spec.ts               00:20        4        4        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  clients_saml_test.spec.ts                00:15        5        5        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  clients_test.spec.ts                     00:51       15       15        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  events_test.spec.ts                      00:49       14       14        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  group_test.spec.ts                       00:35        9        9        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  identity_providers_oidc_test.spec.t      00:26        5        5        -        -        - │
  │    s                                                                                           │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  identity_providers_saml_test.spec.t      01:02       12       12        -        -        - │
  │    s                                                                                           │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  identity_providers_test.spec.ts          00:42        9        9        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  login_test.spec.ts                       00:06        2        2        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  masthead_test.spec.ts                    00:47        2        2        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  partial_export_test.spec.ts              00:12        3        3        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  partial_import_test.spec.ts              00:36        4        4        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  realm_roles_test.spec.ts                 00:22        3        3        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  realm_settings_client_policies_test      00:46       18       18        -        -        - │
  │    .spec.ts                                                                                    │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  realm_settings_client_profiles_test      00:43       21       21        -        -        - │
  │    .spec.ts                                                                                    │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  realm_settings_events_test.spec.ts       01:17       17       16        -        1        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  realm_settings_tabs_test.spec.ts         00:24        6        6        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  realm_settings_user_profile_tab.spe      00:13        3        3        -        -        - │
  │    c.ts                                                                                        │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  realm_test.spec.ts                       00:10        4        4        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  realm_user_registration.spec.ts          00:08        3        3        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  sessions_test.spec.ts                    00:34       11       11        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  user_fed_kerberos_test.spec.ts           00:44        9        9        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  user_fed_ldap_hardcoded_mapper_test      01:15       12       12        -        -        - │
  │    .spec.ts                                                                                    │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  user_fed_ldap_mapper_test.spec.ts        01:21       12       12        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  user_fed_ldap_test.spec.ts               00:50        8        8        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  users_test.spec.ts                       00:26       13       12        -        1        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✔  All specs passed!                        17:52      251      249        -        2        -  
```

2022-02-21 12:14 UTC, jonkoops approved these changes

2022-02-21 12:14 UTC, merged