Add form for User Profile attribute groups
keycloak/keycloak-admin-ui pull request #2021
Opened 2022-02-07 11:58 UTC by jonkoops

Implements the Attribute Groups under the User Profile as per [design](https://marvelapp.com/prototype/5eed532/section/1460646). This allows Attribute Groups to be created and edited using a form.

## Verification Steps
1. Enable 'User Profile' under the realm settings and save the settings.
2. Go to 'User Profile' :arrow_right: 'Attributes Groups' and create a group.
3. Verify that you return to the overview and the new entry is displayed.
4. Edit the newly created entry and verify that it is saved correctly.

Tests will follow in a separate PR.

2022-02-07 12:01 UTC, jonkoops commented
@yih-wang @xianli123 could y'all verify that this feature is working as expected from a UDX point of view?

2022-02-08 08:27 UTC, yih-wang commented
Hi @jonkoops , here are some issues I found in the current implementation:

Create group
1. Breadcrumb is missing ([design](https://marvelapp.com/prototype/5eed532/screen/82246803))
2. Tooltips are missing for the Name, Display name and Display description (all the same with the old console)
3. "Add annotation" is disabled until the current row (key) is filled 

Groups list

4. Group names in the list should be clickable (clicking the group name can edit the group)

Edit group ([design](https://marvelapp.com/prototype/5eed532/screen/85071685) is missing before)

5. Group name cannot be edited once it's created
6. Header is wrong
7. Same issues with the Create page (breadcrumb, tooltips, "Add annotation" behavior)

2022-02-08 08:29 UTC, yih-wang requested changes
Hi @jonkoops , here are some issues I found in the current implementation:

Create group

1. Breadcrumb is missing ([design](https://marvelapp.com/prototype/5eed532/screen/82246803))
2. Tooltips are missing for the Name, Display name and Display description (all the same with the old console)
3. "Add annotation" should be disabled until the current row (key) is filled

Groups list

4. Group names in the list should be clickable (clicking the group name can edit the group)

Edit group ([design](https://marvelapp.com/prototype/5eed532/screen/85071685) is missing before)

5. Group name cannot be edited once it's created
6. Header is wrong
7. Same issues with the Create page (breadcrumb, tooltips, "Add annotation" behavior)

2022-02-08 12:03 UTC, jonkoops commented
@yih-wang Thanks for the feedback, I will try to take a look at it today.

2022-02-08 14:47 UTC, edewit requested changes

2022-02-08 14:47 UTC, edewit commented on src/realm-settings/routes/EditAttributesGroup.ts
> +  path: "/:realm/realm-settings/userProfile/attributesGroup/edit/:name",
I think it's nicer to only use lower case in urls, WDYT?

2022-02-08 14:47 UTC, edewit commented on src/realm-settings/user-profile/AttributesGroupForm.tsx
> +  const form = useForm<FormFields>({ defaultValues });
Why not use a destructure here:
```suggestion
  const { control, register, errors, reset } = useForm<FormFields>({ defaultValues });
```

2022-02-08 14:47 UTC, edewit commented on src/realm-settings/user-profile/AttributesGroupForm.tsx
> +            <Flex direction={{ default: "column" }}>
There is a pre made `<AttributeInput` component that does this

2022-02-08 15:17 UTC, jonkoops commented on src/realm-settings/routes/EditAttributesGroup.ts
> +  path: "/:realm/realm-settings/userProfile/attributesGroup/edit/:name",
I agree, this is just very inconsistent everywhere already. Perhaps we can log it as an issue to resolve this for all routes in one go?

2022-02-09 14:40 UTC, jonkoops commented on src/realm-settings/user-profile/AttributesGroupForm.tsx
> +            <Flex direction={{ default: "column" }}>
I did mess around with this but ended up going for this solution. Let me check if I can implement it.

2022-02-09 16:14 UTC, edewit commented on src/realm-settings/user-profile/AttributesGroupForm.tsx
> +  const form = useForm<FormFields>({ defaultValues });
okay, I can see why you feel this way, atm there are 50 components that already do it like that

2022-02-09 16:16 UTC, edewit commented on src/realm-settings/user-profile/AttributesGroupForm.tsx
> +            <Flex direction={{ default: "column" }}>
it should be a drop in replacement, although it got slightly polluted with the new `<Dropdown ` keys I think we might want to get rid of those.

2022-02-14 10:29 UTC, agagancarczyk approved these changes

2022-02-16 19:18 UTC, edewit approved these changes

2022-02-23 14:43 UTC, jonkoops commented on src/realm-settings/user-profile/AttributesGroupForm.tsx
> +  const form = useForm<FormFields>({ defaultValues });
Yeah, that's unfortunate.

2022-02-28 16:38 UTC, jonkoops commented
@yih-wang I've resolved all the issues you mentioned, would you mind taking another look?

2022-02-28 16:40 UTC, jonkoops commented on src/realm-settings/user-profile/AttributesGroupForm.tsx
> +            <Flex direction={{ default: "column" }}>
I'll do some work to clean this up after the PR has been merged. I'd like to make the component a bit more re-usable.

2022-02-28 16:44 UTC, edewit approved these changes

2022-02-28 16:55 UTC, agagancarczyk approved these changes

2022-03-01 00:09 UTC, mfrances17 approved these changes
LGTM, tested fine - good job

2022-03-01 05:44 UTC, merged

2022-03-01 06:37 UTC, yih-wang commented
@jonkoops The updates look good! I only found a low-impact issue that won't block the merge. Raised a separate issue #2167 to track that.

2022-03-01 08:06 UTC, jonkoops commented
@yih-wang Great, thanks for testing this!