Refactored user credentials into seperate components
keycloak/keycloak-admin-ui pull request #2024
Opened 2022-02-08 06:58 UTC by edewit

User credentials tab component was big, so I refactored it into seperate components

2022-02-08 13:19 UTC, jonkoops requested changes

2022-02-08 13:19 UTC, jonkoops commented on src/user/user-credentials/CredentialsResetActionMultiSelect.tsx
> +            selections={value.map((o: string) => o)}
Why map this value to itself? Can it not be passed directly?
```suggestion
            selections={value}
```

2022-02-08 13:19 UTC, jonkoops commented on src/user/user-credentials/ResetCredentialDialog.tsx
> +import { isEmpty } from "lodash";
```suggestion
import { isEmpty } from "lodash-es";
```

2022-02-09 09:44 UTC, jonkoops approved these changes

2022-02-09 09:45 UTC, jonkoops commented on src/user/user-credentials/CredentialRow.tsx
> +    const credentialData = JSON.parse(credential.credentialData);
I would say so, since we are already making this assumption [later on](https://github.com/keycloak/keycloak-admin-ui/pull/2024/files/0da0d5bb3f4e7babddc2d4411204694a8bac30ec#diff-bd4fd0ea80364d48bc1df0477f92521a193b1b1349e27efa67831fd3208e0b67R44-R46) in the code.

2022-02-09 13:30 UTC, agagancarczyk approved these changes

2022-02-09 14:39 UTC, merged