User Federation card view implementation
keycloak/keycloak-admin-ui pull request #208
Opened 2020-11-04 21:16 UTC by mfrances17

## Motivation
Related JIRA/Github issues:
https://issues.redhat.com/browse/APPDUX-538
https://github.com/keycloak/keycloak-admin-ui/issues/146

Design spec:
https://marvelapp.com/prototype/ecjc94b/screen/72071045

## Brief Description
Adds a card view for the user federation databases. Utilizes the user federation empty state if no user federation databases exist. Preliminary delete card functionality is working, but there should be a confirm dialog TBD. Create new provider functionality (aka button in header, LDAP & Kerberos) is not part of this PR.

## Verification Steps
Creating providers is not yet available in the new UI, so if they do not exist on your locally running server, you'll need to create them with the old admin UI (aka the one running on localhost:8180)

**In the old admin console:**
1. Go to Configure > User Federation.
2. In the Add provider dropdown, select either kerberos or ldap.
3. Enter values for all required (*) fields and then click Save. For the purposes of testing, you can just enter dummy string values, they aren't verified.
4. Repeat steps 1-3 to create however many providers you want to test.

**In the new admin UI:**
1. Go to Configure > User federation.
2. Verify that each of the providers you created in steps 1-4 now appear as cards in the card view.
3. Choose a card and select Delete from the card menu. Verify that a notification appears to say that the card was successfully deleted, and the card no longer appears in the card view.
4. Delete each of the cards from the view. Verify that the empty state view appears instead of the card view.

## Checklist:
- [x] Code has been tested locally by PR requester
- [x] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated
- [x] Formatting has been performed via prettier/eslint
- [ ] Type checking has been performed via 'yarn check-types'

## Additional Notes

**User fed DBs exist:**
![uf-populated](https://user-images.githubusercontent.com/39063664/98167383-fba97500-1eb6-11eb-8061-11dc5eb13819.png)

**User fed DBs empty:**
![uf-empty-state](https://user-images.githubusercontent.com/39063664/98167401-0237ec80-1eb7-11eb-8b4b-92df7ad5392d.png)

**Delete user fed DB/card:**
![uf-delete](https://user-images.githubusercontent.com/39063664/98167406-0532dd00-1eb7-11eb-8c8a-f30cb29c6c5f.png)

2020-11-05 08:37 UTC, edewit requested changes
Looking good nice PR

2020-11-05 08:37 UTC, edewit commented on src/user-federation/UserFederationCard.tsx
> +    <>
you don't need the extra "Fragment" tag here right?

2020-11-05 08:37 UTC, edewit commented on src/user-federation/UserFederationSection.tsx
> +      parentId: `${realm}`,
```suggestion
      parentId: realm,
```

2020-11-05 08:37 UTC, edewit commented on src/user-federation/UserFederationSection.tsx
> +                `${t("userFederation:userFedDeleteError")} ${error}`,
if you change the message bundle to have a param, like this:
```
"userFedDeleteError": "Could not delete user federation: '{{error}}'"
```
then you can change this to:
```suggestion
                t("userFedDeleteError", {error})},
```
also no need to prefix the namespace `userFederation` as that is the default

2020-11-05 08:37 UTC, edewit commented on src/user-federation/UserFederationSection.tsx
> +        <Title headingLevel="h3" size={TitleSizes["2xl"]}>
you should use the `<ViewHeader` here as it has some logic for showing / hiding page explanation

2020-11-05 08:37 UTC, edewit commented on src/user-federation/messages.json
> +    "userFedDeleteError": "Could not delete user federation:",
```suggestion
    "userFedDeleteError": "Could not delete user federation: '{error}'",
```

2020-11-05 15:32 UTC, srambach commented on src/user-federation/UserFederationSection.tsx
> +        <Title headingLevel="h3" size={TitleSizes["2xl"]}>
It also handles the "learn more" link. Can we refactor the ViewHeader to allow additional contents like the dropdown toggle here to be included?

2020-11-05 15:32 UTC, srambach commented on src/user-federation/user-federation.css
> +    width: 20%;
Specifying width doesn't seem to be necessary?

2020-11-05 15:34 UTC, srambach commented on src/user-federation/user-federation.css
> +    margin-top: 24px;
Let's never use pixels. This is a standard spacer `var(--pf-global--spacer--lg)`

2020-11-05 15:37 UTC, srambach commented on src/user-federation/user-federation.css
> +    margin-left: 24px;
Same here, let's never use pixels. This is a standard spacer var(--pf-global--spacer--lg)

2020-11-05 15:40 UTC, mfrances17 commented on src/user-federation/UserFederationCard.tsx
> +    <>
Good catch, removed it. Thanks.

2020-11-05 15:40 UTC, mfrances17 commented on src/user-federation/UserFederationSection.tsx
> +      parentId: `${realm}`,
Fixed, ty.

2020-11-05 15:42 UTC, mfrances17 commented on src/user-federation/UserFederationSection.tsx
> +                `${t("userFederation:userFedDeleteError")} ${error}`,
ah, that's nice, i changed it accordingly. also merged my translation strings with existing ones, there were some dups, i temporarily created my own section in the messages to ease the initial merge.

2020-11-05 15:44 UTC, mfrances17 commented on src/user-federation/UserFederationSection.tsx
> +        <Title headingLevel="h3" size={TitleSizes["2xl"]}>
the problem with ViewHeader is that it does not allow me to add the Add New Provider dropdown to the header, i attempted but failed, so i created my own header

2020-11-05 15:44 UTC, mfrances17 commented on src/user-federation/messages.json
> +    "userFedDeleteError": "Could not delete user federation:",
fixed, thanks

2020-11-05 15:47 UTC, srambach commented
Looks good other than the few comments. I did notice one thing that I'm not sure about - if I add a provider in the other console, then refresh the page in the new console, it doesn't update until I switch off the page and back again.

2020-11-05 15:49 UTC, srambach commented
Oh, also - I guess there's no sorting to these? I don't see any in the old console and honestly, no rhyme or reason to the order.

2020-11-05 16:00 UTC, mfrances17 commented
> Looks good other than the few comments. I did notice one thing that I'm not sure about - if I add a provider in the other console, then refresh the page in the new console, it doesn't update until I switch off the page and back again.

hmmm, that's different than the behavior i'm seeing. if you refresh the page, the new ones appear.

2020-11-05 16:01 UTC, mfrances17 commented
> Oh, also - I guess there's no sorting to these? I don't see any in the old console and honestly, no rhyme or reason to the order.

there wasn't anything in the spec about that, it could be added easily enough in a future PR.

2020-11-05 16:03 UTC, srambach commented
The delete alert just says "The user federation.." Can we add the name of what was deleted?

2020-11-05 16:15 UTC, mfrances17 commented on src/user-federation/user-federation.css
> +    margin-top: 24px;
old habits die hard... fixed

2020-11-05 16:15 UTC, mfrances17 commented on src/user-federation/user-federation.css
> +    width: 20%;
yes, and looks better without it... at some point i needed to do this. removed.

2020-11-05 16:16 UTC, mfrances17 commented on src/user-federation/user-federation.css
> +    margin-left: 24px;
used the var instead, thanks!

2020-11-05 16:19 UTC, mfrances17 commented
> The delete alert just says "The user federation.." Can we add the name of what was deleted?

Yes, we could easy enough, but i'm staying consistent with what the rest of the UI is currently doing. When you delete a client, realm role, or anything else that's been implemented so far, it displays a similar message. So if we do that, we should do it across the board.

2020-11-05 17:51 UTC, jenny-s51 commented on src/user-federation/UserFederationSection.tsx
> +            href="http://www.google.com"
Currently "learn more" redirects the user to the home page of Google. While this presents a lot of creative freedom (and 100% made my day 😂) we should probably change this to something like [https://www.keycloak.org/docs/latest/server_admin/index.html#_user-storage-federation](https://www.keycloak.org/docs/latest/server_admin/index.html#_user-storage-federation)

2020-11-05 17:52 UTC, jenny-s51 reviewed
Behavior is looking great! Just one comment from me 😄

2020-11-05 20:29 UTC, jenny-s51 approved these changes

2020-11-05 20:31 UTC, mfrances17 commented on src/user-federation/UserFederationSection.tsx
> +            href="http://www.google.com"
thanks for the better URL 😄  was hoping this would come from an annotation from the spec, so the google was a TBD, but i like your solution better. also added a target because i don't think linked pages should replace the UI in the current window.

2020-11-06 02:49 UTC, dlabaj requested changes
A few comments otherwise looks good.

2020-11-06 02:49 UTC, dlabaj commented on src/user-federation/UserFederationCard.tsx
> +  title: string;
We should start documenting the props.

2020-11-06 02:49 UTC, dlabaj commented on src/user-federation/UserFederationCard.tsx
> +    <Card>
Will we need cards elsewhere ... if so could this be a more generic component moved under components?

2020-11-06 02:49 UTC, dlabaj commented on src/user-federation/UserFederationCard.tsx
> +  const [isDropdownOpen, setDropdownOpen] = useState(false);
would call it setIsDropdownOpen

2020-11-06 02:49 UTC, dlabaj commented on src/user-federation/UserFederationSection.tsx
> +  useEffect(() => {
What's the reason for the empty array as the second parameter?

2020-11-06 02:49 UTC, dlabaj commented on src/user-federation/UserFederationSection.tsx
> +  const [providerOpen, isProviderMenuOpen] = useState(false);
isProviderMenuOpen and setIsProviderMenuOpen

2020-11-06 02:49 UTC, dlabaj commented on src/user-federation/UserFederationSection.tsx
> +        <Title headingLevel="h3" size={TitleSizes["2xl"]}>
Can we update ViewHeader to add this ability add a dropdown?

2020-11-06 07:23 UTC, edewit commented on src/user-federation/UserFederationSection.tsx
> +        <Title headingLevel="h3" size={TitleSizes["2xl"]}>
I don't see why we couldn't add that to the view header we might need it on other pages as well, could do something like this:
```html
<ViewHeader ...>
   <Dropdown
          className="keycloak__user-federation__dropdown"
          toggle={
            <DropdownToggle
              onToggle={() => isProviderMenuOpen(!providerOpen)}
              isPrimary
              id="ufToggleId"
            >
              {t("addNewProvider")}
            </DropdownToggle>
          }
          isOpen={providerOpen}
          dropdownItems={ufAddProviderDropdownItems}
        />
</ViewHeader>
```
what do you think?

2020-11-06 15:49 UTC, mfrances17 commented on src/user-federation/UserFederationSection.tsx
> +        <Title headingLevel="h3" size={TitleSizes["2xl"]}>
Yeah as the 3 of you point out, I think you are all right, it should probably be added to the ViewHeader component... at the time I thought it might be too specific to my use case. But there may be other times when it is needed. I'll rework it so it's part of the component. Thanks.

2020-11-09 14:53 UTC, mfrances17 commented on src/user-federation/UserFederationSection.tsx
> +  useEffect(() => {
Not sure, but i thought the same thing because i saw it this way in other parts of the code. But when I remove it, the page never loads. Add it back, and it loads fine.

2020-11-09 15:12 UTC, mfrances17 commented on src/user-federation/UserFederationCard.tsx
> +  const [isDropdownOpen, setDropdownOpen] = useState(false);
fixed, thanks

2020-11-09 15:12 UTC, mfrances17 commented on src/user-federation/UserFederationSection.tsx
> +  const [providerOpen, isProviderMenuOpen] = useState(false);
fixed, thanks

2020-11-09 16:53 UTC, mfrances17 commented on src/user-federation/UserFederationSection.tsx
> +        <Title headingLevel="h3" size={TitleSizes["2xl"]}>
i've modified the ViewHeader component accordingly, and used that component inside of the user fed card view.

2020-11-09 20:35 UTC, mfrances17 commented on src/user-federation/UserFederationCard.tsx
> +    <Card>
Created a generic keycloak card component and used that instead of a user fed card

2020-11-09 21:05 UTC, ssilvert requested changes
- Need a confirmation dialog when you delete a fed provider.
- "Add new provider" dropdown should be hidden when in empty state.  You can add by clicking one of the cards.
- When in empty state, need the "To get started..." text as shown in the wireframe.

2020-11-09 22:41 UTC, dlabaj approved these changes

2020-11-09 22:47 UTC, mfrances17 commented
> * Need a confirmation dialog when you delete a fed provider.
> * "Add new provider" dropdown should be hidden when in empty state.  You can add by clicking one of the cards.
> * When in empty state, need the "To get started..." text as shown in the wireframe.

Latest commit handles both of your empty state suggestions.

2020-11-10 16:03 UTC, mfrances17 commented
Added a confirm dialog for the card delete action in the latest commit. All PR review comments should be addressed at this point. Screen shots of confirm:

![uf-delete-confirm](https://user-images.githubusercontent.com/39063664/98698695-5540f200-2344-11eb-8543-f7bf06fb2bd6.png)

![uf-delete-msg](https://user-images.githubusercontent.com/39063664/98698704-583be280-2344-11eb-8d78-abb4f1df2bf6.png)

2020-11-10 20:01 UTC, ssilvert approved these changes

2020-11-10 20:11 UTC, ssilvert requested changes

2020-11-10 20:11 UTC, ssilvert commented on src/user-federation/UserFederationSection.tsx
> +              userFederation.config.enabled
```suggestion
              userFederation.config.enabled[0] === "true"
```

2020-11-10 20:25 UTC, ssilvert approved these changes

2020-11-10 20:26 UTC, merged