fix mapperTableBugs
keycloak/keycloak-admin-ui pull request #2093
Opened 2022-02-14 17:13 UTC by jenny-s51

Closes #1948

2022-02-14 17:44 UTC, jonkoops requested changes

2022-02-14 18:33 UTC, jenny-s51 commented on src/identity-providers/add/DetailSettings.tsx
> +                      onClick={() =>
Updated!

2022-02-14 19:49 UTC, jonkoops approved these changes
LGTM!

2022-02-15 19:41 UTC, jenny-s51 commented
All Cypress tests passed locally ✅

2022-02-15 19:42 UTC, merged