User Credentials -> Draggable user credentials
keycloak/keycloak-admin-ui pull request #2131
Opened 2022-02-21 09:53 UTC by agagancarczyk

## Motivation
Make the rows in the Credentials tab draggable. Add more tests.

## Verification Steps
### In the new console, add "Password" credential (If you don't have it already)
### In the old console, add credentials as follows: 

1. To add "webauth register passwordless" credential -> While in Master realm, go to Users menu item, select Details tab, select "Webauthn Register Passwordless" from Required User actions dropdown, save, logout. (If you don't have "Webauthn register passwordless" option in dropdown, go to Authentication sidebar menu, select "Required Actions", select "Register" btn in the right top corner, select "Webauthn register password", tick enable and default action -> you should now be able to select it from Required User actions dropdown on Users/Details tab).

Login, select "Register" btn in Security Key Registration dialog, select "This device" and leave the default label "WebAuthn Authenticator (Default Label)", select ok btn.

2. To add "otp" credential, go to Manage Account in the top right corner, Account Security, select Signing in Device Activity, select Signing In and Set up Authenticator Application, logout, login.

### To test this feature:

1. Go to Users -> select user -> select Credentials tab 
2. Drag and drop credentials to change their position

There is a bug open for drag & drop of credentials within an expandable row #2130

All tests are passing locally: 
![Screenshot 2022-02-21 at 09 29 52](https://user-images.githubusercontent.com/4890675/154926949-af1bc0c1-41c8-4123-8c72-e425cb514f7e.png)

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

2022-02-21 11:50 UTC, jonkoops requested changes

2022-02-21 11:50 UTC, jonkoops commented on src/user/UserCredentials.tsx
> +    }
Since the `if` clause terminates the function with a return statement, you can omit the `else` branch.

2022-02-21 11:50 UTC, jonkoops commented on src/user/UserCredentials.tsx
> +      ).findIndex((item) => item.id === dragId);
If the previous suggestion is applied you can remove the null checks here.
```suggestion
      const draggingToItemIndex = Array.from(bodyRef.current.children).findIndex(
        (item) => item.id === dragId
      );
```

2022-02-21 11:50 UTC, jonkoops commented on src/user/UserCredentials.tsx
> +      return null;
I think you can return here without a value.
```suggestion
      return;
```

2022-02-21 11:50 UTC, jonkoops commented on src/user/UserCredentials.tsx
> +      }
You can reduce the nesting of this statement by using an early return.
```suggestion
    if (draggingToItemIndex === state.draggingToItemIndex) {
      return;
    }
    const tempItemOrder = moveItem(
      itemOrder,
      state.draggedItemId,
      draggingToItemIndex
    );
    move(tempItemOrder);
    setState({
      ...state,
      draggingToItemIndex,
      tempItemOrder,
    });
```

2022-02-21 11:50 UTC, jonkoops commented on src/user/UserCredentials.tsx
> +  };
Are you sure `target` is always an table row? Unlike [`currentTarget`](https://developer.mozilla.org/en-US/docs/Web/API/Event/currentTarget) it is possible for [`target`](https://developer.mozilla.org/en-US/docs/Web/API/Event/target) to be different depending on where the event originated.

Instead of using a type-cast you could do a run-time check to see if it is the element you expected it to be.

```suggestion
  const onDragEnd = ({ target }: React.DragEvent) => {
    if (!(target instanceof HTMLTableRowElement)) {
      return;
    }
    target.classList.remove(styles.modifiers.ghostRow);
    target.setAttribute("aria-pressed", "false");
    setState({
      ...state,
      draggedItemId: "",
      draggingToItemIndex: -1,
      dragging: false,
    });
  };
```

2022-02-21 11:50 UTC, jonkoops commented on src/user/UserCredentials.tsx
> +    const td = evt.target as HTMLTableCellElement;
Are you sure `target` is always an table cell? Unlike [`currentTarget`](https://developer.mozilla.org/en-US/docs/Web/API/Event/currentTarget) it is possible for [`target`](https://developer.mozilla.org/en-US/docs/Web/API/Event/target) to be different depending on where the event originated.

Instead of using a type-cast you could do a run-time check to see if it is the element you expected it to be.

```ts
if (!(target instanceof HTMLTableCellElement)) {
  return;
}
```

Or if you don't care what kind of element it is:
```ts
if (!(target instanceof HTMLElement)) {
  return;
}
```

2022-02-21 11:50 UTC, jonkoops commented on src/user/UserCredentials.tsx
> +    const keys = groupedUserCredentials.map((e) => e.value.map((c) => c.id));
You can make this code a bit more readable by dropping the single letter variables and using destructuring instead.
```suggestion
    const keys = groupedUserCredentials.map(({ value }) =>
      value.map(({ id }) => id)
    );
```

2022-02-21 11:50 UTC, jonkoops commented on src/user/UserCredentials.tsx
> +      for (let index = 0; index < Math.abs(times); index++) {
Any change these API calls can be made in parallel by using `Promise.all()`?

2022-02-21 11:50 UTC, jonkoops commented on src/user/UserCredentials.tsx
> +              ref={bodyRef}
You could probably get rid of this ref since all event listeners added here will have a `currentTarget` that should be equal to the body element.

2022-02-21 11:50 UTC, jonkoops commented on src/user/UserCredentials.tsx
> +                      .toString()}
This code could be a little smaller.
```suggestion
                    id={groupedCredential.value.map(({ id }) => id).toString()}
```

2022-02-21 11:50 UTC, jonkoops commented on src/user/UserCredentials.tsx
> +                          }
This code could be a little smaller.
```suggestion
                        id: `draggable-row-${groupedCredential.value.map(
                          ({ id }) => id
                        )}`,
```

2022-02-21 12:36 UTC, agagancarczyk commented on src/user/UserCredentials.tsx
> +                        key={`child-key-${credential.id}`}
Thanks @jonkoops , but it seems to be required. Removing it is causing "Missing "key" prop for element in iteratoreslint[react/jsx-key](https://github.com/yannickcr/eslint-plugin-react/tree/master/docs/rules/jsx-key.md)"

2022-02-21 12:53 UTC, agagancarczyk commented on src/user/UserCredentials.tsx
> +    return arr;
very nice! Thx

2022-02-21 13:17 UTC, agagancarczyk commented on src/user/UserCredentials.tsx
> +    }
The else seems to be required. Otherwise, drag & drop doesn't work.

2022-02-21 13:20 UTC, agagancarczyk commented on src/user/UserCredentials.tsx
> +    evt.preventDefault();
Good question. This is however needed for drag & drop to work.

2022-02-21 13:22 UTC, agagancarczyk commented on src/user/UserCredentials.tsx
> +      ).findIndex((item) => item.id === dragId);
The else seems to be required. Otherwise, drag & drop doesn't work. Therefore this change can't be made.

2022-02-21 13:57 UTC, agagancarczyk commented on src/user/UserCredentials.tsx
> +              ref={bodyRef}
This ref is required somehow. Otherwise, drag & drop is not going to work.

2022-02-21 14:05 UTC, agagancarczyk commented on src/user/UserCredentials.tsx
> +  };
Thanks @jonkoops - this works too.

2022-02-21 14:11 UTC, agagancarczyk commented on src/user/UserCredentials.tsx
> +    const td = evt.target as HTMLTableCellElement;
thanks @jonkoops event is needed here so I can't change it to target. Otherwise, drag & drop doesn't work.

2022-02-21 14:46 UTC, agagancarczyk commented on src/user/UserCredentials.tsx
> +      for (let index = 0; index < Math.abs(times); index++) {
Here I'm trying to be consistent with the similar implementations as in FlowDetails and RequiredActions.

2022-03-07 14:18 UTC, jonkoops commented on src/user/UserCredentials.tsx
> +    evt.preventDefault();
Strange, but not a problem I guess.

2022-03-07 14:19 UTC, jonkoops approved these changes

2022-03-07 14:32 UTC, merged