fixed Consent screen text was not shown
keycloak/keycloak-admin-ui pull request #2145
Opened 2022-02-24 14:17 UTC by ikhomyn

## Motivation
Closes #2051 & #1991 

## Brief Description
Fixed **Consent screen text** input was not shown when switch **Display on consent screen** was turned ON. Also fixed issue when **Consent screen text** was impossible to set/modify.
![Screenshot from 2022-02-24 15-13-38](https://user-images.githubusercontent.com/89014675/155540857-29d7a70a-ba99-429f-bbc6-9c636488bf5e.png)

## Checklist:

- [X] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

## Additional Notes

2022-02-24 14:17 UTC, ikhomyn commented
```
 (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  authentication_policies.spec.ts          00:28        3        3        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  authentication_test.spec.ts              02:11       15       15        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  client_authorization_test.spec.ts        00:32        9        9        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  client_scopes_test.spec.ts               01:15       20       20        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  clients_saml_test.spec.ts                00:30        5        5        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  clients_test.spec.ts                     03:49       25       25        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  events_test.spec.ts                      01:46       14       14        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  group_test.spec.ts                       01:15        9        9        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  identity_providers_oidc_test.spec.t      00:51        5        5        -        -        - │
  │    s                                                                                           │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  identity_providers_saml_test.spec.t      01:56       12       12        -        -        - │
  │    s                                                                                           │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  identity_providers_test.spec.ts          01:17        9        9        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  login_test.spec.ts                       00:10        2        2        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  masthead_test.spec.ts                    00:28        2        2        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  partial_export_test.spec.ts              00:25        3        3        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  partial_import_test.spec.ts              00:59        4        4        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  realm_roles_test.spec.ts                 00:22        7        7        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  realm_settings_client_policies_test      01:01       18       18        -        -        - │
  │    .spec.ts                                                                                    │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  realm_settings_client_profiles_test      00:59       21       21        -        -        - │
  │    .spec.ts                                                                                    │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  realm_settings_events_test.spec.ts       02:43       17       16        -        1        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  realm_settings_tabs_test.spec.ts         00:49        6        6        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  realm_settings_user_profile_tab.spe      00:26        3        3        -        -        - │
  │    c.ts                                                                                        │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  realm_test.spec.ts                       00:48        4        4        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  realm_user_registration.spec.ts          00:16        3        3        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  sessions_test.spec.ts                    00:35        5        5        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  user_fed_kerberos_test.spec.ts           01:12        9        9        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  user_fed_ldap_hardcoded_mapper_test      02:00       12       12        -        -        - │
  │    .spec.ts                                                                                    │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  user_fed_ldap_mapper_test.spec.ts        02:00       12       12        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  user_fed_ldap_test.spec.ts               01:18        8        8        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  users_test.spec.ts                       00:37       13       12        -        1        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✔  All specs passed!                        33:10      275      273        -        2        -  

```

2022-02-24 14:19 UTC, ikhomyn commented
Only I have a doubt if **Display on consent screen** should be turned ON by default as it was before I the changes? Or better to have it disabled by default?

2022-02-24 14:45 UTC, jonkoops requested changes

2022-02-24 14:45 UTC, jonkoops commented on src/client-scopes/details/ScopeForm.tsx
> +    clientScope["attributes"]?.["display.on.consent.screen"];
You don't have to use the bracket notation here for the `attributes` property.

```suggestion
    clientScope.attributes?.["display.on.consent.screen"];
```

2022-02-24 14:45 UTC, jonkoops commented on src/client-scopes/details/ScopeForm.tsx
> +        : displayOnConsentScreenEnabled,
I think you can shorten your code here by getting rid of the intermediate variable. If you cast the attribute here directly to a boolean and then back to a string it will automatically turn undefined values into `false`.

```suggestion
    defaultValue: Boolean(clientScope.attributes?.["display.on.consent.screen"]).toString(),
```

2022-02-24 14:54 UTC, ikhomyn commented on src/client-scopes/details/ScopeForm.tsx
> +        : displayOnConsentScreenEnabled,
@jonkoops Sure, looks better. Thanks!

2022-02-24 15:16 UTC, ikhomyn reviewed
Hmm, I just tried it, and during the creation of new scope, when value consent is undefined, it converts to false, but for existent scope, whether value is "true" or "false" it cast to Boolean True always as there is a string.

2022-02-24 15:51 UTC, jonkoops requested changes

2022-02-24 15:51 UTC, jonkoops commented on src/client-scopes/details/ScopeForm.tsx
> +        : clientScope.attributes["display.on.consent.screen"],
Perhaps we can use [nullish coalescing](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator) here to fall back to `"true"`?
```suggestion
    defaultValue: clientScope.attributes?.["display.on.consent.screen"] ?? "true",
```

2022-02-24 16:20 UTC, ikhomyn commented on src/client-scopes/details/ScopeForm.tsx
> +        : clientScope.attributes["display.on.consent.screen"],
Tried this one and works same way, thank you!

2022-02-24 16:46 UTC, jonkoops commented on src/client-scopes/details/ScopeForm.tsx
> +        : clientScope.attributes["display.on.consent.screen"],
Awesome!

2022-02-24 16:49 UTC, jonkoops commented
@ikhomyn If you can fix the linting error we can go ahead and merge this.

2022-02-25 10:27 UTC, ikhomyn commented
@jonkoops now should be fine. thanks!

2022-02-25 17:25 UTC, jonkoops approved these changes

2022-02-25 17:26 UTC, merged