refacored the keys tab removed duplication
keycloak/keycloak-admin-ui pull request #2146
Opened 2022-02-24 15:17 UTC by edewit

2022-02-24 15:52 UTC, jonkoops requested changes
@edewit seems there is a merge conflict, can you rebase your work?

2022-02-25 09:21 UTC, edewit commented
done

2022-02-25 17:39 UTC, jonkoops requested changes
This PR is amazing Erik, love the cleanup!

2022-02-25 17:39 UTC, jonkoops commented on src/realm-settings/routes/KeyProvider.ts
> +  providerType: string;
If this is a set of limited options you could create a special type for it.

2022-02-25 17:39 UTC, jonkoops commented on src/realm-settings/messages.ts
> +      "Are you sure you want to permanently delete the key provider {{provider}} ?",
```suggestion
      "Are you sure you want to permanently delete the key provider {{provider}}?",
```

2022-02-25 17:39 UTC, jonkoops commented on src/realm-settings/keys/KeysListTab.tsx
> +  const [filterType, setFilterType] = useState<string>(FILTER_OPTIONS[0]);
I think you can omit the type here, as it should be inferrable by the default you are providing.
```suggestion
  const [filterType, setFilterType] = useState(FILTER_OPTIONS[0]);
```

2022-02-25 17:39 UTC, jonkoops commented on src/realm-settings/keys/KeysListTab.tsx
> +        ? keys?.filter((i) => i.status === filterType)
You can get rid of the single letter variable if you use destructuring here.
```suggestion
        ? keys?.filter(({ status }) => status === filterType)
```

2022-02-28 06:36 UTC, edewit commented on cypress/support/pages/admin_console/manage/realm_settings/KeysTab.ts
> +    this.goToKeysTab();
yes it is

2022-02-28 06:36 UTC, edewit commented on src/clients/authorization/AuthorizationEvaluate.tsx
> +  const handleKeyDown = (e: KeyboardEvent<HTMLInputElement>) => {
I know

2022-02-28 10:03 UTC, jonkoops approved these changes

2022-02-28 10:04 UTC, jonkoops commented
Looks good to me, @edewit can you verify the tests are still passing locally?

2022-02-28 13:21 UTC, edewit commented
```
       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  authentication_policies.spec.ts          00:33        3        3        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  authentication_test.spec.ts              02:57       15       15        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  client_authorization_test.spec.ts        00:33        9        9        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  client_scopes_test.spec.ts               01:20       20       20        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  clients_saml_test.spec.ts                00:28        5        5        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  clients_test.spec.ts                     04:24       25       25        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  events_test.spec.ts                      02:01       14       14        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  group_test.spec.ts                       01:24        9        9        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  identity_providers_oidc_test.spec.t      00:57        5        5        -        -        - │
  │    s                                                                                           │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  identity_providers_saml_test.spec.t      02:20       12       12        -        -        - │
  │    s                                                                                           │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  identity_providers_test.spec.ts          01:29        9        9        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  login_test.spec.ts                       00:11        2        2        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  masthead_test.spec.ts                    00:31        2        2        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  partial_export_test.spec.ts              00:27        3        3        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  partial_import_test.spec.ts              01:06        4        4        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  realm_roles_test.spec.ts                 00:21        7        7        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  realm_settings_client_policies_test      01:02       18       18        -        -        - │
  │    .spec.ts                                                                                    │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  realm_settings_client_profiles_test      01:01       21       21        -        -        - │
  │    .spec.ts                                                                                    │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  realm_settings_events_test.spec.ts       02:52       17       16        -        1        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  realm_settings_tabs_test.spec.ts         00:57        6        6        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  realm_settings_user_profile_tab.spe      00:30        3        3        -        -        - │
  │    c.ts                                                                                        │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  realm_test.spec.ts                       00:22        4        4        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  realm_user_registration.spec.ts          00:18        3        3        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  sessions_test.spec.ts                    00:41        5        5        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  user_fed_kerberos_test.spec.ts           01:26        9        9        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  user_fed_ldap_hardcoded_mapper_test      02:24       12       12        -        -        - │
  │    .spec.ts                                                                                    │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  user_fed_ldap_mapper_test.spec.ts        02:27       12       12        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  user_fed_ldap_test.spec.ts               01:38        8        8        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  users_test.spec.ts                       00:38       13       12        -        1        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✔  All specs passed!                        37:33      275      273        -        2        -  
```

2022-02-28 15:22 UTC, merged