fixed msg error when clientScope created with whitespace (#1997)
keycloak/keycloak-admin-ui pull request #2162
Opened 2022-02-28 13:57 UTC by ikhomyn

## Motivation
Closes #1997 

## Brief Description
During creation of new client scope, if name contains white-space, error message is shown

## Checklist:

- [X] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

## Additional Notes

2022-02-28 13:57 UTC, ikhomyn commented
```
  (Run Finished)


       Spec                                              Tests  Passing  Failing  Pending  Skipped  
  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ ✔  authentication_policies.spec.ts          00:25        3        3        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  authentication_test.spec.ts              02:11       15       15        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  client_authorization_test.spec.ts        00:31        9        8        1        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  client_scopes_test.spec.ts               01:13       20       20        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  clients_saml_test.spec.ts                00:30        5        5        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  clients_test.spec.ts                     03:47       25       25        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  events_test.spec.ts                      01:45       14       14        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  group_test.spec.ts                       01:12        9        9        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  identity_providers_oidc_test.spec.t      00:50        5        5        -        -        - │
  │    s                                                                                           │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  identity_providers_saml_test.spec.t      01:57       12       12        -        -        - │
  │    s                                                                                           │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  identity_providers_test.spec.ts          01:17        9        9        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  login_test.spec.ts                       00:10        2        2        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  masthead_test.spec.ts                    00:28        2        2        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  partial_export_test.spec.ts              00:25        3        3        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  partial_import_test.spec.ts              00:58        4        4        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✖  realm_roles_test.spec.ts                 01:51        7        6        1        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  realm_settings_client_policies_test      01:06       18       18        -        -        - │
  │    .spec.ts                                                                                    │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  realm_settings_client_profiles_test      00:59       21       21        -        -        - │
  │    .spec.ts                                                                                    │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  realm_settings_events_test.spec.ts       02:43       17       16        -        1        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  realm_settings_tabs_test.spec.ts         00:49        6        6        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  realm_settings_user_profile_tab.spe      00:26        3        3        -        -        - │
  │    c.ts                                                                                        │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  realm_test.spec.ts                       00:48        4        4        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  realm_user_registration.spec.ts          00:17        3        3        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  sessions_test.spec.ts                    00:35        5        5        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  user_fed_kerberos_test.spec.ts           01:10        9        9        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  user_fed_ldap_hardcoded_mapper_test      01:58       12       12        -        -        - │
  │    .spec.ts                                                                                    │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  user_fed_ldap_mapper_test.spec.ts        02:01       12       12        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  user_fed_ldap_test.spec.ts               01:17        8        8        -        -        - │
  ├────────────────────────────────────────────────────────────────────────────────────────────────┤
  │ ✔  users_test.spec.ts                       00:37       13       12        -        1        - │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘
    ✖  2 of 29 failed (7%)                      34:29      275      271        2        2        -  


```

2022-02-28 15:24 UTC, jonkoops requested changes

2022-02-28 15:24 UTC, jonkoops commented on src/client-scopes/details/ScopeForm.tsx
> +  const validate = (event: any) => {
Can you at the correct type here instead of `any`?

2022-02-28 16:15 UTC, ikhomyn commented
@jonkoops I've set the type, should be okay

2022-02-28 21:08 UTC, mfrances17 approved these changes
LGTM, tested great. It's an ok from me to merge as long as all tests pass locally.

2022-03-01 06:27 UTC, edewit requested changes
So in order to not have whitepace we change the whitespace into `_` ? That is not what the old console does. I think it would be better to add a validate function to see if there are only spaces like this:

```jsx
<TextInput
        ref={register({
        required: true,
        validate: (value: string) =>
          !!value.trim() || t("common:required").toString(),
      })}
      type="text"
```

2022-03-01 08:53 UTC, ikhomyn commented
> So in order to not have whitepace we change the whitespace into `_` ? That is not what the old console does. I think it would be better to add a validate function to see if there are only spaces like this:
> 
> ```js
> <TextInput
>         ref={register({
>         required: true,
>         validate: (value: string) =>
>           !!value.trim() || t("common:required").toString(),
>       })}
>       type="text"
> ```

Hi @edewit, I checked this and it works removing white-spaces around string but not in the middle.

The reason I replaced white space with _ is because when I create scope with name: 'a b' I am getting this:
![Screenshot from 2022-03-01 09-45-21](https://user-images.githubusercontent.com/89014675/156136169-a3f99511-5fb6-42d4-9116-d8ae2b7e4623.png)
And the item is created with forllowing name: 'a_b'
![Screenshot from 2022-03-01 09-50-07](https://user-images.githubusercontent.com/89014675/156136313-880757c2-e632-46b2-b331-27dd217d2310.png)

Should we keep that issue as it is in the old console only adding a white-space trim() to validate it?  Or can we also add replace ' ' with '_'  as well? Let me know how to better proceed. Thanks!

2022-03-01 13:03 UTC, edewit commented
Yes I see, so it should be your fix and mine combined

2022-03-01 13:26 UTC, ikhomyn commented
@edewit The thing is, when scope is created with same name as is created on server back side, then it redirects:
from (Client scope create)
![Screenshot from 2022-03-01 14-24-02](https://user-images.githubusercontent.com/89014675/156177026-a34a97ce-cb0e-4c12-a2ec-cec2d2bc9000.png)
to (Client scope details)
![Screenshot from 2022-03-01 14-24-32](https://user-images.githubusercontent.com/89014675/156177087-57796999-61ba-43ec-925f-63e7706ff77e.png)
But if name is not the same, then seems like it is showing that err message and not redirecting to the page. Maybe there is a way to take the name value of the scope prior to redirection?

2022-03-01 13:31 UTC, edewit commented
The error is here: https://github.com/edewit/keycloak-admin/blob/cf6413af41731b3b6ddbccd03f6bc90e911bcb79/src/client-scopes/form/ClientScopeForm.tsx#L123 it tries to find the created client scope by name. The name is already trimmed before creating it we could also put your regex here. That is much nicer then doing it on every key press

2022-03-01 13:41 UTC, edewit approved these changes

2022-03-01 13:42 UTC, ikhomyn commented
@edewit Good catch. I didn't went so far, Thank you! I've tried the change manually and it works as expected. Do I need to rerun testsuite?

2022-03-01 13:43 UTC, edewit requested changes
we also need the validator right, to not allow a blank value?

2022-03-01 13:59 UTC, ikhomyn commented
@edewit true, now it should be okay

2022-03-01 14:06 UTC, edewit approved these changes

2022-03-01 14:06 UTC, edewit commented
:+1:

2022-03-06 15:26 UTC, jonkoops approved these changes

2022-03-06 15:26 UTC, jonkoops commented on src/client-scopes/details/ScopeForm.tsx
> +              !!value.trim() || t("common:required").toString(),
Why is `.toString()` needed here? Should the return value not always be a string?
```suggestion
              !!value.trim() || t("common:required"),
```

2022-03-06 15:26 UTC, merged