add checkbox fields, more tests
keycloak/keycloak-admin-ui pull request #2164
Opened 2022-02-28 16:48 UTC by jenny-s51

Towards #1968

2022-03-01 01:46 UTC, mfrances17 requested changes
Looking good, I was able to save values ok from old console to new and vice-versa. Two quick comments:

- I believe the **Front-channel logout URL** field should only be visible if the **Front channel logout** switch is set to ON.
- Getting the following console warning on page load:

```
react_devtools_backend.js:4061 Warning: Received the string `false` for the boolean attribute `checked`. The browser will interpret it as a truthy value. Did you mean checked={false}?
    at input
    at div
    at Checkbox (http://localhost:8080/_snowpack/pkg/@patternfly/react-core.v4.198.5/common/Truncate-4af863b5.js:3036:9)
    at div
    at InputGroup (http://localhost:8080/_snowpack/pkg/@patternfly/react-core.v4.198.5/common/Truncate-4af863b5.js:3711:11)
    at Controller (http://localhost:8080/_snowpack/pkg/react-hook-form.v6.15.8.js:1914:13)
    at div
    at GridItem (http://localhost:8080/_snowpack/pkg/@patternfly.react-core.v4.198.5.js:255:11)
    at div
    at Grid (http://localhost:8080/_snowpack/pkg/@patternfly.react-core.v4.198.5.js:239:11)
    at div
    at div
    at FormGroup (http://localhost:8080/_snowpack/pkg/@patternfly/react-core.v4.198.5/common/Truncate-4af863b5.js:5942:11)
    at form
    at Form (http://localhost:8080/_snowpack/pkg/@patternfly/react-core.v4.198.5/common/Truncate-4af863b5.js:5879:11)
    at FormAccess (http://localhost:8080/components/form-access/FormAccess.js:28:3)
    at CapabilityConfig (http://localhost:8080/clients/add/CapabilityConfig.js:31:3)
    at section
    at ScrollPanel (http://localhost:8080/components/scroll-form/ScrollPanel.js:26:5)
    at div
    at GridItem (http://localhost:8080/_snowpack/pkg/@patternfly.react-core.v4.198.5.js:255:11)
    at div
    at Grid (http://localhost:8080/_snowpack/pkg/@patternfly.react-core.v4.198.5.js:239:11)
    at ScrollForm (http://localhost:8080/components/scroll-form/ScrollForm.js:36:3)
    at ClientSettings (http://localhost:8080/clients/ClientSettings.js:38:3)
    at section
    at TabContentBase (http://localhost:8080/_snowpack/pkg/@patternfly/react-core.v4.198.5/common/Truncate-4af863b5.js:9686:11)
    at Tabs (http://localhost:8080/_snowpack/pkg/@patternfly/react-core.v4.198.5/common/Truncate-4af863b5.js:9714:9)
    at RoutableTabs (http://localhost:8080/components/routable-tabs/RoutableTabs.js:27:3)
    at FormProvider (http://localhost:8080/_snowpack/pkg/react-hook-form.v6.15.8.js:1410:11)
    at section
    at PageSection (http://localhost:8080/_snowpack/pkg/@patternfly/react-core.v4.198.5/common/Truncate-4af863b5.js:8533:11)
    at ClientDetails (http://localhost:8080/clients/ClientDetails.js:141:7)
    at Suspense
    at SecuredRoute (http://localhost:8080/App.js:55:3)
    at component
    at Route (http://localhost:8080/_snowpack/pkg/react-router.v5.2.1.js:459:29)
    at Switch (http://localhost:8080/_snowpack/pkg/react-router.v5.2.1.js:661:29)
    at ErrorBoundary (http://localhost:8080/_snowpack/pkg/react-error-boundary.v3.1.4.js:46:35)
    at main
    at div
    at Page (http://localhost:8080/_snowpack/pkg/@patternfly/react-core.v4.198.5/common/Truncate-4af863b5.js:6591:9)
    at SubGroups (http://localhost:8080/groups/SubGroupsContext.js:28:3)
    at ServerInfoProvider (http://localhost:8080/context/server-info/ServerInfoProvider.js:51:3)
    at AlertProvider (http://localhost:8080/components/alert/Alerts.js:42:3)
    at Help (http://localhost:8080/components/help-enabler/HelpHeader.js:44:3)
    at AccessContextProvider (http://localhost:8080/context/access/Access.js:40:3)
    at RealmContextProvider (http://localhost:8080/context/realm-context/RealmContext.js:33:3)
    at RealmsProvider (http://localhost:8080/context/RealmsContext.js:32:3)
    at WhoAmIContextProvider (http://localhost:8080/context/whoami/WhoAmI.js:80:3)
    at Router (http://localhost:8080/_snowpack/pkg/react-router.v5.2.1.js:90:30)
    at HashRouter (http://localhost:8080/_snowpack/pkg/react-router-dom.v5.3.0.js:116:35)
    at AppContexts (http://localhost:8080/App.js:46:3)
    at App (http://localhost:8080/App.js:75:3)
```

2022-03-01 14:30 UTC, jenny-s51 commented
Thank you for your helpful comments @mfrances17 ! I've addressed both in my latest commit 🙂

2022-03-01 16:35 UTC, jonkoops requested changes

2022-03-01 16:35 UTC, jonkoops commented on src/clients/ClientSettings.tsx
> +            {frontchannelLogout && eval(frontchannelLogout.toString()) && (
Under [no circumstances](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval#never_use_eval!) should `eval()` ever be used, this is a huge potential attack vector as it allows for arbitrary code to be executed.

An attacker can put a malicious string in `frontchannelLogout` and take over control of the whole admin ui.

2022-03-01 16:35 UTC, jonkoops commented on src/clients/ClientSettings.tsx
> +                        uri.indexOf("*") === -1) ||
You can use [`includes()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/includes) here instead of `indexOf()`.

2022-03-01 18:36 UTC, jonkoops approved these changes
LGTM

2022-03-02 21:57 UTC, jenny-s51 commented
Thanks @mfrances17 ! Looks like this was happening in multiple places.

2022-03-02 21:59 UTC, mfrances17 approved these changes
nice job, @jenny-s51... LGTM

2022-03-02 21:59 UTC, merged