Realm role details UI
keycloak/keycloak-admin-ui pull request #217
Opened 2020-11-12 19:38 UTC by jenny-s51

## Motivation

Closes https://issues.redhat.com/browse/APPDUX-652

## Verification Steps

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated
- [ ] Formatting has been performed via prettier/eslint
- [ ] Type checking has been performed via 'yarn check-types'

## Additional Notes

<img width="2553" alt="Screen Shot 2020-11-12 at 2 37 33 PM" src="https://user-images.githubusercontent.com/32821331/98987755-ab549780-24f4-11eb-95b7-3442a00b9f2e.png">

2020-11-16 20:12 UTC, mfrances17 requested changes
Ran the storybook locally. It looks like the spacing is a bit off compared to the design spec. There should be more space between the top of the tab and Role name, and less space between the bottom of the description field and the action buttons. Compare to:

![spec-realm-roles](https://user-images.githubusercontent.com/39063664/99302925-17e5d400-281e-11eb-91c7-4fc17970bcfe.png)

2020-11-16 20:16 UTC, ssilvert requested changes

2020-11-16 20:16 UTC, ssilvert commented on src/route-config.ts
> +    access: "view-realm",
The code that processes `route-config.ts` needs to be able to handle multiple roles.  And we don't do anything with subroutes right now anyway so I'm not sure how we need to check them.  We don't have any of that yet, but I believe that you should still be able to code it like this:  
```suggestion
    access: ["view-realm", "view-users"],
```

2020-11-16 21:18 UTC, jenny-s51 commented on src/route-config.ts
> +    access: "view-realm",
Thank you for your helpful review comments @ssilvert ! this doesn't seem to work at the moment, I get `Forbidden` displayed on the page instead of the details tab. what do you suggest would be an acceptable fix in the meantime? Should I just leave `view-realm`?

2020-11-16 21:27 UTC, ssilvert commented on src/route-config.ts
> +    access: "view-realm",
> Thank you for your helpful review comments @ssilvert ! this doesn't seem to work at the moment, I get `Forbidden` displayed on the page instead of the details tab. what do you suggest would be an acceptable fix in the meantime? Should I just leave `view-realm`?

That's fine.  I'll just make an issue for it.

2020-11-17 20:44 UTC, ssilvert requested changes

2020-11-17 20:44 UTC, ssilvert commented on src/realm-roles/RealmRoleDetails.tsx
> +              role="manage-clients"
@jenny-s51 This should be "manage-realm"

2020-11-18 18:59 UTC, jenny-s51 commented on src/realm-roles/RealmRoleDetails.tsx
> +              role="manage-clients"
nice catch, updated - thank you

2020-11-18 20:53 UTC, ssilvert reviewed
LGTM.  If Sarah agrees we can merge.

2020-11-18 20:53 UTC, ssilvert approved these changes

2020-11-18 21:02 UTC, mfrances17 approved these changes
LGTM, spacing issues I flagged previously are fixed.

2020-11-18 21:52 UTC, merged