use string[] directly removed need for converstion
keycloak/keycloak-admin-ui pull request #2175
Opened 2022-03-02 08:23 UTC by edewit

Small refactor that removes the need to convert multiline fields to objects, but instead uses string[] directly

2022-03-07 16:03 UTC, jonkoops requested changes

2022-03-07 16:03 UTC, jonkoops commented on src/components/multi-line-input/MultiLineInput.tsx
> +        <Fragment key={index}>
Indexes should not be used as a key as they can be unstable, causing more DOM manipulation than needed. `useFieldArray()` can provide you with a stable key here as well.

2022-03-07 16:03 UTC, jonkoops commented on src/components/multi-line-input/MultiLineInput.tsx
> +                fields[index] = value;
This also updates an existing value in-place, if you want this to be free of side-effects you should clone the array first.

2022-03-07 17:56 UTC, edewit commented on src/components/multi-line-input/MultiLineInput.tsx
> +  const fields = watch(name, defaultValue || []);
yes, but it also makes adds the need to use objects instead of strings thus adding the need to convert the field from string[] to object[] and back.

2022-03-07 19:44 UTC, edewit commented on src/components/multi-line-input/MultiLineInput.tsx
> +    setValue(name, [...fields]);
on line 34, I clone the fields array

2022-03-07 19:51 UTC, edewit commented on src/components/multi-line-input/MultiLineInput.tsx
> +        <Fragment key={index}>
using the index is fine when the order of items doesn't change

2022-03-08 09:55 UTC, jonkoops commented on src/components/multi-line-input/MultiLineInput.tsx
> +  const fields = watch(name, defaultValue || []);
Ahhh, yes. This will only complicate things, consider this resolved.

2022-03-08 09:57 UTC, jonkoops commented on src/components/multi-line-input/MultiLineInput.tsx
> +        <Fragment key={index}>
Yes, I see it's not an option here. Consider it resolved.

2022-03-08 09:57 UTC, jonkoops commented on src/components/multi-line-input/MultiLineInput.tsx
> +    setValue(name, [...fields]);
Right, but you already mutated it  on line 33 before you cloned it.

2022-03-08 16:26 UTC, jonkoops commented
@edewit Looks like there are still some test failures, could you take a look at those?

2022-03-09 16:42 UTC, jonkoops approved these changes

2022-03-09 16:42 UTC, merged