initial version of writing tests document
keycloak/keycloak-admin-ui pull request #2176
Opened 2022-03-02 08:52 UTC by edewit

As promised, initial version of writing tests document, feel free to add / discuss here futher.

2022-03-07 16:17 UTC, jenny-s51 commented on cypress/WRITING_TESTS.md
> +If there where no calls, but you still get this error try using `{force: true}`, but try not to use it everywhere, there could be an unexpected modal opened blocking the element so even the user woul
```suggestion
If there were no calls and you still get this error, try using `{force: true}`, but try not to use it everywhere. For example, there could be an unexpected open modal blocking the element, so even the user wouldn’t be able to use that element.
```

2022-03-07 16:23 UTC, jenny-s51 requested changes
Great content @edewit ! Will be an awesome addition to the repo. Left a few comments

2022-03-07 16:23 UTC, jenny-s51 commented on cypress/WRITING_TESTS.md
> +Instead use a page object it just a lot easier to get the intended of the test
```suggestion
Instead use a page object as it is a lot easier to get the intended functionality of the test:
```

2022-03-07 16:23 UTC, jenny-s51 commented on cypress/WRITING_TESTS.md
> +This is because the DOM has been updated in between selectors you can remedy this by waiting on REST calls.
```suggestion
This is because the DOM has been updated in between selectors. You can remedy this by waiting on REST calls. 
```

2022-03-07 16:23 UTC, jenny-s51 commented on cypress/WRITING_TESTS.md
> +don't do this:
```suggestion
Don't do this:
```

2022-03-07 21:53 UTC, mfrances17 approved these changes
LGTM, this is great to have and we can build on it from here.

2022-03-09 11:46 UTC, Aboullos commented on cypress/WRITING_TESTS.md
> +We have `keycloakBefore` that will navigate to the main page and setup some things.
```suggestion
We have `keycloakBefore` that will navigate to the main page, control request errors and wait for the load to finish.
```

2022-03-09 11:46 UTC, Aboullos commented on cypress/WRITING_TESTS.md
> +  it("should edit realm role details", () => {
Maybe we can set a convention to capitalize the first word of the sentence from `describe` and `it`

2022-03-09 16:43 UTC, jonkoops requested changes
@edewit can you incorporate the changes from #2215?

2022-03-14 15:06 UTC, ssilvert commented
@edewit Is there a particular *.spec.ts file that we can cite as the canonical example for people to look at?  It should be a file that uses all or most of the tips included here.  It would be good to point to a file and say, "This is how you should do it".

2022-03-15 06:24 UTC, edewit commented
@ssilvert @jonkoops done

2022-03-15 10:47 UTC, Aboullos approved these changes

2022-03-15 13:10 UTC, jonkoops commented on cypress/WRITING_TESTS.md
> +Use `keycloakBeforeEach` to keep the keycloak cookie and stay logged in.
No need to do before each anymore

2022-03-15 14:15 UTC, jonkoops approved these changes

2022-03-16 09:39 UTC, merged