split out the key based into a sperate component
keycloak/keycloak-admin-ui pull request #2177
Opened 2022-03-02 14:30 UTC by edewit

it's made it's base component to hard to reuse and was only used once

2022-03-07 22:51 UTC, jenny-s51 requested changes
Good idea splitting this up into a separate component @edewit !

I tested this in the Authorization -> Evaluate tab of Clients and noticed that whatever was typed into the "value" field wasn't being sent with the data. 

Passing the `name` prop to `ValueInput` seems to fix it!

2022-03-07 22:51 UTC, jenny-s51 commented on src/clients/authorization/KeyBasedAttributeInput.tsx
> +              isDisabled={!watchLastValue}
Currently this is always disabled even if a value is typed into the attribute value input field.

2022-03-07 22:51 UTC, jenny-s51 commented on src/clients/authorization/KeyBasedAttributeInput.tsx
> +              attribute={attribute}
```suggestion
              name={name}
              attribute={attribute}
```

2022-03-09 07:14 UTC, edewit commented on src/clients/authorization/KeyBasedAttributeInput.tsx
> +              attribute={attribute}
good catch...

2022-03-09 16:43 UTC, jonkoops requested changes

2022-03-10 11:11 UTC, jonkoops requested changes
Changes look good, but the tests are failing. @edewit can you take a look?

2022-03-15 20:21 UTC, jenny-s51 approved these changes

2022-03-16 09:39 UTC, jonkoops approved these changes

2022-03-16 09:39 UTC, merged