fixed title and link to page
keycloak/keycloak-admin-ui pull request #2183
Opened 2022-03-03 09:11 UTC by edewit

fixes: #2060

2022-03-03 09:32 UTC, jonkoops requested changes

2022-03-03 09:32 UTC, jonkoops commented on src/clients/authorization/Resources.tsx
> +                    onClick={() =>
This can be turned into a link by using the `component` prop.

2022-03-03 09:32 UTC, jonkoops commented on src/clients/authorization/Scopes.tsx
> +                      onClick={() =>
Same here, this could be a link.

2022-03-07 19:11 UTC, mfrances17 requested changes
Code looks good, tested fine. The help for Policies (permissionPolicies) is not working for scope-based and resource-based permissions. Otherwise will approve.

2022-03-09 13:38 UTC, mfrances17 approved these changes
LGTM

2022-03-09 16:44 UTC, jonkoops approved these changes

2022-03-09 16:44 UTC, merged