remove capabities step from wizard for SAML
keycloak/keycloak-admin-ui pull request #2191
Opened 2022-03-04 08:24 UTC by edewit

fixes: #1513

2022-03-07 16:05 UTC, jenny-s51 approved these changes
LGTM! 👍

2022-03-07 16:07 UTC, jonkoops requested changes
Looks like the tests are failing.

2022-03-07 20:10 UTC, mfrances17 approved these changes
LGTM, the Capability config step now only appears during OIDC client creation and not SAML client creation

2022-03-09 16:45 UTC, jonkoops approved these changes

2022-03-09 16:45 UTC, merged