User fed kerberos settings controllers
keycloak/keycloak-admin-ui pull request #224
Opened 2020-11-16 20:04 UTC by srambach

## Motivation
https://issues.redhat.com/browse/APPDUX-543

## Brief Description
This adds controllers to the user federation Kerberos screen. It does not yet have calls to save but there are test buttons on each section (commented out) that verify that the controllers. Follow on task will implement the REST calls to save.

## Verification Steps
View the form in storybook under "User Federation Kerberos Settings Tab"
Corresponding Marvel is at https://marvelapp.com/prototype/ecjc94b/screen/72098368

## Checklist:
- [x] Code has been tested locally by PR requester
- [x] User-visible strings are using the react-i18next framework (useTranslation)
- [x] Help has been implemented
- [x] axe report has been run and resulting a11y issues have been resolved
- [NA] Unit tests have been created/updated
- [x] Formatting has been performed via prettier/eslint
- [x] Type checking has been performed via 'yarn check-types'

2020-11-17 22:06 UTC, ssilvert commented
@srambach This looks good, but I'm not sure that "Edit mode" should be there for Kerberos.  Have you asked about that?  Might be a mistake in the wireframe.

2020-11-18 16:12 UTC, srambach commented
> @srambach This looks good, but I'm not sure that "Edit mode" should be there for Kerberos. Have you asked about that? Might be a mistake in the wireframe.

@ssilvert April pointed out that the field shows up when "Allow Password Authentication" is switched on.

2020-11-18 18:30 UTC, srambach commented
I added fields for cache settings that are conditional on the cache policy. None of the conditional fields are shown/hidden yet but are marked with todos.

2020-11-18 20:39 UTC, ssilvert commented
> > @srambach This looks good, but I'm not sure that "Edit mode" should be there for Kerberos. Have you asked about that? Might be a mistake in the wireframe.
> 
> @ssilvert April pointed out that the field shows up when "Allow Password Authentication" is switched on.

OK.  Only issue I see is that it has the wrong help text.  It's using the help text for LDAP edit mode.

2020-11-19 13:59 UTC, ssilvert requested changes
I think that user-federation.ts is not needed as these model definitions can now come from the newly added keycloak-nodejs-admin-client package.  Check with @edewit for how this should be handled.

2020-11-19 13:59 UTC, ssilvert commented on src/user-federation/KerberosSettingsCache.tsx
> +                <SelectOption key={7} value="Saturday" />
@srambach Please localize.

2020-11-19 13:59 UTC, ssilvert commented on src/user-federation/KerberosSettingsCache.tsx
> +                <SelectOption key={0} value="Choose..." isPlaceholder />
Localize

2020-11-19 13:59 UTC, ssilvert commented on src/user-federation/KerberosSettingsCache.tsx
> +                <SelectOption key={0} value="Choose..." isPlaceholder />
Localize

2020-11-19 13:59 UTC, ssilvert commented on src/user-federation/KerberosSettingsCache.tsx
> +                <SelectOption key={0} value="Choose..." isPlaceholder />
localize

2020-11-19 14:48 UTC, ssilvert commented on src/user-federation/KerberosSettingsCache.tsx
> +      <Form isHorizontal onSubmit={handleSubmit(onSubmit)}>
@srambach This should use `<FormAccess>` instead of `<Form>`.  Please add a comment so that it will be fixed when this is fully implemented.

2020-11-23 16:27 UTC, jenny-s51 commented on src/user-federation/KerberosSettingsCache.tsx
> +  const hourOptions = [
From a user’s perspective, I think it would make more sense to start at 1 (rather than 0) here

2020-11-23 16:28 UTC, jenny-s51 commented on src/user-federation/KerberosSettingsCache.tsx
> +    hourOptions.push(<SelectOption key={index + 1} value={index} />);
From a user’s perspective, I think it would make more sense to start at 1 (rather than 0) here 
```suggestion
    hourOptions.push(<SelectOption key={index + 1} value={index + 1} />);
```

2020-11-23 16:42 UTC, jenny-s51 reviewed
Form looks great and seems to match the Marvel prototype @srambach ! Per our discussion in Slack, it might make more sense to set the minute/hour dropdowns to `TextInput` with validation for numeric inputs

2020-11-23 16:42 UTC, jenny-s51 commented on src/user-federation/KerberosSettingsCache.tsx
> +    minuteOptions.push(<SelectOption key={index + 1} value={index} />);
From a user’s perspective, I think it would make more sense to start at 1 (rather than 0) here. Can 

```suggestion
    minuteOptions.push(<SelectOption key={index + 1} value={index + 1} />);
```

2020-11-23 21:22 UTC, jenny-s51 approved these changes

2020-11-24 13:56 UTC, ssilvert approved these changes

2020-11-24 13:56 UTC, merged