Realm settings(login tab): Add login tests
keycloak/keycloak-admin-ui pull request #2260
Opened 2022-03-14 17:42 UTC by jenny-s51

Adds login tests: 

https://docs.google.com/spreadsheets/d/1eCngdn3wmMeQ0u5u-eKYJo1XdT2fHvi7ki51mrcu-Ys/edit#gid=1613790516&range=443:446

2022-03-14 19:11 UTC, mfrances17 requested changes
I think you missed the test for the duplicate emails enabled/disabled switch (445)

2022-03-15 18:03 UTC, jenny-s51 commented
Marking as draft -- these tests revealed some bugs in how these switches are currently implemented. Investigating a fix! Plan to have a PR up shortly with an updated implementation for saving switch values.

2022-03-21 12:16 UTC, jonkoops commented on src/realm-settings/LoginTab.tsx
> +                      ? t("common:on").toLowerCase()
Why do we need to use a translated label as the value of this? Should this not be the same value regardless of language?

2022-03-21 12:17 UTC, jonkoops requested changes

2022-03-21 12:17 UTC, jonkoops commented on src/realm-settings/PoliciesTab.tsx
> +    console.log(switchValues);
Stray console log.
```suggestion
```

2022-03-28 11:14 UTC, jonkoops requested changes

2022-03-28 11:14 UTC, jonkoops commented on src/realm-settings/LoginTab.tsx
> +                      : t("common:off").toLowerCase()
The value should not be translated here right? I suppose these should be replaced with static values.

2022-03-28 11:14 UTC, jonkoops commented on src/realm-settings/LoginTab.tsx
> +                      : t("common:off").toLowerCase()
Some here, the value is again translated.

2022-03-28 11:14 UTC, jonkoops commented on src/realm-settings/LoginTab.tsx
> +                      : t("common:off").toLowerCase()
Same here.

2022-03-28 11:14 UTC, jonkoops commented on src/realm-settings/LoginTab.tsx
> +                      : t("common:off").toLowerCase()
And here.

2022-03-28 11:14 UTC, jonkoops commented on src/realm-settings/LoginTab.tsx
> +                      : t("common:off").toLowerCase()
And here again.

2022-03-28 11:14 UTC, jonkoops commented on src/realm-settings/LoginTab.tsx
> +                      : t("common:off").toLowerCase()
Also here.

2022-03-28 11:15 UTC, jonkoops commented
@jenny-s51 can you also rebase this PR on `main` so the tests can pass again?

2022-03-28 13:34 UTC, jonkoops approved these changes
Looking good, let's see if the tests will pass.

2022-03-28 15:34 UTC, merged