Introduce CodeQL analysis
keycloak/keycloak-admin-ui pull request #2262
Opened 2022-03-14 20:33 UTC by abstractj

The changes proposed here will run the CodeQL analysis in the admin-ui
repository, skipping `cypress` and `mocks` paths to prevent false
alerts.

Closes #2261

### PoC

- [Pull-request with the worst practices](https://github.com/keycloak-poc/keycloak-admin-ui/pull/72/files)

2022-03-16 10:05 UTC, jonkoops requested changes

2022-03-16 10:05 UTC, jonkoops commented on .github/workflows/codeql-analysis.yml
> +    - name: Run build task
Can we add some whitespace here as with the other steps?
```suggestion
        node-version: ${{ env.NODE_VERSION }}

    - name: Run build task
```

2022-03-17 14:12 UTC, abstractj commented on .github/workflows/codeql-analysis.yml
> +  schedule:
That was pretty much to keep consistency with the main repository. But I don't see any issue about changing it.

2022-03-17 14:19 UTC, abstractj commented on .github/workflows/codeql-analysis.yml
> +      uses: actions/checkout@v2
That was pretty much to keep consistency with the Keycloak repo.

2022-03-22 14:55 UTC, abstractj commented on .github/workflows/codeql-analysis.yml
> +on:
@jonkoops do you think that targeting only `main` is ok, or should we run CodeQL on every branch? The reason why I ask is because, in the Keycloak repository, we had to create a backport branch to 17.0.1

2022-03-29 09:31 UTC, jonkoops commented on .github/workflows/codeql-analysis.yml
> +    if: (github.actor != 'dependabot[bot]')
Perhaps [this](https://github.com/envoyproxy/envoy/pull/20342/files#diff-9bb3f1ca8ba78a01ab8019d18b9b7feee618734f56f235ab411a39ec9a300241R7) would be a better option as Dependabot always prefixes branches.

2022-03-29 10:11 UTC, jonkoops commented on .github/workflows/codeql-analysis.yml
> +on:
Yeah, this is what is recommended by Github so seems fine to me.

2022-03-29 10:35 UTC, jonkoops approved these changes

2022-03-29 10:35 UTC, merged