Add Clients tests
keycloak/keycloak-admin-ui pull request #2270
Opened 2022-03-15 16:01 UTC by Aboullos

## Brief Description
Add Clients tests

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

2022-03-16 09:48 UTC, jonkoops approved these changes

2022-03-16 22:34 UTC, mfrances17 requested changes
LGTM, i would remove debugger then approved

2022-03-16 22:34 UTC, mfrances17 commented on cypress/integration/clients_test.spec.ts
> +      cy.debug();
should remove debugger

2022-03-17 12:08 UTC, Aboullos commented on cypress/integration/clients_test.spec.ts
> +      cy.debug();
Oh, right!

2022-03-17 12:12 UTC, Aboullos commented on cypress/integration/clients_test.spec.ts
> +      cy.debug();
Resolved

2022-03-28 13:14 UTC, merged