fixed required in general settings
keycloak/keycloak-admin-ui pull request #2279
Opened 2022-03-16 15:32 UTC by agagancarczyk

## Motivation
Added switch logic as per the old console. Setting the "Required" toggle to false should hide the "Required For" and "Required When" fields. Related Design https://marvelapp.com/prototype/5eed532/screen/82246809

## Verification Steps

1. Go to realm-settings, user profile tab (if not present, enable it in general settings)
2. Create a new attribute and scroll down to the "Required" toggle. Verify that when the toggle is set to false the "Required For" and "Required When" fields are hidden. Set the toggle to true, complete the fields and save the attribute. 

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

2022-03-17 07:56 UTC, edewit requested changes
Seems you are using tabs instead of spaces to indent

2022-03-17 07:56 UTC, edewit commented on src/realm-settings/user-profile/attribute/AttributeGeneralSettings.tsx
> +  const [requiredToggle, setRequiredToggle] = useState(false);
instead of introducing extra state you could use a watch on the form value:

```typescript
  const requiredToggle = useWatch({
    control,
    name: "required",
    defaultValue: false,
  });
```

2022-03-21 09:44 UTC, agagancarczyk commented on src/realm-settings/user-profile/attribute/AttributeGeneralSettings.tsx
> +  const [requiredToggle, setRequiredToggle] = useState(false);
Thanks @edewit great idea. This is now implemented.

2022-03-21 13:16 UTC, edewit commented
seems you still have the indentation using tabs instead of spaces

2022-03-21 14:27 UTC, agagancarczyk commented
> 

This should now be fixed. Thanks Erik

2022-03-21 14:41 UTC, edewit approved these changes

2022-03-21 14:46 UTC, merged