Adds tab for realm role details + update/save functionality
keycloak/keycloak-admin-ui pull request #228
Opened 2020-11-19 16:48 UTC by jenny-s51

## Motivation

https://issues.redhat.com/secure/RapidBoard.jspa?rapidView=4966&view=detail&selectedIssue=APPDUX-562

## Brief Description

Adds role details tab and functionality to edit name and description of role.

Extends #207 

## Verification Steps

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated
- [ ] Formatting has been performed via prettier/eslint
- [ ] Type checking has been performed via 'yarn check-types'

2020-11-20 09:00 UTC, edewit requested changes
Is this Component supposed to be used for new roles and editing existing roles? If so I think these changes break the new role usecase right?

2020-11-20 16:18 UTC, jenny-s51 commented on src/realm-roles/RealmRoleDetails.tsx
> +  const [, setDescription] = useState("");
nice catch, thank you. deleted

2020-11-20 19:04 UTC, jenny-s51 commented
@edewit great question, I just reached out to Haley on Zulip to confirm the expected behavior from the design

2020-11-20 21:08 UTC, mfrances17 requested changes
Changes look good, functionality is working as expected when tested. One reproducible issue I found, console is throwing an error on first load of the realm role details page, does not seem to appear on subsequent loads. Should be investigated either as part of this PR or a separate issue should be filed:

```
Warning: React does not recognize the `isDisabled` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `isdisabled` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in textarea (created by TextArea)
    in TextArea (created by Controller)
    in Controller (created by RolesForm)
    in div (created by FormGroup)
    in div (created by FormGroup)
    in FormGroup (created by RolesForm)
    in form (created by Form)
    in Form (created by FormAccess)
    in FormAccess (created by RolesForm)
    in section (created by TabContentBase)
    in TabContentBase (created by ForwardRef)
    in ForwardRef (created by Tabs)
    in Tabs (created by RolesForm)
    in section (created by PageSection)
    in PageSection (created by RolesForm)
    in RolesForm (created by SecuredRoute)
    in SecuredRoute (created by component)
    in component (created by Context.Consumer)
    in Route (created by App)
    in Switch (created by App)
    in main (created by Page)
    in div (created by Page)
    in Page (created by App)
    in Router (created by BrowserRouter)
    in BrowserRouter (created by App)
    in DataLoader (created by ServerInfoProvider)
    in ServerInfoProvider (created by AppContexts)
    in AlertProvider (created by AppContexts)
    in Help (created by AppContexts)
    in AccessContextProvider (created by AppContexts)
    in AppContexts (created by App)
    in App
    in RealmContextProvider
    in DataLoader (created by WhoAmIContextProvider)
    in WhoAmIContextProvider

```

2020-11-21 14:25 UTC, edewit commented
@mfrances17 I know what that is, it's not caused by this PR but by the
`<FormAccess` component, I'll create a Jira for it #230

On Fri, Nov 20, 2020 at 10:08 PM mfrances17 <notifications@github.com>
wrote:

> *@mfrances17* requested changes on this pull request.
>
> Changes look good, functionality is working as expected when tested. One
> reproducible issue I found, console is throwing an error on first load of
> the realm role details page, does not seem to appear on subsequent loads.
> Should be investigated either as part of this PR or a separate issue should
> be filed:
>
> Warning: React does not recognize the `isDisabled` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `isdisabled` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
>     in textarea (created by TextArea)
>     in TextArea (created by Controller)
>     in Controller (created by RolesForm)
>     in div (created by FormGroup)
>     in div (created by FormGroup)
>     in FormGroup (created by RolesForm)
>     in form (created by Form)
>     in Form (created by FormAccess)
>     in FormAccess (created by RolesForm)
>     in section (created by TabContentBase)
>     in TabContentBase (created by ForwardRef)
>     in ForwardRef (created by Tabs)
>     in Tabs (created by RolesForm)
>     in section (created by PageSection)
>     in PageSection (created by RolesForm)
>     in RolesForm (created by SecuredRoute)
>     in SecuredRoute (created by component)
>     in component (created by Context.Consumer)
>     in Route (created by App)
>     in Switch (created by App)
>     in main (created by Page)
>     in div (created by Page)
>     in Page (created by App)
>     in Router (created by BrowserRouter)
>     in BrowserRouter (created by App)
>     in DataLoader (created by ServerInfoProvider)
>     in ServerInfoProvider (created by AppContexts)
>     in AlertProvider (created by AppContexts)
>     in Help (created by AppContexts)
>     in AccessContextProvider (created by AppContexts)
>     in AppContexts (created by App)
>     in App
>     in RealmContextProvider
>     in DataLoader (created by WhoAmIContextProvider)
>     in WhoAmIContextProvider
>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/keycloak/keycloak-admin-ui/pull/228#pullrequestreview-535776904>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAMPPN5JF74247C2V6B4BLSQ3LENANCNFSM4T3UXSNQ>
> .
>

2020-11-23 10:18 UTC, edewit commented
@jenny-s51 what I mean is that the name field should be disabled: https://marvelapp.com/prototype/f39d464/screen/72683271

2020-11-23 15:16 UTC, dlabaj approved these changes
LGTM

2020-11-23 15:16 UTC, dlabaj commented on src/realm-roles/RealmRoleDetails.tsx
> +                    // defaultValue={name}
Remove unneeded code.

2020-11-23 15:20 UTC, merged