don't test ldap when form isn't valid
keycloak/keycloak-admin-ui pull request #2294
Opened 2022-03-18 12:17 UTC by edewit

fixes: #1776

2022-03-18 20:05 UTC, jenny-s51 requested changes
Form validation working as expected @edewit - nice fix!

Can we use the `helperTextInvalid` prop on the `connectionUrl` field? The helper text renders in black for this field but for the other fields the invalid text shows up red. Using `helperTextInvalid` seems to fix it! WDYT @edewit ?

2022-03-21 10:29 UTC, edewit commented
Yes @jenny-s51 seems that parts of this form have some custom helper text rendering, updated this PR to change it to PF

2022-03-22 14:15 UTC, jenny-s51 requested changes
Thanks for refactoring those @edewit ! LDAP form is looking good -- there are just a couple areas in the Kerberos form where we should be using dot notation to prevent undefined errors

2022-03-22 14:15 UTC, jenny-s51 commented on src/user-federation/kerberos/KerberosSettingsRequired.tsx
> +          helperTextInvalid={form.errors.config.kerberosRealm[0].message}
```suggestion
          helperTextInvalid={form.errors.config.kerberosRealm?.[0].message}
```

2022-03-22 14:15 UTC, jenny-s51 commented on src/user-federation/kerberos/KerberosSettingsRequired.tsx
> +          helperTextInvalid={form.errors.config.keyTab[0].message}
```suggestion
          helperTextInvalid={form.errors.config.keyTab?.[0].message}
```

2022-03-22 16:29 UTC, edewit commented
Good catch @jenny-s51 don't know why I didn't see that...

2022-03-22 17:44 UTC, jenny-s51 approved these changes
LGTM! 👍

2022-03-29 07:49 UTC, merged