fixed the filter dropdown
keycloak/keycloak-admin-ui pull request #2315
Opened 2022-03-21 14:29 UTC by edewit

fixes: #2289

2022-03-21 16:10 UTC, jonkoops commented on src/components/table-toolbar/KeycloakDataTable.tsx
> +  loader: T[] | LoaderFunction<T>;
Neat, that is quite useful.

2022-03-21 16:13 UTC, jonkoops requested changes

2022-03-21 16:13 UTC, jonkoops commented on src/components/table-toolbar/KeycloakDataTable.tsx
> +type LoaderFunction<T> = (
It looks like some of the arguments here are always passed, perhaps we can make them required?

2022-03-21 16:13 UTC, jonkoops commented on src/components/table-toolbar/KeycloakDataTable.tsx
> +    [key, first, max, search, loader]
If `loader` is an unmemoized function this will trigger the effect every time the parent component is rendered.

2022-03-22 06:55 UTC, edewit commented on src/components/table-toolbar/KeycloakDataTable.tsx
> +type LoaderFunction<T> = (
no you can use the keycloak data table with a loader that has 0 arguments when do not use `isPaginated`

2022-03-22 06:55 UTC, edewit commented on src/components/table-toolbar/KeycloakDataTable.tsx
> +    [key, first, max, search, loader]
right loader should only be a dependency when it's data

2022-03-28 20:57 UTC, jonkoops approved these changes

2022-03-28 20:57 UTC, merged