Fixes header and cancel when adding realm roles
keycloak/keycloak-admin-ui pull request #2327
Opened 2022-03-22 21:41 UTC by mfrances17

## Motivation
Fixes https://github.com/keycloak/keycloak-admin-ui/issues/1851.

## Brief Description
Added header and fixed cancel button on create realm role form.

## Verification Steps
See the linked issue for specifics including how to reproduce.

## Checklist:
- [x] Code has been tested locally by PR requester
- [x] User-visible strings are using the react-i18next framework (useTranslation)
- [x] Help has been implemented
- [x] Unit tests have been created/updated

## Additional Notes
None

2022-03-24 09:03 UTC, edewit approved these changes

2022-03-24 15:17 UTC, jenny-s51 approved these changes

2022-03-29 07:53 UTC, edewit requested changes
@mfrances17 seems the clients test fail because of this change

2022-03-31 04:03 UTC, mfrances17 commented
@edewit @jonkoops latest push fixes issue with clients that was failing the client tests... test now passes locally (headless only, couldn't test with the cypress UI it will fail with the OOM issue - client test should probably be broken up into smaller tests).
![client-tests](https://user-images.githubusercontent.com/39063664/160974082-c771beaf-7c93-4539-8c36-052b1b2beed8.png)

2022-04-01 15:10 UTC, agagancarczyk commented
@edewit I have run the tests locally and they are passing. If you are happy that your changes have been addressed, I think we can merge it.

![Screenshot 2022-04-01 at 16 07 33](https://user-images.githubusercontent.com/4890675/161291291-c0fec1b3-e185-4b90-8318-981e0168c6fa.png)

2022-04-01 15:11 UTC, agagancarczyk approved these changes

2022-04-05 07:17 UTC, edewit approved these changes

2022-04-05 07:17 UTC, merged