improved use of indexes making rendering faster
keycloak/keycloak-admin-ui pull request #2332
Opened 2022-03-23 14:28 UTC by edewit

@jonkoops optimised use of the indexes to make the rendering faster and more robust

2022-03-23 15:40 UTC, jonkoops requested changes
I am not sure this would actually make the performance any different. Both before and now the `index` is still changed for all items that are after the point where an entry is removed so they will still re-render.

2022-03-23 15:40 UTC, jonkoops commented on src/components/multi-line-input/MultiLineInput.tsx
> +  const [indexes, setIndexes] = useState<number[]>(
I think you can omit the type here as it should be inferrable.
```suggestion
  const [indexes, setIndexes] = useState(
```

2022-03-23 15:40 UTC, jonkoops commented on src/components/multi-line-input/MultiLineInput.tsx
>          <Fragment key={index}>
Would this really prevent re-renders though? The `index` would always be the same :thinking:

2022-03-24 09:01 UTC, edewit commented on src/components/multi-line-input/MultiLineInput.tsx
>          <Fragment key={index}>
The problem is removing a row and adding one again, then it would reuse the same number. Now it counts the total number of rows and this newly added row will not share the same row index as the removed one.

2022-03-28 15:37 UTC, jonkoops commented on src/components/multi-line-input/MultiLineInput.tsx
>          <Fragment key={index}>
Ah great, then this makes sense.

2022-03-28 15:37 UTC, jonkoops approved these changes

2022-03-30 09:08 UTC, closed without merging