refactor clients tests
keycloak/keycloak-admin-ui pull request #2368
Opened 2022-03-29 10:34 UTC by ikhomyn

## Motivation
Add additional layer for the test creation in order to simplify and make code reusable within different pages.

## Brief Description
Were added CommonElements class and CommonPage class.

## Verification Steps

## Checklist:

- [X] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [X] Unit tests have been created/updated

## Additional Notes
I would appreciate to get any opinion on this approach and any required change if needed. WDYT?

2022-03-29 13:23 UTC, jonkoops requested changes

2022-03-29 13:23 UTC, jonkoops commented on cypress/support/pages/CommonElements.ts
> +  primaryBtn;
These should be probably be typed and should also be marked as `private`. For example:

```ts
private primaryBtn: string;
```

2022-03-29 13:23 UTC, jonkoops commented on cypress/support/pages/CommonElements.ts
> +  constructor(parentSelector: string = "") {
The type here can be inferred from the default value.
```suggestion
  constructor(parentSelector = "") {
```

2022-03-29 13:23 UTC, jonkoops commented on cypress/support/pages/CommonElements.ts
> +  checkElementIsDisabled(element: any, disabled: boolean) {
Can we add the correct type here?

2022-03-29 13:23 UTC, jonkoops commented on cypress/support/pages/CommonElements.ts
> +      ($btn: { classList: Iterable<unknown> | ArrayLike<unknown> }[]) => {
I think most of the jQuery methods exist in Cypress, so you can probably do something like [`.hasClass()`](https://api.jquery.com/hasclass/).

2022-03-29 13:23 UTC, jonkoops commented on cypress/support/pages/CommonPage.ts
> +  private mastheadPage: Masthead;
Since these are instantiated immediately you can get rid of the constructor and initialize them inline.
```suggestion
  private mastheadPage = new Masthead();
```

2022-03-29 13:23 UTC, jonkoops commented on cypress/support/pages/admin_console/components/ActionToolbarPage.ts
> +    }
This could possibly be a tenary.

```ts
const condition = exists ? "exist" : "not.exist";
```

2022-03-29 13:23 UTC, jonkoops commented on cypress/support/pages/admin_console/components/TabPage.ts
> +  tabItemSelector;
Can we add an access modifier and type here?
```suggestion
  protected tabItemSelector: string;
```

2022-03-29 13:23 UTC, jonkoops commented on cypress/support/pages/admin_console/components/TabPage.ts
> +    let condition = "exist";
This could be a tenary as well.

2022-03-29 13:23 UTC, jonkoops commented on cypress/support/pages/admin_console/components/TablePage.ts
> +  /*selectRowItemToggleValue(itemName: string, toggleValue: string){
Can we get rid of this commented out code?

2022-03-29 13:23 UTC, jonkoops commented on cypress/support/pages/admin_console/components/TablePage.ts
> +  tableRowItem;
Can we add types and access modifiers here?

2022-03-29 13:23 UTC, jonkoops commented on cypress/support/pages/admin_console/components/TablePage.ts
> +  static tableSelector: string = "table[aria-label]";
Type can be inferred here.
```suggestion
  static tableSelector = "table[aria-label]";
```

2022-03-29 13:23 UTC, jonkoops commented on cypress/support/pages/admin_console/components/TableToolbarPage.ts
> +  searchBtn;
Same here.

2022-03-29 13:23 UTC, jonkoops commented on cypress/support/pages/admin_console/components/TableToolbarPage.ts
> +  //=== checks on elements
Can we remove this comment?

2022-03-29 13:23 UTC, jonkoops commented on cypress/support/pages/admin_console/manage/clients/ClientRolesTab.ts
> +  usersInRole = "Users in role",
Can we use the same convention as TypeScript?
```suggestion
  Details = "Details",
  Attributes = "Attributes",
  UsersInRole = "Users in role",
```

2022-03-29 13:23 UTC, jonkoops commented on cypress/support/pages/admin_console/manage/clients/ClientsPage.ts
> +  initialAccessToken = "Initial access token",
```suggestion
  ClientsList = "Clients list",
  InitialAccessToken = "Initial access token",
```

2022-03-29 13:23 UTC, jonkoops commented on cypress/support/pages/admin_console/manage/clients/CreateInitialAccessTokenPage.ts
> +    cy.findByTestId(this.expirationInput).clear().type(`${expiration}`);
```suggestion
    cy.findByTestId(this.expirationInput).clear().type(expiration);
```

2022-03-29 13:23 UTC, jonkoops commented on cypress/support/pages/admin_console/manage/clients/client_details/ClientDetailsPage.ts
> +  settingsTab: SettingsTab;
Can we add the access modifiers here?

2022-03-29 13:23 UTC, jonkoops commented on cypress/support/pages/admin_console/manage/clients/client_details/ClientDetailsPage.ts
> +  scope = "Scope",
```suggestion
  Settings = "Settings",
  Keys = "Keys",
  Credentials = "Credentials",
  Roles = "Roles",
  ClientScopes = "Client scopes",
  Authorization = "Authorization",
  ServiceAccountsRoles = "Service accounts roles",
  Advanced = "Advanced",
  Scope = "Scope",
```

2022-03-29 13:23 UTC, jonkoops commented on cypress/support/pages/admin_console/manage/clients/client_details/ClientDetailsPage.ts
> +    this.advancedTab = new AdvancedTab();
These can all be initialized inline, no need for constructor.

2022-03-29 13:23 UTC, jonkoops commented on cypress/support/pages/admin_console/manage/clients/client_details/DedicatedScopesMappersTab.ts
> +  byConfiguration = "By configuration",
```suggestion
  FromPredefinedMappers = "From predefined mappers",
  ByConfiguration = "By configuration",
```

2022-03-29 13:23 UTC, jonkoops commented on cypress/support/pages/admin_console/manage/clients/client_details/DedicatedScopesMappersTab.ts
> +  configureaNewMapper = "Configure a new mapper",
```suggestion
  AddPredefinedMapper = "Add predefined mapper",
  ConfigureaNewMapper = "Configure a new mapper",
```

2022-03-29 13:23 UTC, jonkoops commented on cypress/support/pages/admin_console/manage/clients/client_details/DedicatedScopesPage.ts
> +  scope = "Scope",
```suggestion
  Mappers = "Mappers",
  Scope = "Scope",
```

2022-03-29 13:23 UTC, jonkoops commented on cypress/support/pages/admin_console/manage/clients/client_details/DedicatedScopesPage.ts
> +    this.scopeTab = new DedicatedScopesScopeTab();
Can be initialized inline

2022-03-29 13:23 UTC, jonkoops commented on cypress/support/pages/admin_console/manage/clients/client_details/DedicatedScopesScopeTab.ts
> +  constructor() {
Do we need this constructor?

2022-03-29 13:23 UTC, jonkoops commented on cypress/support/pages/admin_console/manage/clients/client_details/tabs/AdvancedTab.ts
> +  constructor() {
Do we need this constructor?

2022-03-29 13:23 UTC, jonkoops commented on cypress/support/pages/admin_console/manage/clients/client_details/tabs/AuthorizationTab.ts
> +  export = "Export",
```suggestion
  Settings = "Settings",
  Resources = "Resources",
  Scopes = "Scopes",
  Policies = "Policies",
  Permissions = "Permissions",
  Evaluate = "Evaluate",
  Export = "Export",
```

2022-03-29 13:23 UTC, jonkoops commented on cypress/support/pages/admin_console/manage/clients/client_details/tabs/AuthorizationTab.ts
> +    this.settingsSubTab = new SettingsTab();
These can be initialized statically.

2022-03-29 13:23 UTC, jonkoops commented on cypress/support/pages/admin_console/manage/clients/client_details/tabs/ClientScopesTab.ts
> +  evaluate = "Evaluate",
```suggestion
  Setup = "Setup",
  Evaluate = "Evaluate",
```

2022-03-29 13:23 UTC, jonkoops commented on cypress/support/pages/admin_console/manage/clients/client_details/tabs/ClientScopesTab.ts
> +    this.setupSubTab = new SetupTab();
Can be initialized statically.

2022-03-29 13:23 UTC, jonkoops commented on cypress/support/pages/admin_console/manage/clients/client_details/tabs/KeysTab.ts
> +  constructor() {
Do we need this constructor?

2022-03-29 13:23 UTC, jonkoops commented on cypress/support/pages/admin_console/manage/clients/client_details/tabs/authorization_subtabs/PermissionsTab.ts
> +    this.createPermissionPage = new CreatePermissionPage();
Can be instantiated inline.

2022-03-29 13:23 UTC, jonkoops commented on cypress/support/pages/admin_console/manage/clients/client_details/tabs/authorization_subtabs/PoliciesTab.ts
> +  createPolicy(type: string, first: boolean | undefined = false) {
```suggestion
  createPolicy(type: string, first = false) {
```

2022-03-29 13:23 UTC, jonkoops commented on cypress/support/pages/admin_console/manage/clients/client_details/tabs/authorization_subtabs/ResourcesTab.ts
> +    this.createResourcePage = new CreateResourcePage();
Can be instantiated statically.

2022-03-29 13:23 UTC, jonkoops commented on cypress/support/pages/admin_console/manage/clients/client_details/tabs/authorization_subtabs/ScopesTab.ts
> +    this.createAuthorizationScopePage = new CreateAuthorizationScopePage();
Can be instantiated statically.

2022-03-29 13:23 UTC, jonkoops commented on cypress/support/pages/admin_console/manage/clients/client_details/tabs/clientscopes_subtabs/SetupTab.ts
> +  assignedType = "Assigned type",
```suggestion
  Name = "Name",
  AssignedType = "Assigned type",
```

2022-03-29 13:23 UTC, jonkoops commented on cypress/support/pages/admin_console/manage/clients/client_details/tabs/clientscopes_subtabs/SetupTab.ts
> +  optional = "Optional",
```suggestion
  AllTypes = "All types",
  Default = "Default",
  Optional = "Optional",
```

2022-03-29 13:23 UTC, jonkoops commented on cypress/support/pages/admin_console/manage/clients/client_details/tabs/clientscopes_subtabs/SetupTab.ts
> +  //constructor() {
Can we delete this commented out code?

2022-03-29 14:11 UTC, Aboullos requested changes
Also it would be good to have some information in a README about the structural organization of the CommonPage and its connection to other elements, and the utilities in the new elements

2022-03-29 14:11 UTC, Aboullos commented on cypress/support/pages/CommonPage.ts
> +  form() {
```suggestion
  formUtils() {
```
Maybe it would be better to rename it, with `form` it seems like you can have the form as an object and get the required actions to fill data in a specific form, instead of just using the typical save, cancel buttons on one

2022-03-29 14:11 UTC, Aboullos commented on cypress/support/pages/CommonPage.ts
> +  tab() {
```suggestion
  tabUtils() {
```
Same as in form()

2022-03-29 14:11 UTC, Aboullos commented on cypress/support/pages/CommonPage.ts
> +    this.modalPage = new ModalUtils();
```suggestion
    this.modalUtils = new ModalUtils();
```

2022-03-29 14:11 UTC, Aboullos commented on cypress/support/pages/CommonPage.ts
> +    this.tabPage = new TabPage();
```suggestion
    this.tabUtils = new TabUtils();
```

2022-03-29 14:11 UTC, Aboullos commented on cypress/support/pages/CommonPage.ts
> +    this.emptyStatePage = new EmptyStatePage();
```suggestion
    this.actionToolbarUtils = new ActionToolbarUtils();
    this.tableUtils = new TableUtils();
    this.tableToolbarUtils = new TableToolbarUtils();
```
They are not an actual page representing a screen, but a class with utilities for a generalization of an element

2022-03-29 14:11 UTC, Aboullos commented on cypress/support/util/ModalUtils.ts
> +    this.tablePage = new TablePage(TablePage.tableSelector);
Could be initialized in the variable declaration

2022-03-31 10:05 UTC, ikhomyn commented on cypress/integration/client_authorization_test.spec.ts
>  describe.skip("Client authentication subtab", () => {
Sure, I will remove skip

2022-03-31 10:05 UTC, ikhomyn commented on cypress/support/pages/CommonElements.ts
> +import { trim } from "lodash";
I'll change it. thanks

2022-03-31 10:07 UTC, ikhomyn commented on cypress/integration/clients_test.spec.ts
> +    //fails, issue
Yes, but it was closed, so what actually should I do with this one? https://github.com/keycloak/keycloak-admin-ui/issues/1874

2022-03-31 11:36 UTC, ikhomyn commented on cypress/support/pages/CommonElements.ts
> +  primaryBtn;
If I do this way, then I am unable to access those elements from children clases TablePage or FormPage

2022-04-01 10:27 UTC, Aboullos requested changes
A README or adding some information about the new structure of the added elements (CommonPage and the other components) in the best practices README would be good

2022-04-01 10:27 UTC, Aboullos commented on cypress/support/pages/CommonElements.ts
> +  primaryBtn;
But if you set the variables as protected you could access them from the children

2022-04-01 10:27 UTC, Aboullos commented on cypress/support/pages/CommonPage.ts
> +  private EmptyStatePage = new EmptyStatePage();
```suggestion
  private formUtils = new FormUtils();
  private modalUtils = new ModalUtils();
  private actionToolbarUtils = new ActionToolbarUtils();
  private tableUtils = new TableUtils();
  private tableToolbarUtils = new TableToolbarUtils();
  private emptyStatePage = new EmptyStatePage();
```

2022-04-01 10:27 UTC, Aboullos commented on cypress/support/pages/admin_console/components/TablePage.ts
> +  static tableSelector = "table[aria-label]";
Variables should be private or protected

2022-04-01 10:27 UTC, Aboullos commented on cypress/support/pages/admin_console/components/TableToolbarPage.ts
> +  public actionToggleBtn: string;
Variables should be private or protected

2022-04-01 10:27 UTC, Aboullos commented on cypress/support/pages/admin_console/manage/clients/ClientsPage.ts
> +  }
It this necessary?

2022-04-01 10:27 UTC, Aboullos commented on cypress/support/pages/admin_console/manage/clients/client_details/ClientDetailsPage.ts
> +  public advancedTab = new AdvancedTab();
Variables should be private or protected

2022-04-01 10:27 UTC, Aboullos commented on cypress/support/pages/admin_console/manage/clients/client_details/DedicatedScopesPage.ts
> +  public scopeTab = new DedicatedScopesScopeTab();
Variables should be private or protected

2022-04-01 10:27 UTC, Aboullos commented on cypress/support/pages/admin_console/manage/clients/client_details/tabs/AuthorizationTab.ts
> +  public exportSubTab = new ExportTab();
Variables should be private or protected

2022-04-01 10:27 UTC, Aboullos commented on cypress/support/pages/admin_console/manage/clients/client_details/tabs/ClientScopesTab.ts
> +  public dedicatedScopesPage = new DedicatedScopesPage();
Variables should be private or protected

2022-04-01 10:28 UTC, Aboullos commented on cypress/support/util/ModalUtils.ts
> +    this.tablePage = new TablePage(TablePage.tableSelector);
```suggestion
  private tablePage: TablePage = new TablePage(TablePage.tableSelector);

  constructor() {
    super(".pf-c-modal-box");
```

2022-04-04 10:46 UTC, Aboullos requested changes

2022-04-04 10:46 UTC, Aboullos commented on cypress/support/pages/admin_console/components/TablePage.ts
> +  }
The parameter appendChildren doesn't look very intuitive to use nor the method have a description on how it works

2022-04-05 12:07 UTC, agagancarczyk commented
hi @ikhomyn in the addition to the above, I run the tests in this PR locally and noticed that tests in client_authorization_test.spec.ts and users_test.spec.ts are falling.

![Screenshot 2022-04-05 at 13 06 23](https://user-images.githubusercontent.com/4890675/161750294-560637fd-7fe0-4326-ac31-70f61b37d74b.png)

2022-04-06 09:30 UTC, jonkoops commented on cypress/integration/clients_test.spec.ts
> +    //fails, issue
Perhaps you create a new one and log this code specifically?

2022-04-06 09:32 UTC, jonkoops commented
@ikhomyn could you rebase your PR on `main` and resolve the conflicts?

2022-04-06 09:39 UTC, jonkoops approved these changes
Changes look good to me, let's see if we can get the tests to pass after a rebase.

2022-04-11 07:49 UTC, Aboullos approved these changes
Looks good to me, but some explanation about the new structure in the README would be good

2022-04-19 12:25 UTC, merged