fixes empty key value convert
keycloak/keycloak-admin-ui pull request #2370
Opened 2022-03-29 15:48 UTC by edewit

Empty attributes `attributes: [{ key: "", value: "" }]` where not detected as such, this fixes that

2022-03-29 15:54 UTC, jonkoops requested changes

2022-03-29 15:54 UTC, jonkoops commented on src/util.ts
> +        Object.prototype.hasOwnProperty.call(e, "value")
Instead of using `hasOwnProperty()` you can use [`Object.hasOwn()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/hasOwn), which is intended as a modern replacement.
```suggestion
        Object.hasOwn(e, "key") &&
        Object.hasOwn(e, "value")
```

2022-03-30 06:22 UTC, edewit commented on src/util.ts
> +        Object.prototype.hasOwnProperty.call(e, "value")
Okay didn't know about that... let's do that

2022-03-30 16:12 UTC, jonkoops approved these changes

2022-04-05 07:39 UTC, merged