Realm-settings -> User Profile -> Create/Edit Attribute tests
keycloak/keycloak-admin-ui pull request #2410
Opened 2022-04-08 09:41 UTC by agagancarczyk

## Motivation
Cypress tests for creating and editing attributes.

![Screenshot 2022-04-08 at 10 38 25](https://user-images.githubusercontent.com/4890675/162409947-88f76e69-ea20-47da-be73-eedf0706adc5.png)

## Verification Steps
1. Running realm_settings_user_profile_tab.spec.ts tests locally. 

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

2022-04-08 19:57 UTC, jonkoops requested changes

2022-04-08 19:57 UTC, jonkoops commented on src/realm-settings/user-profile/attribute/AttributeGeneralSettings.tsx
> +  nameInput?.focus();
This should be wrapped in a `useEffect()`

2022-04-11 09:58 UTC, jonkoops requested changes

2022-04-11 09:58 UTC, jonkoops commented on src/realm-settings/user-profile/attribute/AttributeGeneralSettings.tsx
> +  const nameInput = document.getElementById("kc-attribute-name");
Instead of using `getElementById()` you can use a `Ref` (see [React documentation](https://reactjs.org/docs/refs-and-the-dom.html#refs-and-function-components)).

2022-04-11 10:36 UTC, edewit commented on src/realm-settings/user-profile/attribute/AttributeGeneralSettings.tsx
> +  const nameInput = document.getElementById("kc-attribute-name");
why would you want to focus the name attribute? you could also solve it by adding the `autofocus` attirbute to the input field

2022-04-11 10:57 UTC, agagancarczyk commented on src/realm-settings/user-profile/attribute/AttributeGeneralSettings.tsx
> +  const nameInput = document.getElementById("kc-attribute-name");
thanks @edewit , just added a fix into AttributeInput so that the Annotations key input field doesn't focus on the page load.

2022-04-11 11:05 UTC, agagancarczyk commented on src/realm-settings/user-profile/attribute/AttributeGeneralSettings.tsx
> +  nameInput?.focus();
This isn't required anymore.

2022-04-11 11:11 UTC, jonkoops commented
Changes look good like this, let's see if the tests will pass.

2022-04-11 14:00 UTC, merged