User Federation: populate Kerberos required and cache settings data
keycloak/keycloak-admin-ui pull request #243
Opened 2020-12-01 17:06 UTC by mfrances17

## Motivation
Related JIRA issues:
https://issues.redhat.com/browse/APPDUX-655

Design spec:
https://marvelapp.com/prototype/ecjc94b/screen/72098368

## Brief Description
Fetches and displays settings data for a specific individual provider card that is clicked in the user federation card view. This PR does **not** cover save nor the showing/hiding of UI components based on selections. These will be handled in future PRs. This PR only covers pulling in the data and getting to the settings page from the cards.

## Verification Steps
1. Click a card in the user fed card view.
2. Verify that all settings match those that have been configured for that provider (presumably, the ones configured and saved in the old admin UI).
3. Change the values and verify that the changes are reflected in the new UI.

## Checklist:
- [x] Code has been tested locally by PR requester
- [x] User-visible strings are using the react-i18next framework (useTranslation)
- [x] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated
- [x] Formatting has been performed via prettier/eslint
- [ ] Type checking has been performed via 'yarn check-types'

## Additional Notes
Required settings:
![kerberos-req-settings](https://user-images.githubusercontent.com/39063664/100771949-016a7b80-33cd-11eb-941c-fcb73dd76ac9.png)

Cache settings:
![kerberos-cache-settings](https://user-images.githubusercontent.com/39063664/100771929-fc0d3100-33cc-11eb-965c-45e4a846761a.png)

2020-12-02 07:50 UTC, edewit requested changes

2020-12-02 07:50 UTC, edewit commented on src/components/bread-crumb/PageBreadCrumbs.tsx
> +                <Link to="/user-federation">User federation</Link>
Why did you need this? I was hoping we could keep this component very generic and not introduce page specific logic

2020-12-02 07:50 UTC, edewit commented on src/components/keycloak-card/KeycloakCard.tsx
> +    console.log(`Card ${title} was clicked!`);
you don't need this anymore right?

2020-12-02 07:50 UTC, edewit commented on src/user-federation/KerberosSettingsCache.tsx
> +    console.log(component);
can go?

2020-12-02 07:50 UTC, edewit commented on src/user-federation/KerberosSettingsRequired.tsx
> +      if (entry[0] === "config") {
I guess you did this to work around the problem that the react-form-hook wants to create object when the keys have a "." right? If that is the case I have created an util function that converts the dots to "_" (e.g. `convertToFormValues`) and then you can use the config object keys like `config.claim_name`

2020-12-02 12:51 UTC, mfrances17 commented on src/components/bread-crumb/PageBreadCrumbs.tsx
> +                <Link to="/user-federation">User federation</Link>
Because the API is component, not 'user federation'... so the breadcrumb would be > Component > which means nothing to end users.

2020-12-02 12:52 UTC, mfrances17 commented on src/components/keycloak-card/KeycloakCard.tsx
> +    console.log(`Card ${title} was clicked!`);
I was going to leave in the debugging statements until the Save and component display/hide logic was added, which I would assume would be next sprint.

2020-12-02 13:25 UTC, edewit commented on src/components/bread-crumb/PageBreadCrumbs.tsx
> +                <Link to="/user-federation">User federation</Link>
so why put `/components/` in the path? Or am I missing something?

2020-12-02 13:25 UTC, edewit commented on src/components/keycloak-card/KeycloakCard.tsx
> +    console.log(`Card ${title} was clicked!`);
okay

2020-12-02 13:39 UTC, mfrances17 commented on src/components/bread-crumb/PageBreadCrumbs.tsx
> +                <Link to="/user-federation">User federation</Link>
The breadcrumb is supposed to be > User federation > ... how else would this be achieved? Why is this a problem?

2020-12-02 13:40 UTC, mfrances17 commented on src/user-federation/KerberosSettingsRequired.tsx
> +      if (entry[0] === "config") {
Is that solution any better than this one?

2020-12-02 15:41 UTC, jenny-s51 requested changes
This is looking great @mfrances17 ! 👍 Fields are populating as expected. Would be awesome if we could make the cards selectable before merging (see comment below).

2020-12-02 15:41 UTC, jenny-s51 commented on src/components/keycloak-card/KeycloakCard.tsx
>      <Card>
When I tested this, I initially tried to click on the console display name (kerberos, ldap) to get to the settings, which didn't take me there. Instead had to click on the center of the card. I think it might make sense to make these cards selectable/hoverable and pass in an `onClick` as it's done here to make it clearer for the user: https://www.patternfly.org/v4/components/card#selectable-and-selected

2020-12-03 08:16 UTC, edewit commented on src/components/bread-crumb/PageBreadCrumbs.tsx
> +                <Link to="/user-federation">User federation</Link>
right so we can just remove `/componnents` in the route-config right?

2020-12-03 19:37 UTC, mfrances17 commented on src/components/bread-crumb/PageBreadCrumbs.tsx
> +                <Link to="/user-federation">User federation</Link>
i don't think so, no. this is the route-config:
```
  {
    path: "/components/:id",
    component: UserFederationKerberosSettings,
    breadcrumb: t("common:settings"),
    access: "view-realm",
  },

```
you can't change it to /user-federation/:id, because that URI doesn't exist. the rest call needs to be /components/:id. unless I am totally missing something?

2020-12-03 19:39 UTC, mfrances17 commented on src/components/bread-crumb/PageBreadCrumbs.tsx
> +                <Link to="/user-federation">User federation</Link>
it does need to change, though... clicking 'components' in the breadcrumb will fail but id will pass. so i'll try to figure this out.

2020-12-03 20:05 UTC, mfrances17 commented on src/components/keycloak-card/KeycloakCard.tsx
>      <Card>
Thanks, I originally had attempted to do something similar but any click on the card kept sending it to details, including a menu click which is obviously not what we want. So I'll need to take another look.

2020-12-04 07:00 UTC, edewit commented on src/components/bread-crumb/PageBreadCrumbs.tsx
> +                <Link to="/user-federation">User federation</Link>
The `path` in the route config does not have to match the path in the backend call it can be anything. Here you configure the path that the browser uses and also the hierarchy of our breadcrumbs.

2020-12-04 08:34 UTC, edewit commented on src/components/bread-crumb/PageBreadCrumbs.tsx
> +                <Link to="/user-federation">User federation</Link>
I create a PR on you PR with the change that I mean

2020-12-04 14:17 UTC, srambach commented on src/user-federation/KerberosSettingsRequired.tsx
> +        // setValue("enabled", entry[1].enabled);
Enabled is a switch at the top in the header https://marvelapp.com/prototype/ecjc94b/screen/72098368
I don't know about priority. I just asked on the marvel.

2020-12-04 16:09 UTC, mfrances17 commented on src/components/bread-crumb/PageBreadCrumbs.tsx
> +                <Link to="/user-federation">User federation</Link>
This is perfect, thanks for the help @edewit. I'll make these changes. Feeling a bit stupid for not figuring that out.

2020-12-04 17:12 UTC, mfrances17 commented on src/user-federation/KerberosSettingsRequired.tsx
> +        // setValue("enabled", entry[1].enabled);
@srambach yes i saw it in the old UI but was wondering why it was left out of new UI, whether it was a design change or reason why you left it out

2020-12-04 22:07 UTC, mfrances17 commented on src/components/keycloak-card/KeycloakCard.tsx
>      <Card>
i've made the appropriate changes so the entire card can be clicked and the card menu still works as expected

2020-12-04 22:07 UTC, mfrances17 commented on src/components/bread-crumb/PageBreadCrumbs.tsx
> +                <Link to="/user-federation">User federation</Link>
changes are in the latest commit

2020-12-07 13:34 UTC, srambach commented on src/user-federation/KerberosSettingsRequired.tsx
> +        // setValue("enabled", entry[1].enabled);
@mfrances17 comments here from design; priority is intended to move to a different place but TBD whether it can in this iteration. Haley's going to ask at the Weds meeting. https://marvelapp.com/prototype/ecjc94b/screen/72098368/comment/55c7d99d-7e0a-477b-bdee-f975bc160272?

2020-12-07 17:35 UTC, mfrances17 commented on src/user-federation/KerberosSettingsRequired.tsx
> +      if (entry[0] === "config") {
Ah, I've got this working with your utility now. Will have an update soon.

2020-12-07 17:58 UTC, mfrances17 commented on src/user-federation/KerberosSettingsRequired.tsx
> +      if (entry[0] === "config") {
This is working with the utility in the latest version

2020-12-07 18:04 UTC, edewit commented on src/components/bread-crumb/PageBreadCrumbs.tsx
> +              <Link to={match.url}>{crumb}</Link>
This is my fault, sorry, but we don't need any change to the `PageBreadCrumb` right. I might have incorrectly reverted the change

2020-12-07 18:14 UTC, jenny-s51 approved these changes
Nice work @mfrances17 ! Card view looks great.

2020-12-07 18:16 UTC, mfrances17 commented on src/components/bread-crumb/PageBreadCrumbs.tsx
> +              <Link to={match.url}>{crumb}</Link>
@edewit no worries, yeah we wound up not needing any changes to breadcrumb. i reverted it back to what it was originally in the latest commit.

2020-12-08 06:30 UTC, edewit approved these changes

2020-12-08 06:30 UTC, merged