now also removes the already added validators after closing the dialog
keycloak/keycloak-admin-ui pull request #2435
Opened 2022-04-11 11:25 UTC by edewit

Used to only remove the validators as long as the dialog stayed open
now also removes the already installed validators when the dialog
is opened again.

fixes: #2397

2022-04-11 14:16 UTC, agagancarczyk approved these changes

2022-04-11 17:25 UTC, jonkoops requested changes

2022-04-11 17:25 UTC, jonkoops commented on src/realm-settings/user-profile/attribute/AddValidatorDialog.tsx
> +  const [validators, setValidators] = useState(
If you use a callback here the initial state will only be computed once instead of every render.

2022-04-13 13:18 UTC, jonkoops approved these changes

2022-04-13 13:18 UTC, merged