wip: realm_test fix/improvement attempt
keycloak/keycloak-admin-ui pull request #2446
Opened 2022-04-12 15:11 UTC by agagancarczyk

## Motivation
An attempt at fixing/improving the "should create Test Disabled realm" test detected by Cypress Dashboard as flaky.

realm_test suit is passing locally:

![Screenshot 2022-04-12 at 15 57 27](https://user-images.githubusercontent.com/4890675/162994644-a144dfa6-af4e-4e54-b1ce-d76c63d027f3.png)

## Verification Steps
1. Run tests in `realm_test.spec.ts` locally.

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

2022-04-12 16:08 UTC, jonkoops requested changes
Changes look good, but it looks like the test still fails.

2022-04-12 16:08 UTC, jonkoops commented on cypress/support/pages/admin_console/CreateRealmPage.ts
> -  private browseBtn = "#kc-realm-filename-browse-button";
Nice cleanup!

2022-04-13 09:24 UTC, edewit commented on cypress/integration/realm_test.spec.ts
> +      sidebarPage.waitForPageLoad();
`goToCreateRealm` already does a `waitForPageLoad`

2022-04-13 09:28 UTC, agagancarczyk commented on cypress/integration/realm_test.spec.ts
> +      sidebarPage.waitForPageLoad();
thanks @edewit it seems to be needed. Would you recommend using something else here in the form of waiting?

2022-04-13 11:06 UTC, jonkoops approved these changes
Changes look good to me.

2022-04-13 12:16 UTC, edewit commented on cypress/integration/realm_test.spec.ts
> +      sidebarPage.waitForPageLoad();
ahh okay I see... there are 2 loading spinners... no, it's fine like this

2022-04-13 12:16 UTC, merged