fixed error when data not found
keycloak/keycloak-admin-ui pull request #2449
Opened 2022-04-13 14:40 UTC by edewit

fixes: #2447

2022-04-13 14:45 UTC, jonkoops requested changes

2022-04-13 14:45 UTC, jonkoops commented on src/clients/authorization/KeyBasedAttributeInput.tsx
> +    { key: string; name: string }[] | undefined
Can we split this into a separate type?

2022-04-13 14:45 UTC, jonkoops commented on src/clients/authorization/KeyBasedAttributeInput.tsx
> +  const [attributeValues, setAttributeValues] = useState<
Since this value is derived it can be a `useMemo()` instead of a `useState()`.

2022-04-19 10:51 UTC, jonkoops approved these changes

2022-04-20 19:10 UTC, merged

2022-04-20 19:11 UTC, ssilvert commented
Partial import test didn't pass, but I know this is not a regression.  So I merged.