TextArea is child of controller
keycloak/keycloak-admin-ui pull request #245
Opened 2020-12-04 09:52 UTC by edewit

fixes: #230

## Motivation

## Brief Description

prevents warning in console

## Verification Steps

Go to any page that has a TextArea component like the new realm role page or the role detail page

## Checklist:

- [x] Code has been tested locally by PR requester
- [NA] User-visible strings are using the react-i18next framework (useTranslation)
- [NA] Help has been implemented
- [NA] axe report has been run and resulting a11y issues have been resolved
- [NA] Unit tests have been created/updated
- [x] Formatting has been performed via prettier/eslint
- [x] Type checking has been performed via 'yarn check-types'

## Additional Notes

2020-12-08 19:20 UTC, mfrances17 requested changes
When I run this code, I still get the same isDisabled prop missing warning for textArea. I tested it with role details. Possibly important to note that this warning only appears the first time the role details is opened - on subsequent loads the warning does not appear.

2020-12-09 06:54 UTC, edewit commented
oops yeah I see, fixed it now

2020-12-09 14:35 UTC, mfrances17 commented
Strange... I do see it is fixed for realm details, I'm no longer getting the error. But when I access Client details, textArea is throwing the same isDisabled missing error (only on first instance, as was the case for realm details).

2020-12-10 07:32 UTC, edewit commented
@mfrances17 okay now I really really fixed it

2020-12-10 14:10 UTC, mfrances17 approved these changes
LGTM, could no longer get the error anywhere in my testing. Great job.

2020-12-10 14:10 UTC, merged