Fine-grained permissions for user section.
keycloak/keycloak-admin-ui pull request #2451
Opened 2022-04-13 23:42 UTC by ssilvert

## Motivation
This implements fine-grained permissions for the user section only.

Implements part of https://github.com/keycloak/keycloak-admin-ui/issues/2403

## Brief Description
This is a fairly simple approach.  In some cases we could do better with how we present a restricted screen to the user.  But overall it's on par with the implementation in the old UI.  So I think this approach is good for a first pass and we can improve it later.  Higher priority is to get all of FGP implemented and then create an FGP test suite.

## Verification Steps
Since the [fine-grained permissions configuration screens](https://github.com/keycloak/keycloak-admin-ui/issues/2402) are not implemented in the new UI yet, verification requires going to the old UI.  You can follow the [examples in the documentation](https://www.keycloak.org/docs/latest/server_admin/#_fine_grain_permissions).

You can also see the access object that is returned in the user record when a user is queried.  It looks something like this:
`"access":{"manageGroupMembership":false,"view":true,"mapRoles":true,"impersonate":true,"manage":false}`

This will give hints as to what the user should be allowed to do in the UI.  Note that sometimes you also need the proper roles to be set on the realm-management client.

Lastly, make sure your permissions are set on a test realm.  The user restricted by the fine-grained access should log in to the test realm.  Using snowpack, you will need to go to that realm like this localhost:8080/?realm=test

2022-04-19 09:43 UTC, jonkoops approved these changes

2022-04-20 06:16 UTC, edewit commented
If we need the user for these fine grained permissions, I think it would be better to put it on the context instead of passing it in. WDYT?

2022-04-20 09:52 UTC, jonkoops commented
I agree with @edewit, can we get that change in @ssilvert?

2022-04-20 12:41 UTC, ssilvert commented
> If we need the user for these fine grained permissions, I think it would be better to put it on the context instead of passing it in. WDYT?

@edewit I'm not sure what you are referring to.  I never needed to pass the user around as it was already available.

Also, it's been 7 days so it is time to merge.  Perhaps we merge and then you submit a PR with desired refactoring?

2022-04-20 12:52 UTC, edewit requested changes

2022-04-20 12:52 UTC, edewit commented on src/components/attribute-form/AttributeForm.tsx
> +  fineGrainedAccess,
Instead of passing this in it would be better to have a context for User or extend the `whoAmI` context with the `fineGrainedAccess`

2022-04-20 19:01 UTC, ssilvert commented on src/components/attribute-form/AttributeForm.tsx
> +  fineGrainedAccess,
It wouldn't make sense to put this in the whoAmI.  Whenever you query for users or clients or whatever, Keycloak puts the access object on that entity (See verification steps above).   The access object says, "The user who made the request has this access to this user/client/group/etc."  The access granted can be different for each entity.  So I might have full manage access for this client but only view access for another client.  The UI needs to look inside the client object to see the access and set the UI accordingly.  You won't know until after you do the query, so it can't go into the whoAmI.

So for this PR, we are looking at managing users.  But AttributeForm shouldn't know anything about users.  It only knows about attributes and whether or not it should display as read-only.  So we pass in fineGrainedAccess to govern that.

2022-04-21 08:21 UTC, edewit approved these changes

2022-04-21 15:03 UTC, merged