Realm role attributes
keycloak/keycloak-admin-ui pull request #247
Opened 2020-12-04 20:56 UTC by jenny-s51

## Motivation

Towards https://issues.redhat.com/browse/APPDUX-679

## Brief Description

## Verification Steps

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated
- [ ] Formatting has been performed via prettier/eslint
- [ ] Type checking has been performed via 'yarn check-types'

## Additional Notes

2020-12-08 20:23 UTC, jenny-s51 commented on src/realm-roles/RoleAttributes.tsx
> +            <Tr className="labels">
@srambach it looks like there's a bit more space than there should be between the labels and the input fields... do you think there is a good CSS fix to remedy this?

2020-12-11 07:16 UTC, edewit requested changes
Why do we need `src/realm-roles/RealmRoleDetails.tsx`? I thought we changed the `RealmRoleForm.tsx` so that we could use one page in both cases? Now you introduce this page and we have 2 again.

2020-12-11 14:01 UTC, srambach commented on src/realm-roles/RealmRolesSection.css
> +  --pf-c-table--BorderColor: transparent;
You can remove the BorderColor and instead use
  --pf-c-table--border-width--base: 0;

That gets rid of one extra pixel between the header and body of the table.

2020-12-11 14:02 UTC, srambach commented on src/realm-roles/RoleAttributes.tsx
> +            <Tr className="labels">
I left a comment on the css file - There was just one pixel in the transparent border of the table. There's nothing else there, so I think it's just the line height making it appear that there's more.

2020-12-11 14:33 UTC, srambach commented on src/realm-roles/RoleAttributes.tsx
> +        <PlusCircleIcon />
These should have aria labels. (You'll need to i118n the text for the button) Also, should the ids be prefixed with kc? I'm not sure of our coding convention here. I'd personally make them more descriptive to include "label" since those are identifying the labels, not the actual keys and values.
      <TextInput aria-labelledby="key" />,
      <TextInput aria-labelledby="value" />,
      <Button
        id="plus-icon"
        .......
        aria-label="Add an attribute"
      >

2020-12-14 08:08 UTC, edewit commented
@jenny-s51 seems like adding of the file is due to a bad rebase? would it make sense to create a new PR for this?

2020-12-15 07:21 UTC, edewit approved these changes

2020-12-15 07:21 UTC, merged