added user permission tab
keycloak/keycloak-admin-ui pull request #2501
Opened 2022-04-25 10:37 UTC by edewit

added permission tab to users and made it more look like [the design](https://marvelapp.com/prototype/6gd34hh/screen/86305765)

2022-04-25 11:07 UTC, jonkoops requested changes

2022-04-25 11:07 UTC, jonkoops commented on src/components/permission-tab/PermissionTab.tsx
> +              }) as unknown as ManagementPermissionReference;
Is this type missing in the admin client? If so, can we fix this type there first?

2022-04-25 11:07 UTC, jonkoops commented on src/components/permission-tab/PermissionTab.tsx
> +        }) as unknown as ManagementPermissionReference;
Is this type missing in the admin client? If so, can we fix this type there first?

2022-04-25 11:07 UTC, jonkoops commented on src/components/permission-tab/PermissionTab.tsx
> +  const togglePermissionEnabled = (enabled: boolean) => {
Perhaps instead of kind of duplicating this logic here you could add an `enabled` state that could be a dependency of the `useFetch()`. That way it could automatically refresh the data when this dependency changes.

2022-04-25 11:07 UTC, jonkoops commented on src/components/permission-tab/PermissionTab.tsx
> +                    )
Starting to think we are using this pattern often enough to justify putting it in it's own hook, but perhaps out of scope for this PR.

2022-04-25 11:45 UTC, edewit commented on src/components/permission-tab/PermissionTab.tsx
> +              }) as unknown as ManagementPermissionReference;
there is already a PR that addresses this: https://github.com/keycloak/keycloak-nodejs-admin-client/pull/463

2022-04-25 11:48 UTC, edewit commented on src/components/permission-tab/PermissionTab.tsx
> +  const togglePermissionEnabled = (enabled: boolean) => {
what do you mean with duplicating logic in `useFetch` it fetches and here it updates

2022-04-26 09:44 UTC, jonkoops commented on src/components/permission-tab/PermissionTab.tsx
> +  const togglePermissionEnabled = (enabled: boolean) => {
Ahhh, yes. I missed that one.

2022-04-26 09:45 UTC, jonkoops approved these changes

2022-04-26 10:11 UTC, merged