convert single array values to values
keycloak/keycloak-admin-ui pull request #2506
Opened 2022-04-26 10:40 UTC by edewit

fixes: #2381

2022-04-26 11:11 UTC, jonkoops requested changes

2022-04-26 11:11 UTC, jonkoops commented on src/util.test.ts
> +    });
I think this test could be simplified a bit by only testing the contract of the `setValue` callback.
```suggestion
    const given = {
      config: { group: ["one"], another: { nested: ["value"] } },
    };
    const setValue = jest.fn();

    //when
    convertToFormValues(given, setValue);

    //then
    expect(setValue).toHaveBeenCalledWith("config", {
      group: "one",
      another: { nested: "value" },
    });
```

2022-04-26 11:11 UTC, jonkoops commented on src/util.ts
> +      if (!isEmpty(value)) {
This function is getting quite complex and nested, perhaps it could be optimized?

2022-04-26 11:23 UTC, edewit commented on src/util.ts
> +      if (!isEmpty(value)) {
We could change the backend to not give back different values, sometimes arrays are use with only one element and sometimes it's a string

2022-04-27 15:32 UTC, jonkoops approved these changes

2022-04-27 15:32 UTC, merged