no spinner when no have rights for realm load
keycloak/keycloak-admin-ui pull request #2515
Opened 2022-04-27 08:05 UTC by edewit

fixes: #2504

2022-04-27 08:11 UTC, jonkoops approved these changes

2022-04-27 12:24 UTC, ssilvert approved these changes
Tested manually.  Looks good.

2022-04-27 12:29 UTC, ssilvert requested changes
Approved too soon.

With this code, if you have a federation provider, it does not prompt you to search for a user.

2022-04-27 15:18 UTC, edewit commented
Yes, how can it know you have user federation setup if you don't have rights to query the user federation?

2022-04-27 23:57 UTC, ssilvert commented
> Yes, how can it know you have user federation setup if you don't have rights to query the user federation?

The user federation still gets queried on the back end when you do a user query.  As long as you have "query-users" rights, it will query users in the user federation.  

The problem is that you don't have access to the component that is letting you find out if a federated provider exists or not unless you have "view-realm" access.

That's why I suggested that when you don't have "view-realm" rights we can just fall back to the behavior where we tell the user to do a search.

2022-04-28 08:45 UTC, jonkoops approved these changes

2022-04-28 18:33 UTC, ssilvert commented on public/resources/en/users.json
> +  "searchForUserDescription": "This realm has a federated provider. Viewing all users may cause the system to slow down, but it can be done by searching for \"*\". Please search for a user above.",
```suggestion
  "searchForUserDescription": "This realm may have a federated provider. Viewing all users may cause the system to slow down, but it can be done by searching for \"*\". Please search for a user above.",
```

2022-04-28 18:55 UTC, merged