Removed unused column
keycloak/keycloak-admin-ui pull request #2529
Opened 2022-04-29 07:04 UTC by edewit

fixes: #1758

2022-04-29 11:37 UTC, jonkoops approved these changes

2022-04-29 12:20 UTC, ssilvert requested changes
See my latest comment on the issue.  https://github.com/keycloak/keycloak-admin-ui/issues/1758

Another option might be to add italicized word Inherited in parens "(_Inherited_)" at the end of the name. WDYT?

2022-05-02 11:53 UTC, ssilvert approved these changes
LGTM

2022-05-02 13:59 UTC, jonkoops approved these changes

2022-05-02 14:50 UTC, merged