added search and operational info
keycloak/keycloak-admin-ui pull request #2530
Opened 2022-04-29 08:14 UTC by edewit

fixes: #2510

2022-04-29 11:36 UTC, jonkoops requested changes

2022-04-29 11:36 UTC, jonkoops commented on src/dashboard/ProviderInfo.tsx
> +                        <>
I believe this Fragment should have a key prop.

2022-04-29 11:36 UTC, jonkoops commented on src/dashboard/ProviderInfo.tsx
> +                          {operationalInfo && (
Under what circumstances would `operationalInfo` not be set? Is this type incorrect?

2022-04-30 13:34 UTC, edewit commented on src/dashboard/ProviderInfo.tsx
> +                          {operationalInfo && (
Yes most of the time it's not set

2022-05-02 05:17 UTC, edewit commented on src/dashboard/ProviderInfo.tsx
> +                          {operationalInfo && (
fixed it in PR https://github.com/keycloak/keycloak-nodejs-admin-client/pull/470

2022-05-02 14:05 UTC, jonkoops requested changes

2022-05-02 14:25 UTC, jonkoops approved these changes

2022-05-02 14:30 UTC, merged