added tool tips on flow icons
keycloak/keycloak-admin-ui pull request #2573
Opened 2022-05-05 05:25 UTC by edewit

2022-05-05 07:46 UTC, jonkoops requested changes

2022-05-05 07:46 UTC, jonkoops commented on src/authentication/components/EditFlowDropdown.tsx
> +      <>
I think you can get rid of this fragment.

2022-05-06 06:11 UTC, edewit commented on src/authentication/components/EditFlowDropdown.tsx
> +      <>
No `Tooltip` can have only one child

2022-05-09 10:41 UTC, jonkoops commented on src/authentication/components/EditFlowDropdown.tsx
> +      <>
Oh, yeah that's a bug in PatternFly. Consider this resolved.

2022-05-09 10:41 UTC, jonkoops approved these changes

2022-05-09 10:41 UTC, merged