#11851 Use new parameter useRealmDefaultLocaleFallback when fetching the realm localization texts
keycloak/keycloak-admin-ui pull request #2577
Opened 2022-05-06 07:20 UTC by leischt

Relates to keycloak issue #11851

2022-05-06 08:21 UTC, jonkoops commented
Looks like https://github.com/keycloak/keycloak/pull/11852 will have to be merged first before this will start working.

2022-05-06 09:00 UTC, leischt commented
> Looks like [keycloak/keycloak#11852](https://github.com/keycloak/keycloak/pull/11852) will have to be merged first before this will start working.

Yes. I created this PR so that the new Admin UI is not forgotten when this change is done for all other UIs inside of the keycloak/keycloak repository.

2022-05-06 09:51 UTC, jonkoops requested changes

2022-05-06 09:51 UTC, jonkoops commented on src/i18n.ts
> +      return `/admin/realms/${adminClient.realmName}/localization/{{lng}?useRealmDefaultLocaleFallback=true}`;
```suggestion
      return `/admin/realms/${adminClient.realmName}/localization/{{lng}}?useRealmDefaultLocaleFallback=true`;
```

2022-05-06 10:06 UTC, edewit approved these changes

2022-06-10 18:38 UTC, ssilvert approved these changes
I merged the other PR.  LGTM.

2022-06-10 18:38 UTC, merged