User Federation: populate all LDAP settings
keycloak/keycloak-admin-ui pull request #261
Opened 2020-12-14 22:00 UTC by mfrances17

## Motivation
Related JIRA issues:
https://issues.redhat.com/browse/APPDUX-655

Design spec:
https://marvelapp.com/prototype/ecjc94b/screen/72098368

## Brief Description
Fetches and displays settings data for a specific individual LDAP provider card that is clicked in the user federation card view. 

This PR does not cover Save nor the showing/hiding of UI components based on selections. These will be handled in future PRs. This PR only covers pulling in the data and getting to the settings page from the cards.

## Verification Steps
1. Click an LDAP card in the user fed card view.
2. Verify that all settings match those that have been configured for that LDAP provider (presumably, the ones configured and saved in the old admin UI). There should be 7 sections: **General options**, **Connection and authentication settings**, **LDAP searching and updating**, **Synchronization settings**, **Kerberos integration**, **Cache settings**, and **Advanced settings**.
3. Change the values in the old admin UI and verify that the changes are reflected in the new UI.
4. Click a Kerberos card in the user fed card view.
5. Verify that the kerberos-specific settings are displayed (**Required settings** and **Cache settings**).

## Checklist:
- [x] Code has been tested locally by PR requester
- [x] User-visible strings are using the react-i18next framework (useTranslation)
- [x] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated
- [x] Formatting has been performed via prettier/eslint
- [ ] Type checking has been performed via 'yarn check-types'

## Additional Notes
Screen caps:
![ldap-cards](https://user-images.githubusercontent.com/39063664/102140663-976ebf00-3e2d-11eb-88d6-dbbda60ad33e.png)

![ldap-settings-1](https://user-images.githubusercontent.com/39063664/102140669-9b9adc80-3e2d-11eb-882f-fb9815ce13e0.png)

![ldap-settings-2](https://user-images.githubusercontent.com/39063664/102140674-9dfd3680-3e2d-11eb-8927-a428dccd8d07.png)

![ldap-settings-3](https://user-images.githubusercontent.com/39063664/102140681-a0f82700-3e2d-11eb-84f2-582a0aaac77e.png)

![ldap-settings-4](https://user-images.githubusercontent.com/39063664/102140692-a35a8100-3e2d-11eb-8476-05801cef7fb1.png)

2020-12-15 08:02 UTC, edewit requested changes
Very nice PR

2020-12-15 08:02 UTC, edewit commented on src/user-federation/ldap/LdapSettingsSearching.tsx
> +        return "One Level";
doesn't this need translation as well?

2020-12-15 08:02 UTC, edewit commented on src/route-config.ts
> +export const routes: RoutesFn = (t: any) => [
don't think this change is needed right?

2020-12-15 14:22 UTC, mfrances17 commented on src/route-config.ts
> +export const routes: RoutesFn = (t: any) => [
@edewit this was needed because i wanted to be able to pass null, otherwise it would fail

2020-12-15 14:25 UTC, mfrances17 commented on src/user-federation/ldap/LdapSettingsConnection.tsx
> +                <SelectOption key={0} value="Always" />
good catch, ty... updated in latest commit

2020-12-15 14:25 UTC, mfrances17 commented on src/user-federation/ldap/LdapSettingsSearching.tsx
> +        return "One Level";
yes, definitely... updated in latest commit

2020-12-16 07:02 UTC, edewit approved these changes

2020-12-16 07:02 UTC, edewit commented on src/route-config.ts
> +export const routes: RoutesFn = (t: any) => [
why not be more precise and make it:  
```suggestion
export const routes: RoutesFn = (t: TFunction|null) => [
```

2020-12-16 07:02 UTC, merged