Fix role-based authorization in Clients section.
keycloak/keycloak-admin-ui pull request #2632
Opened 2022-05-12 19:48 UTC by ssilvert

## Motivation
The PR fixes role-based authorization in the Clients section by hiding components or making them read-only as needed.

## Brief Description
This is in preparation for implementing fine-grained authorization, where flags such as `isManager` will also include a check for fine-grained authorization.

## Verification Steps
To verify the PR, it is best to log into a test realm with a test user.  Then set limited client roles for that user on the realm-management client.

To see the Clients section the user should have "view-clients" and "query-clients" roles.
To see the Permissions tab, the user also needs "manage-authorization" role.
To see Keys and Credentials tabs, the client needs to have `Client authentication` enabled.
To see Authorization tab, the client needs to have `Authorization` enabled.
To see Service account roles tab, the client needs to have `Service account roles` enabled.

2022-05-13 09:38 UTC, jonkoops requested changes

2022-05-13 09:38 UTC, jonkoops commented on src/clients/authorization/Settings.tsx
> +          isActive={true}
For boolean props that are true the value can be omitted.
```suggestion
          isActive
```

2022-05-13 09:38 UTC, jonkoops commented on src/components/role-mapping/RoleMapping.tsx
> +                  onRowClick: async (role) => {
There is nothing asynchronous happening here, so I believe you can omit the `async` keyword.
```suggestion
                  onRowClick: (role) => {
```

2022-05-15 01:16 UTC, ssilvert commented on src/components/role-mapping/RoleMapping.tsx
> +                  onRowClick: async (role) => {
That was not my code, but I think whoever wrote it was correct.  When I remove the `async` I get `Type 'boolean' is not assignable to type 'void | Promise<boolean>`

2022-05-15 01:18 UTC, ssilvert commented on src/clients/authorization/Settings.tsx
> +          isActive={true}
fixed

2022-05-15 01:18 UTC, ssilvert commented on src/clients/ClientsSection.tsx
> +              toolbarItem={ToolbarItems()}
fixed

2022-05-17 07:51 UTC, jonkoops commented on src/components/role-mapping/RoleMapping.tsx
> +                  onRowClick: async (role) => {
Ah, yes. That's fine then.

2022-05-17 07:52 UTC, jonkoops approved these changes

2022-05-17 07:52 UTC, merged