Adds functionality to attributes tab of realm roles section
keycloak/keycloak-admin-ui pull request #264
Opened 2020-12-16 18:09 UTC by jenny-s51

## Motivation

https://issues.redhat.com/browse/APPDUX-563

## Brief Description

Adds functionality for realm role attributes tab. Can save key, value attribute pairs to server and these pairs remain visible in the UI. Can also delete key, value pairs from UI and server.

## Verification Steps

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated
- [ ] Formatting has been performed via prettier/eslint
- [ ] Type checking has been performed via 'yarn check-types'

## Additional Notes

2020-12-16 20:22 UTC, srambach commented on src/realm-roles/RoleAttributes.tsx
> +      <FormAccess role="anyone" isHorizontal onSubmit={form.handleSubmit(save)}>
If you remove `isHorizontal` then the ActionGroup buttons will be left justified. It's trying to move them over to align with the fields when the labels are on the left instead of above as they are here.

2020-12-17 20:59 UTC, mfrances17 requested changes
General testing comments... i was not able to save attributes from a newly created role. 

Also some styling issues, I don't think the tab body should allow selectable, it serves no purpose and makes it look too busy... i tend to disable that on tabs. 

You've got a couple of linting issues just need to run the formatter on those files.

Just noticed that this was a draft PR so will wait for save functionality to be working to continue review.

2021-01-05 07:43 UTC, edewit requested changes

2021-01-05 07:43 UTC, edewit commented on src/realm-roles/RoleAttributes.tsx
> +  const [isValueInputValid, setValueInputValid] = useState(
Isn't this a bit complicated?

2021-01-05 07:43 UTC, edewit commented on src/realm-roles/RoleAttributes.tsx
> +            isDisabled={!isKeyInputValid || !isValueInputValid}
Isn't `isValueInputValid` the same as `form.formState.isValid` for this to work though you have to pass `onChange` to the `useForm` hook like this:

```javascript
useForm({ mode: "onChange" })
```

2021-01-08 15:41 UTC, srambach commented on src/realm-roles/RealmRolesSection.css
> +    var(--pf-global--spacer--2xl)*-1); */
Are these comments still needed?

2021-01-08 15:43 UTC, jenny-s51 commented on src/realm-roles/RealmRolesSection.css
> +    var(--pf-global--spacer--2xl)*-1); */
nope! nice catch @srambach - removed

2021-01-08 15:48 UTC, srambach commented on src/realm-roles/RoleAttributes.tsx
> +                    </Button>
Since this button doesn't have text, it needs to either use aria-label or aria-labelledby. In this case, there really isn't another element to label it. Best would be to concatenate in the values you are deleting, so something like "Remove mykey with value myvalue"

Also, the id needs to be unique, so you will need to append rowIndex or something.

2021-01-08 15:49 UTC, srambach commented on src/realm-roles/RoleAttributes.tsx
> +                    id="kc-minus-button"
This id needs to be unique

2021-01-08 16:17 UTC, edewit commented on src/realm-roles/RoleAttributes.tsx
> +      <Form role="anyone" onSubmit={form.handleSubmit(save)}>
```suggestion
      <FormAccess role="anyone" onSubmit={form.handleSubmit(save)}>
```

2021-01-08 16:18 UTC, srambach commented on src/realm-roles/RoleAttributes.tsx
> +      <Form role="anyone" onSubmit={form.handleSubmit(save)}>
I think this needs to be `FormAccess`

2021-01-11 09:34 UTC, edewit submitted a review, later dismissed
Don't we need error labels on the key and value fields when they are not filled out?

2021-01-11 09:34 UTC, edewit commented on src/realm-roles/RealmRoleForm.tsx
> +        <Button variant="link" onClick={() => location.reload()}>
why not do a form reset here instead of reloading the entire application?

2021-01-11 09:34 UTC, edewit commented on src/realm-roles/RoleAttributes.tsx
> +          <Button variant="link" onClick={() => history.push(`${url}/roles`)}>
this gives a "Page not found" also here I would use reset function of the react-form-hook

2021-01-11 09:34 UTC, edewit commented on src/realm-roles/RoleAttributes.tsx
> +                        value: 1,
This can be removed right? `minLenght` of 1 is the same as `required: true`

2021-01-11 21:09 UTC, jenny-s51 commented on src/realm-roles/RealmRoleForm.tsx
> +        <Button variant="link" onClick={() => location.reload()}>
great idea - thank you! planning to address these as part of a separate issue

2021-01-11 21:09 UTC, jenny-s51 commented on src/realm-roles/RoleAttributes.tsx
> +          <Button variant="link" onClick={() => history.push(`${url}/roles`)}>
great idea - thank you! planning to address these as part of a separate issue

2021-01-11 21:29 UTC, jenny-s51 commented
> Don't we need error labels on the key and value fields when they are not filled out?

The "save" button is disabled when the key field is not filled out

2021-01-11 21:48 UTC, mfrances17 approved these changes

2021-01-11 21:49 UTC, mfrances17 commented
LGTM - this can be merged with the stipulation that the outstanding issues will be handled as separate issues

2021-01-11 21:49 UTC, merged