refresh and message on group delete
keycloak/keycloak-admin-ui pull request #270
Opened 2020-12-18 09:59 UTC by edewit

fixing: #129

2021-01-04 21:41 UTC, ssilvert requested changes

2021-01-04 21:41 UTC, ssilvert commented on src/groups/GroupsSection.tsx
> +      addAlert(t("groupsDeleted"), AlertVariant.success);
Should be `groupDeleted` instead of `groupsDeleted`.  Probably need a new message for singular delete?

2021-01-05 06:37 UTC, edewit commented on src/groups/GroupsSection.tsx
> +      addAlert(t("groupsDeleted"), AlertVariant.success);
good catch I have the message already just didn't use the right key here, fixed now

2021-01-05 19:56 UTC, ssilvert approved these changes

2021-01-05 19:56 UTC, merged