Add cypress framework
keycloak/keycloak-admin-ui pull request #271
Opened 2020-12-21 14:46 UTC by Aboullos

## Motivation
Cover testing

## Brief Description
Add testing framework and a few tests

## Verification Steps
1- Run KC and the new admin console
2- Go to the folder tests
3- Run yarn
4- Run `npx cypress open` to open Cypress interface, or `npx cypress run` to run the tests

## Checklist:

- [X ] Code has been tested locally by PR requester
- [ ] Formatting has been performed via prettier/eslint
- [ ] Type checking has been performed via 'yarn check-types'

2021-01-04 14:03 UTC, edewit requested changes

2021-01-04 14:04 UTC, edewit commented
@Aboullos would it be a good idea to put this into the github action as well?

2021-01-04 19:20 UTC, jenny-s51 requested changes
@Aboullos thank you for adding these changes - it's very exciting that we'll be using Cypress as our integration testing framework! 

After navigating to the `/test` directory, the Cypress interface opens on `npx cypress open` and I am able to run the tests. 

In Patternfly we just run `yarn start:cypress` from the root and the interface opens. Would be great if we could do something like `"start:cypress": "npx cypress open",` in the root package.json here as well! Is that possible @Aboullos ?

Also it looks like `client_scopes_test.spec.js` and `login_test.spec.js` currently are not passing

2021-01-04 21:54 UTC, ssilvert requested changes
@Aboullos I'm happy to see this.

Agree with @edewit that we need this to run as a GitHub action.  That is top priority and I don't want to merge until we have that working.

2021-01-04 21:54 UTC, ssilvert commented on tests/.gitignore
> +
Please remove this file and add what you need to the root .gitignore

We only want a .gitignore here if we need to override what is in the root.

Perhaps all you need is the Cypress stuff?

2021-01-04 21:54 UTC, ssilvert commented on tests/LICENSE
> +                                 Apache License
Please remove this file.  It already exists in the root.

2021-01-05 12:21 UTC, Aboullos commented on tests/README.md
> +npx cypress open
Done, will add it in the next commit squash

2021-01-05 12:22 UTC, Aboullos commented on tests/package.json
> +    "test": "echo \"Error: no test specified\" && exit 1"
Done, will add it in the next commit squash

2021-01-05 12:24 UTC, Aboullos commented
> @Aboullos thank you for adding these changes - it's very exciting that we'll be using Cypress as our integration testing framework!
> 
> After navigating to the `/test` directory, the Cypress interface opens on `npx cypress open` and I am able to run the tests.
> 
> In Patternfly we just run `yarn start:cypress` from the root and the interface opens. Would be great if we could do something like `"start:cypress": "npx cypress open",` in the root package.json here as well! Is that possible @Aboullos ?
> 
> Also it looks like `client_scopes_test.spec.js` and `login_test.spec.js` currently are not passing

The login test could be failing if there is no "admin" user with "admin" as password, the client_scope test is failing because the delete a client scope functionality was not working. I did the changes for the "start:cypress", will add it on the next commit.

2021-01-05 12:24 UTC, Aboullos commented on tests/LICENSE
> +                                 Apache License
Done, will add it in the next commit squash

2021-01-05 12:25 UTC, Aboullos commented on tests/.gitignore
> +
Done, will add it in the next commit squash

2021-01-05 12:25 UTC, Aboullos commented
Will check on the GitHub action

2021-01-05 18:55 UTC, ssilvert commented
@Aboullos FYI. You don't have to squash your commits on this project.  We just do "Squash and merge" when we merge the PR.

2021-01-11 18:53 UTC, ssilvert commented
@Aboullos Very glad to see this running with GitHub Action.  Please either fix or remove the failing test.  We can give this one extra day to merge but I don't want to wait any longer than Tuesday.

2021-01-12 07:51 UTC, edewit commented
@ssilvert the test is already fixed PR for it is open #276

2021-01-12 17:04 UTC, merged