added delete client scope functionality
keycloak/keycloak-admin-ui pull request #272
Opened 2021-01-04 14:48 UTC by edewit

2021-01-05 15:14 UTC, jenny-s51 requested changes
Nice work @edewit - the deletion functionality is working as expected! 

Wondering if we can modify the error message to match the same message that's shown under `Networks` in chrome dev tools.  

For example, when I try to delete one of the built-in scopes, this is the error message I get:
`Could not delete client scope: Error: Request failed with status code 400`

But when I look under `Networks`, I see:
`errorMessage: "Cannot remove client scope, it is currently in use"`

I think the latter message clarifies what's going on a bit better, and it might be a good idea to use that one in the alert instead... WDYT?

2021-01-06 12:01 UTC, edewit commented
@jenny-s51 for sure did that in a313116

2021-01-06 15:38 UTC, jenny-s51 approved these changes

2021-01-07 18:35 UTC, merged

2021-01-07 18:35 UTC, ssilvert approved these changes