renamed `useFetch` to `asyncStateFetch`
keycloak/keycloak-admin-ui pull request #277
Opened 2021-01-07 06:53 UTC by edewit

otherwise React will mistake it for a react hook and will complain.

## Motivation

Seems our webpack build in storybook does some more checks that the snowpack build does not. If a function starts with `use` react will check if it's used as a proper react hook. Our `useFetch` is not a react hook just a helper function, so renamed it to `asyncStateFetch`

## Verification Steps

Storybook build should work again

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated
- [ ] Formatting has been performed via prettier/eslint
- [ ] Type checking has been performed via 'yarn check-types'

## Additional Notes

2021-01-07 15:01 UTC, ssilvert requested changes

2021-01-07 15:01 UTC, ssilvert commented on src/context/auth/AdminClient.tsx
> +export function asyncStateFetch<T>(
Let's put some doc here so future developers will know when, how, and why to use it.

2021-01-07 15:16 UTC, srambach commented
Fixes the storybook build problem although the two user federation stories still give `Cannot read property 'includes' of undefined`

2021-01-08 14:48 UTC, srambach approved these changes
LGTM when @ssilvert is happy with documentation 👍

2021-01-11 18:56 UTC, ssilvert approved these changes

2021-01-11 18:56 UTC, merged