added groups to dropdown menu
keycloak/keycloak-admin-ui pull request #2780
Opened 2022-06-09 07:38 UTC by edewit

fixes: #2747

## Motivation

## Brief Description

## Verification Steps

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

## Additional Notes

2022-06-13 09:14 UTC, jonkoops requested changes

2022-06-13 09:14 UTC, jonkoops commented on src/realm-settings/NewAttributeSettings.tsx
> +    adminClient.users.getProfile,
Not a fan of this as it makes the contract between `useFetch` and it's callback implicit. This means that if the callback is changed to accept some parameters then they will automatically be passed, leading to possible undefined behavior.

```suggestion
    () => adminClient.users.getProfile(),
```

2022-06-13 09:14 UTC, jonkoops commented on src/realm-settings/user-profile/attribute/AttributeGeneralSettings.tsx
> +  useFetch(adminClient.users.getProfile, setConfig, []);
Again, not a fan of making this implicit.
```suggestion
  useFetch(() => adminClient.clientScopes.find(), setClientScopes, []);
  useFetch(() => adminClient.users.getProfile(), setConfig, []);
```

2022-06-13 09:15 UTC, jonkoops approved these changes

2022-06-13 11:10 UTC, merged

2022-06-14 09:09 UTC, edewit commented on src/realm-settings/user-profile/attribute/AttributeGeneralSettings.tsx
> +  useFetch(adminClient.users.getProfile, setConfig, []);
we do this everywhere though, if you feel strongly about we should agree on this and make a code style rule for it