new group tests
keycloak/keycloak-admin-ui pull request #2789
Opened 2022-06-10 10:20 UTC by ikhomyn

## Motivation
New group tests and refactor of existent ones.

## Checklist:

- [x] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [x] Unit tests have been created/updated

## Additional Notes

2022-06-13 10:12 UTC, jonkoops commented
@ikhomyn could you give this PR a rebase on `main`? There have been some changes due to the Cypress 10 upgrade so you might have to move some files.

2022-06-14 06:51 UTC, jonkoops requested changes
There is a merge conflict present

2022-06-14 12:15 UTC, jonkoops requested changes

2022-06-14 12:15 UTC, jonkoops commented on cypress/e2e/group_test.spec.ts
> +    console.log(users);
Stray console log statements.

2022-06-14 12:15 UTC, jonkoops commented on cypress/e2e/group_test.spec.ts
> +    });
You can return the Promise here instead of awaiting it.
```suggestion
    before(() => adminClient.createGroup(groupNameDeleteHeaderAction));
```

2022-06-14 12:15 UTC, jonkoops commented on cypress/e2e/group_test.spec.ts
> +        adminClient.addUserToGroup(users[i].id!, createdGroups[i % 3].id);
Perhaps this can be batched as well?

2022-06-14 12:15 UTC, jonkoops commented on cypress/e2e/group_test.spec.ts
> +        .asseertRowItemsEqualTo(1);
Small typo
```suggestion
        .assertRowItemsEqualTo(1);
```

2022-06-14 12:15 UTC, jonkoops commented on cypress/support/pages/admin_console/manage/groups/group_details/GroupDetailPage.ts
> +  /* clickAdd() {
Can we get rid of this commented out code?

2022-06-16 12:03 UTC, ikhomyn commented on cypress/e2e/group_test.spec.ts
> +      });
Hi @jonkoops, can you give an example on how approach this? thanks

2022-06-21 14:42 UTC, jonkoops commented on cypress/e2e/group_test.spec.ts
> +      });
Something like: 
```ts
const users = Promise.all(range(5).map((index) => async () => {
  const username = "user" + index;
  const user = await adminClient.createUser({
    username,
    enabled: true,
  });

  return { id: user.id, username };
}));
```

2022-06-27 08:47 UTC, jonkoops approved these changes

2022-06-27 08:47 UTC, merged