Fix error message and update and add tests
keycloak/keycloak-admin-ui pull request #2807
Opened 2022-06-14 08:57 UTC by Aboullos

Fix and add tests for error messages in user federation

2022-06-14 10:24 UTC, jonkoops requested changes

2022-06-14 10:24 UTC, jonkoops commented on cypress/e2e/user_fed_ldap_test.spec.ts
> +  it.only("Should create LDAP provider from empty state", () => {
```suggestion
  it("Should create LDAP provider from empty state", () => {
```

2022-06-14 10:24 UTC, jonkoops commented on cypress/e2e/user_fed_ldap_test.spec.ts
> +  it.only("Should update LDAP searching and updating settings and save", () => {
```suggestion
  it("Should update LDAP searching and updating settings and save", () => {
```

2022-06-14 10:24 UTC, jonkoops commented on cypress/e2e/user_fed_ldap_test.spec.ts
> +  it.only("Should delete LDAP provider using Settings view Action menu", () => {
```suggestion
  it("Should delete LDAP provider using Settings view Action menu", () => {
```

2022-06-14 10:37 UTC, Aboullos commented on cypress/e2e/user_fed_ldap_test.spec.ts
> +  it.only("Should create LDAP provider from empty state", () => {
Yes, this is just a draft to run those tests only, to check that there was a bug, now I already removed the only function

2022-06-20 14:04 UTC, ssilvert commented
@Aboullos My fix is now merged.  Please rebase and see if it fixes the failing test.

2022-06-20 14:07 UTC, Aboullos commented
> @Aboullos My fix is now merged. Please rebase and see if it fixes the failing test.

I was checking it locally, but I am getting the same error

2022-06-20 17:04 UTC, Aboullos commented
Looks like it is working @ssilvert

2022-06-21 11:50 UTC, jonkoops approved these changes

2022-06-21 11:53 UTC, edewit requested changes

2022-06-21 11:53 UTC, edewit commented on public/resources/en/user-federation.json
> +  "ldapErrorValidatePasswordPolicyAvailableForWritableOnly": "Validate Password Policy is applicable only with WRITABLE edit mode",
this is no longer needed right? this translation is done by keycloak

2022-06-21 11:53 UTC, edewit commented on src/components/alert/Alerts.tsx
> +        error: t(getErrorMessage(error)),
also this is not needed, it can't work like this as it's missing the namespace

2022-06-21 12:13 UTC, edewit approved these changes

2022-06-21 12:15 UTC, merged