Issue 2838
keycloak/keycloak-admin-ui pull request #2865
Opened 2022-06-22 11:15 UTC by agagancarczyk

## Motivation
Fixes for https://github.com/keycloak/keycloak-admin-ui/issues/2838

## Verifications
The following are showing all critical issues for the Users page (subtabs & dialogs) fixed.

1. Fixed
![Screenshot 2022-06-22 at 12 05 51](https://user-images.githubusercontent.com/4890675/175014580-aaf54869-16d9-49a0-bfce-96e67a1ee826.png)

2. Fixed
![Screenshot 2022-06-22 at 12 07 59](https://user-images.githubusercontent.com/4890675/175014808-412f670e-c42e-4197-9755-ee057a174c15.png)

3. Fixed
![Screenshot 2022-06-22 at 12 09 33](https://user-images.githubusercontent.com/4890675/175014978-b68f96fa-38f8-4fa2-ada1-8bf63526b8ec.png)

4. Fixed
![Screenshot 2022-06-22 at 12 05 51](https://user-images.githubusercontent.com/4890675/175014580-aaf54869-16d9-49a0-bfce-96e67a1ee826.png)

5. Fixed
![Screenshot 2022-06-22 at 12 10 42](https://user-images.githubusercontent.com/4890675/175015158-f1dc5001-b197-40fd-b9d3-35b5b65ff4ea.png)

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

2022-06-23 10:13 UTC, jonkoops requested changes

2022-06-23 10:13 UTC, jonkoops commented on src/components/group/GroupPickerDialog.tsx
> +                    aria-label="data-list-check"
This should be a human readable text.

2022-06-23 11:05 UTC, agagancarczyk commented on src/components/group/GroupPickerDialog.tsx
> +                    aria-label="data-list-check"
Thanks @jonkoops I have added more human-readable aria-label `aria-label={t("users:checkbox") + `${group.name}`}`, but this doc is suggesting we should use 'true', 'false' or 'mixed' https://dequeuniversity.com/rules/axe/4.4/aria-valid-attr-value?application=AxeChrome. Just wondering what you think? Thanks

2022-06-24 12:08 UTC, agagancarczyk commented on src/components/group/GroupPickerDialog.tsx
> +                    aria-label="data-list-check"
I have now tried using `aria-label={group.name}` again and it seems to be ok - not showing a critical issue anymore.

2022-06-27 08:45 UTC, merged