Critical accessibility fixes for Identity providers page - Issue #2847
keycloak/keycloak-admin-ui pull request #2871
Opened 2022-06-23 08:46 UTC by agagancarczyk

## Motivation
Fixes for https://github.com/keycloak/keycloak-admin-ui/issues/2847.

## Verifications
1. Fixed
![Screenshot 2022-06-22 at 16 42 47](https://user-images.githubusercontent.com/4890675/175074316-57ba56f4-7804-43bc-ac87-2a96882d503d.png)

2. Fixed
![Screenshot 2022-06-22 at 16 51 20](https://user-images.githubusercontent.com/4890675/175076179-d40ea3d5-2456-4ceb-ab7f-226915b9a0f7.png)

3 & 4. Fixed
![Screenshot 2022-06-22 at 17 11 48](https://user-images.githubusercontent.com/4890675/175081095-7a92a12f-768d-4a99-afa6-dbd7e43a92e8.png)

5. Fixed
- Bitbucket
![Screenshot 2022-06-22 at 17 17 36](https://user-images.githubusercontent.com/4890675/175082615-d5866019-ba79-4772-9d31-7ddbbbd8b8d0.png)

- Facebook
![Screenshot 2022-06-22 at 17 19 56](https://user-images.githubusercontent.com/4890675/175083275-9482724c-70e0-4e98-96ef-5d4ed0e8d573.png)

- Github
![Screenshot 2022-06-22 at 17 21 51](https://user-images.githubusercontent.com/4890675/175084003-8792782e-415a-4cb6-b3d3-754731274658.png)

- Gitlab
![Screenshot 2022-06-22 at 17 22 29](https://user-images.githubusercontent.com/4890675/175084186-2925a88e-4072-4a3d-9217-53638cb886c0.png)

- Google
![Screenshot 2022-06-22 at 17 23 01](https://user-images.githubusercontent.com/4890675/175084368-20320e07-7bd9-44d6-bfe1-7e82d7ae610a.png)

- Instagram
![Screenshot 2022-06-22 at 17 23 35](https://user-images.githubusercontent.com/4890675/175084567-2bb95b57-c6df-4923-8777-c970e5039278.png)

- Linkedin
![Screenshot 2022-06-22 at 17 24 07](https://user-images.githubusercontent.com/4890675/175084770-83d5ef01-307a-4c64-8050-07bac7b5cead.png)

- Mircrosoft
![Screenshot 2022-06-22 at 17 24 40](https://user-images.githubusercontent.com/4890675/175085057-a7db9f4d-dbaa-4e79-b115-8508045fd93d.png)

- Openshift-v3
![Screenshot 2022-06-22 at 17 25 40](https://user-images.githubusercontent.com/4890675/175085375-4e0f807f-6f95-47e5-ada0-14153cce4826.png)

- Openshift-v4
![Screenshot 2022-06-22 at 17 26 16](https://user-images.githubusercontent.com/4890675/175085599-33cc4364-0795-4ccf-9d46-3d7836f44319.png)

- Paypal
![Screenshot 2022-06-22 at 17 27 01](https://user-images.githubusercontent.com/4890675/175085865-a8e99920-73f1-4983-989f-7b6a7529583a.png)

- Stackoverflow
![Screenshot 2022-06-22 at 17 27 33](https://user-images.githubusercontent.com/4890675/175086065-a50a69f4-cd8f-4359-aed3-ba7039d5d9ea.png)

- Twitter
![Screenshot 2022-06-22 at 17 28 13](https://user-images.githubusercontent.com/4890675/175086314-97e2fe9c-5bbd-402b-8cdf-0cd02c86c10a.png)

6. Fixed
![Screenshot 2022-06-22 at 17 30 57](https://user-images.githubusercontent.com/4890675/175087462-88f774eb-069a-4e68-a714-6e6d980f8edd.png)

7. Fixed
![Screenshot 2022-06-23 at 09 43 35](https://user-images.githubusercontent.com/4890675/175256861-67391cce-910e-418c-be4d-fea06184a25a.png)

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

2022-06-23 09:18 UTC, edewit approved these changes

2022-06-23 09:32 UTC, jonkoops commented on src/identity-providers/add/DescriptorSettings.tsx
> +        fieldId="kc-service-provider-entityId"
Why change the casing of this string halfway through?

2022-06-23 09:32 UTC, jonkoops requested changes

2022-06-23 09:32 UTC, jonkoops commented on src/identity-providers/add/DescriptorSettings.tsx
> +        fieldId="kc-service-provider-entityId"
Why change the casing of this string halfway through?

2022-06-23 09:32 UTC, jonkoops commented on src/identity-providers/component/DisplayOrder.tsx
> +            aria-label={`value-${value}`}
This should be a human readable string.

2022-06-23 09:50 UTC, agagancarczyk commented on src/identity-providers/add/DescriptorSettings.tsx
> +        fieldId="kc-service-provider-entityId"
There is another instance of "kc-service-provider-entity-id" in SamlConnectSettings.tsx and AXE tool is complaining that ids should be unique. This is why I made this small change.

2022-06-23 09:58 UTC, agagancarczyk commented on src/identity-providers/component/DisplayOrder.tsx
> +            aria-label={`value-${value}`}
yes, that's correct @jonkoops . I tried to do my best to make it human-readable :). This is the numerical selector field. I cannot leave it just as a value. 

![Screenshot 2022-06-23 at 10 55 03](https://user-images.githubusercontent.com/4890675/175272754-76dbf5f2-64b5-42c6-8161-7278ceae9fd7.png)

I can change it to `aria-label={`selected-${value}`}`. Wdyt?

2022-06-23 10:09 UTC, jonkoops commented on src/identity-providers/component/DisplayOrder.tsx
> +            aria-label={`value-${value}`}
That seems strange to me as this is simply a numerical input. Perhaps this is just not associated with the label on the left somehow?

2022-06-24 15:13 UTC, agagancarczyk commented on src/identity-providers/add/DescriptorSettings.tsx
> +        fieldId="kc-service-provider-entityId"
@jonkoops I have now changed the `id`.

2022-06-27 08:43 UTC, jonkoops commented on src/identity-providers/add/DescriptorSettings.tsx
> +        fieldId="kc-service-provider-entityId"
Looks good :+1:

2022-06-27 08:44 UTC, jonkoops requested changes
Still some unaddressed review comments.

2022-06-27 14:45 UTC, agagancarczyk commented on src/identity-providers/component/DisplayOrder.tsx
> +            aria-label={`value-${value}`}
hi @jonkoops there was an issue with the id. I have fixed it now and we are critical-free. 
![Screenshot 2022-06-27 at 15 42 28](https://user-images.githubusercontent.com/4890675/175968604-f6fbe532-8b94-422d-89f7-9bbb494bfd53.png)

2022-06-27 14:53 UTC, jonkoops commented on src/identity-providers/component/DisplayOrder.tsx
> +            aria-label={value}
Why do we need this `aria-label` attribute? Since the input already contains a value it should be read automatically by a screen reader.

2022-06-27 15:05 UTC, agagancarczyk commented on src/identity-providers/component/DisplayOrder.tsx
> +            aria-label={value}
Good catch @jonkoops - Removed it.

2022-06-27 15:07 UTC, jonkoops approved these changes

2022-06-27 15:09 UTC, merged