Serious accessibility fixes for Home/Provider Info page #2839
keycloak/keycloak-admin-ui pull request #2899
Opened 2022-07-01 16:13 UTC by agagancarczyk

## Motivation
Fixes and closes https://github.com/keycloak/keycloak-admin-ui/issues/2839

Verification: 
![Screenshot 2022-07-01 at 17 08 40](https://user-images.githubusercontent.com/4890675/176931546-8e8e511e-748a-4d7f-8d30-9f2b0e724065.png)

## Verification Steps

1. Run axe scan for the `Provider info` tab on the Home page.

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

2022-07-04 14:07 UTC, jonkoops requested changes

2022-07-04 14:07 UTC, jonkoops commented on src/dashboard/ProviderInfo.tsx
> +                        {operationalInfo && (
Instead of having a conditional here you can instead filter the collection first so that all elements are always defined.

2022-07-05 10:29 UTC, agagancarczyk commented on src/dashboard/ProviderInfo.tsx
> +                      <Fragment key={key}>
Left unchanged as discusssed

2022-07-05 10:29 UTC, agagancarczyk commented on src/dashboard/ProviderInfo.tsx
> +                        {operationalInfo && (
Left unchanged as discusssed

2022-07-05 11:04 UTC, jonkoops approved these changes

2022-07-05 11:41 UTC, merged