refactored a little and fixed bug
keycloak/keycloak-admin-ui pull request #2918
Opened 2022-07-04 08:02 UTC by edewit

Closes #2895

2022-07-04 14:18 UTC, jonkoops requested changes

2022-07-05 05:45 UTC, edewit commented on src/components/users/UserSelect.tsx
> +              adminClient.users.findOne({ id }) as UserRepresentation
because `(UserRepresentation | undefined)[]` is not the same as `UserRepresentation[]` but it can't be that they are not found as you just picked them with this select component

2022-07-05 05:50 UTC, edewit commented on src/clients/authorization/AuthorizationEvaluate.tsx
> +    )) as PolicyEvaluationResponse;
fixed in: https://github.com/keycloak/keycloak-nodejs-admin-client/pull/509

2022-07-05 10:25 UTC, jonkoops requested changes

2022-07-05 10:25 UTC, jonkoops commented on prometheus.yml
> +# my global config
Why do we have this prometheus config?

2022-07-05 10:25 UTC, jonkoops commented on src/clients/authorization/AuthorizationEvaluate.tsx
> +    )) as PolicyEvaluationResponse;
Merged this one, can you pull in the new version and remove this assertion?

2022-07-05 11:00 UTC, edewit commented on prometheus.yml
> +# my global config
oops... i was trying something let me update

2022-07-06 10:30 UTC, jonkoops approved these changes

2022-07-06 10:30 UTC, merged