fix order dialogs
keycloak/keycloak-admin-ui pull request #2922
Opened 2022-07-05 07:09 UTC by edewit

in favour of #2896

## Motivation

## Brief Description

## Verification Steps

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

## Additional Notes

2022-07-05 10:14 UTC, jonkoops requested changes

2022-07-05 10:14 UTC, jonkoops commented on src/identity-providers/ManageOrderDialog.tsx
> +                    <span>{provider.alias}</span>
Do we still need this `span` element?
```suggestion
                    {provider.alias}
```

2022-07-05 10:14 UTC, jonkoops commented on src/user-federation/ManagePriorityDialog.tsx
> +                    <span>{component.name}</span>
```suggestion
                    {component.name}
```

2022-07-06 09:40 UTC, agagancarczyk approved these changes

2022-07-06 10:31 UTC, merged