made automatic removal of alerts more robust
keycloak/keycloak-admin-ui pull request #2955
Opened 2022-07-12 06:49 UTC by edewit

## Motivation

## Brief Description

## Verification Steps

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

## Additional Notes

2022-07-12 08:39 UTC, jonkoops requested changes

2022-07-12 08:39 UTC, jonkoops commented on src/components/alert/AlertPanel.tsx
> +  key: number;
It doesn't look like this prop is used anymore, perhaps it can be removed?
```suggestion
```

2022-07-12 08:39 UTC, jonkoops commented on src/components/alert/Alerts.tsx
> +        key: new Date().getTime(),
Can we call this something different than `key`? Since this is a timestamp of when the alert was created.

2022-07-12 08:39 UTC, jonkoops commented on src/components/alert/Alerts.tsx
> +    const interval = setInterval(() => clearAlerts(), 3000);
Why run a constant timer to check this if we can set a timeout in the `addAlert()` function? If you are looking to tie this into the component lifecycle we also have a [`useSetTimout()`](https://github.com/keycloak/keycloak-admin-ui/blob/main/src/utils/useSetTimeout.ts) utility.

2022-07-12 09:12 UTC, Aboullos approved these changes
Great solution to the notification problem!

2022-07-13 06:26 UTC, edewit commented on src/components/alert/Alerts.tsx
> +    const interval = setInterval(() => clearAlerts(), 3000);
I would if it would work, but it sometimes doesn't fire this way even if the trigger was missed it will remove the alert

2022-07-13 06:27 UTC, edewit commented on src/components/alert/Alerts.tsx
> +        key: new Date().getTime(),
renamed it to `created`

2022-07-13 10:12 UTC, jonkoops approved these changes

2022-07-13 10:17 UTC, merged