Changed button text from Delete to Revoke (Issue 1703)
keycloak/keycloak-admin-ui pull request #2982
Opened 2022-07-18 10:54 UTC by dominikkawka

## Motivation
Close #1703

## Brief Description
See #1703

## Verification Steps
1. You can enable the "Consent required" and "Display client on screen" in the settings page of the "security-admin-console-v2" client.
2. Then you can logout and login again.
3. You will find some consents in the User>Consent page.
4. After clicking the kebab menu, there will be an option list that includes "Revoke" option.

![image](https://user-images.githubusercontent.com/31955648/179496537-0c0f4bdc-3e8e-4d7b-8020-7b7f7882bbc8.png)

## Checklist:

- [x] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

## Additional Notes

2022-07-21 13:08 UTC, jonkoops requested changes

2022-07-21 13:08 UTC, jonkoops commented on src/user/UserConsents.tsx
> +    continueButtonLabel: "common:Revoke",
I believe this should start with a lower case.
```suggestion
    continueButtonLabel: "common:revoke",
```

2022-07-22 11:35 UTC, dominikkawka commented on src/user/UserConsents.tsx
> +    continueButtonLabel: "common:Revoke",
When I change it to lower case it appears as lower case in the button. revoke doesn't seem to be effected by "common"
I looked around for a few min to see if I could but wasn't able to do so. 

![image](https://user-images.githubusercontent.com/31955648/180430656-58610079-c0b8-4442-b83a-13802538a6d4.png)

2022-07-23 11:21 UTC, jonkoops commented on src/user/UserConsents.tsx
> +    continueButtonLabel: "common:Revoke",
I think this is because this key does not exist in any of the language bundles, so instead it defaults to the name of the key. You'll have to add a `revoke` entry to [`public/resources/en/common.json`](https://github.com/keycloak/keycloak-admin-ui/blob/main/public/resources/en/common.json).

2022-07-25 09:36 UTC, jonkoops approved these changes

2022-07-25 11:09 UTC, merged