add empty input field, make value not required
keycloak/keycloak-admin-ui pull request #300
Opened 2021-01-13 17:10 UTC by jenny-s51

## Motivation

#291 

## Brief Description

## Verification Steps

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated
- [ ] Formatting has been performed via prettier/eslint
- [ ] Type checking has been performed via 'yarn check-types'

## Additional Notes

2021-01-14 06:59 UTC, edewit requested changes

2021-01-14 06:59 UTC, edewit commented on src/realm-roles/RoleAttributes.tsx
> +          {
why the extra curly brackets and why only call `onAdd()` when the form is dirty? If I press the `-` and press save I don't need an extra new row? Also in this case I would do an if instead of the ternary operator

2021-01-14 06:59 UTC, edewit commented on src/realm-roles/RoleAttributes.tsx
>                      ref={form.register({
you can remove this completely:

```suggestion
ref={form.register()}
```

2021-01-14 14:34 UTC, jenny-s51 commented on src/realm-roles/RoleAttributes.tsx
> +          {
thank you for your feedback - will update accordingly

2021-01-19 10:14 UTC, edewit commented on src/realm-roles/RoleAttributes.tsx
> +  console.dir(form.formState.dirtyFields.attributes);
Is this meant for debugging?

2021-01-19 10:16 UTC, edewit requested changes
looks simple enough

2021-01-19 13:19 UTC, closed without merging