back to changing dots instead of unflatten
keycloak/keycloak-admin-ui pull request #3035
Opened 2022-08-03 07:35 UTC by edewit

fixes: #3022
and also fixes: https://github.com/keycloak/keycloak/issues/13416

2022-08-03 07:36 UTC, edewit commented
This fix might be better then https://github.com/keycloak/keycloak-admin-ui/pull/3023 @lexcao want to give it a try?

2022-08-03 10:06 UTC, jonkoops commented on src/util.test.ts
> +const TOKEN = "🍺";
Proost! :beers:

2022-08-03 15:12 UTC, lexcao commented
Hi, @edewit 
This fix makes sense to me.
It replaces all fields of the form.
Thank you!

2022-08-03 16:28 UTC, jonkoops requested changes

2022-08-03 16:28 UTC, jonkoops commented on src/identity-providers/add/AddMapper.tsx
> -    form.setValue("config.attributes", JSON.parse(mapper.config.attributes));
This should still be parsed, no?

2022-08-08 06:54 UTC, edewit commented on src/authentication/components/ExecutionConfigModal.tsx
> +    if (configDescription) setupForm(config);
I think this was a left over of a old implementation now the `configDescription` is used to in conjunction with the dynamic fields

2022-08-09 08:31 UTC, jonkoops approved these changes

2022-08-09 08:32 UTC, merged

2022-09-07 09:44 UTC, mortenjoenby commented
Hi.
This is a critical issue to us as we are supporting several hundred realms across several Keycloak cluster, which we have just upgraded to 19.0.1 ...!
When can we expect 19.0.2 to be released - assuming this will contain the fix?
Is it an option to run with the old Admin Console until then?

Thanks,
Morten