Enabled and Disable features incorrect
keycloak/keycloak-admin-ui pull request #3054
Opened 2022-08-04 11:50 UTC by mabartos

Fixes #1718

## Motivation

## Brief Description

## Verification Steps

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

## Additional Notes
Result screen
![Screenshot from 2022-08-04 12-00-12](https://user-images.githubusercontent.com/38039883/182824427-668e793a-ea25-48a6-9180-c9153f0fb0d1.png)

-------------------
@edewit @jonkoops Could you please take a look at it? It's only a template with the working solution for the bug, so feel free to add some commit with a cleaner approach or use some parts of this PR. Perhaps, it'd be good to create some separate utility for the feature states. WDYT? 

Thanks!

2022-08-04 12:02 UTC, mabartos commented
I've just noticed, that the collection of enabled features is already present in the `useIsFeatureEnabled` utility. It'd be probably suitable for this issue.

2022-08-04 12:53 UTC, edewit approved these changes

2022-08-04 15:21 UTC, jonkoops requested changes

2022-08-04 15:21 UTC, jonkoops commented on src/dashboard/Dashboard.tsx
> +                                  className="keycloak__features_list_item"
Instead of using custom styling to set the margin you can use the [PatternFly utility classes](https://www.patternfly.org/v4/utilities/spacing). These use a standardized set of spacing sizes.

2022-08-04 15:29 UTC, mabartos commented on src/dashboard/Dashboard.tsx
> +                                  className="keycloak__features_list_item"
Fixed

2022-08-08 08:03 UTC, mabartos commented
@jonkoops I've fixed the CSS. Could you please review it again, please? Thank you :)

2022-08-08 10:58 UTC, jonkoops approved these changes

2022-08-08 10:59 UTC, merged

2022-08-08 10:59 UTC, jonkoops commented
Thanks @mabartos!

2022-08-08 11:49 UTC, mabartos commented
@edewit @jonkoops Thanks!