Add Save/Cancel buttons and logic to Kerberos settings
keycloak/keycloak-admin-ui pull request #307
Opened 2021-01-15 20:47 UTC by mfrances17

## Motivation
https://issues.redhat.com/browse/APPDUX-721

## Brief Description
Adds the ability to save (or cancel) changes made to the User Federation Kerberos settings page.

## Verification Steps
1. Go to User federation and select a Kerberos card.
2. Change any of the values in the Required Settings or Cache Settings sections.
3. Click Save. You should see a success alert.
4. Verify that the changes have been saved by traversing anywhere else in the UI and then re-clicking the card to make sure the values that were changed are displayed correctly.

## Checklist:
- [x] Code has been tested locally by PR requester
- [x] User-visible strings are using the react-i18next framework (useTranslation)
- [x] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated
- [x] Formatting has been performed via prettier/eslint
- [ ] Type checking has been performed via 'yarn check-types'

## Additional Notes
Screen cap of successful save:
![kerberos-save-success](https://user-images.githubusercontent.com/39063664/104776853-b91ed700-5748-11eb-8f2d-f7f62da96e41.png)

2021-01-18 14:22 UTC, jenny-s51 approved these changes
LGTM @mfrances17 - tested in UI, working as expected!

2021-01-18 21:04 UTC, srambach commented
- If the user selects "Allow password authentication" but doesn't select an edit mode, they will get an error 500 with no other indication of the problem.
- Changing the cache policy to "select an option" yields an error 500 even though that field is not marked as required.
- I think the save button is not supposed to be active unless the form is "dirty" but is currently active when editing an existing entry without any changes.
- If I clear out the required text inputs, it still saves ok, and in fact I was able to save without a name, which causes an empty card back on the main user federation page.

2021-01-21 15:51 UTC, mfrances17 commented
> * If the user selects "Allow password authentication" but doesn't select an edit mode, they will get an error 500 with no other indication of the problem.
> * Changing the cache policy to "select an option" yields an error 500 even though that field is not marked as required.
> * Also if cache policy is set to evict but the resulting drop downs don't have values (and they are not marked as required), then you get an error 500.

All fields that are required, including those that are only visible if you select a certain option, are now marked as required. Also, I've removed all of the 'Select an option' dropdown selections as they are causing errors and the old admin UI did not do this. 

> * If I clear out the required text inputs, it still saves ok, and in fact I was able to save without a name, which causes an empty card back on the main user federation page.

Text fields that are empty will now show a field-level error on submit, and the form won't be saved.

> * I think the save button is not supposed to be active unless the form is "dirty" but is currently active when editing an existing entry without any changes.

No other forms are doing that in the new UI.

2021-01-22 07:01 UTC, edewit requested changes
Still get a 500 when switching from `DEFAULT` to `DAILY` and then hit save

2021-01-22 07:07 UTC, edewit commented on src/user-federation/kerberos/KerberosSettingsCache.tsx
>                defaultValue=""
either add a default value here or add a "select option" with empty and make it required with: `rules={{ required: true }}`

2021-01-22 15:19 UTC, mfrances17 commented on src/user-federation/kerberos/KerberosSettingsCache.tsx
>                defaultValue=""
good catch, i needed to add default values to those three fields since removing the choose string... working now

2021-01-22 18:43 UTC, ssilvert requested changes

2021-01-22 18:43 UTC, ssilvert commented on src/user-federation/kerberos/KerberosSettingsCache.tsx
> +    minuteOptions.push(<SelectOption key={index - 1} value={[`${index}`]} />);
In the dropdown, choices for eviction minute go from 1 to 60.  Look at old console.  It should be 00 to 59.

2021-01-22 18:43 UTC, ssilvert commented on src/user-federation/kerberos/KerberosSettingsCache.tsx
> +    hourOptions.push(<SelectOption key={index - 1} value={[`${index}`]} />);
In the dropdown, choices for eviction hour go from 1 to 24.  Look at old console.  It should go from 00 to 23.

2021-01-22 18:43 UTC, ssilvert commented on src/user-federation/kerberos/KerberosSettingsCache.tsx
> +            isRequired
This is not a required field in the old console.  I suspect that if it is blank that means "forever".  You aren't failing on that anyway, so I think we can just remove `isRequired`.

2021-01-22 20:15 UTC, merged