removed AssociatedRolesModal and optimized mapping dialog
keycloak/keycloak-admin-ui pull request #3073
Opened 2022-08-08 06:41 UTC by edewit

fixes: #2523

## Motivation

## Brief Description

## Verification Steps

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

## Additional Notes

2022-08-08 09:58 UTC, jonkoops requested changes

2022-08-08 09:58 UTC, jonkoops commented on src/components/role-mapping/AddRoleMappingModal.tsx
> +    const params: { [name: string]: string | number } = {
You could use a `Record` type here.
```suggestion
    const params: Record<string, string | number> = {
```

2022-08-08 09:58 UTC, jonkoops commented on src/components/role-mapping/AddRoleMappingModal.tsx
> +  };
In order to make this work with different locales you'll have to use some form of locale based sorting. For example:

```ts
const localeSort = useLocaleSort();
const alphabetize = (rolesList: Row[]) => localeSort(rolesList, ({ role }) => role.name?.toUpperCase());
```

2022-08-08 09:58 UTC, jonkoops commented on src/components/role-mapping/AddRoleMappingModal.tsx
> +    }
This can be shortened by removing the intermediate variable.
```suggestion
    if (search) {
      params.search = search;
    }
```

2022-08-08 09:58 UTC, jonkoops commented on src/components/role-mapping/AddRoleMappingModal.tsx
> +  /* this is still pretty expensive querying all client and then all roles */
Yeah this isn't ideal, perhaps we can log an API issue for this?

2022-08-08 09:58 UTC, jonkoops commented on src/components/role-mapping/AddRoleMappingModal.tsx
> +    return alphabetize(roles);
Since this is only used here, perhaps this function can be inlined here?

2022-08-09 11:19 UTC, edewit commented on src/components/role-mapping/AddRoleMappingModal.tsx
> +  /* this is still pretty expensive querying all client and then all roles */
we have multiple

2022-08-10 10:05 UTC, jonkoops approved these changes

2022-08-11 14:22 UTC, edewit commented
closing in favour of https://github.com/keycloak/keycloak-admin-ui/pull/3094

2022-08-11 14:22 UTC, closed without merging