initial version of cypress component test
keycloak/keycloak-admin-ui pull request #3079
Opened 2022-08-08 12:03 UTC by edewit

## Motivation

## Brief Description

## Verification Steps

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

## Additional Notes

2022-08-09 08:20 UTC, jonkoops requested changes

2022-08-09 08:20 UTC, jonkoops commented on cypress/component/ConfirmDialogModal.cy.tsx
> +export {};
Can we remove this empty export statement?
```suggestion
```

2022-08-09 08:20 UTC, jonkoops commented on cypress/support/component-index.html
> +    <meta http-equiv="X-UA-Compatible" content="IE=edge">
This is only needed for Internet Explorer, so I think we can get rid of it.
```suggestion
```

2022-08-09 08:20 UTC, jonkoops commented on cypress/support/component.ts
> +
We're never going to do this.
```suggestion
```

2022-08-09 08:20 UTC, jonkoops commented on cypress/support/component.ts
> +Cypress.Commands.add("mount", mount);
Instead of making this a global command I'd prefer to simply import the `mount` function from `cypress/react` in every test.

2022-08-09 10:06 UTC, edewit commented on cypress/component/ConfirmDialogModal.cy.tsx
> +export {};
seems it doesn't work without this, maybe we need some config in order to be able to remove it?

2022-08-09 10:09 UTC, edewit commented on cypress/support/component.ts
> +Cypress.Commands.add("mount", mount);
it's not global it adds it to the `cypress` object

2022-08-11 14:29 UTC, edewit commented on cypress/component/ConfirmDialogModal.cy.tsx
> +export {};
I can be removed... don't know why it was complaining in the first place... removed it now

2022-08-12 13:42 UTC, jonkoops commented on cypress/support/component.ts
> +Cypress.Commands.add("mount", mount);
Which is global 😉

2022-08-12 13:43 UTC, jonkoops commented on cypress/component/ConfirmDialogModal.cy.tsx
> +export {};
Probably it was that this module was not importing or exporting anything, which is the bare minimum that is expected.

2022-08-12 13:46 UTC, jonkoops approved these changes

2022-08-12 19:55 UTC, merged

2022-08-12 19:56 UTC, jonkoops commented
@edewit merged this PR, but be aware that these tests might not be running on CI at the moment.