initial version of authentication section
keycloak/keycloak-admin-ui pull request #309
Opened 2021-01-19 12:12 UTC by edewit

## Motivation

updated the admin client to support flows and excutions and implemented front sreeen [marvel](https://marvelapp.com/prototype/bh91013/screen/75647039)

## Brief Description

First page with "delete" and "duplicate" functionality

## Verification Steps

## Checklist:

- [x] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated
- [x] Formatting has been performed via prettier/eslint
- [x] Type checking has been performed via 'yarn check-types'

## Additional Notes

2021-01-20 22:35 UTC, ssilvert requested changes
Table does not update after doing Duplicate flow.

On an unrelated note, REST API lets you duplicate a new flow to the same Flow name.  Old console has same issue.

2021-01-20 22:35 UTC, ssilvert commented on src/authentication/messages.json
> +    "buildIn": "Build in",
```suggestion
    "buildIn": "Built-in",
```

Maybe should change the key as well.  The English expression is "Built-in"

2021-01-20 22:35 UTC, ssilvert commented on src/authentication/messages.json
> +    "deleteFlowSuccess": "Flow successfully delete",
```suggestion
    "deleteFlowSuccess": "Flow successfully deleted",
```

2021-01-20 22:35 UTC, ssilvert commented on src/authentication/AuthenticationSection.tsx
> +              searchPlaceholderKey="authentication:searchForEvent"
Should be `searchForFlow`.  Needs key/value pair as well.

2021-01-21 08:52 UTC, edewit commented on src/authentication/AuthenticationSection.tsx
> +              searchPlaceholderKey="authentication:searchForEvent"
This screen doesn't have a search input text, but the component can't handle that yet

2021-01-25 21:52 UTC, ssilvert commented
@edewit Looked at this again.  It's fine except that the table doesn't update when you duplicate.  Do you want to fix that now or open an issue?

2021-01-26 19:21 UTC, ssilvert approved these changes

2021-01-26 19:39 UTC, merged