Fix tests
keycloak/keycloak-admin-ui pull request #3091
Opened 2022-08-10 17:49 UTC by ikhomyn

## Motivation
Fixes some failing and flaky tests. Also some fixed some skipped tests. Related to #2664

## Checklist:

- [X] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

## Additional Notes

2022-08-11 10:37 UTC, jonkoops requested changes
Awesome work fixing the flaky tests, it does seems like some tests are still failing though.

2022-08-11 10:37 UTC, jonkoops commented on cypress/e2e/group_test.spec.ts
> +  });
Since a Promise is returned here this can be shortened a bit.
```suggestion
  after(() => adminClient.deleteGroups());
```

2022-08-11 10:37 UTC, jonkoops commented on cypress/e2e/users_test.spec.ts
> +    cy.wait(2000);
Any chance we can remove this wait? Perhaps by verifying that indeed all notification have been dismissed from the DOM?

2022-08-11 10:37 UTC, jonkoops commented on cypress/support/pages/admin_console/Masthead.ts
> +    });
I believe the following code (same as before) should yield the same result. At least according to the [Cypress documentation](https://docs.cypress.io/api/commands/click#Click-all-elements-with-id-starting-with-btn).
```suggestion
    cy.get(this.closeAlertMessageBtn).click({ force: true, multiple: true });
```

2022-08-11 10:41 UTC, ikhomyn commented on cypress/support/pages/admin_console/Masthead.ts
> +    });
I've tried this way. But the problem is. When Cypress perform cy.get(this.closeAlertMessageBtn).click({ force: true, multiple: true });  it finds multiple elements present, after first notification is closed. Dom is updated, and it loses other elements. So in this case it will only close last notification, but not all of them. So after each click, I have to find again the elements.

2022-08-11 10:46 UTC, ikhomyn commented on cypress/e2e/users_test.spec.ts
> +    cy.wait(2000);
I've tried without timeout but seems it still need some extra time in order to update dom or some refresh request is made on the table. And without timeout it causes the problem that Cypress loses focus on opened dropdown items.
I mean:
- All notifications are closed
- Click on item dropdown element. Dropdown options are shown
- Meanwhile list or Dom is updated and focus is lost, dropdown options are hidden
- Attempt to click on dropdown option which is not longer visible.

I've tried several ways, but only adding timeout fixed the problem.

2022-08-11 10:51 UTC, ikhomyn commented
@jonkoops Regarding the other 2 failing tests, I was not sure about the flow of the test in order to fix them.

2022-08-11 11:23 UTC, ikhomyn commented
@jonkoops I have updated 2 remaining failing tests for clients_saml_test.spec. But 1 will still fail as of this issue: https://github.com/keycloak/keycloak-admin-ui/issues/3092

2022-08-12 10:50 UTC, jonkoops commented on cypress/support/pages/admin_console/Masthead.ts
> +    });
Ahhh, yeah that makes sense. Let's keep it like this then.

2022-08-12 10:51 UTC, jonkoops commented on cypress/e2e/users_test.spec.ts
> +    cy.wait(2000);
Hmmm, well if it's too complex let's just keep it like this for now. Either way it's already a massive improvement.

2022-08-12 10:52 UTC, jonkoops approved these changes

2022-08-12 10:52 UTC, merged