Ldap settings save
keycloak/keycloak-admin-ui pull request #311
Opened 2021-01-19 17:02 UTC by mfrances17

## Motivation

## Brief Description
Adds the ability to save (or cancel) changes made to the User Federation Kerberos settings page.

## Verification Steps
1. Go to User federation and select an LDAP card.
2. Change any of the values in any of the subsections.
3. Click Save. You should see a success alert.
4. Verify that the changes have been saved by traversing anywhere else in the UI and then re-clicking the card to make sure the values that were changed are displayed correctly.

## Checklist:
- [x] Code has been tested locally by PR requester
- [x] User-visible strings are using the react-i18next framework (useTranslation)
- [x] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated
- [x] Formatting has been performed via prettier/eslint
- [ ] Type checking has been performed via 'yarn check-types'

## Additional Notes
Screen cap of successful save:

2021-01-19 19:25 UTC, jenny-s51 requested changes
Nice work @mfrances17 - this is looking great! There are some things I seem to be running into when I try saving.

1) A couple of the switches cause a save error. This seems to specifically be happening with: 
- "Enable the LDAPv3 password modify extended operation" under "Advanced Settings"
- "Enable StartTLS" under "Connection and Authentication Settings"
2) As discussed in the Keycloak team meeting this morning, this form can still currently be submitted even if the required fields are empty or invalid in some way. It would be nice if we could find a way to disable the `save` button on the form and/or provide error messages below the invalid fields, though this can definitely be addressed in a separate issue if necessary.

2021-01-19 19:28 UTC, mfrances17 commented on src/user-federation/messages.json
These strings are introduced in the kerberos save which is currently in PR.

2021-01-20 06:54 UTC, edewit commented on src/user-federation/UserFederationLdapSettings.tsx
> +        console.log(fetchedComponent);
```suggestion
```
These can be removed I guess

2021-01-20 06:55 UTC, edewit commented on src/user-federation/UserFederationLdapSettings.tsx
> +    console.log(`COMPONENT SAVED OUT`);
```suggestion
```

2021-01-20 06:57 UTC, edewit requested changes
looks good to me...

2021-01-21 18:13 UTC, mfrances17 commented on src/user-federation/messages.json
Fixed save on the two fields identified in comment #1.

2021-01-21 18:13 UTC, mfrances17 commented on src/user-federation/UserFederationLdapSettings.tsx
> +        console.log(fetchedComponent);
Removed

2021-01-21 18:13 UTC, mfrances17 commented on src/user-federation/UserFederationLdapSettings.tsx
> +    console.log(`COMPONENT SAVED OUT`);
Removed

2021-01-21 18:43 UTC, jenny-s51 approved these changes
Looking good!

2021-01-21 21:32 UTC, mfrances17 commented on src/user-federation/messages.json
Added some simple validation for empty fields, so the form is prevented from being saved. Also removed "select an option" type selections in dropdowns to prevent them from being submitted, as i have down with kerberos settings. This should address comment 2, at least at this point.

2021-01-22 20:10 UTC, ssilvert requested changes
The `Save` button is active even when nothing on the form has changed.

Any time I try to save changes I get a 500 error.  Shows this on the server side:
`15:07:35,471 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (default task-17) Uncaught server error: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.util.ArrayList<java.lang.Object>` out of VALUE_STRING token
 at [Source: (io.undertow.servlet.spec.ServletInputStreamImpl); line: 1, column: 614] (through reference chain: org.keycloak.representations.idm.ComponentRepresentation["config"]->org.keycloak.common.util.MultivaluedHashMap["startTls"])`

2021-01-22 20:10 UTC, ssilvert commented on src/user-federation/messages.json
>      "importUsers": "Import users",
Wrong help text.  See old console.

2021-01-25 21:18 UTC, mfrances17 commented on src/user-federation/ldap/LdapSettingsConnection.tsx
>              <TextInput // TODO: Make password field switch to type=text with button
Yes, filed an issue for it to be handled separately.

2021-01-25 21:19 UTC, mfrances17 commented
> The `Save` button is active even when nothing on the form has changed.
> 
> Any time I try to save changes I get a 500 error. Shows this on the server side:
> `15:07:35,471 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (default task-17) Uncaught server error: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.util.ArrayList<java.lang.Object>` out of VALUE_STRING token at [Source: (io.undertow.servlet.spec.ServletInputStreamImpl); line: 1, column: 614] (through reference chain: org.keycloak.representations.idm.ComponentRepresentation["config"]->org.keycloak.common.util.MultivaluedHashMap["startTls"])`

There was a mismatch of data due to a bad defaultValue in the startTls and usePasswordModifyExtendedOp, which should be fixed now.

2021-01-25 21:22 UTC, mfrances17 commented on src/user-federation/messages.json
>      "importUsers": "Import users",
Added the help from the old console.

2021-01-25 21:22 UTC, mfrances17 commented on src/user-federation/ldap/LdapSettingsSearching.tsx
> +                <SelectOption key={0} value="RACT_ONLY" isPlaceholder />
Changed the text to READ_ONLY.

2021-01-25 21:22 UTC, mfrances17 commented on src/user-federation/ldap/LdapSettingsConnection.tsx
>            label={t("enableStartTls")}
Fixed

2021-01-26 01:41 UTC, ssilvert approved these changes

2021-01-26 01:41 UTC, merged