added roles tab to clients
keycloak/keycloak-admin-ui pull request #312
Opened 2021-01-20 10:55 UTC by edewit

## Motivation
Roles tab under clients is the same as the roles section this PR add it see [marvel](https://marvelapp.com/prototype/bi16ff1/screen/75842763)

## Brief Description

## Verification Steps

See that there is a new tab under client details named roles that has the same functionality as the roles section

## Checklist:

- [x] Code has been tested locally by PR requester
- [x] Formatting has been performed via prettier/eslint
- [x] Type checking has been performed via 'yarn check-types'

## Additional Notes

2021-01-20 21:37 UTC, jenny-s51 requested changes
The new roles tab displays the list of roles as expected, and it looks like "create role" is also working through client details! There are a few things I noticed while testing:

- Go to clients -> click on one of the roles -> details page renders as expected -> click on "attributes" tab -> `TypeError: Cannot read property 'name' of null
    at RealmRoleTabs.js:85`
- Go to clients -> click on one of the roles -> details page renders as expected -> click on "details" tab again -> form is cleared of all data and `TypeError: Cannot read property 'name' of null at RealmRoleTabs.js:85`
- if either of the above two are done, clicking on "Client Details" in the breadcrumb results in a loading spinner without taking you back 
- if we try to create a new role, the role itself is created but the same form-clearing errors show up when we try to click on "details" or "attributes"
- role description doesn't get updated when update is attempted

2021-01-21 10:09 UTC, edewit commented
@jenny-s51 right there was a duplicated `id` parameter fixed that now.

2021-01-25 16:35 UTC, jenny-s51 approved these changes
Looks great @edewit !

2021-01-26 19:13 UTC, ssilvert requested changes
@edewit The roles tab displays the wrong set of roles.  It's pulling up the realm roles instead of the client's roles.

2021-01-27 07:08 UTC, edewit commented
@ssilvert didn't know client had roles the design just said it should be the same page

2021-01-27 15:27 UTC, ssilvert commented
> @ssilvert didn't know client had roles the design just said it should be the same page

Yes they do.  I think the designer just meant it was the same design.  Different data though.  Check out old console.

2021-01-27 16:34 UTC, mfrances17 requested changes
Found a couple of issues when testing:

When I initially create a role, I can't add a description - I can type one but it isn't saved. I can only enter a description later after the initial save.

When I delete a role, I get a success notification but my view is still of an empty role details screen, and in the console there is the following error:
`Uncaught (in promise) TypeError: Cannot read property 'name' of null at RealmRoleTabs.js:83`

2021-01-28 07:38 UTC, edewit commented
@mfrances17 good catch the delete problem only happened when you delete from the attributes tab, didn't notice that. Also fixed the create with description

2021-01-28 19:36 UTC, mfrances17 approved these changes
Both of the issues I had found while testing are now fixed, the Roles tab is working really well now. Just need to resolve some newly introduced conflicts but LGTM.

2021-01-29 13:59 UTC, merged