realm roles: associated roles modal (roles list)
keycloak/keycloak-admin-ui pull request #316
Opened 2021-01-20 16:09 UTC by jenny-s51

## Motivation

## Brief Description

## Verification Steps

1. Go to Realm Roles section.
2. Click on one of the roles in the list.
3. Go to the dropdown in the upper right.
4. Click "Add associated roles"
5. Verify that the modal renders and displays the list of existing realm roles. 

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated
- [ ] Formatting has been performed via prettier/eslint
- [ ] Type checking has been performed via 'yarn check-types'

## Additional Notes

2021-01-21 10:41 UTC, edewit commented
I guess the list of this dialog it should not have the role itself. I mean, if I want to associate the role "admin" with another role the role "admin" should not be in the dialog?

2021-01-21 18:14 UTC, jenny-s51 commented
@edewit nice catch - fixed!

2021-01-22 07:29 UTC, edewit requested changes

2021-01-22 07:29 UTC, edewit commented on src/realm-roles/RealmRolesSection.tsx
> +  // });
Let's remove these comments
```suggestion
```

2021-01-22 07:29 UTC, edewit commented on src/realm-roles/AssociatedRolesModal.tsx
> +  };
we could move this to `./util.js`, it's used in 2 places I think

2021-01-25 16:25 UTC, jenny-s51 commented on src/realm-roles/AssociatedRolesModal.tsx
> +  };
great idea - done

2021-01-27 17:14 UTC, mfrances17 requested changes
Getting the following error when selecting the Action menu or one of its commands:
`Encountered two children with the same key, `.$action`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.`
Your menu commands are probably using the same key.

Also, if I add associated roles, what is the expected result? I don't see any way to see associated roles to verify that they've been added.

2021-01-27 17:14 UTC, mfrances17 commented on src/realm-roles/messages.json
> +    "add": "Add",
You should use the Add string that already exists in common

2021-01-27 20:23 UTC, jenny-s51 commented on src/realm-roles/messages.json
> +    "add": "Add",
@mfrances17 nice catch - updated!

2021-01-27 20:49 UTC, jenny-s51 commented
@mfrances17 thank you for your helpful feedback! I fixed the duplicate keys and the "add"/"cancel" strings.

This PR is meant to address just the implementation of a selectable modal populated with realm roles from the backend. I plan on addressing the functionality in a separate PR (see JIRA issue: https://issues.redhat.com/browse/APPDUX-791) and  https://github.com/jenny-s51/keycloak-admin/tree/associated-roles-modal-functionality

2021-01-28 06:51 UTC, edewit approved these changes

2021-01-28 12:48 UTC, ssilvert commented
@mfrances17 Are you ok with merging this?

2021-01-28 17:13 UTC, mfrances17 approved these changes

2021-01-28 17:14 UTC, mfrances17 commented
Yep, with Jenny's explanation that this isn't meant for that functionality yet, this can be merged. Need to resolve conflicts first, of course.

2021-01-28 18:19 UTC, merged