Add enable switch and action menu to kerberos settings
keycloak/keycloak-admin-ui pull request #326
Opened 2021-01-25 17:01 UTC by mfrances17

## Motivation
https://issues.redhat.com/browse/APPDUX-722

## Brief Description
Adds an Enable switch and Actions menu to the Kerberos settings page.

Design spec:
https://marvelapp.com/prototype/ecjc94b/screen/72098368

## Verification Steps

1. Go to User federation and select a Kerberos card.
2. Enable (if disabled) or disable (if enabled) the switch and click Save.
3. Verify that the Kerberos card you enabled/disabled now appears on the User Fed card view with the correct tag of enabled or disabled.
4. Click the card and verify that the Enabled/Disabled switch is correct.
5. Select Action > Delete provider to delete the user fed provider. 
6. Go back to the User federation card view and verify that the card is now gone and the provider has been deleted.

## Checklist:

- [x] Code has been tested locally by PR requester
- [x] User-visible strings are using the react-i18next framework (useTranslation)
- [x] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated
- [x] Formatting has been performed via prettier/eslint
- [ ] Type checking has been performed via 'yarn check-types'

## Additional Notes
Screen caps:
![kerb-enable-and-actions](https://user-images.githubusercontent.com/39063664/105738194-c421f600-5f04-11eb-9af7-b3993a4a2d0f.png)
![delete-confirm](https://user-images.githubusercontent.com/39063664/105738208-c71ce680-5f04-11eb-894b-c4a18caebd04.png)
![disable-confirm](https://user-images.githubusercontent.com/39063664/105738218-ca17d700-5f04-11eb-9ad9-5da0c654f641.png)

2021-01-25 21:16 UTC, jenny-s51 requested changes
This is looking great @mfrances17! Just a small suggestion about the route (see below) 🙂

2021-01-25 21:57 UTC, mfrances17 commented on src/user-federation/UserFederationKerberosSettings.tsx
> +        addAlert(t("userFedDeletedSuccess"), AlertVariant.success);
Yeah that makes sense, definitely. I'll make that change.

2021-01-26 06:47 UTC, edewit reviewed
Shouldn't it save automatically after you click 'disable' in the dialog? Then it works the same for the delete

2021-01-27 22:12 UTC, mfrances17 commented on src/user-federation/UserFederationKerberosSettings.tsx
> +        addAlert(t("userFedDeletedSuccess"), AlertVariant.success);
@jenny-s51 it navigates back to the user federation card view after delete, thanks for the suggestion

2021-01-28 17:48 UTC, jenny-s51 approved these changes
LGTM @mfrances17! 👍

2021-01-28 18:18 UTC, merged