multiple ux issues around realms
keycloak/keycloak-admin-ui pull request #330
Opened 2021-01-26 13:36 UTC by edewit

fixes: #324

2021-01-26 20:40 UTC, jenny-s51 commented on src/realm/messages.json
> +    "saveRealmError": "Could not create realm {{error}}"
```suggestion
    "providerInfo": "Provider Info"
```

2021-01-26 20:57 UTC, jenny-s51 requested changes
Save and cancel buttons are working as expected!

I'm seeing an empty sidebar when I navigate to the "create realm" page though.

Also, `providerInfo` hasn't been declared in `common-messages.json` even though it's localized here in `Dashboard`: https://github.com/keycloak/keycloak-admin-ui/blob/master/src/dashboard/Dashboard.tsx#L53

2021-01-26 20:57 UTC, jenny-s51 commented on public/index.css
> +  max-width: 768px;
@edewit @yih-wang 768px still seems a bit narrow... the "resource file" placeholder text is getting truncated:

<img width="1352" alt="Screen Shot 2021-01-26 at 3 47 56 PM" src="https://user-images.githubusercontent.com/32821331/105903792-5225db80-5fee-11eb-8053-d85506ffc384.png">

2021-01-27 02:14 UTC, yih-wang commented on public/index.css
> +  max-width: 768px;
Agree. And it looks different from what I expected... Maybe the actual size in the screen should be twice 768px? Basically, the width of this form equals the form with a scroll-spy. So when users jump between different screens, the forms can keep in the same position.

2021-01-27 07:14 UTC, edewit commented on public/index.css
> +  max-width: 768px;
seems those forms are 1024px so changed it to that size

2021-01-27 07:16 UTC, edewit commented
@jenny-s51 can't seem to get the empty navigation on the create role screen how did you do that?

2021-01-27 16:15 UTC, jenny-s51 reviewed
@edewit this is what the left sidebar looks like for me when I navigate to "create realm". Are you seeing something else?

EDIT: Ah ok, I understand now this is the expected behavior.

<img width="1680" alt="Screen Shot 2021-01-27 at 11 13 16 AM" src="https://user-images.githubusercontent.com/32821331/106019679-e9dc0600-6090-11eb-8500-6378da98d23a.png">

2021-01-27 16:33 UTC, jenny-s51 commented on src/dashboard/Dashboard.tsx
>          <Button variant="link" onClick={() => setRealm("master")}>
```suggestion
        <Button variant="link" onClick={() => setRealm("master")}>
```

Clicking on "realm info" for any of the realms always changes to realm to "master" in the realm dropdown, and takes me to the info page for the master realm.

2021-01-28 06:58 UTC, edewit commented on src/dashboard/Dashboard.tsx
>          <Button variant="link" onClick={() => setRealm("master")}>
right changed the button to say 'Server info'

2021-01-28 07:42 UTC, edewit commented
> @edewit this is what the left sidebar looks like for me when I navigate to "create realm". Are you seeing something else?
> 
> EDIT: Ah ok, I understand now this is the expected behavior.
> 
> <img alt="Screen Shot 2021-01-27 at 11 13 16 AM" width="1680" src="https://user-images.githubusercontent.com/32821331/106019679-e9dc0600-6090-11eb-8500-6378da98d23a.png">

This is a fix, it was designed to behave that way

2021-01-28 20:11 UTC, mfrances17 requested changes
I tested vs the issues that were filed and the changes look great. I noticed a couple of other issues that you may want to fix here or we can add them as new Issues:

Clear button string needs to be capitalized:
![lower-case-clear](https://user-images.githubusercontent.com/39063664/106192984-ea50cb80-617a-11eb-8db1-5e10e7ed2e4c.png)

There are a bunch of errors thrown if the user starts typing directly into the resource file field, about one per keystroke. We probably want to handle this:
![json-errors](https://user-images.githubusercontent.com/39063664/106193129-18cea680-617b-11eb-804f-e96e1afe0f09.png)

2021-01-29 07:17 UTC, edewit commented
@mfrances17 right, that is not nice fixed those

2021-01-29 13:48 UTC, mfrances17 requested changes
Both of the issues i raised are fixed... just one quick change needed to fix the message reference:
![clear](https://user-images.githubusercontent.com/39063664/106282571-c76ff700-620e-11eb-9187-70142ef6a506.png)

2021-01-29 13:48 UTC, mfrances17 commented on src/components/json-file-upload/JsonFileUpload.tsx
> +          {t("clearExplain")}
should be clearFileExplain

2021-02-08 19:49 UTC, ssilvert requested changes
Other than the `any` thing and the one failing test, this looks very good to me.

2021-02-08 19:49 UTC, ssilvert commented on src/realm/add/NewRealmForm.tsx
> +    let obj: { [name: string]: any } = defaultRealm;
Avoid `any`

2021-02-09 12:32 UTC, ssilvert approved these changes

2021-02-09 12:32 UTC, merged