toggle help on kebab click
keycloak/keycloak-admin-ui pull request #339
Opened 2021-01-27 14:53 UTC by edewit

fixes: #305

2021-01-27 21:36 UTC, jenny-s51 requested changes
Toggle functionality working as expected - see comment below

2021-01-27 21:36 UTC, jenny-s51 commented on src/PageHeader.tsx
> +      <DropdownItem icon={<HelpIcon />} onClick={toggleHelp}>
Would be helpful to have some sort of indicator here when help is toggled... maybe a checkbox or a switch. There is currently no way of telling that help is on or off unless you specifically check for changes on the page

2021-01-31 17:45 UTC, ssilvert approved these changes
LGTM

2021-01-31 17:50 UTC, ssilvert requested changes
Noticed something here.

2021-01-31 17:50 UTC, ssilvert commented on src/PageHeader.tsx
> +        {t("help")} {enabled ? t("on") : t("off")}
This is not always localizable.  You need to translate as a single phrase.

2021-02-01 18:01 UTC, jenny-s51 approved these changes

2021-02-08 20:35 UTC, ssilvert approved these changes

2021-02-08 20:35 UTC, merged