Add enable switch and action menu to LDAP settings
keycloak/keycloak-admin-ui pull request #349
Opened 2021-02-01 19:22 UTC by mfrances17

## Motivation
https://issues.redhat.com/browse/APPDUX-719

## Brief Description
Adds layout for Enable toggle switch, Action menu and commands, and Remove imported modal. Adds business logic for the Enable switch and the Delete provider menu command. 

Note that the logic for the 4 user-related menu commands is tracked in a different JIRA (https://issues.redhat.com/browse/APPDUX-724) and will be handled in a separate PR as they will probably require backend work.

## Verification Steps

1. Go to User federation and select an LDAP card.
2. Enable (if disabled) or disable (if enabled) the switch and click **Save**.
3. Verify that the LDAP card you enabled/disabled now appears on the User Fed card view with the correct tag of enabled or disabled.
4. Click the card and verify that the Enabled/Disabled switch is correct.
5. Select **Action > Delete provider** to delete the user fed provider.
6. Go back to the User federation card view and verify that the card is now gone and the provider has been deleted.

Marvel spec:
https://marvelapp.com/prototype/ecjc94b/screen/72379134

## Checklist:
- [x] Code has been tested locally by PR requester
- [x] User-visible strings are using the react-i18next framework (useTranslation)
- [x] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated
- [x] Formatting has been performed via prettier/eslint
- [ ] Type checking has been performed via 'yarn check-types'

## Additional Notes
Screen cap:
![LDAP-enable-action](https://user-images.githubusercontent.com/39063664/106507065-8b4fc700-6498-11eb-8113-b6b5f667b9d6.png)

2021-02-02 12:33 UTC, ssilvert requested changes

2021-02-02 12:33 UTC, ssilvert commented on src/user-federation/messages.json
>      "userFedDisableConfirm": "If you disable this user federation provider, you cannot make changes to the provider.",
Where did you get this text?  You can still make changes to the provider configuration when it is disabled.  Look at the help text for "Enabled" in the old console.

2021-02-02 12:33 UTC, ssilvert commented on src/user-federation/UserFederationLdapSettings.tsx
> +  value: any;
Avoid `any`

2021-02-02 12:37 UTC, ssilvert commented
In the design for the dropdown, there is a line spacer between `Remove imported` and `Delete provider`.

2021-02-02 18:49 UTC, jenny-s51 approved these changes
enable/disable toggle and actions dropdown look good @mfrances17 ! See question about the dialog message below

2021-02-02 18:49 UTC, jenny-s51 commented on src/user-federation/messages.json
> +    "removeImportedUsersMessage": "Do you really want to remove all imported users? The option \"Unlink users\" makes sense just for the Edit Mode \"Unsynced\" and there should be a warning that \"un
This dialog message seems a bit too verbose. I think the second part can be removed with the understanding that once "Unlink Users" is implemented, the dialog can specify the password authentication warning there? Those are  my thoughts ... WDYT? I know this is how it looks in the mocks but I think we could potentially clean it up somehow
```suggestion
    "removeImportedUsersMessage": "Do you really want to remove all imported users? 
```

2021-02-03 15:02 UTC, mfrances17 commented on src/user-federation/UserFederationLdapSettings.tsx
> +  value: any;
I was getting errors unless using any. This is how it's done in clients and realms as well.

2021-02-03 15:05 UTC, mfrances17 commented on src/user-federation/messages.json
> +    "removeImportedUsersMessage": "Do you really want to remove all imported users? The option \"Unlink users\" makes sense just for the Edit Mode \"Unsynced\" and there should be a warning that \"un
I completely agree that the wording is extremely weak, but I think it's a slippery slope on editing the text from the mocks because I can see making tens if not hundreds of changes. I think we leave that to the doc resource and/or a text sweep later in the project.

2021-02-03 15:14 UTC, mfrances17 commented on src/user-federation/messages.json
>      "userFedDisableConfirm": "If you disable this user federation provider, you cannot make changes to the provider.",
Added the text from the help in old console

2021-02-03 15:14 UTC, mfrances17 commented
> In the design for the dropdown, there is a line spacer between `Remove imported` and `Delete provider`.

Added a separator

2021-02-03 16:28 UTC, jenny-s51 commented on src/user-federation/messages.json
> +    "removeImportedUsersMessage": "Do you really want to remove all imported users? The option \"Unlink users\" makes sense just for the Edit Mode \"Unsynced\" and there should be a warning that \"un
Sounds like a good plan!

2021-02-03 21:23 UTC, ssilvert commented on src/user-federation/UserFederationLdapSettings.tsx
> +  value: any;
This works but we could probably do better:
```suggestion
  onChange: (...event: unknown[]) => void;
  value: "true" | null;
```

Then you can also change line 183 to say:
`onChange={(value) => onChange(value)}`

2021-02-03 21:30 UTC, ssilvert commented
@mfrances17 You should not have to scroll down and hit `Save` button after doing enable/disable.  It should be changed immediately as this UI treats it as an action and not part of the user's form.  See how it is implemented in Clients.

2021-02-04 19:35 UTC, mfrances17 commented
> @mfrances17 You should not have to scroll down and hit `Save` button after doing enable/disable. It should be changed immediately as this UI treats it as an action and not part of the user's form. See how it is implemented in Clients.

@ssilvert I don't get it... for everything else, we say make it work like the old UI. In the old UI, you needed to click Save or the Enable or Disable didn't work. So I guess I will rework this.

2021-02-08 10:23 UTC, edewit requested changes
created PR with the changes: https://github.com/mfrances17/keycloak-admin-ui/pull/2

2021-02-08 18:55 UTC, mfrances17 commented
> created PR with the changes: [mfrances17#2](https://github.com/mfrances17/keycloak-admin-ui/pull/2)

thanks... i actually had a fix going in today but wish i saw this sooner, yours is more concise, going with your solution, ty

2021-02-08 19:01 UTC, mfrances17 commented
@ssilvert @edewit added all PR review changes/suggestions... please review and approve your requested changes and let's get this merged if possible

2021-02-08 19:01 UTC, edewit approved these changes

2021-02-08 20:49 UTC, ssilvert approved these changes

2021-02-08 20:50 UTC, merged