Issue 327: Fix for showing/hiding password text in Bind credentials field
keycloak/keycloak-admin-ui pull request #350
Opened 2021-02-01 21:44 UTC by mfrances17

## Motivation
https://github.com/keycloak/keycloak-admin-ui/issues/327

## Brief Description
Added ability to show/hide newly-typed passwords in LDAP settings bind credentials field so it works as it did in the old admin UI.

## Verification Steps

1. Go to the User federation card view and click an LDAP card.
2. In the Connection and authentication settings section, enter a new password in the Bind credentials field.
3. Click the eye button on the field. The password should display in plain text. 
4. Edit the password, and click the eye button again to continue to toggle off/on the text visibility of the password.

## Checklist:

- [x] Code has been tested locally by PR requester
- [x] User-visible strings are using the react-i18next framework (useTranslation)
- [x] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated
- [x] Formatting has been performed via prettier/eslint
- [ ] Type checking has been performed via 'yarn check-types'

## Additional Notes
Screen cap before button click:
![pre-click](https://user-images.githubusercontent.com/39063664/106521481-4cc40780-64ac-11eb-94f9-8972c85837d1.png)

Screen cap after button click:
![post-click](https://user-images.githubusercontent.com/39063664/106521503-4fbef800-64ac-11eb-81f5-11435cb08dac.png)

2021-02-02 19:20 UTC, jenny-s51 requested changes
Looking good! Just one small tweak 🙂

2021-02-02 19:20 UTC, jenny-s51 commented on src/user-federation/ldap/LdapSettingsConnection.tsx
>                <EyeIcon />
```suggestion
              {!isPasswordVisible ? <EyeIcon /> : <EyeSlashIcon />}

```

2021-02-02 19:20 UTC, jenny-s51 commented on src/user-federation/ldap/LdapSettingsConnection.tsx
>                <EyeIcon />
Add `import { EyeIcon, EyeSlashIcon } from "@patternfly/react-icons";` to the top of the file so the eye button can be a helpful on/off indicator

2021-02-03 15:26 UTC, mfrances17 commented on src/user-federation/ldap/LdapSettingsConnection.tsx
>                <EyeIcon />
good call Jenny, thanks... added

2021-02-03 16:30 UTC, jenny-s51 approved these changes
👍 🚀

2021-02-04 21:43 UTC, merged