Realm Roles: associated roles modal functionality
keycloak/keycloak-admin-ui pull request #351
Opened 2021-02-02 16:40 UTC by jenny-s51

## Motivation

Will close https://issues.redhat.com/browse/APPDUX-791

Also addresses https://issues.redhat.com/browse/APPDUX-728

## Brief Description

See #284, #316 

Extends modal with functionality to POST/FETCH associated roles and display them in the realm roles section.

## Verification Steps

1. Go to  Realm Roles section.
2. Create a new role or click on an existing role.
3. Click on the Action dropdown -> select "Add associated role"s.
4. Select roles and click "Add".
5. Navigate back to roles list.
6. Return to previously selected role and verify that "Associated Roles" tab is visible.
7. Verify that associated roles are in the table.

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated
- [ ] Formatting has been performed via prettier/eslint
- [ ] Type checking has been performed via 'yarn check-types'

## Additional Notes

2021-02-03 18:47 UTC, mfrances17 requested changes
FormAccess test is failing... if you do a 'yarn test -u' and commit the changed test, it will fix it.

2021-02-03 18:49 UTC, mfrances17 requested changes

2021-02-03 18:49 UTC, mfrances17 commented on src/realm-roles/messages.json
> +    "add": "Add",
delete and use the Add from common messages

2021-02-03 19:42 UTC, mfrances17 commented on package.json
> +    "react-hook-form": "^6.8.3",
i'm still seeing a bunch of watched fields spam in the console, even after the bump to 6.8.3

2021-02-03 20:20 UTC, jenny-s51 commented on package.json
> +    "react-hook-form": "^6.8.3",
this got rid of them all for me 🤔

2021-02-03 21:39 UTC, mfrances17 commented on package.json
> +    "react-hook-form": "^6.8.3",
Indeed it has... must've been a caching issue on my part, i installed clean and they are gone. 👍

2021-02-03 21:39 UTC, mfrances17 approved these changes
LGTM

2021-02-04 20:37 UTC, ssilvert requested changes

2021-02-04 20:37 UTC, ssilvert commented on src/realm-roles/RealmRoleTabs.tsx
> +    console.log("refresh?");
Remove

2021-02-04 20:50 UTC, ssilvert approved these changes

2021-02-04 20:50 UTC, merged