Realm roles: associated roles tab
keycloak/keycloak-admin-ui pull request #358
Opened 2021-02-09 19:49 UTC by jenny-s51

## Motivation

#285 , https://issues.redhat.com/browse/APPDUX-728

## Brief Description

Implements attributes tab to resemble the mock: https://marvelapp.com/prototype/f39d464/screen/72684631

## Verification Steps

1. Go to Realm Roles section. 
2. Create a new role
3. Click on the "Action" menu in the upper left
4. Select "Add associated roles"
5. Add associated roles
6. Verify the "Associated roles tab" is selected
7. Go to the "action" menu again
8. Select "delete all associated roles"
9. Verify the functionality works as expected 

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated
- [ ] Formatting has been performed via prettier/eslint
- [ ] Type checking has been performed via 'yarn check-types'

## Additional Notes

2021-02-10 15:46 UTC, edewit requested changes
clicking on the role in the associated role table gives me a "Page not found", also after deleting the role from the table the table doesn't update.

2021-02-10 15:46 UTC, edewit commented on src/realm-roles/AssociatedRolesTab.tsx
> +  // const [k, setK] = useState(0);
can go I guess

2021-02-10 15:46 UTC, edewit commented on src/realm-roles/AssociatedRolesTab.tsx
> +        addAlert(`${t("roleDeleteError")} ${error}`, AlertVariant.danger);
it's better to do this concatenation in the message key
```suggestion
        addAlert({t("roleDeleteError", {error}), AlertVariant.danger);
```
then in the message bundle use:
```json
"roleDeleteError": "Could not delete role: {{error}}"
```

2021-02-10 15:46 UTC, edewit commented on src/realm-roles/RealmRoleTabs.tsx
> +          t("compositesRemoved"),
missing in `messages.json`

2021-02-10 18:39 UTC, jenny-s51 commented
@edewit thank you for your review! updated to address your helpful feedback

2021-02-15 10:51 UTC, edewit requested changes

2021-02-15 10:51 UTC, edewit commented on src/realm-roles/AssociatedRolesTab.tsx
>            setRefresher={setRefresher}
just noticed this refresher seems this was added in another PR, why use this instead of the `key` prop? I think it would be better to use the `key` prop as we do in other places

2021-02-15 14:46 UTC, jenny-s51 commented on src/realm-roles/AssociatedRolesTab.tsx
>            setRefresher={setRefresher}
I see what you're saying and certainly agree that using the `key` prop here would be ideal ... I tried a bunch of different implementations using `key` with `useEffect` and `setTimeout` but the table would never refresh correctly

2021-02-16 13:08 UTC, edewit approved these changes

2021-02-17 07:17 UTC, merged