Realm roles: fix pagination by 10
keycloak/keycloak-admin-ui pull request #367
Opened 2021-02-15 16:29 UTC by jenny-s51

## Motivation

#365 : Upon reviewing/testing Erik's PR I noticed a bug in the realm roles section when paginating by 10 items per page. This PR addresses and fixes the bug described below.

## Brief Description

When a user would select 10 items per page, it was possible to infinitely paginate with the same data showing on every page. 

## Verification Steps

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated
- [ ] Formatting has been performed via prettier/eslint
- [ ] Type checking has been performed via 'yarn check-types'

## Additional Notes

2021-02-17 07:12 UTC, edewit requested changes
What was the error that you got? Because the loader is passed in right?

it is here: https://github.com/keycloak/keycloak-admin-ui/blob/678ec591d61f97b0cf7b841a4ab252c8b918a07d/src/realm-roles/RealmRolesSection.tsx#L9-L16

2021-02-17 08:35 UTC, edewit commented
I see the fix would be to rename `to` to `first` because that what it's should be called for the `find` function

2021-02-17 15:17 UTC, jenny-s51 commented
@edewit thank you for your feedback, that makes more sense - updated

2021-02-17 21:34 UTC, ssilvert commented
I imported 50 realm roles without this fix and there was no pagination.  Then I used this PR, which seems to have fixed it.  @edewit @jenny-s51 if you want to use the same import file I'm attaching it on Zulip.  Just go to the old console and do the import from there.

2021-02-18 06:38 UTC, edewit approved these changes

2021-02-18 06:38 UTC, merged