Realm roles: add "users in role" tab
keycloak/keycloak-admin-ui pull request #401
Opened 2021-02-24 21:05 UTC by jenny-s51

## Motivation

https://issues.redhat.com/browse/APPDUX-843

## Brief Description

Adds "Users in role" tab to realm roles section of Keycloak.

## Verification Steps

1. Go to Realm Roles section.
2. Create a new realm role.
3. Click on the "Users in role tab".
4. Verify that the empty state appears.
5. In the old console, go to Users -> Add user. 
6. Make sure to fill out each of the fields Username, Email, First Name, and Last Name
7. Click save and go to the Role Mappings tab.
8. Select the realm role you created in the "Realm roles" box and click "Add selected".
9. Go back to the admin console and refresh.
10. Select the "Users in Role" tab again and verify that the role information displays in the data table. 

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated
- [ ] Formatting has been performed via prettier/eslint
- [ ] Type checking has been performed via 'yarn check-types'

## Additional Notes

2021-02-25 07:56 UTC, edewit commented on cypress/integration/realm_roles_test.spec.ts
> +        .get("#users-empty-state > div > h4")
wouldn't we rather use `data-testid` instead of `id` or `data-cy`?

2021-02-25 08:15 UTC, edewit requested changes

2021-02-25 08:15 UTC, edewit commented on src/realm-roles/UsersInRoleTab.tsx
> +        {users.length == 0 ? (
you don't need this check the `<KeycloakDataTable` has a emptyState Property just add the empty state to that like this:

```tsx
      <KeycloakDataTable
          ....
          emptyState={
            <ListEmptyState
              hasIcon={true}
              message={t("noDirectUsers")}
              instructions={t("noUsersEmptyStateDescription")}
              id="users-empty-state"
          />
          }
      />
```

2021-02-25 13:50 UTC, jenny-s51 commented on src/realm-roles/UsersInRoleTab.tsx
> +        {users.length == 0 ? (
Thank you for suggesting this @edewit - I tried this initially but it seems the tab should only contain an empty state as shown here https://marvelapp.com/prototype/f39d464/screen/72685385

Adding it to the `emptyState` prop of `KeycloakDataTable` also renders a table toolbar with a search input field, but from the mock it looks like we don't want any toolbar or search input on the empty state.

2021-02-25 18:00 UTC, ssilvert commented on cypress/integration/realm_roles_test.spec.ts
> +        .get("#users-empty-state > div > h4")
@edewit  @jenny-s51 @mfrances17 We do need to standardize this.  Did we all agree that we would use data-testid?

2021-03-01 09:39 UTC, edewit commented on cypress/integration/realm_roles_test.spec.ts
> +        .get("#users-empty-state > div > h4")
we agreed on `data-testid` as it is less bound to the testing framework `cy` is derived from cypress

2021-03-01 09:41 UTC, edewit commented on src/realm-roles/UsersInRoleTab.tsx
> +        {users.length == 0 ? (
yes I've seen that and that and I have a fix for that in #387 but that is not merged yet

2021-03-01 14:39 UTC, jenny-s51 commented on cypress/integration/realm_roles_test.spec.ts
> +        .get("#users-empty-state > div > h4")
sounds good, will update with `data-testid`

2021-03-01 18:23 UTC, edewit requested changes

2021-03-01 18:23 UTC, edewit commented on src/realm-roles/UsersInRoleTab.tsx
> +  }, []);
This is not needed right?

2021-03-01 19:22 UTC, jenny-s51 commented on src/realm-roles/UsersInRoleTab.tsx
> +  }, []);
nice catch - updated

2021-03-01 20:55 UTC, ssilvert reviewed
- Needs pagination, but we can do that in another PR if you want.
- The help text for "Who appears in this list" should be hidden when global help is turned off.

2021-03-02 20:41 UTC, mfrances17 requested changes
Code looks good, followed the testing steps and it worked as expected.

Two comments that are both test-related:
I cannot get the final cypress test to pass, it fails on this line every time:

`cy.get("[data-testid=add-role-button]").click();`

I see you set a timeout before that action but apparently it's not enough. Maybe this can 
 be split out into its own test?
 
Also, you may want to consider creating functions in the create realm role page object for some of these test actions and then call them from the test. It seems we're standardizing on this kind of abstraction in the tests.

2021-03-03 07:15 UTC, edewit approved these changes
:+1: :1st_place_medal:

2021-03-03 14:59 UTC, jenny-s51 commented
Thank you for your helpful feedback @mfrances17 ! The cypress tests are now passing and I split out the calls into separate tests like you suggested. Please kindly re-review as soon as you get a chance 🙂

2021-03-03 21:24 UTC, mfrances17 approved these changes
LGTM - tests all pass now, good job

2021-03-03 21:24 UTC, merged