Group details
keycloak/keycloak-admin-ui pull request #425
Opened 2021-03-09 17:59 UTC by edewit

## Motivation
Added the group details to the group section

## Verification Steps

Go to the groups section create a couple of groups click on the group see the new group details

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated
- [ ] Formatting has been performed via prettier/eslint
- [ ] Type checking has been performed via 'yarn check-types'

## Additional Notes

2021-03-09 20:24 UTC, jenny-s51 requested changes
Subgroup functionality is looking good @edewit !

There seems to be a small bug with the `reload()` function in the attributes section...

To reproduce:

1) add a user attribute
2) click 'save'
3) click 'reload'
4) the user attribute field disappears even though the new value should be posted to the server, reload should not remove the field in this case
5) try the same thing in the realm roles section -> when you save an attribute and click 'reload' it does not remove the field for the most recently saved attribute (which is the expected behavior)

2021-03-09 20:24 UTC, jenny-s51 commented on src/realm-roles/RealmRolesSection.css
> -.kc-add-role-button {
Looks like we need this styling here

<img width="367" alt="Screen Shot 2021-03-09 at 3 05 18 PM" src="https://user-images.githubusercontent.com/32821331/110530876-e8b6e380-80e8-11eb-97bf-40708c8f298d.png">

2021-03-10 07:04 UTC, edewit commented on src/realm-roles/RealmRolesSection.css
> -.kc-add-role-button {
Oops seems like I moved one of the styles from here to the new component. But I don't think we even need it. I fixed it by wrapping the controls in `<ToolbarItem>`s

2021-03-10 19:54 UTC, mfrances17 requested changes
Found a couple of things. Also, Action > Delete Group and the Add Member button are not working, but that functionality might not be considered part of this PR, if so, ignore.

2021-03-10 19:54 UTC, mfrances17 commented on src/groups/Members.tsx
> +            <Button data-testid="addMember" variant="primary">
intentionally skipped and will be handled separately?

2021-03-10 19:54 UTC, mfrances17 commented on src/groups/GroupTable.tsx
> +              return deleteGroup(group);
we should provide a confirmation modal on delete, as we do in other parts of the UI

2021-03-11 06:44 UTC, edewit commented on src/groups/Members.tsx
> +            <Button data-testid="addMember" variant="primary">
yeah this PR was already getting big so I opted to do those in a separate PR

2021-03-11 06:46 UTC, edewit commented on src/groups/GroupTable.tsx
> +              return deleteGroup(group);
Right this was already there I'll create an issue for that #430

2021-03-11 14:20 UTC, mfrances17 approved these changes

2021-03-12 15:06 UTC, jenny-s51 requested changes
reload is not quite working as expected - when I click "reload" after saving a new attribute the field disappears ... after some investigating/testing these suggested changes fixed the reload for me 🙂

2021-03-12 15:06 UTC, jenny-s51 commented on src/groups/GroupAttributes.tsx
> +          attributes: convertAttributes(),
```suggestion
          attributes: attributes,
```

2021-03-12 15:06 UTC, jenny-s51 commented on src/groups/GroupAttributes.tsx
> +  attributesToArray,
```suggestion
  attributesToArray,
  KeyValueType,
```

2021-03-12 15:06 UTC, jenny-s51 commented on src/groups/GroupAttributes.tsx
> +
```suggestion
  const [ attributes, setAttributes ] = useState<KeyValueType[]>([]);

```

2021-03-12 15:06 UTC, jenny-s51 commented on src/groups/GroupAttributes.tsx
> +    const attributes = attributesToArray(attr || currentGroup().attributes!);
```suggestion
    const attributes = attributesToArray(attr || currentGroup().attributes!);
    setAttributes(attributes);
```

2021-03-15 07:48 UTC, edewit commented
thanks @jenny-s51 I fixed it a little different then you suggested... the reload was still broken after a save... I fixed that now as well

2021-03-16 12:14 UTC, jenny-s51 approved these changes
LGTM! 👍

2021-03-16 12:37 UTC, merged