Users: Adds user details tab and save/update functionality
keycloak/keycloak-admin-ui pull request #426
Opened 2021-03-09 19:35 UTC by jenny-s51

## Motivation

https://issues.redhat.com/browse/APPDUX-864

## Brief Description

Adds details tab to users section. 

## Verification Steps

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated
- [ ] Formatting has been performed via prettier/eslint
- [ ] Type checking has been performed via 'yarn check-types'

## Additional Notes

2021-03-10 07:09 UTC, edewit commented on cypress/support/pages/admin_console/manage/users/UserDetailsPage.ts
> +      this.saveBtn = "[data-testid=save-user]";
I've introduced an extension method for this you can set this to:
```suggestion
      this.saveBtn = "save-user";
```

2021-03-10 07:10 UTC, edewit commented on cypress/support/pages/admin_console/manage/users/UserDetailsPage.ts
> +      cy.get(this.saveBtn).click();
and here where you use it use:
```suggestion
      cy.getId(this.saveBtn).click();
```

2021-03-10 07:14 UTC, edewit requested changes
Very good PR nice work

2021-03-10 20:31 UTC, mfrances17 approved these changes
LGTM - everything worked great, including the tests

2021-03-11 20:22 UTC, edewit approved these changes

2021-03-11 20:23 UTC, merged