fixed visual and logical errors described in #423
keycloak/keycloak-admin-ui pull request #429
Opened 2021-03-10 13:42 UTC by edewit

fixing: #423

2021-03-16 15:14 UTC, mfrances17 requested changes
Some quick changes:

- 'reload' is now 'revert' in common messages, as per recent bug fix
- he had asked for more spacing between the two columns of auth flow checkboxes, i think you missed it:
![auth-flow-spacing](https://user-images.githubusercontent.com/39063664/111332876-8b6ee500-8648-11eb-87c9-772572e37a6d.png)

- the left margins for section heads are inconsistent between tabs - check out the difference between the settings tab and the advanced tab:
![settings-left-margin](https://user-images.githubusercontent.com/39063664/111332923-945fb680-8648-11eb-900e-4f3c76d097c9.png)

![advanced-left-margin](https://user-images.githubusercontent.com/39063664/111332940-988bd400-8648-11eb-9ed7-5e094e8893e5.png)

2021-03-16 15:14 UTC, mfrances17 commented on src/clients/ClientSettings.tsx
> +              {t("common:reload")}
this was changed to 'revert' in a recent bug fix

2021-03-16 18:55 UTC, jenny-s51 requested changes
Looking good @edewit ! 

A couple small things:

1) The login theme dropdown has a "blank" option that is clickable ... instead we probably want something like the client type dropdown where the default state has the "Select an option" text:
<img width="954" alt="Screen Shot 2021-03-16 at 2 51 30 PM" src="https://user-images.githubusercontent.com/32821331/111364065-270f4e00-8667-11eb-9531-f526d368f833.png">
2) In the "Advanced" tab the scroll form needs left padding. 

This can be fixed by updating form-panel.css as shown below:

```
.kc-form-panel__panel {
  padding-top: var(--pf-global--spacer--lg);
  padding-bottom: var(--pf-global--spacer--2xl);
  padding-left: var(--pf-global--spacer--lg); /* add this line */
  max-width: 768px;
}
```

2021-03-17 07:21 UTC, edewit commented
The left margins are fixed in the PR for the UXD review of the Advanced settings page

2021-03-17 13:05 UTC, mfrances17 approved these changes

2021-03-17 14:16 UTC, jenny-s51 approved these changes

2021-03-19 07:49 UTC, merged