Realm roles ux
keycloak/keycloak-admin-ui pull request #433
Opened 2021-03-11 21:27 UTC by jenny-s51

## Motivation

#416 

## Brief Description

Towards #416

- Removes the margin of the Role list, reference the latest style of the Client list.
- Removes the margin of the Associated Role list
- Search box in the toolbar: search now works by hitting enter
- When searching for something that doesn't have a matched result, show the header of the table instead of empty state
- Adds chip group functionality for filtering (TBD/ in discussion with @yih-wang regarding whether the realm roles section requires this kind of filtering)
- 

## Verification Steps

Verify that all the fixes listed above have been addressed 

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated
- [ ] Formatting has been performed via prettier/eslint
- [ ] Type checking has been performed via 'yarn check-types'

## Additional Notes

2021-03-15 08:03 UTC, edewit reviewed
I'm confused about these `filterChips` how are they supposed to work? I thought it would be that when I search for one term and then search for something else after that these terms would end up beneath the search input?

2021-03-16 09:17 UTC, yih-wang commented
> I'm confused about these `filterChips` how are they supposed to work? I thought it would be that when I search for one term and then search for something else after that these terms would end up beneath the search input?

Each time the user clicks the search, the term will show as a chip beneath the toolbar. Reference this demo - https://www.patternfly.org/v4/components/table/react-demos/#filterable

2021-03-16 15:43 UTC, mfrances17 requested changes
Aside from the filter chips, which we are handling as a separate issue, only one of the issues from the bulleted list of fixed items wasn't working in my testing. I am still getting the empty state when searching for a string that does not exist:

![search](https://user-images.githubusercontent.com/39063664/111337794-c2df9080-864c-11eb-97e7-56005e78dd01.png)

![result](https://user-images.githubusercontent.com/39063664/111337813-c6731780-864c-11eb-87d3-6991cbe03155.png)

2021-03-17 14:27 UTC, jenny-s51 commented
@mfrances17 thank you for your comment - I rebased and search empty state should now be addressed (https://github.com/keycloak/keycloak-admin-ui/pull/435). Please kindly re-review when you have a moment :)

2021-03-17 15:36 UTC, edewit commented on src/components/table-toolbar/KeycloakDataTable.tsx
> -  };
don't we still need this?

2021-03-17 15:38 UTC, edewit requested changes
Filtering still needed right?

2021-03-17 16:01 UTC, jenny-s51 commented on src/components/table-toolbar/KeycloakDataTable.tsx
> -  };
`filter` (which calles 'getNodeText`) is never used so eslint throws an error... this function was used to filter in real-time as the user types, right?

Per @yih-wang:

> It's better to keep consistency among all the search behaviors in a console. I looked into some other websites and think it's a common usage that return to the list by deleting the search input and search again. So let's keep using that. I update the clarification of the behaviors in this issue https://github.com/keycloak/keycloak-admin-ui/issues/417

2021-03-17 17:56 UTC, jenny-s51 commented
@edewit filter (which calls `getNodeText`) is never used here so eslint throws an error... this function was used to filter in real-time as the user types

Per @yih-wang:

> It's better to keep consistency among all the search behaviors in a console. I looked into some other websites and think it's a common usage that return to the list by deleting the search input and search again. So let's keep using that. I update the clarification of the behaviors in this issue #417

2021-03-18 21:53 UTC, mfrances17 approved these changes
The issue I had flagged about empty state on not finding a role name search result is now fixed... LGTM. Nice job.

2021-03-19 07:55 UTC, edewit requested changes
we still need filtering just not the while you type.

2021-03-19 07:55 UTC, edewit commented on src/components/table-toolbar/KeycloakDataTable.tsx
> -  };
Yes it was used to filter in real time, but we only want to change it that we no longer filter in real time not that we don't filter at all. If you remove this searching on the client scope page will no longer work.

2021-03-19 14:21 UTC, jenny-s51 commented
@edewit that makes sense - thank you for clarifying! Updated to use the filter function again

2021-03-22 08:14 UTC, edewit approved these changes

2021-03-22 08:14 UTC, merged