changed time select order + added success message
keycloak/keycloak-admin-ui pull request #447
Opened 2021-03-16 08:55 UTC by edewit

fixes: #445

2021-03-16 09:20 UTC, edewit commented
now wraps the column title:
![image](https://user-images.githubusercontent.com/51133/111285301-4a270700-8641-11eb-96ff-e28e2a54987f.png)

2021-03-16 18:30 UTC, mfrances17 requested changes
Code looks good! One small issue, the rest seems to be working well to address the issues in 445

2021-03-16 18:30 UTC, mfrances17 commented on src/clients/initial-access/CreateInitialAccessToken.tsx
> +              defaultValue={86400}
expiration needs a min val of 1, as per the UX review... i was able to select blank and 0, and type a negative value

2021-03-17 07:04 UTC, edewit commented on src/clients/initial-access/CreateInitialAccessToken.tsx
> +              defaultValue={86400}
This is behavior we need as per old console

2021-03-17 13:04 UTC, mfrances17 commented on src/clients/initial-access/CreateInitialAccessToken.tsx
> +              defaultValue={86400}
ok

2021-03-17 13:04 UTC, mfrances17 approved these changes

2021-03-17 19:14 UTC, jenny-s51 approved these changes

2021-03-18 08:07 UTC, merged