alphabetize and sort roles in associated roles table
keycloak/keycloak-admin-ui pull request #451
Opened 2021-03-18 18:36 UTC by jenny-s51

## Motivation

Towards #416 

## Verification Steps

1. Go to Realm Roles section.
2. Click on a role. 
3. Add a few associated roles.
4. Verify that the roles are alphabetized. 
5. Search for a particular associated role in the search input field. 
6. Click the search button and verify that filtering works as expected.

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated
- [ ] Formatting has been performed via prettier/eslint
- [ ] Type checking has been performed via 'yarn check-types'

## Additional Notes

2021-03-22 18:59 UTC, ssilvert requested changes
Looks good except for one stray console log.  Need someone on UXD team to review before we merge though.

2021-03-22 18:59 UTC, ssilvert commented on src/realm-roles/AssociatedRolesTab.tsx
> +  console.log(selectedRows);
Remove.

2021-03-23 08:43 UTC, yih-wang commented
The search of the Add associated roles modal doesn't work. 
![image](https://user-images.githubusercontent.com/23331885/112117932-d6639c00-8bf6-11eb-9874-74760597cb6c.png)
![image](https://user-images.githubusercontent.com/23331885/112117956-dcf21380-8bf6-11eb-8cc8-bbb1d0f5c321.png)

2021-03-26 14:38 UTC, jenny-s51 commented
@yih-wang thank you for your feedback! I've addressed the `revert` in this PR , the pagination/search in #460, and opened a separate issue for the implementation of disabled kebabs/checkboxes. Please kindly review again when you have a moment :)

2021-03-26 17:29 UTC, mfrances17 requested changes
When testing the Attributes tab, the Key and Value fields only show up for 1 of my 5 defined roles - the design says they should be visible by default. So obviously i’m only able to add, save, etc on this one role. Is this working as expected - is this prevented for those other 4 roles because of permission(s) or the type of defined role? this by design or is it an issue?

2021-03-26 17:33 UTC, jenny-s51 commented
@mfrances17 thank you for your comment; nice catch! There was no initial key/value field in the attributes tab as soon as a role was created. I just fixed this - let me know if you're able to see the fields now 🙂

2021-03-26 17:41 UTC, mfrances17 approved these changes
Ok, great... your latest push fixes the issue I was experiencing with no default key/value empty fields. LGTM.

2021-03-29 11:35 UTC, merged