Fix roles pagination
keycloak/keycloak-admin-ui pull request #460
Opened 2021-03-24 14:16 UTC by jenny-s51

## Motivation

## Brief Description

## Verification Steps

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated
- [ ] Formatting has been performed via prettier/eslint
- [ ] Type checking has been performed via 'yarn check-types'

## Additional Notes

2021-03-26 15:11 UTC, mfrances17 requested changes
Changes look good, and behave as expected. One thing that may be worth looking into... when i click to show the next 10 items in the pagination, it briefly shows '11-20' then changes to '11-19'. And when I click to go back to '1-10', it briefly displays '1-9' then '1-10'. Maybe this can be handled in a separate issue from this PR?

2021-03-29 06:34 UTC, edewit requested changes

2021-03-29 06:34 UTC, edewit commented on src/components/table-toolbar/KeycloakDataTable.tsx
> +        const sliced = data.slice(first!, first! + max!);
you need to keep the result in state because the loader is only called once.

2021-03-29 06:34 UTC, edewit commented on src/realm-roles/AssociatedRolesModal.tsx
> +  const loader = async (first?: number, max?: number, search?: string) => {
```suggestion
  const loader = async (_first?: number, _max?: number, search?: string) => {
```
first and max are not used

2021-03-29 06:34 UTC, edewit commented on src/realm-roles/AssociatedRolesModal.tsx
> +    };
```suggestion
```
don't think you need this

2021-03-29 06:34 UTC, edewit commented on src/realm-roles/AssociatedRolesModal.tsx
> +    }
```suggestion
```
this can go as well

2021-03-29 06:34 UTC, edewit commented on src/realm-roles/AssociatedRolesModal.tsx
> +    }
```suggestion
```

2021-03-29 15:36 UTC, jenny-s51 commented on src/components/table-toolbar/KeycloakDataTable.tsx
> +        const sliced = data.slice(first!, first! + max!);
reverting for now based on your changes in https://github.com/keycloak/keycloak-admin-ui/pull/472

2021-03-29 15:43 UTC, jenny-s51 commented
@mfrances17 thank you for your feedback - I've been trying to reproduce this issue and can't seem to get the behavior you're seeing ... are you still running into this bug?

2021-03-30 18:48 UTC, mfrances17 reviewed
i've spent half an afternoon but am still unable to get this code to run, but it seems to work for others, so i'm removing myself from the review approval list

2021-03-31 12:58 UTC, edewit requested changes
Just remove the `isPaginated` from the `KeycloakDatatable` and all the filtering logic.

2021-03-31 12:58 UTC, edewit commented on src/realm-roles/AssociatedRolesModal.tsx
> +    };
you don't need this searching is handled by the `KeycloakDatatabe`

2021-03-31 20:07 UTC, jenny-s51 commented
@ssilvert reverted my latest changes - the assign role modal should be working now. I added those WIP changes to https://github.com/jenny-s51/keycloak-admin/tree/addFilterType in order to address #480, which @edewit and I have been discussing today - I spent the afternoon debugging the search input and will have a separate PR up for it soon

2021-03-31 23:26 UTC, ssilvert commented
@jenny-s51  When I go to the "Add roles" dialog I get lots of 404 errors and other errors in the console.

2021-04-01 00:07 UTC, ssilvert approved these changes
I'm OK with merging this, but I'd like approval from @edewit as well since he has been involved.

2021-04-01 13:41 UTC, edewit approved these changes
we can fixe the filter in a separate Pr

2021-04-01 13:41 UTC, merged