WIP: Created add service account roles assign screen
keycloak/keycloak-admin-ui pull request #465
Opened 2021-03-26 14:58 UTC by edewit

## Motivation

Service account roles assign screen as designed [marvel](https://marvelapp.com/prototype/f058374/screen/71931944)

## Brief Description

Couldn't put the filter dropdown next to the search filter as the select needs to be a direct child of the modal.
Maybe somebody with some more css skills can have a look

## Verification Steps

Create a service account client and go to the service account tab and press assign

## Checklist:

- [x] Code has been tested locally by PR requester
- [x] User-visible strings are using the react-i18next framework (useTranslation)
- [x] Help has been implemented
- [x] axe report has been run and resulting a11y issues have been resolved
- [x] Unit tests have been created/updated
- [x] Formatting has been performed via prettier/eslint
- [x] Type checking has been performed via 'yarn check-types'

## Additional Notes

2021-03-31 14:45 UTC, jenny-s51 commented on src/clients/service-account/AddServiceAccountModal.tsx
> +          key="confirm"
```suggestion
          isDisabled={selectedRows?.length === 0}
```

2021-03-31 14:47 UTC, jenny-s51 requested changes
LGTM @edewit - role assignment works as expected! Just one small suggested update to disable the "Assign" button if no roles are selected ... currently an error gets thrown if you click "Assign" without selecting anything.

2021-04-01 07:15 UTC, edewit commented
thanks @jenny-s51

2021-04-01 14:14 UTC, ssilvert approved these changes
I'm going to go ahead and merge this before the holiday weekend.  I'll open some issues for things I think should be addressed.

2021-04-01 14:14 UTC, merged