Users(groups): list top level groups, implement direct membership check
keycloak/keycloak-admin-ui pull request #467
Opened 2021-03-26 20:09 UTC by jenny-s51

## Motivation

#466 

## Brief Description

## Verification Steps

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated
- [ ] Formatting has been performed via prettier/eslint
- [ ] Type checking has been performed via 'yarn check-types'

## Additional Notes

2021-03-29 06:49 UTC, edewit approved these changes
:+1:

2021-03-29 19:20 UTC, ssilvert requested changes
If I have group A/B/C and then I join group C, only A and C will be shown in the list.

2021-04-01 18:34 UTC, ssilvert commented
@jenny-s51 It is now showing indirect membership but it is not as per spec.  When you show the indirect group, it should have its checkbox disabled and the "Leave" link should not appear.

2021-04-01 18:46 UTC, ssilvert approved these changes

2021-04-01 18:47 UTC, merged