Allow four ways to set location of keycloak server.
keycloak/keycloak-admin-ui pull request #482
Opened 2021-03-30 19:40 UTC by ssilvert

## Motivation
Need to be able to run new admin console from keycloak.org.

## Brief Description
Four ways to set location of Keycloak server:

1. http://anydomain/anycontext/?keyclaok-server=http://my-keycloak-server.com
2. Usual dev mode, which defaults server to http://localhost:8180
3. Demo mode, http://anydomain/adminv2/?demo=true, which defaults server to http://localhost:8080
4. Integrated into keycloak server, http://keycloak-server-domain/adminv2

## Verification Steps
Try out any or all of the modes above.

## Checklist:

- [X] Code has been tested locally by PR requester
- [NA] User-visible strings are using the react-i18next framework (useTranslation)
- [NA] Help has been implemented
- [NA] axe report has been run and resulting a11y issues have been resolved
- [NA] Unit tests have been created/updated
- [X] Formatting has been performed via prettier/eslint
- [X] Type checking has been performed via 'yarn check-types'

2021-04-01 06:59 UTC, edewit requested changes

2021-04-01 06:59 UTC, edewit commented on src/context/auth/keycloak.ts
> +    return "http://localhost:8180" + authContext;
Shouldn't dev mode be only `authContext` until the CORS issue is solved?

2021-04-01 23:29 UTC, ssilvert commented on src/context/auth/keycloak.ts
> +    return "http://localhost:8180" + authContext;
@edewit The CORS issue is solved and merged yesterday: https://github.com/keycloak/keycloak/pull/7891

Did this not work for you?  I'll change it to plain authContext if it's not working with older keycloak servers.

2021-04-02 00:09 UTC, ssilvert commented on src/context/auth/keycloak.ts
> +    return "http://localhost:8180" + authContext;
@edewit You were right of course.  With a different port it's considered a different domain.

I changed it so it will continue to work in dev.  We can change it back once everyone is able to upgrade to Keycloak 13.

2021-04-06 06:44 UTC, edewit approved these changes
:+1:

2021-04-06 06:44 UTC, merged