Realm roles(associated roles): fix search filtering bug
keycloak/keycloak-admin-ui pull request #497
Opened 2021-04-01 18:54 UTC by jenny-s51

## Motivation

#480 

## Verification Steps

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated
- [ ] Formatting has been performed via prettier/eslint
- [ ] Type checking has been performed via 'yarn check-types'

## Additional Notes

2021-04-07 07:31 UTC, edewit requested changes

2021-04-07 07:31 UTC, edewit commented on src/realm-roles/AssociatedRolesModal.tsx
> +
you don't need this change, right?

2021-04-07 07:31 UTC, edewit commented on src/realm-roles/AssociatedRolesModal.tsx
> +    );
don't need this, this is done in KeycloakDataTable

2021-04-07 07:31 UTC, edewit commented on src/realm-roles/AssociatedRolesModal.tsx
> +    );
same here

2021-04-07 07:31 UTC, edewit commented on src/realm-roles/AssociatedRolesTab.tsx
> +// import { AliasRendererComponent } from "./AliasRendererComponent";
this can be removed
```suggestion
```

2021-04-08 19:00 UTC, ssilvert commented
@edewit Please re-review.

2021-04-09 06:44 UTC, edewit requested changes

2021-04-09 06:44 UTC, edewit commented on src/components/table-toolbar/KeycloakDataTable.tsx
> +      }
I think this can be simplified to:

```suggestion
   setRows(
        (filteredData || rows).map((row) => {
          row.selected = isSelected;
          return row;
        })
      );
```

2021-04-09 06:44 UTC, edewit commented on src/components/table-toolbar/KeycloakDataTable.tsx
> +
Same here? Could it be replaced by:
```suggestion
      (filteredData || rows)[rowIndex].selected = isSelected;
```

2021-04-09 13:31 UTC, jenny-s51 commented on src/components/table-toolbar/KeycloakDataTable.tsx
> +
Thank you for your helpful suggestions @edewit ! I tested this one out - if we make this change, the selected items do not remain selected if a user enters a search filter (all the selected items will get reset).

2021-04-09 13:39 UTC, jenny-s51 commented
Thank you for your helpful suggestions @edewit

2021-04-09 15:08 UTC, merged