disable when nothing selected
keycloak/keycloak-admin-ui pull request #508
Opened 2021-04-07 06:21 UTC by edewit

fixing: #495

fixing: #493

2021-04-07 07:27 UTC, edewit commented
instead of #501 to enable the CI checks

2021-04-07 19:06 UTC, ssilvert requested changes
Now if I go to assign a service account role for a client called "foo", the header will say "Assign roles to account".  It should say "Assign roles to foo service account".

The Assign button is disabled until I check a box, but then if I uncheck the box it stays enabled.  

Lastly, you might as well go ahead and make the Cancel button be the link style since this is what we decided to do.

2021-04-08 19:58 UTC, jenny-s51 approved these changes
Looks good 👍

2021-04-09 13:23 UTC, ssilvert approved these changes

2021-04-09 13:23 UTC, merged