Begin implementation of Partial Import modal.
keycloak/keycloak-admin-ui pull request #515
Opened 2021-04-09 19:18 UTC by ssilvert

## Motivation
Start to implement Partial Import: [Marvel](https://marvelapp.com/prototype/fg26f9b/screen/75624791)

## Brief Description
This just handles:

- Open/Close Partial import dialog
- Enable/Disable import button when json added or cleared
- Show/Hide (unfinished) [section for "choose resources" and "if resource exists"](https://marvelapp.com/prototype/fg26f9b/screen/75624792)
- Implement Cancel

## Verification Steps
Go to Realm Settings -> Actions menu -> Partial Import
Verify above works as expected.

## Checklist:

- [X] Code has been tested locally by PR requester
- [X] User-visible strings are using the react-i18next framework (useTranslation)
- [NA] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [X] Unit tests have been created/updated
- [X] Formatting has been performed via prettier/eslint
- [X] Type checking has been performed via 'yarn check-types'

2021-04-12 06:18 UTC, edewit approved these changes

2021-04-13 16:51 UTC, jenny-s51 commented on cypress/integration/partial_import_test.spec.ts
> +    console.log("beforeEach");
```suggestion
```

2021-04-13 16:52 UTC, jenny-s51 requested changes
Looks great @ssilvert ! Just one `console.log` to delete

2021-04-13 17:57 UTC, ssilvert commented on cypress/integration/partial_import_test.spec.ts
> +    console.log("beforeEach");
Oops.  Thanks @jenny-s51.

2021-04-13 18:10 UTC, jenny-s51 approved these changes

2021-04-13 18:40 UTC, mfrances17 requested changes
Code looks good. 

This could just be my lacking knowledge of keycloak, but for testing I did the following:
In old admin console:
1. Selected Manage/Export and enabled both switches ('export groups and roles' and 'export clients').
In new admin console:
1. Created a new realm.
1. Imported the realm settings using the partial import UI in this PR.

When verifying the data, i did see some clients and resources in the new realm, but no users data was imported and i assume no users data was exported. But the partial import UI says it allows you to import **users**, clients, and resources, so the wording should probably change.

2021-04-13 18:40 UTC, mfrances17 commented on src/realm-settings/messages.json
> -}
might want to add an empty line at EOF to avoid this warning

2021-04-14 14:17 UTC, ssilvert reviewed
> When verifying the data, i did see some clients and resources in the new realm, but no users data was imported and i assume no users data was exported. But the partial import UI says it allows you to import **users**, clients, and resources, so the wording should probably change.

@mfrances17 Partial import does allow import of uses but partial export does not allow export of users.  To export users (and everything else), there are some switches you can pass in during server startup.

So it's a little weird, but the text is correct.

2021-04-14 14:17 UTC, ssilvert commented on src/realm-settings/messages.json
> -}
Interestingly, there is already a newline at EOF in my editor.  The json is correct so I'm not going to worry about it.

2021-04-14 14:17 UTC, merged