Users(Consents): add empty state
keycloak/keycloak-admin-ui pull request #516
Opened 2021-04-09 19:28 UTC by jenny-s51

## Motivation

## Brief Description

## Verification Steps

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated
- [ ] Formatting has been performed via prettier/eslint
- [ ] Type checking has been performed via 'yarn check-types'

## Additional Notes

2021-04-12 23:40 UTC, ssilvert requested changes

2021-04-12 23:40 UTC, ssilvert commented on src/user/messages.json
> +    "noConsentsText": "The consents will only be recorded when users try to access a client that is configured to require consent. In that case, users will get a consent page which asks them to grant
The last sentence and its link don't make any sense.  A user isn't assigned to one particular client, so there is no point in going to a client settings page.  You wouldn't know which one to go to anyway.  I think you can just remove the last sentence and the "Settings" link.  I believe we need to change the design.

Other than that, this PR looks good to me.

2021-04-13 15:13 UTC, jenny-s51 commented on src/user/messages.json
> +    "noConsentsText": "The consents will only be recorded when users try to access a client that is configured to require consent. In that case, users will get a consent page which asks them to grant
Agreed - will update

2021-04-13 20:49 UTC, mfrances17 approved these changes
LGTM... both the empty state and populated consents tab look good.

2021-04-14 18:39 UTC, merged