Users(Create user form): Update create user form with new design
keycloak/keycloak-admin-ui pull request #542
Opened 2021-04-20 13:02 UTC by jenny-s51

## Motivation

https://issues.redhat.com/browse/APPDUX-912

## Verification Steps

1. Go to Users section. 
2. Click "Add user"
3. Create the new user and add groups to the user within the form.
4. Verify that groups selected show up in the "Groups" tab once the user is created.

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated
- [ ] Formatting has been performed via prettier/eslint
- [ ] Type checking has been performed via 'yarn check-types'

## Additional Notes

2021-04-20 21:09 UTC, mfrances17 requested changes
Functionality is working great... tested creating a new user and adding groups directly in the add. Small change required, you probably want to localize the hardcoded strings.

2021-04-20 21:09 UTC, mfrances17 commented on src/user/JoinGroupDialog.tsx
> +        username ? `Join groups for user ${username}` : "Select groups to join"
these strings should be localized

2021-04-21 05:47 UTC, edewit approved these changes
Apart from the comment of @mfrances17 looking good

2021-04-21 13:54 UTC, jenny-s51 commented on src/user/JoinGroupDialog.tsx
> +        username ? `Join groups for user ${username}` : "Select groups to join"
Nice catch - localized

2021-04-21 14:17 UTC, mfrances17 approved these changes

2021-04-21 14:17 UTC, mfrances17 approved these changes
LGTM, good job

2021-04-21 14:17 UTC, merged