Realm settings(themes): Add themes tab + tests
keycloak/keycloak-admin-ui pull request #544
Opened 2021-04-22 18:49 UTC by jenny-s51

## Motivation

https://issues.redhat.com/browse/APPDUX-939

## Brief Description

Adds themes tab, cypress tests for Realm Settings

## Verification Steps

1. Go to Realm Settings -> Themes tab.
2. Populate fields and save.
3. Navigate to another location in Keycloak and return to Realm Settings -> Themes tab.
4. Verify that the data saves correctly.

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated
- [ ] Formatting has been performed via prettier/eslint
- [ ] Type checking has been performed via 'yarn check-types'

2021-04-23 19:01 UTC, ssilvert requested changes
You are getting the wrong values for the theme dropdowns.  Each theme type (Login, Account, Admin Console, Email) has its own set of themes.  It looks like you are using the same values for all of them.

For instance `keycloak.v2` will only show up for the account theme.

2021-04-26 14:03 UTC, edewit requested changes

2021-04-26 20:27 UTC, jenny-s51 commented on src/realm-settings/ThemesTab.tsx
> +  const themeTypes = ["base", "keycloak", "keycloakV2"];
nice catch - thank you

2021-04-26 20:28 UTC, jenny-s51 commented on src/realm-settings/ThemesTab.tsx
> +  ];
sounds good, working on this

2021-04-27 19:55 UTC, ssilvert requested changes
@jenny-s51  Everything is working well now.  Just one comment on the code.

2021-04-27 19:55 UTC, ssilvert commented on src/realm-settings/messages.json
> +    },
This stuff is not needed, right?

2021-04-27 20:10 UTC, jenny-s51 commented on src/realm-settings/messages.json
> +    },
We do need this - it translates the ISO codes to the language of the locale as in the mock: https://marvelapp.com/prototype/6fd5iga/screen/75632704. 

They get localized/translated here:
https://github.com/keycloak/keycloak-admin-ui/pull/544/files#diff-aa0d9341b1e4e3e2c1857217bc2d047d4ba69d985f5da6dc670c2db755cdc062R351

I tried doing this with [the `Intl.DisplayNames()` constructor ](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DisplayNames/DisplayNames) as @edewit suggested but it looks like TS does not recognize the `DisplayNames` prop on `Intl` without an external package/polyfill.

2021-04-28 05:59 UTC, edewit commented on src/realm-settings/messages.json
> +    },
Yeah there is no safari support for that yet, that's why it's not part of typescript. @ssilvert we also have this in the old console.

2021-04-29 00:11 UTC, ssilvert commented on src/realm-settings/messages.json
> +    },
@edewit @jenny-s51 OK.  That makes sense for the locales.  We can add a package later if needed.

But I still question lines 42-46.  What is the reason for hard-coded theme names?  We get those from serverinfo, right?

2021-04-29 06:58 UTC, edewit commented on src/realm-settings/messages.json
> +    },
@ssilvert right we don't need those

2021-04-29 12:58 UTC, jenny-s51 commented on src/realm-settings/messages.json
> +    },
👍 removed theme types @ssilvert @edewit

2021-04-29 13:11 UTC, edewit approved these changes

2021-04-29 17:39 UTC, ssilvert approved these changes

2021-04-29 17:39 UTC, merged