add OIDC provider to the idp section
keycloak/keycloak-admin-ui pull request #553
Opened 2021-04-27 14:12 UTC by edewit

## Motivation

implements:
     OIDC provider details - General
     OIDC provider details - OIDC settings
     OIDC provider details - Advanced
     github provider details - Advanced

## Brief Description

## Verification Steps

## Checklist:

- [x] Code has been tested locally by PR requester
- [x] User-visible strings are using the react-i18next framework (useTranslation)
- [x] Help has been implemented
- [x] axe report has been run and resulting a11y issues have been resolved
- [x] Unit tests have been created/updated
- [x] Formatting has been performed via prettier/eslint
- [x] Type checking has been performed via 'yarn check-types'

## Additional Notes

2021-04-30 01:24 UTC, ssilvert requested changes
Help text is wrong for `Post Login Flow` and `Sync Mode`.

Also, the dropdown for `Sync Mode` is partially obstructed.
![SyncModeObstructed](https://user-images.githubusercontent.com/507202/116637186-30abf700-a931-11eb-9657-67bdd939df82.png)

2021-04-30 05:57 UTC, edewit commented on src/identity-providers/messages.json
> +    "scopes": "Scopes",
It's called scopes in the design? @xianli123

2021-04-30 06:09 UTC, edewit commented
@ssilvert don't have the problem that the dropdown is obscured I can still use it:
![image](https://user-images.githubusercontent.com/51133/116655349-3cc4a280-a98b-11eb-85f9-df2d8f589132.png)
@xianli123 is good like this or do you agree with @ssilvert and should we look at how to change this?

2021-04-30 09:14 UTC, yih-wang commented on src/identity-providers/messages.json
> +    "scopes": "Scopes",
Right, the word "default scopes" doesn't fit the scenario. So changed it.

2021-04-30 09:19 UTC, yih-wang commented
@edewit I'm good with your screenshot.

2021-04-30 12:49 UTC, ssilvert commented on src/identity-providers/messages.json
> +    "scopes": "Scopes",
OK

2021-04-30 13:05 UTC, ssilvert commented
> @ssilvert don't have the problem that the dropdown is obscured I can still use it:
> ![image](https://user-images.githubusercontent.com/51133/116655349-3cc4a280-a98b-11eb-85f9-df2d8f589132.png)
> @xianli123 is good like this or do you agree with @ssilvert and should we look at how to change this?

It can still be used, but the bottom of the dropdown and the label are cut off.  Does yours look like mine when the dropdown is closed?

Looks like it just needs some spacing at the bottom of the form.

2021-05-04 07:49 UTC, edewit commented
@ssilvert no when I scroll all the way down it looks like this:
![image](https://user-images.githubusercontent.com/51133/116974168-f68a7e80-acbd-11eb-8140-c7a11c3b0b9c.png)

2021-05-04 11:19 UTC, ssilvert commented
> @ssilvert no when I scroll all the way down it looks like this:
> ![image](https://user-images.githubusercontent.com/51133/116974168-f68a7e80-acbd-11eb-8140-c7a11c3b0b9c.png)

@edewit OK.  In that case, let's just fix the conflicts and merge.  We can let this slide for now.

2021-05-06 18:58 UTC, ssilvert approved these changes

2021-05-06 18:59 UTC, merged