Realm settings keys
keycloak/keycloak-admin-ui pull request #555
Opened 2021-04-28 20:45 UTC by jenny-s51

WIP realm settings keys

2021-04-30 18:47 UTC, ssilvert commented
@jenny-s51 Please fix conflicts.

2021-04-30 19:44 UTC, jenny-s51 commented
@ssilvert fixed

2021-05-14 17:58 UTC, ssilvert requested changes
@jenny-s51 Everything looks good and works right.  

Just had a couple of refactoring suggestions but up to you if you want to implement.

However, I don't see any tests for this page.  We do need tests.

2021-05-14 17:58 UTC, ssilvert commented on src/realm-settings/KeysListTab.tsx
> +            </Button>
Looks like this same button is repeated above.  It can be refactored into one.

2021-05-14 17:58 UTC, ssilvert commented on src/realm-settings/KeysListTab.tsx
> +    } else if (provider === "rsa-generated" || provider === "fallback-RS256") {
"else if" is not needed.  Just "if" should work here.

2021-05-14 17:58 UTC, ssilvert commented on src/realm-settings/KeysTab.tsx
> +    } else if (provider === "rsa-generated" || provider === "fallback-RS256") {
"else if" can be just "if".

2021-05-14 18:32 UTC, jenny-s51 commented on src/realm-settings/KeysListTab.tsx
> +            </Button>
good suggestion - done

2021-05-14 18:58 UTC, ssilvert approved these changes

2021-05-14 18:58 UTC, merged