filter recent used realms as well as others
keycloak/keycloak-admin-ui pull request #580
Opened 2021-05-04 07:43 UTC by edewit

fixing: #577

2021-05-04 10:29 UTC, jonkoops requested changes

2021-05-04 10:29 UTC, jonkoops commented on src/components/realm-selector/RealmSelector.tsx
> +    );
This will create a new instance and also do a possibly expensive transformation on every render. To prevent this you can memoize the value.

```ts
// This will prevent new instances of 'RecentUsed' from being constructed on every render.
// Instead only a single instance will be created an memoized beteen render cycles.
const recentUsed = useMemo(() => new RecentUsed(), []);

// Here 'all' will only be recalculated if one of it's dependencies change.
const all = useMemo<RecentUsedRealm[]>(() => recentUsed.used
  .map((name) => ({ name, used: true }))
  .concat(realms
    .filter((r) => !recentUsed.used.includes(r.realm!))
    .map((r) => ({ name: r.realm!, used: false }))
  ),
  [recentUsed.used, realms]
)
```

2021-05-04 10:29 UTC, jonkoops commented on src/components/realm-selector/RealmSelector.tsx
> +  const [filteredItems, setFilteredItems] = useState<RecentUsedRealm[]>();
Instead of using a side-effect when `search` change it would make more sense to make `filteredItems` a memoized value based on on `search`, so basically a computed property.

For example, if we remove the `onFilter` function we can do this:

```ts
const filteredItems = useMemo(() => {
  if (search === "") {
    return undefined;
  }

  return all.filter((r) => r.name.toLowerCase().includes(search.toLowerCase()))
}, [search, all])
```

This relies on the assumption that the `onSearchButtonClick` event is not actually really needed as `onSearchInputChange` already updates the `search` value which subsequently triggers the side-effect to update the results.

2021-05-04 10:29 UTC, jonkoops commented on src/components/realm-selector/RealmSelector.tsx
> +          {(filteredItems || all).map((item) => (
Note that you can also use the [nullish coalescing operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator) here to expicitly handle `undefined` and `null` values instead of 'falsy' values.

```suggestion
          {(filteredItems ?? all).map((item) => (
```

2021-05-05 14:04 UTC, edewit commented on src/components/realm-selector/RealmSelector.tsx
> +          {(filteredItems || all).map((item) => (
you suggested that somewhere else as well I don't see the value in it as this list of items can only be undefined or an array of strings

2021-05-05 14:09 UTC, edewit commented on src/components/realm-selector/RealmSelector.tsx
> +  const [filteredItems, setFilteredItems] = useState<RecentUsedRealm[]>();
Why would that be better?

2021-05-05 15:29 UTC, jonkoops commented on src/components/realm-selector/RealmSelector.tsx
> +          {(filteredItems || all).map((item) => (
Yeah, this is just a personal preference.

2021-05-05 15:55 UTC, jonkoops commented on src/components/realm-selector/RealmSelector.tsx
> +  const [filteredItems, setFilteredItems] = useState<RecentUsedRealm[]>();
In my opinion it is better because is immediately clear that `filteredItems` is a derived value from `search` and `all`. Whereas in the original code this is handled a little less transparently because you first have to set a different value, and then wait for a side-effect to be triggered, which will then set's the actual state you want.

Besides that all the logic is isolated in a single block of code, instead of spread out through the file in different places.

Also if for some reason in the future `search` would get a value that is not empty by default (for example coming from a query parameter) the following would happen.

1. The value of `search` is set to a value like `Hello World`
2. The component renders with `filteredItems` set to `undefined`
3. The `useEffect` triggers
4. The value of `filteredItems` is set to the actual content we want
5. This causes the component to rerender again since state has changed

This would mean that the component re-renders for no reason besides that we are doing this in a `useEffect`. This is due to fact that a `useEffect` is triggered **after** a render takes place (see the [React documentation](https://reactjs.org/docs/hooks-effect.html#example-using-hooks)). 

You can see this happen in this example: https://stackblitz.com/edit/react-ts-kfllpr
Wheras with a `useMemo` it only renders once: https://stackblitz.com/edit/react-ts-kbq7rk

2021-05-05 19:59 UTC, jenny-s51 reviewed
Looks and works great @edewit 👍 I like @jonkoops's suggestion with the `useMemo` hook

2021-05-05 19:59 UTC, jenny-s51 commented on src/components/realm-selector/RealmSelector.tsx
> +    );
This is a good idea.

2021-05-05 20:00 UTC, jenny-s51 commented on src/components/realm-selector/RealmSelector.tsx
> +    );
> This will create a new instance and also do a possibly expensive transformation on every render. To prevent this you can memoize the value.
> 
> ```ts
> // This will prevent new instances of 'RecentUsed' from being constructed on every render.
> // Instead only a single instance will be created and memoized beteen render cycles.
> const recentUsed = useMemo(() => new RecentUsed(), []);
> 
> // Here 'all' will only be recalculated if one of it's dependencies change.
> const all = useMemo<RecentUsedRealm[]>(() => recentUsed.used
>   .map((name) => ({ name, used: true }))
>   .concat(realms
>     .filter((r) => !recentUsed.used.includes(r.realm!))
>     .map((r) => ({ name: r.realm!, used: false }))
>   ),
>   [recentUsed.used, realms]
> )
> ```

This is a good idea.

2021-05-18 14:59 UTC, jenny-s51 approved these changes
Looks great!

2021-05-19 12:35 UTC, merged