Realm settings(add providers tab)
keycloak/keycloak-admin-ui pull request #585
Opened 2021-05-04 19:28 UTC by jenny-s51

## Motivation

## Brief Description

## Verification Steps

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated
- [ ] Formatting has been performed via prettier/eslint
- [ ] Type checking has been performed via 'yarn check-types'

## Additional Notes

2021-05-06 09:15 UTC, edewit approved these changes

2021-05-18 08:38 UTC, edewit requested changes

2021-05-18 08:38 UTC, edewit commented on src/realm-settings/KeysListTab.tsx
> +
Don't need to add these console logs right?
```suggestion
```

2021-05-18 15:14 UTC, mfrances17 requested changes
Having some discrepancies while testing, not sure if they should be covered in this PR or not:

- When i create a new key, the public key and certificate aren't listed for the new algorithm:
Old:
![old](https://user-images.githubusercontent.com/39063664/118676608-8bff3580-b7c9-11eb-8265-24f0f8221396.png)
New:
![new](https://user-images.githubusercontent.com/39063664/118676656-94f00700-b7c9-11eb-9900-5d3925a86a11.png)

- In the providers tab, when i click the dots to the left of the Name, nothing happens (I would expect it to have a delete as the old console had but presented differently?)
- In the providers tab, nothing happens when i click any of the names (I would expect the equivalent of the old console's Edit command)

If these are out of the scope of this PR, they can be logged and handled as Issues, not sure how much this PR was intending to cover.

2021-05-18 15:59 UTC, jenny-s51 commented
Thank you @mfrances17! I've updated the public key/certificate to show based on the type rather than the provider name - that should fix the issue you noticed.

In the providers tab, the dots to the left of the name signify the draggable rows as per the design. This PR includes the dragging functionality. https://marvelapp.com/prototype/99i86j9/screen/75627938

I have a separate PR up for the functionality to delete rows and sorting by priority: #606 

Per your suggestion I've also opened #616 to address the edit functionality. I'm currently working on the "create provider" modal and once it's done I plan to use some of that code for the implementation of the edit form.

2021-05-20 13:48 UTC, edewit approved these changes

2021-05-20 15:44 UTC, mfrances17 approved these changes
LGTM, changes look good. Thanks for following up with filing the issues etc. Let's get this functionality merged in.

2021-05-20 15:44 UTC, merged