Fixed bug
keycloak/keycloak-admin-ui pull request #588
Opened 2021-05-06 08:41 UTC by edewit

`Console display name` had a default value of `ldap` making the tests fail
also added a small refactor to the tests putting declare and assign in the same line

2021-05-06 13:14 UTC, mfrances17 requested changes

2021-05-06 13:14 UTC, mfrances17 commented on src/user-federation/ldap/LdapSettingsGeneral.tsx
> -            defaultValue="ldap"
@edewit The default value of 'ldap' was just recently added a few days ago as a must-fix request by UX (see item 2): https://github.com/keycloak/keycloak-admin-ui/issues/436
Apparently that's what the old console UI used to do as well.

2021-05-07 07:46 UTC, edewit commented on src/user-federation/ldap/LdapSettingsGeneral.tsx
> -            defaultValue="ldap"
ahh okay i thought it was an error, fixed it now by clearing the field first

2021-05-07 15:06 UTC, mfrances17 approved these changes
LGTM

2021-05-07 15:34 UTC, merged