Realm settings(keys): add functionality to delete provider
keycloak/keycloak-admin-ui pull request #606
Opened 2021-05-12 19:40 UTC by jenny-s51

## Motivation

#603 

Marking as draft until #585 is merged - will then rebase and open for review.

## Verification Steps

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated
- [ ] Formatting has been performed via prettier/eslint
- [ ] Type checking has been performed via 'yarn check-types'

## Additional Notes

2021-06-01 06:12 UTC, edewit requested changes

2021-06-01 06:12 UTC, edewit commented on src/components/table-toolbar/KeycloakDataTable.tsx
> +      if ((node as TitleCell).title) {
why do you need this check? Isn't `isValidElement` also check if it's undefined?

2021-06-01 06:12 UTC, edewit commented on src/realm-settings/KeysProvidersTab.tsx
> +                      aria-labelledby="check-action-item1 check-action-action1"
this looks like the wrong aria label

2021-06-01 15:48 UTC, jenny-s51 commented on src/components/table-toolbar/KeycloakDataTable.tsx
> +      if ((node as TitleCell).title) {
removed - looks like this is not needed anymore

2021-06-03 20:40 UTC, ssilvert approved these changes

2021-06-03 20:40 UTC, merged