fixes realm save
keycloak/keycloak-admin-ui pull request #633
Opened 2021-05-25 09:13 UTC by edewit

currently save on realm screen didn't work as the email settings where required. Fixed this by changing email to be it's own section. Also email section was using the wrong attributes therefor the changes where not reflected in the old console

2021-05-25 09:41 UTC, edewit commented
fixing comment: https://github.com/keycloak/keycloak-admin-ui/issues/607#issuecomment-846941758

2021-05-25 13:27 UTC, jenny-s51 requested changes
Save/email form updates look great @edewit ! How did you know to use the `smptServer` object? It looked like the old console was also using `attributes`.

Also, a small thing - if the KeysListTab is consolidated into one component, props passed into the loader are `undefined` when accessed, and the `provider` column is empty for each row if the KeysList. This is why it was split up into two components initially. 

What do you think is the best thing to do here? Should we split it up again or is there a way we can just use the one component?

2021-05-25 13:27 UTC, jenny-s51 commented on src/realm-settings/KeysListTab.tsx
> +      const provider = realmComponents.find(
For some reason `realmComponents` is always `undefined` if called in the loader - the providers column of the table is empty when provider is initialized this way. Splitting up into `KeysListTab` into two components resolved this issue and the provider is rendered for each row

2021-05-26 07:19 UTC, edewit commented on src/realm-settings/KeysListTab.tsx
> +      const provider = realmComponents.find(
right it's a timing issue the table gets rendered when the realmComponent array is still empty. Fixed it by making the render depended on the realmComponent array being loaded.

2021-05-26 18:05 UTC, jenny-s51 approved these changes
Thank you for clarifying - updates look awesome 👍

2021-05-27 07:01 UTC, merged