Realm settings(keys): toggle provider modal for all provider types
keycloak/keycloak-admin-ui pull request #642
Opened 2021-05-25 19:56 UTC by jenny-s51

## Motivation

## Brief Description

## Verification Steps

1. Go to Realm settings -> Keys -> Providers tab.
2. Create a provider for each of the options listed.
3. Verify that the provider shows in the table.

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated
- [ ] Formatting has been performed via prettier/eslint
- [ ] Type checking has been performed via 'yarn check-types'

## Additional Notes

2021-05-27 12:05 UTC, edewit requested changes
I get this warning in the console on the rsa provider
![image](https://user-images.githubusercontent.com/51133/119820822-2c540900-bef2-11eb-8feb-a439810d87d0.png)

2021-05-27 12:05 UTC, edewit commented on src/realm-settings/AddProviderModal.tsx
> +        {providerType === "hmac-generated" && (
maybe it would be better to split this up into multiple smaller components based on the provider type?

2021-05-27 12:05 UTC, edewit commented on src/realm-settings/KeysProvidersTab.tsx
> +          open={isCreateModalOpen}
`open` is always true because if it's not it's not rendered

2021-05-27 12:05 UTC, edewit commented on tsconfig.json
> +    "jsx": "react",
why is this?

2021-05-27 17:00 UTC, jenny-s51 commented on src/realm-settings/KeysProvidersTab.tsx
> +          open={isCreateModalOpen}
good point - fixed

2021-05-27 17:01 UTC, jenny-s51 commented on tsconfig.json
> +    "jsx": "react",
don't need this anymore

2021-05-27 17:02 UTC, jenny-s51 commented on src/realm-settings/AddProviderModal.tsx
> +        {providerType === "hmac-generated" && (
That makes sense! I split up the modals into separate components

2021-06-01 06:18 UTC, edewit approved these changes

2021-06-03 18:31 UTC, merged