fixes issue around importing files
keycloak/keycloak-admin-ui pull request #643
Opened 2021-05-26 06:59 UTC by edewit

fixes: #628

2021-06-03 18:35 UTC, ssilvert commented
@yih-wang Can you review this please?  Trying to get old PR's merged.

2021-06-04 06:20 UTC, yih-wang requested changes
For the 2nd issue - 

> I tried to paste and edit the code in the import component. But I can only type one character each time, then this component loses focus.

This function still cannot be used normally. Each time I type a character, the cursor will jump to the end of the code.

2021-06-08 11:47 UTC, yih-wang approved these changes

2021-06-08 11:48 UTC, yih-wang commented
Thanks for the updates @edewit. Looks good to me!

2021-06-08 11:50 UTC, merged