Adjusts toolbar help menu items
keycloak/keycloak-admin-ui pull request #65
Opened 2020-09-04 16:32 UTC by srambach

This adjusts a few things on the toolbar help menu and kebab menu. It fixes alignment and spacing of icons and moves to use the DropdownItem description attribute for the descriptive text. The color of the descriptive text is manually styled pending a bug fix in Patternfly.

Related to comments in #30 as well as other discussions.

2020-09-04 16:42 UTC, ssilvert requested changes
@srambach We should not be doing workarounds for PatternFly bugs.  Like we said earlier today, we want to eliminate custom css.

Please submit a bug report to PatternFly.  Then create an issue in keycloak-admin-ui and link to the bug report.

2020-09-04 18:08 UTC, srambach commented
The dropdown description text color will be fixed by https://github.com/patternfly/patternfly/issues/3411

@stianst do you still want me to create an issue, given that there is nothing to change on our side?

2020-09-04 18:11 UTC, yordis commented on src/PageHeader.tsx
> +  return <DropdownItem icon={<HelpIcon />}>{`${help}`}</DropdownItem>;
```suggestion
  return <DropdownItem icon={<HelpIcon />}>{t("Help")}</DropdownItem>;
```

2020-09-04 18:21 UTC, srambach commented on src/PageHeader.tsx
> +  return <DropdownItem icon={<HelpIcon />}>{`${help}`}</DropdownItem>;
Good catch, thanks!

2020-09-04 19:04 UTC, ssilvert commented
> The dropdown description text color will be fixed by [patternfly/patternfly#3411](https://github.com/patternfly/patternfly/issues/3411)
> 
> @stianst do you still want me to create an issue, given that there is nothing to change on our side?
@srambach 

Thanks.  Yes.  Please create an issue so we will remember to follow up on it.  Granted, with the way it looks I don't think we will forget.

BTW, you messaged @stianst  instead of me.  Happens a lot.  At least you didn't call him Stain.

2020-09-04 19:12 UTC, ssilvert commented
@srambach This code breaks the kabab menu in the masthead.  Reduce viewport size then try to click kabab and it breaks.

2020-09-04 20:54 UTC, srambach commented on src/PageHeader.tsx
> +  return <DropdownItem icon={<HelpIcon />}>{`${help}`}</DropdownItem>;
@yordis, I misread this earlier - thought you were pointing out that the menu item name should be capitalized. I will defer to @ssilvert there because I don't know if it's better to store the text in a variable for future modification/customization maybe? Reverted for now, sorry!

2020-09-07 14:50 UTC, edewit commented
for me it looks like:
![image](https://user-images.githubusercontent.com/51133/92399205-334fa700-f12a-11ea-8622-dce64de99509.png)
is that what we want until patternfly has a fix?

2020-09-07 14:50 UTC, edewit approved these changes

2020-09-08 17:08 UTC, ssilvert commented
> for me it looks like:
> ![image](https://user-images.githubusercontent.com/51133/92399205-334fa700-f12a-11ea-8622-dce64de99509.png)
> is that what we want until patternfly has a fix?

It won't be long before we have a fix.  Let's just leave it as-is for now.

@srambach Do you know why the kabab broke?

2020-09-08 17:09 UTC, ssilvert commented
@srambach Given that we are waiting on the PF fix, do we still need to merge this or should we close it?

2020-09-08 18:52 UTC, srambach commented
@ssilvert The kebab broke because I mistakenly changed the letter case on the help variable after the comment above. It's fixed now.
And yes, we should still merge this because I corrected alignment as well by including a layout element to right justify the icon and switch, as shown in the designs. This PR also moves the text to the description attribute as it will need to be to pick up the PatternFly fix, and removes unnecessary CSS.

2020-09-08 18:54 UTC, ssilvert approved these changes

2020-09-08 18:54 UTC, merged