Localization tab
keycloak/keycloak-admin-ui pull request #685
Opened 2021-06-07 18:16 UTC by jenny-s51

## Motivation

Closes #682 

## Brief Description

Towards https://issues.redhat.com/browse/APPDUX-937

## Verification Steps

1. Go to the old admin console.
2. Navigate to Realm settings -> Localization 
3. Create a locale: you must name it any of the following: ca, cs, da, de, en, es, fr, hu, it, ja, lt, nl, no, pl, pt-BR, ru, sk, sv, tr, zh-CN
4. Add at least one key, value pair and click save.
5. Go to the new console. 
6. Navigate to Realm settings -> localization 
7. Comment out https://github.com/keycloak/keycloak-admin-ui/compare/master...jenny-s51:localizationTab?expand=1#diff-6a013ef3899e308f424b7fd2f79cee59df8f9f2989832ece8ccf14d4081aa2abR178.
7. Enable Internationalization and select your new locale as the "default locale". 
8. Verify that the key-value mappings are listed in the table below. 

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated
- [ ] Formatting has been performed via prettier/eslint
- [ ] Type checking has been performed via 'yarn check-types'

## Additional Notes

2021-06-08 08:37 UTC, edewit requested changes
when I set supported locales in the old console to 'nl' the new console still shows all the locales. And the keys fetch seems to always use English. Sometimes reloading the page will change the values of the form

2021-06-08 08:37 UTC, edewit commented on src/components/table-toolbar/KeycloakDataTable.tsx
> +      if ((node as TitleCell).title && (node as TitleCell).title.props) {
I've seen this change before...

2021-06-08 08:37 UTC, edewit commented on src/realm-settings/LocalizationTab.tsx
> +                  message={t("common:noSearchResults")}
empty state shouldn't show no search results but an action on how to get started

2021-06-08 08:37 UTC, edewit commented on src/realm-settings/messages.json
> +    "messageBundleDescription": "You can edit the supported locales.If you haven't selected supported locales yet, you can only edit the English locale."
```suggestion
    "messageBundleDescription": "You can edit the supported locales. If you haven't selected supported locales yet, you can only edit the English locale."
```

2021-06-08 08:52 UTC, edewit commented on src/realm-settings/LocalizationTab.tsx
> +                    isChecked={internationalizationEnabled}
```suggestion
                    isChecked={value}
```

2021-06-08 11:26 UTC, edewit commented
PR: https://github.com/keycloak/keycloak-nodejs-admin-client/pull/177 adds localization support to the `adminClient`

2021-06-08 14:53 UTC, jenny-s51 commented on src/components/table-toolbar/KeycloakDataTable.tsx
> +      if ((node as TitleCell).title && (node as TitleCell).title.props) {
This line fixed the search because it wasn't working in some cases - it looks like some recent updates to master resolved this

2021-06-09 06:13 UTC, edewit requested changes

2021-06-09 06:13 UTC, edewit commented on src/realm-settings/LocalizationTab.tsx
> +                              {/* {t(`allSupportedLocales.${locale}`)} */}
guess this can go

2021-06-09 06:13 UTC, edewit commented on src/realm-settings/RealmSettingsSection.tsx
> +    setTimeout(update, 100);
is this really necessary?

2021-06-09 06:13 UTC, edewit commented on src/realm-settings/RealmSettingsSection.tsx
> +            </Tab>
The tab will be show first when the realm is not yet loaded, it's better to show it when the data is there.
```suggestion
            {realm && (
              <Tab
                id="localization"
                eventKey="localization"
                title={<TabTitleText>{t("localization")}</TabTitleText>}
              >
                <LocalizationTab
                  key={key}
                  refresh={refresh}
                  save={save}
                  reset={() => setupForm(realm)}
                  realm={realm}
                />
              </Tab>
            )}

```

2021-06-09 06:15 UTC, edewit commented
I get a error realm not defined:

`http://localhost:8180/auth/admin/realms/undefined/localization/nl`

2021-06-09 07:07 UTC, edewit commented
seems internationalizationEnabled is a switch here on the Locale tab and on the themes that is that right?

2021-06-09 14:54 UTC, jenny-s51 commented
> seems internationalizationEnabled is a switch here on the Locale tab and on the themes that is that right?

@edewit Thank you for your helpful feedback and review - I've updated this PR based on your suggestions. Yes the internationalization switch is present in both the Themes and Localization tab

2021-06-14 10:52 UTC, edewit requested changes
When I enable Internationalization on the themes tab and then go to the locale tab the screen looks like this: 
![image](https://user-images.githubusercontent.com/51133/121881250-4faeee80-cd0f-11eb-8a4b-8317f5010d6c.png)

Also it seems even though I have added a key value under 'nl' I don't see it when the default locale is "Nederlands"

2021-06-16 11:38 UTC, ssilvert commented
Checked with @edewit.  He approves.  Merging.

2021-06-16 11:38 UTC, merged