Run tsc on build to check for typescript errors
keycloak/keycloak-admin-ui pull request #69
Opened 2020-09-05 19:36 UTC by ssilvert

2020-09-06 18:09 UTC, ssilvert commented on src/components/realm-selector/RealmSelector.tsx
> +      setRealms(result!);
@jenny-s51 I'm not sure exactly what this was for, but the realm list is guaranteed to at least have one item.  I changed it to make the typescript checker happy.

2020-09-07 10:58 UTC, edewit requested changes

2020-09-07 10:58 UTC, edewit commented on src/components/realm-selector/RealmSelector.tsx
> +      setRealms(result!);
even better option would be to do `setRealms(result || [])`

2020-09-07 10:58 UTC, edewit commented on package.json
> +    "check-types": "tsc --noImplicitAny --strictNullChecks --jsx react -p ./",
I wouldn't add these flags here as they are already defined in the `tsconfig.json`

2020-09-08 05:56 UTC, edewit approved these changes

2020-09-08 05:56 UTC, merged