Consents UI fixes
keycloak/keycloak-admin-ui pull request #691
Opened 2021-06-09 13:37 UTC by jenny-s51

## Motivation

Closes #668 

## Verification Steps

1. Go to Users -> Consents
2. Verify changes are in accordance with UX review. 

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated
- [ ] Formatting has been performed via prettier/eslint
- [ ] Type checking has been performed via 'yarn check-types'

## Additional Notes

2021-06-09 21:24 UTC, mfrances17 requested changes
Everything looks like it was addressed, well done. Thanks for adding the expanded verification steps, it helped a lot. One small change to handle the string better than using the concatenation.

2021-06-09 21:26 UTC, mfrances17 commented on src/user/UserConsents.tsx
> +    messageKey: t("users:revokeClientScopes") + selectedClient?.clientId + "?",
Recommend doing something like this instead of concatenating the string here:
```
    messageKey: t("users:revokeClientScopes", {
      clientId: selectedClient?.clientId,
    }),
```

2021-06-09 21:27 UTC, mfrances17 commented on src/user/messages.json
> +    "revokeClientScopes": "Are you sure you want to revoke all granted client scopes for ",
And change the message to:
```
    "revokeClientScopes": "Are you sure you want to revoke all granted client scopes for {{clientId}}?",
```

2021-06-10 00:27 UTC, ssilvert commented on src/user/UserConsents.tsx
> +    messageKey: t("users:revokeClientScopes") + selectedClient?.clientId + "?",
> Recommend doing something like this instead of concatenating the string here:
> 
> ```
>     messageKey: t("users:revokeClientScopes", {
>       clientId: selectedClient?.clientId,
>     }),
> ```

Good catch @mfrances17.  This is actually not just a recommendation.  It's a must-do.  In different languages, the placement of the param within the sentence can be different, which means that you can't translate it correctly if that placement is hard-coded.  So concatenation of localized strings should almost always be avoided.

Also concur with @mfrances17 overall.  I tried it out and it looks really good.

2021-06-10 15:10 UTC, jenny-s51 commented on src/user/UserConsents.tsx
> +    messageKey: t("users:revokeClientScopes") + selectedClient?.clientId + "?",
@ssilvert That makes sense, thank you for your helpful clarification on this

2021-06-10 15:10 UTC, jenny-s51 commented
@mfrances17 @ssilvert Thank you for your helpful feedback and reviews! I've addressed the localization instance per your review comments

2021-06-10 16:02 UTC, merged