Partial import phase 2
keycloak/keycloak-admin-ui pull request #702
Opened 2021-06-15 00:43 UTC by ssilvert

## Brief Description
This is phase 2 of the Partial import implementation.  Phase 3 will be the final phase where the imported data is sent to the Keycloak server.

Partial import modal now handles the imported JSON and presents the user with import options as per [Marvel](https://marvelapp.com/prototype/fg26f9b/screen/75624791).  

Note: The design did not include functionality for handling JSON files with multiple realms.

## Verification Steps
1. Go to `Realm settings`.
2. Select Partial import form the Action dropdown.
3. Import a previously exported Keycloak json. (Samples included in test data for this PR. `kcexport.json` is a good one to look at)
4. Verify that modal presents the user with options as shown in the design, plus multi-realm functionality.

## Checklist:

- [X] Code has been tested locally by PR requester
- [X] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented (not applicable)
- [ ] axe report has been run and resulting a11y issues have been resolved
- [X] Unit tests have been created/updated
- [X] Formatting has been performed via prettier/eslint
- [X] Type checking has been performed via 'yarn check-types'

2021-06-15 07:02 UTC, edewit requested changes
Looking good nice just checkboxes seem a bit close to the text:
![image](https://user-images.githubusercontent.com/51133/122007536-4e85cc00-cdb8-11eb-9505-449e19086dcc.png)

This is due to a global override in `RealmSettingsSection.css` @jenny-s51 these are not per screen but global

2021-06-15 14:15 UTC, jenny-s51 commented on src/realm-settings/PartialImport.tsx
> +    console.log(resourcesToImport);
```suggestion
```

2021-06-15 14:21 UTC, jenny-s51 approved these changes
Modal and resource logic look great @ssilvert ! Approving per our decision this morning that the we'll address the CSS fixes separately for each section

2021-06-16 11:03 UTC, edewit approved these changes

2021-06-16 11:03 UTC, merged