Realm settings(keys -> providers): adds AES provider details
keycloak/keycloak-admin-ui pull request #729
Opened 2021-06-25 19:03 UTC by jenny-s51

## Motivation

Closes #726 ; Towards #639

## Brief Description

## Verification Steps

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated
- [ ] Formatting has been performed via prettier/eslint
- [ ] Type checking has been performed via 'yarn check-types'

## Additional Notes

2021-07-06 09:39 UTC, jonkoops commented
@jenny-s51 There are some merge conflicts with the upstream, can you rebase your branch?

2021-07-06 13:32 UTC, jonkoops requested changes

2021-07-06 13:32 UTC, jonkoops commented on src/realm-settings/key-providers/aes-generated/AESGeneratedModal.tsx
> +  refresh?: () => void;
All of these types are always passed and can thus be made required.
```suggestion
  providerType: string;
  handleModalToggle: () => void;
  refresh: () => void;
```

2021-07-06 13:32 UTC, jonkoops commented on src/realm-settings/key-providers/aes-generated/AESGeneratedModal.tsx
> +import React from "react";
There is another `AESGeneratedModal` component int he directory above that is no longer used. I believe that file should be removed (see `src/realm-settings/AESGeneratedModal.tsx`).

2021-07-06 13:32 UTC, jonkoops commented on src/realm-settings/key-providers/aes-generated/AESGeneratedForm.tsx
> +  ];
`componentTypes` can be `undefined`, which might cause runtime errors. Let's use optional chaining instead.

```suggestion
  const allComponentTypes = serverInfo.componentTypes?.[
    "org.keycloak.keys.KeyProvider"
  ];
```

If we want to ensure the value is always present we can default to an empty array.

```ts
const allComponentTypes = serverInfo.componentTypes?.["org.keycloak.keys.KeyProvider"] ?? [];
```

2021-07-06 13:32 UTC, jonkoops commented on src/realm-settings/key-providers/aes-generated/AESGeneratedForm.tsx
> +                onChange([value + ""]);
Why are we concatenating this with a string value? If it is needed to cast the boolean to a string there is a `toString()` method available.

```suggestion
                onChange([value.toString()]);
```

2021-07-06 13:32 UTC, jonkoops commented on src/realm-settings/key-providers/aes-generated/AESGeneratedForm.tsx
> +                  onChange([value + ""]);
```suggestion
                  onChange([value.toString()]);
```

2021-07-06 13:32 UTC, jonkoops commented on src/realm-settings/key-providers/aes-generated/AESGeneratedForm.tsx
> +                onChange([value + ""]);
```suggestion
                onChange([value.toString()]);
```

2021-07-06 13:32 UTC, jonkoops commented on src/realm-settings/key-providers/aes-generated/AESGeneratedForm.tsx
> +              {allComponentTypes[0].properties[3].options!.map((item, idx) => (
Perhaps there is a way to make this 'magic' index a bit clearer? Also let's use optional chaining here instead, otherwise we might get exceptions at runtime.
```suggestion
              {allComponentTypes[0].properties[3].options?.map((item, idx) => (
```

2021-07-06 13:32 UTC, jonkoops commented on src/realm-settings/key-providers/aes-generated/AESGeneratedForm.tsx
> +          onClick={!editMode ? () => handleModalToggle!() : () => {}}
```suggestion
          onClick={!editMode ? () => handleModalToggle?.() : () => {}}
```

2021-07-06 13:32 UTC, jonkoops commented on src/realm-settings/key-providers/aes-generated/AESGeneratedForm.tsx
> +  const providerId = url.split("/").slice(-2)[0];
Same here, let's use the router's built-in mechanism to parse URLs instead of doing it ourselves.

2021-07-06 13:32 UTC, jonkoops commented on src/realm-settings/AESGeneratedModal.tsx
> +  ];
Let's use optional chaining here instead.

2021-07-06 13:32 UTC, jonkoops commented on src/realm-settings/ECDSAGeneratedModal.tsx
> +  const allComponentTypes = serverInfo.componentTypes![
Let's use optional chaining here instead.

2021-07-06 13:32 UTC, jonkoops commented on src/realm-settings/HMACGeneratedModal.tsx
> +  const allComponentTypes = serverInfo.componentTypes![
Let's use optional chaining here instead.

2021-07-06 13:32 UTC, jonkoops commented on src/realm-settings/JavaKeystoreModal.tsx
> +  const allComponentTypes = serverInfo.componentTypes![
Let's use optional chaining here instead.

2021-07-06 13:32 UTC, jonkoops commented on src/realm-settings/RSAGeneratedModal.tsx
> +  const allComponentTypes = serverInfo.componentTypes![
Let's use optional chaining here instead.

2021-07-06 13:32 UTC, jonkoops commented on src/realm-settings/RSAModal.tsx
> +  const allComponentTypes = serverInfo.componentTypes![
Let's use optional chaining here instead.

2021-07-06 13:32 UTC, jonkoops commented on src/realm-settings/key-providers/aes-generated/AESGeneratedModal.tsx
> +      refresh!();
Let's use optional chaining here instead.

2021-07-06 13:32 UTC, jonkoops commented on src/realm-settings/key-providers/aes-generated/AESGeneratedModal.tsx
> +      handleModalToggle!();
Let's use optional chaining here instead.

2021-07-06 13:32 UTC, jonkoops commented on src/realm-settings/key-providers/aes-generated/AESGeneratedModal.tsx
> +      );
Let's interpolate this in the translation itself instead of concatenating it here.

2021-07-06 15:42 UTC, jenny-s51 commented on src/realm-settings/key-providers/aes-generated/AESGeneratedForm.tsx
> +  const providerId = url.split("/").slice(-2)[0];
@jonkoops would you mind kindly clarifying what you mean by using a path parameter?

I've updated the code to look like this:

```
  const providerId = useRouteMatch<MatchParams>(
    "/:realm/realm-settings/keys/:id?/:providerType?/settings"
  )?.params.providerType;
```

2021-07-06 15:47 UTC, jenny-s51 commented on src/realm-settings/key-providers/aes-generated/AESGeneratedForm.tsx
> +    },
I get a TS error here unless this function is declared as `async`. 

`Argument of type '() => Promise<ComponentRepresentation> | undefined' is not assignable to parameter of type '() => Promise<ComponentRepresentation>'...`

2021-07-06 16:24 UTC, jonkoops commented on src/realm-settings/key-providers/aes-generated/AESGeneratedForm.tsx
> +  const providerId = url.split("/").slice(-2)[0];
Yeah that looks good! By path parameters I mean the parameters specified in the path with the `:` annotation. Specifically in the format that [path-to-regexp](https://github.com/pillarjs/path-to-regexp/tree/v1.7.0) understands.

2021-07-06 16:29 UTC, jenny-s51 commented on src/realm-settings/key-providers/aes-generated/AESGeneratedForm.tsx
> +  const providerId = url.split("/").slice(-2)[0];
Awesome, that makes sense - thank you!

2021-07-09 07:06 UTC, edewit requested changes
The localization tests work, but the keys test no longer works with the changes you made to it here, als don't add all these waits they slow down the test and you never know if a wait is long enough. If you want to wait for a page to be loaded add a wait for the request to be done

2021-07-09 19:05 UTC, ssilvert requested changes
@jenny-s51 I'm getting a runtime error. 

I click on Realm Settings --> Keys --> Providers
Then I click on `aes-geerated`

I get:
`
Uncaught TypeError: Cannot read property '0' of undefined
    at AESGeneratedForm.js:94
    at Array.map (<anonymous>)
    at setupForm (AESGeneratedForm.js:92)
    at AESGeneratedForm.js:109
    at AdminClient.js:36
`

2021-07-09 19:26 UTC, jenny-s51 commented
@ssilvert nice catch - fixed! Looks like this error was happening only with the default aes provider that's created with the realm.

2021-07-12 05:48 UTC, edewit approved these changes
:+1:

2021-07-12 09:25 UTC, jonkoops approved these changes

2021-07-12 09:28 UTC, jonkoops requested changes

2021-07-12 09:28 UTC, jonkoops commented on src/realm-settings/key-providers/aes-generated/AESGeneratedForm.tsx
> +        component.config!.active
Using the the non-null assertion operator can lead to unexpected runtime errors, use optional chaining instead.

```suggestion
        component.config?.secretSize &&
        component.config?.active
```

2021-07-12 10:29 UTC, jonkoops requested changes

2021-07-12 10:29 UTC, jonkoops commented on src/realm-settings/RSAGeneratedModal.tsx
> +        );
Same as the other modals, I don't think this code is ever reached.

2021-07-12 10:29 UTC, jonkoops commented on src/realm-settings/RSAGeneratedModal.tsx
> +        handleModalToggle!();
Using the non-null assertion operator can lead to runtime errors, in this case `handleModalToggle` is always provided upstream so it can be made required.

```suggestion
        handleModalToggle();
```

2021-07-12 10:29 UTC, jonkoops commented on src/realm-settings/RSAGeneratedModal.tsx
> +        refresh!();
Using the non-null assertion operator can lead to runtime errors, in this case `refresh` is always provided upstream so it can be made required.

```suggestion
        refresh();
```

2021-07-12 10:29 UTC, jonkoops commented on src/realm-settings/RSAModal.tsx
> +        addAlert(t("realm-settings:saveProviderSuccess"), AlertVariant.success);
Same as for all the other modals, I do not think this code is ever reached.

2021-07-12 10:29 UTC, jonkoops commented on src/realm-settings/RSAModal.tsx
> +        handleModalToggle!();
Using the non-null assertion operator can lead to runtime errors, in this case `handleModalToggle` is always provided upstream so it can be made required.

```suggestion
        handleModalToggle();
```

2021-07-12 10:29 UTC, jonkoops commented on src/realm-settings/RSAModal.tsx
> +        refresh!();
Using the non-null assertion operator can lead to runtime errors, in this case `refresh` is always provided upstream so it can be made required.

```suggestion
        refresh();
```

2021-07-12 10:29 UTC, jonkoops commented on src/realm-settings/key-providers/aes-generated/AESGeneratedForm.tsx
> +        <AESGeneratedForm providerType={providerId!} editMode={true} />
Using the the non-null assertion operator can lead to unexpected runtime errors, pass the value as-is, or handle the edge case that this could be `undefined`.

```suggestion
        <AESGeneratedForm providerType={providerId} editMode={true} />
```

2021-07-12 10:29 UTC, jonkoops commented on src/realm-settings/key-providers/aes-generated/AESGeneratedForm.tsx
> +        <AESGeneratedForm providerType={providerId!} editMode={true} />
A prop with a boolean type can be passed as an attribute without a value.

```suggestion
        <AESGeneratedForm providerType={providerId!} editMode />
```

2021-07-12 10:29 UTC, jonkoops commented on src/realm-settings/key-providers/aes-generated/AESGeneratedForm.tsx
> +    "/:realm/realm-settings/keys/:id?/:providerType?/settings"
This path should come from the route definition in `src/route-config.ts`. Ideally all route related information such as the path and type definitions should be in a central location.

The reason for this is that if this path ever changes we will have to manually find these kind of local paths instead of adjusting the single central config.

2021-07-12 10:29 UTC, jonkoops commented on src/realm-settings/key-providers/aes-generated/AESGeneratedForm.tsx
> +          onClick={!editMode ? () => handleModalToggle?.() : () => {}}
Instead of falling back to an empty function, it's also possible to pass in `undefined`.
```suggestion
          onClick={(!editMode && handleModalToggle) || undefined}
```

2021-07-12 10:29 UTC, jonkoops commented on src/realm-settings/key-providers/aes-generated/AESGeneratedForm.tsx
> +  const AESSecretSizeOptions = allComponentTypes[0].properties[3].options;
It's conventional to use the camelCase convention for variables that are not global constants.
```suggestion
  const aesSecretSizeOptions = allComponentTypes[0].properties[3].options;
```

2021-07-12 10:29 UTC, jonkoops commented on src/realm-settings/key-providers/aes-generated/AESGeneratedForm.tsx
> +                  key={`secret-size-option-${idx}`}
Perhaps the `item` itself here is already unique enough to be used as an identifier? Indexes should only be used as a key only as a [last resort](https://reactjs.org/docs/lists-and-keys.html#keys).

```suggestion
                  key={item}
```

2021-07-12 10:29 UTC, jonkoops commented on src/realm-settings/key-providers/aes-generated/AESGeneratedForm.tsx
> +              selections={[value + ""]}
```suggestion
              selections={[value.toString()]}
```

2021-07-12 10:29 UTC, jonkoops commented on src/realm-settings/key-providers/aes-generated/AESGeneratedForm.tsx
> +          defaultValue={["true"]}
This might be some kind of convention, but why is this value passed as an array?

2021-07-12 13:33 UTC, ssilvert approved these changes
I'm approving as this looks fine from a functionality point of view.  But JON's latest comments do need to be addressed.

If you want to go ahead and merge and log an issue to for JON's comments then we can do that.  If you want to fix in this PR then let's make sure it is done ASAP.

2021-07-12 13:57 UTC, jonkoops commented on src/realm-settings/ECDSAGeneratedModal.tsx
>    providerType?: string;
`providerType` can also be made required for almost all of the modals FYI.

2021-07-12 13:58 UTC, jenny-s51 commented on src/realm-settings/key-providers/aes-generated/AESGeneratedForm.tsx
> +          defaultValue={["true"]}
This matches the current data type that the server uses

2021-07-12 14:11 UTC, edewit commented on src/realm-settings/ECDSAGeneratedModal.tsx
>    const { t } = useTranslation("groups");
This should not be `"groups"`, right?

```suggestion
  const { t } = useTranslation("realm-settings");
```

2021-07-12 18:19 UTC, merged

2021-07-13 09:59 UTC, jonkoops commented on src/realm-settings/RSAModal.tsx
> +  const { id } = useParams<{ id: string }>();
This component is never used on any route which includes an `id` parameter, so I don't think any conditions here depending on this to be present will ever be triggered.