Added Security Defenses tab in the realm settings
keycloak/keycloak-admin-ui pull request #738
Opened 2021-06-29 14:48 UTC by edewit

see [marvel](https://marvelapp.com/prototype/13g2f55e/screen/75843596)

2021-07-01 15:07 UTC, mfrances17 requested changes
The naming convention used throughout (dirs, components, tab name, etc) is not using the US-EN version for 'defenses' - you are using 'defences' which I assume is the european equivalent. But it should be 'defenses'. See old admin UI vs new admin UI:

Old admin UI (defenses):
![old-ui-defense](https://user-images.githubusercontent.com/39063664/124147132-6b7afa00-da5c-11eb-87d2-9d0691900bae.png)

New admin UI (defences):
![new-ui-defence](https://user-images.githubusercontent.com/39063664/124147236-82215100-da5c-11eb-983f-e9070f5e96ed.png)

2021-07-08 18:27 UTC, jenny-s51 requested changes

2021-07-08 18:27 UTC, jenny-s51 commented on src/realm-settings/security-defences/BruteForceDetection.tsx
> +          <Time name="minimumQuickLoginWait" />
```suggestion
          <Time name="minimumQuickLoginWaitSeconds" />
```

2021-07-08 18:27 UTC, jenny-s51 commented on src/realm-settings/messages.json
> +    "minimumQuickLoginWait": "Minimum quick login wait"
```suggestion
    "minimumQuickLoginWaitSeconds": "Minimum quick login wait"
```

2021-07-09 06:34 UTC, edewit commented
thanks @jenny-s51 don't know why I didn't see that, guess that's why we do PR reviews!

2021-07-09 13:40 UTC, jenny-s51 approved these changes
LGTM, nice work @edewit!

2021-07-09 14:23 UTC, merged

2021-07-09 14:24 UTC, ssilvert commented
@mfrances17 I went ahead and merged this.  If you still see problems, please open an issue.