Changed the group picker to reflect the updated design
keycloak/keycloak-admin-ui pull request #743
Opened 2021-07-01 09:05 UTC by edewit

Now follows the design more closely

2021-07-05 09:18 UTC, jonkoops requested changes

2021-07-05 09:25 UTC, edewit commented on src/components/group/GroupPickerDialog.tsx
> -      setMax(10);
Yes

2021-07-05 09:29 UTC, edewit commented on src/components/group/GroupPickerDialog.tsx
> +      (group) => group.id === row?.id
Every group has an `id` it's an error in the type information that this field might be optional. It's generated from the java classes and a java `String` can be null

2021-07-05 09:30 UTC, edewit commented on src/components/group/GroupPickerDialog.tsx
> +      let group;
no, it should only make one request

2021-07-05 09:32 UTC, jonkoops commented on src/components/group/GroupPickerDialog.tsx
> -      setMax(10);
Got it :ok_hand:

2021-07-05 09:43 UTC, jonkoops commented on src/components/group/GroupPickerDialog.tsx
> +      (group) => group.id === row?.id
I see, if we are sure that this field is always present then I would say let's update the type information to reflect the real world expectations.

2021-07-06 09:29 UTC, jonkoops commented on src/components/group/GroupPickerDialog.tsx
> +      let group;
I see that it doens't do so in this case. But if an `id` is provided to the `GroupPickerDialog` it should fire two requests.

2021-07-06 09:31 UTC, jonkoops approved these changes

2021-07-06 09:31 UTC, merged