Realm settings: Sessions tab
keycloak/keycloak-admin-ui pull request #807
Opened 2021-07-07 18:14 UTC by jenny-s51

## Motivation

https://issues.redhat.com/browse/APPDUX-938

## Brief Description

Adds sessions tab to realm settings section

## Verification Steps

1. Go to Realm settings -> sessions
2. Populate the fields with test values
3. Save and navigate to a different page
4. Verify the values are saved correctly

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated
- [ ] Formatting has been performed via prettier/eslint
- [ ] Type checking has been performed via 'npm run check-types'

## Additional Notes

2021-07-08 19:14 UTC, ssilvert requested changes
This works properly and the code looks good.

I see a couple of cosmetic changes that need to be fixed:
- Help icons for `SSO Session Idle Remember Me`, `SSO Session Max Remember Me`, and `Login action timeout` should be left-justified.
- Too much spacing between headings and sections.  It makes the page a lot longer than the Marvel wireframe

The tests need to be fleshed out a bit:
- Test does not test changing the dropdowns.  
- Test do not test that the values were actually saved (it only tests the success message).  Looks like you need to go out of Realm settings and come back in order to see the saved values get retrieved from the server.  That's fine, but the test needs to make sure you can do a full round trip to the database and retrieve the saved values.

2021-07-08 20:28 UTC, jenny-s51 commented
@ssilvert thank you for your review - sounds good, working on making these changes

2021-07-12 11:08 UTC, jonkoops requested changes

2021-07-12 11:08 UTC, jonkoops commented on src/realm-settings/SessionsTab.tsx
> +    Object.entries(realm).map((entry) => setValue(entry[0], entry[1]));
The `entry` can be spread here instead of using array indexes.
```suggestion
    Object.entries(realm).map((entry) => setValue(...entry));
```

2021-07-12 11:08 UTC, jonkoops commented on src/realm-settings/SessionsTab.tsx
> +      Object.entries(realm).map((entry) => setValue(entry[0], entry[1]));
I believe you can call `setupForm()` here, as it does the same thing.

```suggestion
      setupForm();
```

2021-07-12 18:04 UTC, jenny-s51 commented on src/realm-settings/SessionsTab.tsx
> +  );
nice catch - looks like this doesn't need to be here

2021-07-13 10:33 UTC, jonkoops commented
@jenny-s51 can you rebase this PR on `master`?

2021-07-14 16:34 UTC, ssilvert commented
@jenny-s51 The spacing problem is fixed now, but it's not reading the language bundle.  So I'm seeing the language keys instead of the values.

2021-07-15 09:31 UTC, jonkoops commented
> @jenny-s51 The spacing problem is fixed now, but it's not reading the language bundle. So I'm seeing the language keys instead of the values.

This is probably because these files were converted by me to prepare for the Snowpack 3 upgrade. To fix this just copy-paste the newly added entries in this PR from their JSON counterparts into the new TypeScript files, the structure is exactly the same.

2021-07-15 09:47 UTC, jonkoops requested changes

2021-07-15 09:47 UTC, jonkoops commented on cypress/support/pages/admin_console/manage/realm_settings/RealmSettingsPage.ts
> +  offlineSessionIdleSelectMenuList =
`offlineSessionIdleSelectMenuList` is never used.

2021-07-15 09:47 UTC, jonkoops commented on cypress/support/pages/admin_console/manage/realm_settings/RealmSettingsPage.ts
> +  offlineSessionMaxSelectMenuList = "#kc-offline-session-max-select-menu-ul";
Both `offlineSessionMaxSelectMenu` and `offlineSessionMaxSelectMenuList` are never used.

2021-07-15 09:47 UTC, jonkoops commented on cypress/support/pages/admin_console/manage/realm_settings/RealmSettingsPage.ts
> +        console.log("Invalid unit, must be 'minutes', 'hours', or 'days'.");
Perhaps we should `throw` here instead?

2021-07-15 09:47 UTC, jonkoops commented on cypress/support/pages/admin_console/manage/realm_settings/RealmSettingsPage.ts
> +  changeTimeUnit(unit: string, inputType: string, listType: string) {
Since this is TypeScript you can provide a string literal union type here so you cannot accidentally pass in an invalid value.

```suggestion
  changeTimeUnit(unit: "Minutes" | "Hours" | "Days", inputType: string, listType: string) {
```

If you call this method with an invalid value:

```ts
this.changeTimeUnit("Foo", ...)
```

You'll get an error at compile-time:

> Argument of type '"Foo"' is not assignable to parameter of type '"Minutes" | "Hours" | "Days"'

2021-07-15 09:47 UTC, jonkoops commented on src/realm-settings/help.json
> +{
This file has been renamed to `help.ts` make sure to paste the new keys you added here.

2021-07-15 09:47 UTC, jonkoops commented on src/realm-settings/messages.json
> +{
This file has been renamed to `messages.ts` make sure to paste the new keys you added here.

2021-07-15 09:47 UTC, jonkoops commented on src/realm-settings/SessionsTab.tsx
> +      setupForm(realm);
It looks like `resetForm()` does the exact same thing as the custom `setupForm()` function, perhaps we can get rid of `setupForm()` altogether?

2021-07-15 09:47 UTC, jonkoops commented on src/realm-settings/SessionsTab.tsx
> +  }, [realm]);
I think we might be able to get away by simply calling `resetForm()` here.
```suggestion
  useEffect(() => resetForm(realm), [realm]);
```

2021-07-15 14:13 UTC, ssilvert approved these changes

2021-07-15 14:25 UTC, merged