Route changes
keycloak/keycloak-admin-ui pull request #835
Opened 2021-07-12 15:22 UTC by jenny-s51

## Motivation

#834 

## Brief Description

## Verification Steps

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated
- [ ] Formatting has been performed via prettier/eslint
- [ ] Type checking has been performed via 'npm run check-types'

## Additional Notes

2021-07-13 09:19 UTC, jonkoops commented
@jenny-s51 could you rebase this PR on `master`? It looks like there are some merge conflicts.

2021-07-13 10:32 UTC, jonkoops requested changes

2021-07-13 10:32 UTC, jonkoops commented on src/realm-settings/key-providers/aes-generated/AESGeneratedForm.tsx
> +  const providerId = useRouteMatch<MatchParams>(AESProviderTypeRoute.path)
Since this match is using the path from `AESProviderTypeRoute` we should also use the corresponding type from that file.

```suggestion
  const providerId = useRouteMatch<AESProviderTypeRouteParams>(AESProviderTypeRoute.path)
```

But since this should be the only route that is triggered anyways I believe we can also use `useParams` here.
```suggestion
  const params = useParams<AESProviderTypeRouteParams>()
```

2021-07-13 10:32 UTC, jonkoops commented on src/realm-settings/key-providers/aes-generated/AESGeneratedForm.tsx
> +              onToggle={() => setIsKeySizeDropdownOpen(!isKeySizeDropdownOpen)}
`onToggle` provides state so we do not have to manage it ourselves:

```suggestion
              onToggle={(isExpanded) => setIsKeySizeDropdownOpen(isExpanded)}
```

2021-07-13 10:32 UTC, jonkoops commented on src/realm-settings/key-providers/aes-generated/AESGeneratedForm.tsx
> +            return (
This can be an arrow function so there is no need for a `return` statement.

2021-07-13 10:32 UTC, jonkoops commented on src/realm-settings/key-providers/aes-generated/AESGeneratedForm.tsx
> +        addAlert(t("saveProviderSuccess"), AlertVariant.success);
From what I can tell this code is never executed as it's on a route that has no `id` parameter.

2021-07-13 17:13 UTC, jenny-s51 commented
@jonkoops Thank you for your helpful comments and feedback! Rebased - looks like the cyclical dependency (AESProviderTypeRoute is used in AESGeneratedSettings and vice versa) is still resulting in an error and the console is currently not loading properly if we try routing this way. What do you think would be the best direction to go here?

2021-07-15 14:34 UTC, jonkoops commented
Closing this, as we want to come up with a better solution for all route related code.

2021-07-15 14:34 UTC, closed without merging