Ugrade to Snowpack 3
keycloak/keycloak-admin-ui pull request #839
Opened 2021-07-13 15:49 UTC by jonkoops

2021-07-13 16:20 UTC, jonkoops commented on src/context/auth/keycloak.ts
>      await kcAdminClient.init(
@ssilvert I went through this file like a butcher, as the basePath was messing with the local development and testing. Perhaps we can take a moment and sit to see what needs to remain for your work to get us integrated as a Keycloak theme.

2021-07-13 17:55 UTC, ssilvert reviewed
I haven't tested this out yet, but offered my feedback so far.

2021-07-13 17:55 UTC, ssilvert commented on themes/keycloak/index.html
> +  <script type="module" src="index.js"></script>
This change will silently break Keycloak server integration done in https://github.com/keycloak/keycloak-admin-ui/pull/840.  To fix, it just requires a simple change to pom.xml.

I'd like to figure out a way to at least be alerted whenever index.html changes.  Hopefully, this file will not change very often.

2021-07-13 17:55 UTC, ssilvert commented on .github/pull_request_template.md
> -- [ ] Type checking has been performed via 'npm run check-types'
Why remove these?

2021-07-13 17:55 UTC, ssilvert commented on .github/workflows/node.js.yml
> -    - run: npm run check-types
Don't we need to keep this?  Is type checking done somewhere else when a PR is opened?

2021-07-13 17:55 UTC, ssilvert commented on security-admin-console-v2-combined.json
> -        "/adminv2/*",
Note that this whole file is deleted in https://github.com/keycloak/keycloak-admin-ui/pull/840

2021-07-13 17:55 UTC, ssilvert commented on snowpack.config.mjs
> +import proxy from "http2-proxy";
Note that changes to snowpack.config.js are made in https://github.com/keycloak/keycloak-admin-ui/pull/840.  I assume those changes will need to be incorporated into snowpack.config.mjs?

2021-07-13 17:55 UTC, ssilvert commented on src/authentication/messages.ts
> +export default {
So all messages.json files were converted to messages.ts?
I think that's fine, but was this necessary to convert to Snowpack 3?  If not, it would have been best to put in a separate PR.

2021-07-13 18:02 UTC, jonkoops commented on .github/pull_request_template.md
> -- [ ] Type checking has been performed via 'npm run check-types'
We now have a GIT hook that will automatically do this for you when a commit is created, so there is no longer a need to run this manually. In the odd case people use `--no-verify` to commit the CI will catch this as well.

2021-07-13 18:04 UTC, jonkoops commented on .github/workflows/node.js.yml
> -    - run: npm run check-types
The type checks are now done by the Snowpack build itself, we're using the `@snowpack/plugin-typescript` plugin to do so.

2021-07-13 18:04 UTC, jonkoops commented on security-admin-console-v2-combined.json
> -        "/adminv2/*",
I'll remove it when we can rebase on top :+1:

2021-07-13 18:05 UTC, jonkoops commented on snowpack.config.mjs
> +import proxy from "http2-proxy";
Correct. Once we merge one of the PRs we can make this change.

2021-07-13 18:06 UTC, jonkoops commented on src/authentication/messages.ts
> +export default {
Yes, this was necessary because Snowpack would create import statements to JSON files in the final build. These import statements would fire a request and the browser would block it because it expects these files to be loaded as JavaScript, which they are not.

2021-07-14 08:16 UTC, edewit commented on themes/keycloak/index.html
> +  <script type="module" src="index.js"></script>
@jonkoops we could also do without this change and change the path back to `/_dist_/` in the snowpack config

2021-07-14 08:27 UTC, edewit requested changes

2021-07-14 08:27 UTC, edewit commented on snowpack.config.mjs
> +    bundle: true,
will this work? I still get erors:

```
[11:27:42] [snowpack] Build failed with 20 errors:
build/web_modules/@patternfly/patternfly/assets/fonts/overpass-mono-webfont/overpass-mono.css:6:11: error: No loader is configured for ".eot" files: build/web_modules/@patternfly/patternfly/assets/fonts/overpass-mono-webfont/overpass-mono-light.eot?#iefix
build/web_modules/@patternfly/patternfly/assets/fonts/overpass-mono-webfont/overpass-mono.css:19:11: error: No loader is configured for ".eot" files: build/web_modules/@patternfly/patternfly/assets/fonts/overpass-mono-webfont/overpass-mono-regular.eot?#iefix
build/web_modules/@patternfly/patternfly/assets/fonts/overpass-mono-webfont/overpass-mono.css:32:11: error: No loader is configured for ".eot" files: build/web_modules/@patternfly/patternfly/assets/fonts/overpass-mono-webfont/overpass-mono-semibold.eot?#iefix
build/web_modules/@patternfly/patternfly/assets/fonts/overpass-mono-webfont/overpass-mono.css:45:11: error: No loader is configured for ".eot" files: build/web_modules/@patternfly/patternfly/assets/fonts/overpass-mono-webfont/overpass-mono-bold.eot?#iefix
build/web_modules/@patternfly/patternfly/assets/fonts/overpass-webfont/overpass.css:4:11: error: No loader is configured for ".eot" files: build/web_modules/@patternfly/patternfly/assets/fonts/overpass-webfont/overpass-thin.eot?#iefix
```

2021-07-14 08:27 UTC, edewit commented on public/rh-sso-index.css
> -}
don't we still need this?

2021-07-14 09:29 UTC, jonkoops commented on public/rh-sso-index.css
> -}
This now in `themes/rh-sso/index.html`

2021-07-14 09:40 UTC, edewit commented on snowpack.config.mjs
> +    bundle: true,
it was me...

2021-07-14 12:40 UTC, jonkoops commented on themes/keycloak/index.html
> +  <script type="module" src="index.js"></script>
I was having some issues when using a non-root path, specifically that the assets could not be found on a static build. Let's merge Stan's PR first, and I will do some research into this after.

2021-07-14 12:44 UTC, edewit commented on themes/keycloak/index.html
> +  <script type="module" src="index.js"></script>
Well if it's a problem to change it here then we can just change it in the `pom.xml`

2021-07-16 08:56 UTC, edewit approved these changes

2021-07-16 08:59 UTC, merged