Run as theme
keycloak/keycloak-admin-ui pull request #840
Opened 2021-07-13 17:16 UTC by ssilvert

## Motivation
Allow new admin console to run as a theme on Keycloak server.

## Brief Description
When you build the app, it will no longer go into `/build`.  Instead, it will be built into `/build/src/main/resources/admin/resources`.  The reason for this change is that we now have a Maven `pom.xml` whose home is `/build`.  This Maven build will facilitate integration in the main Keycloak server build.

## Verification Steps
_Note: The steps below are for verification of Keycloak server integration.  Everything should work normally in development mode._
1.  `npm run build`
2. `cd build`
3. `mvn clean install`
4. copy `/build/target/classes/admin` directory to `<keycloak install>/themes/keycloak.v2`.  Alternatively, you can unzip keycloak-`admin-ui-0.0.1-SNAPSHOT.jar` into that directory.
5. Until we make changes to the Keycloak server, you will need to edit `<keycloak install>/themes/keycloak.v2/admin/index.ftl`.  You will need to hard-code the value for loginRealm.  So most of the time, it will be sufficient to replace `"${loginRealm}"` with `"master"`.
6. Go to `Realm Settings --> Themes` and set Admin Console Theme to `keycloak.v2`.
7. Go directly to Keycloak server with a URL such as [http://localhost:8180/auth/admin/master/console/](http://localhost:8180/auth/admin/master/console/)
8. Step 7 gets you to the console logging into master realm.  But you can also act as an administrator who is restricted to a single realm.  For that, you will need to set the name of the single realm, such as `"test"` in step 5.  Then create a user with proper permissions for the realm and log in with a URL such as [http://localhost:8180/auth/admin/test/console/](http://localhost:8180/auth/admin/test/console/).  See [https://www.keycloak.org/docs/6.0/server_admin/#_per_realm_admin_permissions](https://www.keycloak.org/docs/6.0/server_admin/#_per_realm_admin_permissions)

_You can also test step 8 in development mode.  Follow the same instructions, except the URL will be [http://localhost:8080/?realm=test](http://localhost:8080/?realm=test)_

## Checklist:

- [X] Code has been tested locally by PR requester
- [NA] User-visible strings are using the react-i18next framework (useTranslation)
- [NA] Help has been implemented
- [NA] axe report has been run and resulting a11y issues have been resolved
- [X] Unit tests have been created/updated
- [X] Formatting has been performed via prettier/eslint
- [X] Type checking has been performed via 'npm run check-types'

## Additional Notes
One of the notes in the README.md does not apply yet.  `-Dprofile.feature.newadmin=enabled` does not exist in the Keycloak server yet.  So you do not need to enable it.

2021-07-13 17:56 UTC, jonkoops requested changes

2021-07-13 17:56 UTC, jonkoops commented on .gitignore
> +.build/src
As far as I can tell we never generate a `.build` directory, I think we can remove these entries.

2021-07-13 17:56 UTC, jonkoops commented on build/pom.xml
> +  &lt;/script&gt;
Instead of putting a bunch of vars on the global scope I think it's better if we create a file in the application which can read these variables as JSON by retrieving the element from the DOM. I wrote a blog post on how to do this to [Dockerize front-end applications](https://dev.to/jonkoops/building-portable-front-end-applications-with-docker-2cpm), from which I think we can take some pointers.

2021-07-13 17:56 UTC, jonkoops commented on build/pom.xml
> +    </dependencyManagement>
Do we need these elements if they are empty?

2021-07-13 17:56 UTC, jonkoops commented on build/pom.xml
> +                            <value>src="${resourceUrl}/_dist_</value>
Be aware that in the Snowpack 3 PR (https://github.com/keycloak/keycloak-admin-ui/pull/839) this directory no longer exists, and all is served from the directory root.

2021-07-13 17:56 UTC, jonkoops commented on src/context/whoami/WhoAmI.tsx
> +  constructor(private me?: WhoAmIRepresentation | undefined) {
`me` is already marked as optional, so it's type does not have to be overloaded into `undefined`.
```suggestion
  constructor(private me?: WhoAmIRepresentation) {
```

2021-07-13 18:07 UTC, ssilvert commented on build/pom.xml
> +  &lt;/script&gt;
Note that Maven is creating index.ftl from index.html.

2021-07-13 18:18 UTC, ssilvert commented on build/pom.xml
> +    </dependencyManagement>
Nope.  Need to remove those.

2021-07-13 19:55 UTC, ssilvert commented on build/pom.xml
> +                            <value>src="${resourceUrl}/_dist_</value>
Yes.  We will need to update pom.xml in your PR.

2021-07-14 09:17 UTC, edewit commented on build/pom.xml
> +  &lt;/script&gt;
Instead of having all these `var`s as separate global variables we could create one and have these as properties:

```javascript
const settings = {
    loginRealm: "${loginRealm}",
    authServerUrl: "${authServerUrl}",
    authUrl: "${authUrl}",
    consoleBaseUrl: "${consoleBaseUrl}",
    resourceUrl: "${resourceUrl}",
    masterRealm: "${masterRealm}",
    resourceVersion: "${resourceVersion}",
}
```
this would be a slight improvement, but I must say I like the suggestion of @jonkoops with the json. That is so much cleaner then a global variable

2021-07-14 11:29 UTC, edewit commented on build/pom.xml
> +    var loginRealm = "${loginRealm}";
This seems to not be in the freemarker config

2021-07-14 14:07 UTC, ssilvert commented on build/pom.xml
> +  &lt;/script&gt;
I agree Jon's way would be better, but it's not possible.  Those values have to be embedded into index.ftl so they can be passed in by Freemarker.

2021-07-14 14:08 UTC, ssilvert commented on build/pom.xml
> +    var loginRealm = "${loginRealm}";
@edewit Right.  I've added it on the Keycloak side.  For now, you need to hard-code this by editing index.ftl.  See instructions above.

2021-07-14 14:26 UTC, edewit commented on build/pom.xml
> +  &lt;/script&gt;
@ssilvert yes Jon's way would be possible it would look like this in `index.ftl`:

```html
<script id="settings" type="application/json">
   {
     loginRealm: "${loginRealm}",
     authServerUrl: "${authServerUrl}",
     authUrl: "${authUrl}",
     consoleBaseUrl: "${consoleBaseUrl}",
     resourceUrl: "${resourceUrl}",
     masterRealm: "${masterRealm}",
     resourceVersion: "${resourceVersion}",
  }
</script>
```
And then you could use it like this:
```typescript
getSettings() {
  const element = document.getElementById('settings');

  try {
    return JSON.parse(element.textContent)
  } catch (error) {
    console.error('Unable to parse settings!');
  }

  return {}
}
```
By doing it like this there aren't any global variables

2021-07-14 15:18 UTC, ssilvert commented on build/pom.xml
> +  &lt;/script&gt;
@edewit @jonkoops Yes. I misunderstood what he was wanting to do.  I like that a lot.

2021-07-14 15:30 UTC, jonkoops approved these changes

2021-07-14 15:35 UTC, merged