Ecdsa provider details copy
keycloak/keycloak-admin-ui pull request #850
Opened 2021-07-14 15:59 UTC by jenny-s51

## Motivation

## Brief Description

## Verification Steps

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated
- [ ] Formatting has been performed via prettier/eslint

## Additional Notes

2021-07-15 09:29 UTC, jonkoops requested changes

2021-07-15 09:29 UTC, jonkoops commented on src/realm-settings/KeysProvidersTab.tsx
> -import { ECDSAGeneratedModal } from "./ECDSAGeneratedModal";
The file `src/realm-settings/ECDSAGeneratedModal.tsx` is still present, but no longer used anywhere.

2021-07-15 14:24 UTC, jonkoops requested changes

2021-07-15 14:24 UTC, jonkoops commented on src/realm-settings/key-providers/ecdsa-generated/ECDSAGeneratedModal.tsx
> +        providerType={providerType!}
Using the non-null assertion operator can lead to exceptions at run-time.
```suggestion
        providerType={providerType}
```

2021-07-15 14:24 UTC, jonkoops commented on src/realm-settings/key-providers/ecdsa-generated/ECDSAGeneratedForm.tsx
> +        <ECDSAGeneratedForm providerType={providerId!} editMode />
Using the non-null assertion operator can lead to exceptions at run-time.
```suggestion
        <ECDSAGeneratedForm providerType={providerId} editMode />
```

2021-07-15 14:24 UTC, jonkoops commented on src/realm-settings/key-providers/ecdsa-generated/ECDSAGeneratedForm.tsx
> +  )?.params.providerType;
We really should be using a central route definitions instead of copy-pasting these paths and related types. It's going to be very hard to find all these components and fix them if we ever change the structure of the routes.

2021-07-15 14:24 UTC, jonkoops commented on src/realm-settings/key-providers/ecdsa-generated/ECDSAGeneratedForm.tsx
> +              onToggle={() => setIsKeySizeDropdownOpen(!isKeySizeDropdownOpen)}
We don't have to manager this state ourselves.
```suggestion
              onToggle={(isExpanded) => setIsKeySizeDropdownOpen(isExpanded)}
```

2021-07-15 14:29 UTC, agagancarczyk requested changes

2021-07-15 14:29 UTC, agagancarczyk commented on src/realm-settings/key-providers/ecdsa-generated/ECDSAGeneratedForm.tsx
> +              forID="name"
Suggesting to use forID={t(`common:helpLabel`, { label: t("common:name") })} to avoid introducing accessibility issue.

2021-07-15 14:29 UTC, agagancarczyk commented on src/realm-settings/key-providers/ecdsa-generated/ECDSAGeneratedForm.tsx
> +            forID="name"
Suggesting to use forID={t(`common:helpLabel`, { label: t("common:name") })} to avoid introducing accessibility issue

2021-07-15 14:29 UTC, agagancarczyk commented on src/realm-settings/key-providers/ecdsa-generated/ECDSAGeneratedForm.tsx
> +            forID="kc-enabled"
Suggesting to use forID={t(`common:helpLabel`, { label: t("enabled") })} to avoid introducing accessibility issue

2021-07-15 14:29 UTC, agagancarczyk commented on src/realm-settings/key-providers/ecdsa-generated/ECDSAGeneratedForm.tsx
> +            forID="kc-active"
Suggesting to use forID={t(common:helpLabel, { label: t("active") })} to avoid introducing accessibility issue

2021-07-15 14:29 UTC, agagancarczyk commented on src/realm-settings/key-providers/ecdsa-generated/ECDSAGeneratedForm.tsx
> +            forID="kc-elliptic-curve"
Suggesting to use forID={t(common:helpLabel, { label: t("ellipticCurve") })} to avoid introducing accessibility issue

2021-07-15 14:32 UTC, agagancarczyk requested changes

2021-07-15 14:32 UTC, agagancarczyk commented on src/realm-settings/key-providers/ecdsa-generated/ECDSAGeneratedForm.tsx
> +              id="kc-enabled"
Suggesting to use id="kc-enabled-switch" to avoid introducing accessibility issue.

2021-07-15 14:32 UTC, agagancarczyk commented on src/realm-settings/key-providers/ecdsa-generated/ECDSAGeneratedForm.tsx
> +                id="kc-active"
Suggesting to use id="kc-active-switch" to avoid introducing accessibility issue.

2021-07-15 14:56 UTC, jenny-s51 commented on src/realm-settings/key-providers/ecdsa-generated/ECDSAGeneratedForm.tsx
> +        <ECDSAGeneratedForm providerType={providerId!} editMode />
A type error is yielded here unless the non-null assertion operator is used

2021-07-15 14:58 UTC, jonkoops commented on src/realm-settings/key-providers/ecdsa-generated/ECDSAGeneratedForm.tsx
> +        <ECDSAGeneratedForm providerType={providerId!} editMode />
If that is the case then the props of the `ECDSAGeneratedForm` component will have to be changed so the value can be `undefined`.

2021-07-15 14:59 UTC, jonkoops commented on src/realm-settings/key-providers/ecdsa-generated/ECDSAGeneratedForm.tsx
> +  )?.params.providerType;
This is not a point for this PR by the way, just a side-note we should do something about it project-wide.

2021-07-15 15:15 UTC, jonkoops requested changes

2021-07-15 15:15 UTC, jonkoops commented on src/realm-settings/key-providers/ecdsa-generated/ECDSAGeneratedForm.tsx
> +  providerType: string | undefined;
You can mark a prop as optional, which is the same as making it `T | undefined`
```suggestion
  providerType?: string;
```

2021-07-15 20:50 UTC, mfrances17 requested changes
Looks good... functionality works as described in the testing steps. I noticed two things:

I get a consistent console error when the 'Add provider' modal is invoked:

```TextInputBase contains an input of type text with both value and defaultValue props. Input elements must be either controlled or uncontrolled (specify either the value prop, or the defaultValue prop, but not both). Decide between using a controlled or uncontrolled input element and remove one of these props.```

Also, are there supposed to be other selections for the Elliptic Curve select? Currently, only P-256 is displayed and the dropdown doesn't work to select any other options.

2021-07-16 14:21 UTC, jenny-s51 commented
nice catch @mfrances17 ... thank you - both issues should be now fixed

2021-07-16 17:46 UTC, mfrances17 approved these changes
LGTM - code looks good, the issues I encountered have both been fixed, and functionality works as expected.

2021-07-17 12:43 UTC, jonkoops approved these changes

2021-07-19 13:48 UTC, agagancarczyk approved these changes

2021-07-19 13:58 UTC, merged