Initial version of the authentication section
keycloak/keycloak-admin-ui pull request #887
Opened 2021-07-21 10:52 UTC by edewit

Just wanted to add this because it's getting kinda big, it's not done yet, but it's a start

Missing are adding flows and executions.

2021-07-22 09:28 UTC, jonkoops commented on package.json
> +    "dagre": "^0.8.5",
Do we want to introduce this dependency? From the [README of the project](https://github.com/dagrejs/dagre):

> # Important!
> 
> **This project does not have a maintainer or active project members. There won’t be any support or attention to pull requests. Please do not contact previous maintainers unless you are qualified and have the resources to make a serious commitment to fully take over ownership of the project.**

2021-07-22 09:28 UTC, jonkoops commented on src/authentication/AuthenticationSection.tsx
> +                  >
This `Button` can be a React Router `Link` by providing the `component` prop.
```suggestion
                  <Button component={Link} to={`/${realm}/authentication/create`}>
```

2021-07-22 09:58 UTC, edewit commented on package.json
> +    "dagre": "^0.8.5",
well it works we could also not use it...

2021-07-27 14:34 UTC, jonkoops commented on package.json
> +    "dagre": "^0.8.5",
As discussed during the team meet, let's create an issue for this and keep the dependency for now.

2021-07-27 15:32 UTC, jonkoops requested changes

2021-07-27 15:32 UTC, jonkoops commented on src/authentication/AuthenticationSection.tsx
> +        key={`link-{id}`}
This template string is missing an expression.

```suggestion
        key={`link-${id}`}
```

2021-07-27 15:32 UTC, jonkoops commented on src/authentication/FlowDetails.tsx
> +      const times = c.newIndex - c.oldIndex;
If I remove this cast the code still works, so I think it's not needed.

```suggestion
      const times = change.newIndex - change.oldIndex;
```

2021-07-27 15:32 UTC, jonkoops commented on src/authentication/FlowDetails.tsx
> +          });
These requests will be waiting for each request to finish before firing another. I am not aware of how this API works, but if it doesn't care about the requests completing in order this could be parallelized using `Promise.all()`.

2021-07-27 15:32 UTC, jonkoops commented on src/authentication/FlowDetails.tsx
> +        titleKey={toUpperCase(flow?.alias! || "")}
Since `alias` is already asserted as non-null the default fallback can be removed here.
```suggestion
        titleKey={toUpperCase(flow?.alias!)}
```

2021-07-27 15:32 UTC, jonkoops commented on src/authentication/FlowDetails.tsx
> +          executionList.expandableList.length > 0 && (
To reduce the size of this statement you could use `length` as an implicit truthy or falsy value by letting JavaScript cast it for you:
```suggestion
        {executionList?.expandableList?.length && (
```

2021-07-27 15:32 UTC, jonkoops commented on src/authentication/FlowDetails.tsx
> +                    aria-label="copy icon button"
This label should be a translated human-readable string.

2021-07-27 15:32 UTC, jonkoops commented on src/authentication/FlowDetails.tsx
> +                    aria-label="undo icon button"
This label should be a translated human-readable string.

2021-07-27 15:32 UTC, jonkoops commented on src/authentication/FlowDetails.tsx
> +          executionList.expandableList.length > 0 && (
To reduce the size of this statement you could use `length` as an implicit truthy or falsy value by letting JavaScript cast it for you:

```suggestion
        {tableView && executionList?.expandableList?.length && (
```

2021-07-27 15:39 UTC, edewit commented on src/authentication/FlowDetails.tsx
> +          });
it's only faster when one of these calls fails, even though this code looks synchrones it's not, it is syntactic sugar that makes it easier to write promises

2021-07-27 15:41 UTC, edewit commented on package.json
> +    "dagre": "^0.8.5",
created issue: https://github.com/keycloak/keycloak-admin-ui/issues/919

2021-07-27 15:52 UTC, edewit commented on src/authentication/FlowDetails.tsx
> +      const times = c.newIndex - c.oldIndex;
yeah that is a part of old code I think `LevelChange` has the same properties as `IndexChange` now

2021-07-27 15:53 UTC, jonkoops requested changes

2021-07-27 15:53 UTC, jonkoops commented on src/authentication/__tests__/ExecutionList.test.tsx
> +import { ExecutionList, IndexChange, LevelChange } from "../execution-model";
We're using a mix of tests in `__tests__` directories and `*.test.* files living next to their source files. I personally prefer the latter if we need to settle on a convention here.

Also, tests :partying_face: Yay!

2021-07-27 15:53 UTC, jonkoops commented on src/authentication/__tests__/ExecutionList.test.tsx
> +  it("Move 1 down to the end", () => {
I prefer writing my test cases like a sentence, for example:

```
it moves 1 down to the end
```

or

```suggestion
  it("moves 1 down to the end", () => {
```

But this is a personal preference :man_shrugging:

2021-07-27 15:53 UTC, jonkoops commented on src/realm-settings/messages.json
> +  }
This change now only removes a comma. However it should be removed as we no longer support JSON translation files.

2021-07-27 15:53 UTC, jonkoops commented on src/components/view-header/ViewHeader.tsx
> +  text?: string | ReactNode;
No need to provide `string` as a type here, as a string is already a type under `ReactNode`.
```suggestion
  text?: ReactNode;
```

2021-07-27 19:40 UTC, jonkoops commented on src/realm-settings/messages.json
> +  }
Fixed this in #920

2021-07-27 20:24 UTC, mfrances17 reviewed
Code looks good. I was able to create a new flow and dup existing ones. There's a lot of changes here and I realize this is a WIP, but it would be nice to have test steps within the PR so as to know what is expected to be working and how to test it appropriately. For example, I was not able to select a new or existing flow, i get 'Cannot read property at 'charAt' of undefined' errors. So I'm not sure if that should be working yet or not. Based on the code, I would expect more of that to be working.

2021-07-28 10:51 UTC, jonkoops requested changes

2021-07-28 10:51 UTC, jonkoops commented on src/authentication/form/FlowType.tsx
> +            onToggle={() => setOpen(!open)}
We don't need to manage this state ourselves. We can use the value provided by the select instead.
```suggestion
            onToggle={(isExpanded) => setOpen(isExpanded)}
```

2021-07-28 10:51 UTC, jonkoops commented on src/authentication/form/FlowType.tsx
> +              onChange(value as string);
A `SelectOptionObject` need to implement `toString()` so we do not have to type-cast this value.
```suggestion
              onChange(value.toString());
```

2021-07-28 10:51 UTC, jonkoops commented on src/realm-settings/UserRegistration.tsx
> +        {/* <EvaluateScopes clientId={clientId} protocol={client!.protocol!} /> */}
Why is this code commented out?

2021-07-28 10:51 UTC, jonkoops commented on src/realm-settings/UserRegistration.tsx
> +import React, { useState } from "react";
This file seems like a work-in-progress. I assume the rest of the functionality will be implemented in another PR?

2021-07-28 10:51 UTC, jonkoops commented on src/realm-settings/UserRegistration.tsx
> +      await Promise.all(
I might be mistaken, but it looks like nothing is async here, perhaps we can get rid of the `async`/`await`?

2021-07-28 10:51 UTC, jonkoops commented on src/authentication/components/FlowRow.tsx
> +    execution.executionList && execution.executionList.length > 0;
I believe you could fall back on JavaScript casting here.
```suggestion
  const hasSubList = !!execution.executionList.length;
```

2021-07-28 10:51 UTC, jonkoops commented on src/authentication/components/FlowRow.tsx
> +          key={execution.id}
I don't think a `key` is required at this level.

2021-07-28 10:51 UTC, jonkoops commented on src/authentication/components/FlowRow.tsx
> +              aria-labelledby={execution.displayName}
I don't believe it's valid to use both of these attributes.

2021-07-28 11:16 UTC, edewit commented on src/realm-settings/UserRegistration.tsx
> +import React, { useState } from "react";
yes it wasn't suppose to be here... I'll remove it

2021-07-28 11:27 UTC, edewit commented on src/authentication/components/FlowRow.tsx
> +              aria-labelledby={execution.displayName}
Are you sure? In the [example](https://www.patternfly.org/v4/components/data-list/#datalistdragbutton) they set both of these

2021-07-28 11:39 UTC, jonkoops commented on src/authentication/components/FlowRow.tsx
> +              aria-labelledby={execution.displayName}
Yes, the ARIA conventions used in Patternfly are wrong. According to [Google Developers](https://developers.google.com/web/fundamentals/accessibility/semantics-aria/aria-labels-and-relationships), which states the following:

> Importantly, `aria-labelledby` overrides **all** other name sources for an element. So, for example, if an element has both an `aria-labelledby` and an `aria-label`, or an `aria-labelledby` and a native HTML `label`, the `aria-labelledby` label always takes precedence.

2021-07-28 13:16 UTC, edewit commented on src/authentication/components/FlowRequirementDropdown.tsx
> +          onToggle={() => setOpen(!open)}
wouldn't this `isExpanded` always be `!open` and we still need `open` right?

2021-07-29 07:12 UTC, edewit commented on src/authentication/components/FlowRequirementDropdown.tsx
> +      {flow.requirementChoices && flow.requirementChoices?.length > 1 && (
Can't do that as I need it to be bigger then 1 not exactly 1. The expression `flow.requirementChoices?.length` will be true for a length of one. I can how ever remove the ? as it can't be undefined

2021-07-29 07:15 UTC, edewit commented
@mfrances17 I introduced a bug sorry. Added some tests and it's ready to review again

2021-07-29 15:33 UTC, jonkoops commented on src/authentication/components/FlowRequirementDropdown.tsx
> +      {flow.requirementChoices && flow.requirementChoices?.length > 1 && (
Ahhh, yes. That makes sense!

2021-08-02 09:18 UTC, jonkoops approved these changes

2021-08-09 08:47 UTC, merged