Sessions(actions dropdown): Adds Revocation action item
keycloak/keycloak-admin-ui pull request #896
Opened 2021-07-22 20:37 UTC by jenny-s51

## Motivation

Towards https://issues.redhat.com/browse/APPDUX-1067

## Brief Description

Adds "revocation" functionality to Actions dropdown of sessions page

## Verification Steps

1. Go to Sessions
2. Click on "Actions" menu in the top right and select "Revocation"
3. Click "Set to now".
4. Sign back in
5. Repeat steps 1-2
6. Verify that "Not before" value is correct
7. Click "Clear"
8. Click on "Actions" menu in the top right and select "Revocation"
9. Verify that "Not before" value is set to none.

* Push functionality will be confirmed by @ssilvert - REST call is WIP, empty payload is sent though attributes are declared: https://github.com/keycloak/keycloak-admin-ui/compare/master...jenny-s51:sessionsActionsMenu?expand=1#diff-8cb2449f432ea56b8ea79baaf2d01514e4ec7482e1ae615d2569cfaf19f35b15R96-R99

@edewit can you kindly take a look at this call and share your thoughts when you have a moment?

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

## Additional Notes

2021-07-23 09:49 UTC, edewit reviewed
Looking good so far, why is it a draft?

2021-07-23 09:49 UTC, edewit commented on src/sessions/RevocationModal.tsx
> +    },
Can be written a bit simpler:

```suggestion
  useFetch(
    () => adminClient.realms.findOne({ realm: realmName }),
    (realm) => {
      setRealm(realm);
    },
```

2021-07-23 09:49 UTC, edewit commented on src/sessions/RevocationModal.tsx
> +    adminClient.keycloak.logout({ redirectUri: "" });
why would this be necessary?

2021-07-23 13:17 UTC, jenny-s51 commented on src/sessions/RevocationModal.tsx
> +    adminClient.keycloak.logout({ redirectUri: "" });
@edewit This is currently how it looks like it's done in the old admin console - it logs the user out and the notBefore time is set successfully - otherwise the call results in a network error if you try setting the `notBefore` and then toggling the modal again to clear it

2021-07-23 13:21 UTC, jenny-s51 commented
@edewit does this call look okay to you? https://github.com/keycloak/keycloak-admin-ui/compare/master...jenny-s51:sessionsActionsMenu?expand=1#diff-8cb2449f432ea56b8ea79baaf2d01514e4ec7482e1ae615d2569cfaf19f35b15R96-R99

I've declared `id` and `realm` values here but they are not being sent in the request payload (sent as `{}`)

2021-07-23 13:48 UTC, edewit approved these changes

2021-07-23 13:51 UTC, edewit commented
You don't need `realm` as it will use the "current" realm set on the client

On Fri, Jul 23, 2021 at 3:22 PM Jenny ***@***.***> wrote:

> @edewit <https://github.com/edewit> does this call look okay to you?
> https://github.com/keycloak/keycloak-admin-ui/compare/master...jenny-s51:sessionsActionsMenu?expand=1#diff-8cb2449f432ea56b8ea79baaf2d01514e4ec7482e1ae615d2569cfaf19f35b15R96-R99
>
> I've declared id and realm values here but they are not being sent in the
> request payload (sent as {})
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/keycloak/keycloak-admin-ui/pull/896#issuecomment-885635217>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAAMPPJFAVLDMSSYIJ6VLWTTZFUIDANCNFSM5A2XYG2Q>
> .
>

2021-07-23 15:49 UTC, jonkoops requested changes

2021-07-23 15:49 UTC, jonkoops commented on src/sessions/messages.ts
> +    pushError:
`pushError` is never used as far as I can tell.

2021-07-23 15:49 UTC, jonkoops commented on src/sessions/RevocationModal.tsx
> +  id?: string;
Looks like the `id` prop is never used or passed, so I believe it can be removed.

2021-07-23 15:49 UTC, jonkoops commented on src/sessions/RevocationModal.tsx
> +    await adminClient.realms.update(
Should this perhaps be wrapped in a `try` block so we can show an error message if something goes wrong?

2021-07-23 15:49 UTC, jonkoops commented on src/sessions/RevocationModal.tsx
> +        notBefore: Number(moment().unix()),
Would `Date.now()` not give the same result here?

2021-07-23 15:49 UTC, jonkoops commented on src/sessions/RevocationModal.tsx
> +        })) as unknown as GlobalRequestResult;
This looks like a bug in the admin client? Perhaps we can submit an issue for it?

2021-07-23 15:49 UTC, jonkoops commented on src/sessions/RevocationModal.tsx
> +        const result = (await adminClient.clients.pushRevocation({
Note that this will block on each request being made, I don't know if that is intentional, but this could be parallelized by using `Promise.all()`.

2021-07-23 17:24 UTC, jenny-s51 commented on src/sessions/RevocationModal.tsx
> +    await adminClient.realms.update(
good idea

2021-07-23 18:36 UTC, jenny-s51 commented on src/sessions/RevocationModal.tsx
> +        })) as unknown as GlobalRequestResult;
Opened https://github.com/keycloak/keycloak-nodejs-admin-client/issues/190

2021-07-26 13:41 UTC, jonkoops reviewed
LGTM :heavy_check_mark:

2021-07-26 13:42 UTC, jonkoops approved these changes

2021-07-27 19:40 UTC, ssilvert requested changes
If I'm on a realm other than master, "set to now" should not log me out.   Looks like you are calling the correct API, but your code sends a payload while the old console does not.

For push, it's calling the wrong API.  For "foo" realm, your code calls:
http://localhost:8080/auth/admin/realms/foo/clients/20aacb1c-09cf-46f7-aa0a-532a2c219fa6/push-revocation

Old console calls:
http://localhost:8080/auth/admin/realms/foo/push-revocation

2021-07-27 19:42 UTC, ssilvert commented
@jenny-s51 Also, I re-ran the tests and looks like they are still failing.  Need to figure out if it's the new code or an intermittent failure.

2021-07-27 19:56 UTC, mfrances17 requested changes
Functionality works great from testing the provided steps. A couple of easy string issues you should fix. Otherwise looks good.

2021-07-27 19:56 UTC, mfrances17 commented on src/sessions/LogoutAllSessionsModal.tsx
> +      title={t("signOutAllActiveSessions") + "?"}
You shouldn't concatenate strings like this for L10N... it assumes English. Some languages use different punctuation, e.g. spanish uses upside down question mark at beginning and question mark at end. Best to just put the ? in the messages file string and let the translators sub the correct string.

2021-07-27 19:56 UTC, mfrances17 commented on src/sessions/RevocationModal.tsx
> +                ? (t("None") as string)
this should be lower case 'none' otherwise it's not doing a string lookup it's just forcing 'None'

2021-07-27 19:57 UTC, jenny-s51 commented
@ssilvert @mfrances17 thank you for reviewing! Will make the corresponding updates

2021-07-28 17:18 UTC, jenny-s51 commented
Opened a PR in the nodejs client that adds `pushRevocation` to `realms` so the "Push" calls the correct endpoint as @ssilvert mentioned: https://github.com/keycloak/keycloak-nodejs-admin-client/pull/194

@edewit would be great to get your eyes on it when you have a moment

2021-07-30 13:07 UTC, jonkoops commented
@jenny-s51 Looks like your change landed in 73a7cd42656ec7c7fdcec332d1dc84d428cb0976

2021-07-30 15:42 UTC, jenny-s51 commented
@ssilvert @mfrances17 I've addressed your feedback! Please kindly re-review again when you have a moment

2021-08-02 13:14 UTC, ssilvert reviewed
@jenny-s51 This is still not working properly for realms other than master.  We need to talk this afternoon and decide if we should merge and follow up with an issue.

2021-08-02 13:14 UTC, ssilvert commented on src/sessions/RevocationModal.tsx
> +      }
We should not explicitly log out here.  If you are logged into a realm and you "Set to now" for your own realm, the adapter will log you out.

Conversely, if you "Set to now" for a realm you are not logged into, you will not be logged out.  Never forget that you can get to admin console by logging into a realm that is not master.

Bottom line is that lines 97-99 should be deleted.

2021-08-06 13:28 UTC, mfrances17 approved these changes
LGTM... thanks for making the changes. I swore I had already approved, sorry for the lateness.

2021-08-06 17:23 UTC, jonkoops requested changes

2021-08-06 17:23 UTC, jonkoops commented on src/sessions/SessionsSection.tsx
> +  console.log("🤞", whoAmI);
Hahaha, I feel this `console.log` statement. It can be removed however :smile:

2021-08-06 17:23 UTC, jonkoops commented on cypress/support/pages/admin_console/manage/sessions/SessionsPage.ts
> +  sessionTypeDrpDwn = ".pf-c-select__toggle";
Liking this cleanup :100:

2021-08-06 17:23 UTC, jonkoops commented on src/components/view-header/ViewHeader.tsx
> +  dropdownIsDisabled?: boolean;
I believe the convention used by most props would be `isDropdownDisabled`, but works either way.

2021-08-06 17:23 UTC, jonkoops commented on src/context/whoami/WhoAmI.tsx
> +  public getRealm(): string {
There is no need to add a return type on this method as the type can be inferred from the returned value.
```suggestion
  public getRealm()
```

2021-08-06 17:23 UTC, jonkoops commented on src/context/whoami/WhoAmI.tsx
> +    return this.me.realm;
This code can be shortened using [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining).
```suggestion
    return this.me?.realm ?? "";
```

2021-08-06 17:23 UTC, jonkoops commented on src/sessions/LogoutAllSessionsModal.tsx
> +  id?: string;
The `id` prop is never passed (or used), so I believe it can be removed.

2021-08-06 17:23 UTC, jonkoops commented on src/sessions/LogoutAllSessionsModal.tsx
> +      adminClient.keycloak.logout({ redirectUri: "" });
I see the `keycloak` property has a type of `any`, is this a known bug? If not can you report it on the Keycloak Admin client repo?

2021-08-06 17:23 UTC, jonkoops commented on src/sessions/RevocationModal.tsx
> +  save: (realm?: UserRepresentation) => void;
I don't see `realm` being passed or used anywhere, so I think this could be removed.
```suggestion
  save: () => void;
```

2021-08-06 17:23 UTC, jonkoops commented on src/sessions/RevocationModal.tsx
> +    }) as unknown as GlobalRequestResult;
This looks like an issue with the types from the admin client, could you create an issue for that?

2021-08-16 13:59 UTC, jenny-s51 commented on src/sessions/LogoutAllSessionsModal.tsx
> +      adminClient.keycloak.logout({ redirectUri: "" });
opened https://github.com/keycloak/keycloak-nodejs-admin-client/issues/205

2021-08-16 13:59 UTC, jenny-s51 commented on src/sessions/RevocationModal.tsx
> +  save: (realm?: UserRepresentation) => void;
nice catch

2021-08-16 14:10 UTC, jenny-s51 commented on src/sessions/RevocationModal.tsx
> +    }) as unknown as GlobalRequestResult;
opened https://github.com/keycloak/keycloak-nodejs-admin-client/issues/206

2021-08-16 15:18 UTC, jonkoops requested changes

2021-08-16 15:18 UTC, jonkoops commented on src/components/view-header/ViewHeader.tsx
> +  badgeId?: string;
The `badgeId` prop is never used and can be removed.

2021-08-16 15:21 UTC, jonkoops approved these changes

2021-08-16 19:25 UTC, ssilvert approved these changes
This works fine, but for some reason it always comes back with the message `No push sent. No admin URI configured or no registered cluster nodes available`

This message comes from clients/messages.ts.  I'm going to merge and log an issue.

2021-08-16 19:25 UTC, merged