Add issue template to inform new contributors
keycloak/keycloak-admin-ui pull request #924
Opened 2021-07-28 11:56 UTC by jonkoops

2021-07-28 13:19 UTC, edewit requested changes
can't we put this into html comments `<!--` and `-->` as we do for the other templates? That way one can leave it but it will not be shown. see: ./keycloak-admin-ui/.github/pull_request_template.md

2021-07-28 13:25 UTC, mfrances17 requested changes
Some wording suggestions

2021-07-28 13:25 UTC, mfrances17 commented on .github/issue_template.md
> +This repository contains the new Admin UI for Keycloak which is still experimental and not enabled by default. If you are looking to report an issue with the stable Keycloak Admin UI or other parts o
The docs refer to it as the 'admin console' or 'Administration Console', I would use either of those throughout instead of 'Admin UI'. 

Also, I recommend the following:
 'pre-release' instead of 'new'
 'still in development' vs 'experimental'
'released Keycloak Administration Console' vs 'stable Keycloak Admin UI'

2021-07-28 13:58 UTC, andymunro commented on .github/issue_template.md
> +This repository contains the new Admin UI for Keycloak which is still experimental and not enabled by default. If you are looking to report an issue with the stable Keycloak Admin UI or other parts o
The initial screen for the UI calls it the "Administration Console," however everyone calls it the Admin Console and we are standardizing that in all the documentation.  So please call it the Admin Console.

2021-07-29 15:26 UTC, jonkoops commented on .github/issue_template.md
> +This repository contains the new Admin UI for Keycloak which is still experimental and not enabled by default. If you are looking to report an issue with the stable Keycloak Admin UI or other parts o
@mfrances17 @andymunro I've incorporated the changes, can you take another look?

2021-07-29 15:27 UTC, jonkoops commented
> can't we put this into html comments `<!--` and `-->` as we do for the other templates? 

Done :+1:

2021-07-29 19:01 UTC, andymunro approved these changes
Looks good, Jon.

2021-07-29 20:32 UTC, jenny-s51 approved these changes
LGTM

2021-07-30 12:57 UTC, edewit approved these changes

2021-07-30 13:41 UTC, mfrances17 approved these changes
Changes look great, thanks for doing this Jon.

2021-07-30 13:42 UTC, merged