events: search user events form, chips for searched fields and tests
keycloak/keycloak-admin-ui pull request #930
Opened 2021-07-30 16:50 UTC by agagancarczyk

## Motivation
Add Search for user events as per https://marvelapp.com/prototype/7ca9dhf/screen/73035918/handoff. 

## Brief Description
The main functionality of searching user events is implemented except for renaming chips categories, removing chips from the search results panel, updating the search form when chips are removed, and refreshing search results.

## Verification Steps

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

2021-08-02 11:31 UTC, jonkoops requested changes

2021-08-02 11:31 UTC, jonkoops commented on src/events/EventsSection.tsx
> +                        onToggle={onSelectToggle}
We don't need to manage the toggle state ourselves as the callback provides an argument for it.
```suggestion
                        onToggle={(isOpen) => setSelectOpen(isOpen)}
```

2021-08-02 11:31 UTC, jonkoops commented on src/events/EventsSection.tsx
> +          <DescriptionListGroup key={`detail-${index}`}>
Index should be used as a key as a [last resort only](https://reactjs.org/docs/lists-and-keys.html#keys). In this case I believe you can use `k` as the key since it should be unique.
```suggestion
          <DescriptionListGroup key={k}>
```

2021-08-02 11:31 UTC, jonkoops commented on src/events/EventsSection.tsx
> +  const clearSelection = (e: any) => {
This can be type-safe by specifying the correct type instead of `any`.
```suggestion
  const clearSelection = (e: React.MouseEvent) => {
```

2021-08-02 11:31 UTC, jonkoops commented on src/events/EventsSection.tsx
> +  const deleteIndividualSelection = (e: any, chip: string) => {
This can be type-safe by specifying the correct type instead of `any`.
```suggestion
  const deleteIndividualSelection = (e: React.MouseEvent, chip: string) => {
```

2021-08-02 11:31 UTC, jonkoops commented on src/events/EventsSection.tsx
> +        {(selectedEvents || []).map((chip, index) => (
`selectedEvents` always has a value, so it can be mapped directly.
```suggestion
        {selectedEvents.map((chip, index) => (
```

2021-08-02 11:31 UTC, jonkoops commented on src/events/EventsSection.tsx
> +            isReadOnly={index === 0 ? true : false}
The `index === 0` statement already produces a boolean value, so this ternary operation is not needed.
```suggestion
            isReadOnly={index === 0}
```

2021-08-02 11:31 UTC, jonkoops commented on src/events/EventsSection.tsx
> +  const [isDirty, setIsDirty] = useState(false);
Instead of managing this `dirty` state ourselves I believe we can use the [`formState.isDirty`](https://react-hook-form.com/v6/api#formState) from the forms library instead.

2021-08-02 11:31 UTC, jonkoops commented on src/events/EventsSection.tsx
> +                        }
The size of this statement can be reduced.
```suggestion
                        defaultValue={formValues?.userId ?? ""}
```

2021-08-02 11:31 UTC, jonkoops commented on src/events/EventsSection.tsx
> +                          }
There is some duplicated logic here, I think it can be shortened.
```suggestion
                          const selected = selectedEvents.includes(option)
                            ? selectedEvents.filter((item) => item !== option)
                            : [...selectedEvents, option];

                          setSelectedEvents(selected);
                          setValue("eventTypes", selected);
                          setIsDirty(true);
```

2021-08-02 11:31 UTC, jonkoops commented on src/events/EventsSection.tsx
> +                            setValue("eventTypes", [...selectedEvents, option]);
If `selectedEvents` always has the same value as `eventTypes`, why not use `eventTypes` only?

2021-08-02 11:31 UTC, jonkoops commented on src/events/EventsSection.tsx
> +                        }}
Does this not happen by default?

2021-08-02 11:31 UTC, jonkoops commented on src/events/EventsSection.tsx
> +                          formValues?.client ? formValues?.client : ""
This can be shortened.
```suggestion
                          formValues?.client ??  ""
```

2021-08-02 11:31 UTC, jonkoops commented on src/events/EventsSection.tsx
> +                        }}
Does this not happen by default?

2021-08-02 11:31 UTC, jonkoops commented on src/events/EventsSection.tsx
> +                          formValues?.dateFrom ? formValues?.dateFrom : ""
This can be be shortened.
```suggestion
                          formValues?.dateFrom ?? ""
```

2021-08-02 11:31 UTC, jonkoops commented on src/events/EventsSection.tsx
> +                        }}
Does this not happen by default?

2021-08-02 11:31 UTC, jonkoops commented on src/events/EventsSection.tsx
> +                          formValues?.dateTo ? formValues?.dateTo : ""
Can be shortened
```suggestion
                          formValues?.dateTo ?? ""
```

2021-08-02 11:31 UTC, jonkoops commented on src/events/EventsSection.tsx
> +                      <ChipGroup
When clicking the remove button on the chip nothing happens.

2021-08-02 11:31 UTC, jonkoops commented on src/events/EventsSection.tsx
> +                        {chipsToDisplay.type.map(
`chipsToDisplay.type` is of of type `any`.

2021-08-03 09:21 UTC, agagancarczyk commented on cypress/support/pages/admin_console/manage/events/EventsPage.ts
> +  }
Great idea, thanks.

2021-08-03 09:21 UTC, agagancarczyk commented on cypress/support/pages/admin_console/manage/events/EventsPage.ts
> +    return this;
Correct! The return value is not used.

2021-08-03 09:25 UTC, agagancarczyk commented on package-lock.json
>    "requires": true,
Yeah, that is strange. Should we include package-lock.json with our PRs?

2021-08-03 09:26 UTC, jonkoops commented on package-lock.json
>    "requires": true,
The convention I use here is that I only check in the `package-lock.json` file if I changed the dependencies (so if `package.json` changed as well).

2021-08-03 09:34 UTC, agagancarczyk commented on package-lock.json
>    "requires": true,
yeah, that makes sense. Thanks

2021-08-03 09:44 UTC, agagancarczyk commented on src/events/EventsSection.tsx
> +  const { getValues, register, reset, setValue } = useForm();
Very good point, I was thinking about using the EventRepresentation here, but it doesn't have everything I need, so I'll create a new type for my form.

2021-08-03 11:59 UTC, agagancarczyk commented on src/events/EventsSection.tsx
> +                          formValues?.dateFrom ? formValues?.dateFrom : ""
I like this shorthand - thanks :)

2021-08-03 13:48 UTC, agagancarczyk commented on src/events/EventsSection.tsx
> +    return await adminClient.realms.findEvents({ realm, ...reducedParams });
awesome - done & ty!

2021-08-03 13:50 UTC, agagancarczyk commented on src/events/EventsSection.tsx
> +                          formValues?.dateTo ? formValues?.dateTo : ""
done - ty!

2021-08-03 13:55 UTC, agagancarczyk commented on src/events/EventsSection.tsx
> +                      <ChipGroup
Clicking 'x' on the individual chip within the event type dropdown (in the search form) is removing that chip from the dropdown.
Clicking on the chip from the search result page hasn't been implemented yet - I'll do it next - is this what you mean @jonkoops ?

2021-08-03 14:16 UTC, agagancarczyk commented on src/events/EventsSection.tsx
> +                        }}
yes, correct! I forgot to refactor this beforehand. Thanks!

2021-08-03 14:51 UTC, agagancarczyk commented on src/events/EventsSection.tsx
> +                        {chipsToDisplay.type.map(
thanks! - changed to string

2021-08-04 13:59 UTC, jenny-s51 requested changes
Nice work @agagancarczyk ! The advanced search component + events filtering works great. 

It would be a good idea to add a cypress test that checks the searching functionality. E.g. log out user, log in, and then search for the new event. Could you add a test that does this?

2021-08-06 16:57 UTC, jonkoops commented on cypress/support/pages/admin_console/manage/events/EventsPage.ts
> +  eventsPageTitle: string = ".pf-c-title";
There is no need to specify a type for these fields as TypeScript can infer the type from the assigned value (in this case a string).
```suggestion
  searchEventDrpDwn = ".pf-c-dropdown__toggle";
  searchEventDrpDwnBtn =
    ".keycloak__user_events_search_selector_dropdown__toggle";
  searchForm = ".pf-c-dropdown__menu";
  userIdInputFld = "userId-searchField";
  eventTypeDrpDwnFld = "event-type-searchField";
  clientInputFld = "client-searchField";
  dateFromInputFld = "dateFrom-searchField";
  dateToInputFld = "dateTo-searchField";
  searchEventsBtn = "search-events-btn";
  eventTypeList = ".pf-c-form-control";
  eventTypeOption = ".pf-c-select__menu-item";
  eventTypeBtn = ".pf-c-button.pf-c-select__toggle-button.pf-m-plain";
  eventsPageTitle = ".pf-c-title";
```

2021-08-06 16:57 UTC, jonkoops commented on package-lock.json
>    "requires": true,
@agagancarczyk Could you remove the package lock from the PR? Since nothing really changed I think it's not needed here.

2021-08-06 16:59 UTC, jonkoops requested changes

2021-08-06 16:59 UTC, jonkoops commented on src/events/EventsSection.tsx
> +                      <ChipGroup
Yes, it is. If that gets addressed later then no prob.

2021-08-06 17:26 UTC, jonkoops commented
@agagancarczyk There are are still some open comments that need to be addressed. Github sometimes hides these if the timeline is a bit too busy, but you should be able to see them after pressing this button:

![image](https://user-images.githubusercontent.com/695720/128549207-ca96cb78-04bf-4ddb-99bd-55f783e9ac11.png)

Let me know when they are processed and I will take another look :+1:

2021-08-11 10:17 UTC, agagancarczyk commented on package-lock.json
>    "requires": true,
package-lock.json file removed.

2021-08-11 10:24 UTC, agagancarczyk commented on src/events/EventsSection.tsx
>        max: max!,
addressed - thanks!

2021-08-11 10:33 UTC, agagancarczyk commented on src/events/EventsSection.tsx
> +  const [search, setSearch] = useState(false);
good spot - thanks, I had it in place before proper chips implementation and you're correct it's no longer needed.

2021-08-11 10:54 UTC, agagancarczyk commented on src/events/EventsSection.tsx
> +    const params: { [key: string]: any } = {
thanks @jonkoops - this seems to be needed for params[key] in 

 const reducedParams = Object.fromEntries(
      Object.entries(params).filter(([key]) => key !== "" && params[key])
    );

Otherwise I'm getting an error "No index signature with a parameter of type 'string' was found on type '{ user: string; type: string[]; client: string; dateFrom: string; dateTo: string; first: number | undefined; max: number | undefined; }'."

2021-08-11 11:02 UTC, agagancarczyk commented on src/events/EventsSection.tsx
> +                      onToggle={onDropdownToggle}
addressed - thanks!

2021-08-11 11:42 UTC, agagancarczyk commented on src/events/EventsSection.tsx
> +  const clearSelection = (e: any) => {
that's great! thanks

2021-08-11 11:42 UTC, agagancarczyk commented on src/events/EventsSection.tsx
> +  const deleteIndividualSelection = (e: any, chip: string) => {
addressed - thanks!

2021-08-11 11:48 UTC, agagancarczyk commented on src/events/EventsSection.tsx
> +        {(selectedEvents || []).map((chip, index) => (
true - thanks!

2021-08-11 11:52 UTC, agagancarczyk commented on src/events/EventsSection.tsx
> +            isReadOnly={index === 0 ? true : false}
true, I should have spent some time refactoring the obvious code bits like this one! thanks

2021-08-11 12:06 UTC, agagancarczyk commented on src/events/EventsSection.tsx
> +                          }
true, awesome, thanks Jon!

2021-08-11 12:14 UTC, agagancarczyk commented on src/events/EventsSection.tsx
> +                        }}
fixed, thanks

2021-08-11 12:14 UTC, agagancarczyk commented on src/events/EventsSection.tsx
> +                          formValues?.client ? formValues?.client : ""
fixed, thanks

2021-08-11 12:14 UTC, agagancarczyk commented on src/events/EventsSection.tsx
> +                        }}
fixed, thanks

2021-08-11 12:17 UTC, agagancarczyk commented
> Nice work @agagancarczyk ! The advanced search component + events filtering works great.
> 
> It would be a good idea to add a cypress test that checks the searching functionality. E.g. log out user, log in, and then search for the new event. Could you add a test that does this?

thanks @jenny-s51 yes, perfect idea! I have the test searching for "LOGIN" event types.

2021-08-11 12:18 UTC, agagancarczyk commented on cypress/support/pages/admin_console/manage/events/EventsPage.ts
> +  eventsPageTitle: string = ".pf-c-title";
done, thanks

2021-08-11 15:01 UTC, agagancarczyk commented on src/events/EventsSection.tsx
> +                            setValue("eventTypes", [...selectedEvents, option]);
thanks @jonkoops , I tried to refactor and use eventTypes instead, but it didn't onSelect was not working as expected. Maybe I'm doing something wrong. Would you give me an example? Thanks!

2021-08-11 15:10 UTC, agagancarczyk commented
> @agagancarczyk There are are still some open comments that need to be addressed. Github sometimes hides these if the timeline is a bit too busy, but you should be able to see them after pressing this button:
> 
> ![image](https://user-images.githubusercontent.com/695720/128549207-ca96cb78-04bf-4ddb-99bd-55f783e9ac11.png)
> 
> Let me know when they are processed and I will take another look 👍

Thanks @jonkoops , Could I ask you for a re-review and some advise on isDirty comment and using typeEvents instead of selectedEvents. Thanks a million!

2021-08-12 09:05 UTC, edewit approved these changes
great work!

2021-08-12 09:10 UTC, agagancarczyk commented on cypress/integration/events_test.spec.ts
> +    // it("Check search by event type works", () => {
thanks @edewit not yet. Would you know how to make isDirty to work onSelect? Thanks

2021-08-12 09:29 UTC, jonkoops commented on cypress/integration/events_test.spec.ts
> +    // it("Check search by event type works", () => {
Strange, you'd expect that any value change in the form would turn `isDirty` to be truthy.

2021-08-12 10:12 UTC, agagancarczyk commented on cypress/integration/events_test.spec.ts
> +    // it("Check search by event type works", () => {
@jonkoops after talking to @edewit I'm going to wrap Select with Controller and see if it's going to work.

2021-08-17 16:04 UTC, jonkoops commented on src/events/EventsSection.tsx
> +                        ))}
This has been fixed.

2021-08-17 16:04 UTC, jonkoops commented on src/events/EventsSection.tsx
> +                        key={`chip-group-${index}`}
Fixed

2021-08-17 16:04 UTC, jonkoops commented on cypress/integration/events_test.spec.ts
> +    // it("Check search by event type works", () => {
This seems to have been resolved.

2021-08-17 16:05 UTC, jonkoops commented on src/events/EventsSection.tsx
> +  const [isDirty, setIsDirty] = useState(false);
This is now working :+1:

2021-08-17 16:05 UTC, jonkoops commented on src/events/EventsSection.tsx
> +                            setValue("eventTypes", [...selectedEvents, option]);
This has been resolved.

2021-08-17 16:09 UTC, jonkoops commented
@xianli123 @yih-wang I'd like to have a UX review on this PR before merging to verify this functionality matches your expectations as well. Could you take a look when you have some time?

2021-08-18 04:21 UTC, xianli123 commented
@agagancarczyk @jonkoops @jenny-s51 Thanks for your great work. I think we can optimize the following parts.

We can put the form next to the dropdown. And the scroll bar always show up to remind users that there are more than 5 options.

><img width="516" alt="Screen Shot 2021-08-18 at 11 54 38 AM" src="https://user-images.githubusercontent.com/53931519/129836376-224c2f88-0226-4c4b-b328-471a67b01bbe.png">


The first option should also have the "X" icon. And the layout is a little weird after selecting some options. Could you please modify it?
> <img width="510" alt="Screen Shot 2021-08-18 at 12 01 53 PM" src="https://user-images.githubusercontent.com/53931519/129836389-e7e00e4a-6110-4e91-9a89-dfe32e570ca1.png">

Thanks.

2021-08-19 11:34 UTC, jonkoops commented
> We can put the form next to the dropdown.

I've pushed a fix for this, looks like spacing was applied to the wrong element.

> And the scroll bar always show up to remind users that there are more than 5 options.

We cannot change this behavior as this is dependent on the operating system of the user, for example on my machine the scroll bars are always visible:

![A screenshot showing visible scroll bars](https://user-images.githubusercontent.com/695720/130058481-c4345ffe-0610-4b06-af3b-208bf723b35b.png)

That said, the scrolling behavior is still incorrect as I am seeing a permanent horizontal scroll bar, even though there is no scrollable content on the horizontal axis. I've pushed a fix that resolves that so now it will look like this:

![A screenshot of the dropdown showing only vertical scroll bars](https://user-images.githubusercontent.com/695720/130058797-14b2c7d8-e9de-48ec-86e3-ce95761bd6e9.png)

> The first option should also have the "X" icon. And the layout is a little weird after selecting some options. Could you please modify it?

Looks like this code was copied from the Patternfly example,  I've gone ahead and removed this behavior.

@xianli123 could you give it another look and let me know if all your feedback has been addressed?

2021-08-19 11:48 UTC, jonkoops commented
@agagancarczyk I've disabled some of the tests that were failing, perhaps we can take a look at them once the work is merged.

2021-08-19 16:00 UTC, jenny-s51 approved these changes
LGTM - nice work @agagancarczyk !

@xianli123 pointed this out  too - I'm seeing an overlap with the "delete all" button and the chip text if the text is particularly long. 

Can we log a separate issue to resolve this? I think a potential solution would be to truncate the text in the chip at a lower width, so it does not overlap with the "delete all" button.

<img width="479" alt="Screen Shot 2021-08-19 at 11 54 53 AM" src="https://user-images.githubusercontent.com/32821331/130102227-0cf7e299-dd64-4e83-91ff-97904e94b11d.png">

Overall looks good to merge though 👍

2021-08-20 03:00 UTC, xianli123 commented
Thanks for your work @jenny-s51  @jonkoops and @agagancarczyk. I agree with Jenny. We can merge the current pr and create a new issue to solve the problem of overlapping buttons as the picture shows. If so, I will think about how to show the selected options in the dropdown field. WDYT?
![image](https://user-images.githubusercontent.com/53931519/130172296-cd47dfd0-c392-45ff-9841-7cc591857e48.png)

2021-08-20 09:11 UTC, jonkoops commented
@jenny-s51 @xianli123 I've reported the issue to the Patternfly team here: https://github.com/patternfly/patternfly-react/issues/6194

2021-08-20 09:13 UTC, jonkoops commented
I'm going ahead and merge this, I'll create a separate PR for implementing the date fields.

2021-08-20 09:13 UTC, merged