Convert more links to use new routes
keycloak/keycloak-admin-ui pull request #933
Opened 2021-08-02 13:31 UTC by jonkoops

2021-08-02 20:22 UTC, jenny-s51 requested changes
Nice work @jonkoops - most of these paths work great! One small issue with the breadcrumb but otherwise LGTM. Thank you for putting up your routing PRs in medium-ish chunks like this -- it's helpful for reviewing :)

2021-08-02 20:22 UTC, jenny-s51 commented on src/realm-settings/RealmSettingsSection.tsx
> +          to={toRealmSettings({ realm, tab: "keys" })}
This should redirect back to `/realm-settings/keys`

2021-08-03 09:25 UTC, jonkoops commented on src/realm-settings/RealmSettingsSection.tsx
> +          to={toRealmSettings({ realm, tab: "keys" })}
Good find! This seems to be a bug in Patternfly, I've created a PR to get it fixed: https://github.com/patternfly/patternfly-react/pull/6111

2021-08-04 09:04 UTC, jonkoops commented on src/realm-settings/RealmSettingsSection.tsx
> +          to={toRealmSettings({ realm, tab: "keys" })}
I've fixed this by using the `render` prop instead.

2021-08-10 13:07 UTC, ssilvert commented
@jenny-s51 We are merging this.  Please let us know if you have any issues.

2021-08-10 13:07 UTC, merged