Realm settings(tokens): Add tokens tab
keycloak/keycloak-admin-ui pull request #934
Opened 2021-08-02 17:25 UTC by jenny-s51

## Motivation

https://issues.redhat.com/browse/APPDUX-1103

## Verification Steps

1. Go to `Realm settings -> tokens`.
2. Populate form fields.
3. Save and verify data is saved accurately. 

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

## Additional Notes

2021-08-04 11:22 UTC, jonkoops requested changes

2021-08-04 11:22 UTC, jonkoops commented on src/realm-settings/RealmSettingsSection.tsx
> +                key={key}
I don't believe a `key` prop is needed here.

2021-08-04 11:22 UTC, jonkoops commented on src/realm-settings/SessionsTab.tsx
> -          title={t(".pf-c-data-list__item-draggable-iconclientSessionSettings")}
Good catch!

2021-08-04 11:22 UTC, jonkoops commented on src/util.ts
> +export const forHumans = (seconds: number) => {
This does not really work for other languages than English, it might be better to use the [Intl.RelativeTimeFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat/RelativeTimeFormat) API here to localize.

2021-08-04 11:22 UTC, jonkoops commented on src/realm-settings/TokensTab.tsx
> +  );
Why would we fetch the realm again if it is already being passed in by the parent component?

2021-08-04 11:22 UTC, jonkoops commented on src/realm-settings/TokensTab.tsx
> +    const attributes = flatten(form.getValues()["attributes"]);
Why do we need to perform this `flatten` operation? Under which circumstances would this be a nested structure?

2021-08-04 14:58 UTC, jenny-s51 commented on src/util.ts
> +export const forHumans = (seconds: number) => {
Thank you for suggesting this API - I tested this function with it but `Intl.RelativeTimeFormat` doesn't like big numbers  (`error: values must be finite`) therefore I localized the strings.

2021-08-04 15:16 UTC, jenny-s51 commented on src/realm-settings/TokensTab.tsx
> +    const attributes = flatten(form.getValues()["attributes"]);
Any attribute of `attributes` that begins with the value `attributes.actionTokenGeneratedByUserLifespan` becomes a nested structure due to React Hook Form. RHF reads these attribute names as objects using dot notation, and therefore nests them.  There are four instances of this; here is an example of how the PUT call looks in the old console when these values are updated.

```
actionTokenGeneratedByUserLifespan.execute-actions: "360"
actionTokenGeneratedByUserLifespan.idp-verify-account-via-email: "300"
actionTokenGeneratedByUserLifespan.reset-credentials: "420"
actionTokenGeneratedByUserLifespan.verify-email: "120"
```
The new console needs to send the above format.

2021-08-05 11:09 UTC, jonkoops commented on src/util.ts
> +export const forHumans = (seconds: number) => {
That is already better, however we cannot rely on the order of things in language unfortunately. So in this case we'd have to interpolate the value into the translation.

2021-08-05 19:57 UTC, jenny-s51 commented on src/util.ts
> +export const forHumans = (seconds: number) => {
Good idea. updated

2021-08-06 17:29 UTC, jonkoops approved these changes

2021-08-09 19:28 UTC, merged