Localization dropdown
keycloak/keycloak-admin-ui pull request #936
Opened 2021-08-03 20:07 UTC by jenny-s51

## Motivation

https://issues.redhat.com/browse/APPDUX-1066

## Brief Description

Adds locale filter to message bundle table as shown in https://marvelapp.com/prototype/56d9606/screen/76458142

## Verification Steps

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

## Additional Notes

2021-08-06 17:49 UTC, jonkoops requested changes

2021-08-06 17:49 UTC, jonkoops commented on src/PageNav.tsx
> +            <NavGroup aria-labelledby="" title="">
Should we not be adding a value here?

2021-08-06 17:49 UTC, jonkoops commented on src/PageNav.tsx
> +            <NavGroup aria-labelledby={t("manage")} title={t("manage")}>
Be aware that `aria-labelledby` references the `id` of an element that contains a descriptive text and should not be confused with `aria-label` which provides a text directly.

So probably what we need to do here is:
```suggestion
            <NavGroup aria-label={t("manage")} title={t("manage")}>
```

2021-08-06 17:49 UTC, jonkoops commented on src/PageNav.tsx
> +            <NavGroup aria-labelledby={t("configure")} title={t("configure")}>
```suggestion
            <NavGroup aria-label={t("configure")} title={t("configure")}>
```

2021-08-06 17:49 UTC, jonkoops commented on src/realm-settings/LocalizationTab.tsx
>        return Object.keys(result).map((key) => [key, result[key]]);
Not entirely sure, but we might be able to replace this with `Object.entries()`.
```suggestion
      return Object.entries(result);
```

2021-08-06 17:49 UTC, jonkoops commented on src/realm-settings/LocalizationTab.tsx
> +      return Object.keys(result).map((key) => [key, result[key]]);
Not entirely sure, but we might be able to replace this with `Object.entries()`.
```suggestion
      return Object.entries(result);
```

2021-08-06 17:49 UTC, jonkoops commented on src/realm-settings/LocalizationTab.tsx
> +          <SelectOption key={`supported-locale-${idx}`} value={locale}>
Is `locale` not already unique in this context? React [recommends](https://reactjs.org/docs/lists-and-keys.html#keys) using the `index` as a key only as a last resort.
```suggestion
          <SelectOption key={locale} value={locale}>
```

2021-08-06 17:49 UTC, jonkoops commented on src/realm-settings/LocalizationTab.tsx
> +        .map((locale: string, idx: number) => (
These types are already known, so there is no need to specify them.
```suggestion
        .map((locale, idx) => (
```

2021-08-06 17:49 UTC, jonkoops commented on src/realm-settings/LocalizationTab.tsx
> +        .map((locale: string, idx: number) => (
These types are already known, so there is no need to specify them.
```suggestion
        .map((locale, idx) => (
```

2021-08-06 17:49 UTC, jonkoops commented on src/realm-settings/LocalizationTab.tsx
> +          <SelectOption key={`supported-locale-${idx}`} value={locale}>
Is `locale` not already unique in this context? React [recommends](https://reactjs.org/docs/lists-and-keys.html#keys) using the `index` as a key only as a last resort.
```suggestion
          <SelectOption key={locale} value={locale}>
```

2021-08-06 18:50 UTC, jenny-s51 commented on src/PageNav.tsx
> +            <NavGroup aria-labelledby="" title="">
I'm not sure we need this `<NavGroup>` here at all - it doesn't render anything in the left nav. Do you think we can just put a divider component here instead?

2021-08-06 19:37 UTC, jenny-s51 commented on src/realm-settings/LocalizationTab.tsx
> +      return Object.keys(result).map((key) => [key, result[key]]);
Thank you for the suggestion! Looks like the `loader` prop on `KeycloakDataTable` doesn't like this return type

2021-08-06 19:37 UTC, jenny-s51 commented on src/realm-settings/LocalizationTab.tsx
>        return Object.keys(result).map((key) => [key, result[key]]);
Thank you for the suggestion! Looks like the loader prop on KeycloakDataTable doesn't like this return type

2021-08-06 19:39 UTC, jenny-s51 commented on src/PageNav.tsx
> +            <NavGroup aria-labelledby={t("manage")} title={t("manage")}>
Good suggestion! thank you for clarifying

2021-08-09 08:21 UTC, edewit requested changes
had one strange error when testing this the dropdown on the table got disabled after a reload:
![image](https://user-images.githubusercontent.com/51133/128677700-e7389c55-66cb-4e41-bdf4-1f0c4c6b7399.png)

2021-08-09 08:21 UTC, edewit commented on src/components/table-toolbar/KeycloakDataTable.tsx
> +  keepToolbar?: boolean;
no need to add this we already have a property to do this called `isSearching`, guess we could rename it instead.

2021-08-16 15:45 UTC, jenny-s51 commented on src/components/table-toolbar/KeycloakDataTable.tsx
> +  keepToolbar?: boolean;
thank you - now using the prop `isSearching` on the data table within the localization tab

2021-08-16 17:26 UTC, jenny-s51 commented
@edewit According to this mock, the actions menu should be disabled until Localization configs are saved: https://marvelapp.com/prototype/56d9606/screen/76458134

2021-08-17 06:45 UTC, edewit approved these changes

2021-08-17 09:09 UTC, jonkoops commented on src/realm-settings/LocalizationTab.tsx
> +      return Object.keys(result).map((key) => [key, result[key]]);
This is because the return type is mixed, the `catch` clause returns an empty array which is not assignable to `[string, string]`.

2021-08-17 09:13 UTC, jonkoops approved these changes

2021-08-17 12:50 UTC, merged