Add UI and partial functionality for creating SAML identity providers
keycloak/keycloak-admin-ui pull request #944
Opened 2021-08-05 22:15 UTC by mfrances17

## Motivation
https://issues.redhat.com/browse/APPDUX-1027

## Brief Description
Adds most UI elements for creating/editing a SAML v2.0 identity provider, and preliminary CRUD functionality for a basic SAML provider. Note that not all functionality is working - some fields aren't wired, etc. This is the first of several PRs to come in order avoid one huge PR.

## Verification Steps
Although the intention of this PR is to get most of the UI elements, strings, help, etc into the code, you should be able to successfully create/edit/delete a SAML provider using these steps:
1. Select **Identity Providers** and click the **SAML v2.0** card (if no other identity providers exist), or if other providers exist, click **Add provider** and select **SAML v2.0**. 
2. Set the **Use entity descriptor** to **Off**.
3. Enter a secure URL in the **Single Sign-On service URL**, e.g. "**https://localhost.8180/auth/realms/sso**".
4. Click **Add**. 

Once created, you should be able to view expanded settings, use the jump links, etc. All help strings should be valid, and you should be able to edit some fields and Save (not all are working). You should also be able to Delete.  

## Checklist:
- [x] Code has been tested locally by PR requester
- [x] User-visible strings are using the react-i18next framework (useTranslation)
- [x] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [x] Cypress tests have been created/updated

## Additional Notes
None

2021-08-09 07:20 UTC, edewit submitted a review, later dismissed

2021-08-09 07:20 UTC, edewit commented on src/identity-providers/add/SamlConnectSettings.tsx
> +            ref={register({ required: true })}
```suggestion
            ref={register({ required: true })}
            validated={
              errors.samlEntityDescriptor ? ValidatedOptions.error : ValidatedOptions.default
            }
```

2021-08-09 07:20 UTC, edewit commented on src/identity-providers/add/SamlConnectSettings.tsx
> +          isRequired
This will make the field red with a hint when the user doesn't fill it
```suggestion
          isRequired
          helperTextInvalid={t("common:required")}
          validated={
            errors.samlEntityDescriptor ? ValidatedOptions.error : ValidatedOptions.default
          }
```

2021-08-09 07:20 UTC, edewit commented on src/identity-providers/add/SamlConnectSettings.tsx
> +  };
This part seems copied and the discovering part is not used. It would be better to extract it into a common file

2021-08-09 07:20 UTC, edewit commented on src/identity-providers/routes/IdentityProviderSaml.ts
> +  breadcrumb: (t) => t("identity-providers:addSamlProvider"),
for edit it seems that it's is still add:
![image](https://user-images.githubusercontent.com/51133/128671626-5736a53d-5b95-4172-930c-fb5c68c60689.png)
In this case the breadcrumb should be different I think.

2021-08-10 10:12 UTC, jonkoops requested changes

2021-08-12 14:36 UTC, mfrances17 commented on src/identity-providers/add/DescriptorSettings.tsx
> +            forLabel={t("Single Sign-On service URL")}
fixed, ty... missed some hardcoded strings

2021-08-12 14:57 UTC, mfrances17 commented on src/identity-providers/add/SamlConnectSettings.tsx
> +  };
@edewit i did it mainly as a placeholder, since i'm pretty sure that i will still need this in some form eventually, because SAML config can be imported much like OIDC. since this is just the first of a few PRs for SAML in order to keep the PRs from getting too large, i'm hoping we can keep it for now. if i do wind up using it, i will probably separate it out for reuse and avoid the repetition.

2021-08-12 18:20 UTC, mfrances17 commented on src/identity-providers/routes/IdentityProviderSaml.ts
> +  breadcrumb: (t) => t("identity-providers:addSamlProvider"),
definitely... i spent about a half day trying to figure out how to do this with the new routing, i could not get it to work. i'm going to log this as an issue that i can hopefully fix in the next iteration. fyi this is how it works for the other providers as well.

2021-08-12 18:26 UTC, mfrances17 commented on src/identity-providers/SamlConfigurationRepresentation.ts
> +export interface SamlConfigurationRepresentation {
ty, forgot to delete. was more appropriate to use the existing IdentifyProviderRepresentation type instead

2021-08-12 18:37 UTC, mfrances17 commented on src/identity-providers/add/AddSamlConnect.tsx
> +      history.push(`/${realm}/identity-providers/${id}/settings`);
i'm having issues getting the to method to work as expected, as well as the routing working correctly. i think there is something fundamentally wrong with the identity provider URIs, we need to add an ID in there

2021-08-12 18:42 UTC, mfrances17 commented on src/identity-providers/add/DetailSettings.tsx
> +  const isSAML = id.indexOf("saml") !== -1;
old habits die hard

2021-08-12 18:42 UTC, mfrances17 commented on src/identity-providers/add/AdvancedSettings.tsx
> +        </>
fixed ty

2021-08-12 18:43 UTC, mfrances17 commented on src/identity-providers/add/DetailSettings.tsx
> +                  </>
done ty

2021-08-12 19:01 UTC, mfrances17 commented on src/identity-providers/add/SamlConnectSettings.tsx
> +};
i'm not sure this is correct. the purpose is to add 'error' to the IdentityProviderRepresentation type. without it, it would not recognize error.

2021-08-17 09:39 UTC, jonkoops commented on src/identity-providers/add/AddSamlConnect.tsx
> +      history.push(`/${realm}/identity-providers/${id}/settings`);
`toIdentityProviderTab` seems to have fixed this, fixed this in 869f8dd13deac6a9badebe59081dd9712d007c75

2021-08-17 10:03 UTC, jonkoops commented on src/identity-providers/add/DetailSettings.tsx
> +  const isSAML = id.indexOf("saml") !== -1;
Created an ESLint rule to enforce this https://github.com/keycloak/keycloak-admin-ui/pull/1013

2021-08-17 12:11 UTC, jonkoops requested changes

2021-08-17 13:26 UTC, jonkoops requested changes

2021-08-17 13:26 UTC, jonkoops commented on src/identity-providers/add/DescriptorSettings.tsx
> +  const { register, control, errors } = useFormContext();
A generic type should be specified here to make the returned value type-safe.
```suggestion
  const { register, control, errors } = useFormContext<MyFormFields>();
```

2021-08-17 13:26 UTC, jonkoops commented on src/identity-providers/add/DescriptorSettings.tsx
> +              }
There is no need to manage this state ourselves as the callback provides an argument for it.
```suggestion
              onToggle={(isExpanded) => setNamedPolicyDropdownOpen(isExpanded)}
```

2021-08-17 13:26 UTC, jonkoops commented on src/identity-providers/add/DescriptorSettings.tsx
> +                onChange(value as string);
There is no need to cast this type as `SelectOptionObject` implements `toString()`.
```suggestion
                onChange(value.toString());
```

2021-08-17 13:26 UTC, jonkoops commented on src/identity-providers/add/DescriptorSettings.tsx
> +              />
I don't think it's needed to give these `SelectOption` a `key` prop, as they are statically populated.
```suggestion
              <SelectOption
                data-testid="persistent-option"
                value={t("persistent")}
                isPlaceholder
              />
              <SelectOption
                data-testid="transient-option"
                value={t("transient")}
              />
              <SelectOption
                data-testid="email-option"
                value={t("email")}
              />
              <SelectOption
                data-testid="kerberos-option"
                value={t("kerberos")}
              />
              <SelectOption
                data-testid="x509-option"
                value={t("x509")}
              />
              <SelectOption
                data-testid="windowsDomainQN-option"
                value={t("windowsDomainQN")}
              />
              <SelectOption
                data-testid="unspecified-option"
                value={t("unspecified")}
              />
```

2021-08-17 13:26 UTC, jonkoops commented on src/identity-providers/add/DescriptorSettings.tsx
> +              onToggle={() =>
There is no need to manage this state ourselves as the callback provides an argument for it.
```suggestion
              onToggle={(isExpanded) =>
                setPrincipalTypeDropdownOpen(isExpanded)
              }
```

2021-08-17 13:26 UTC, jonkoops commented on src/identity-providers/add/DescriptorSettings.tsx
> +                onChange(value as string);
There is no need to cast this type as `SelectOptionObject` implements `toString()`.
```suggestion
                onChange(value.toString());
```

2021-08-17 13:26 UTC, jonkoops commented on src/identity-providers/add/DescriptorSettings.tsx
> +              />
I don't think it's needed to give these `SelectOption` a `key` prop, as they are statically populated.
```suggestion
              <SelectOption
                data-testid="subjectNameId-option"
                value={t("subjectNameId")}
                isPlaceholder
              />
              <SelectOption
                data-testid="attributeName-option"
                value={t("attributeName")}
              />
              <SelectOption
                data-testid="attributeFriendlyName-option"
                value={t("attributeFriendlyName")}
              />
```

2021-08-17 13:26 UTC, jonkoops commented on src/identity-providers/add/DescriptorSettings.tsx
> +      {wantAuthnSigned === "true" && (
If the aforementioned changes are implemented to make this a boolean there is no need to compare this value to a string anymore.

```suggestion
      {wantAuthnSigned && (
```

2021-08-17 13:26 UTC, jonkoops commented on src/identity-providers/add/DescriptorSettings.tsx
> +                  }
There is no need to manage this state ourselves as the callback provides an argument for it.

```suggestion
                  onToggle={(isExpanded) =>
                    setSignatureAlgorithmDropdownOpen(isExpanded)
                  }
```

2021-08-17 13:26 UTC, jonkoops commented on src/identity-providers/add/DescriptorSettings.tsx
> +                    onChange(value as string);
There is no need to cast this type as `SelectOptionObject` implements `toString()`.
```suggestion
                    onChange(value.toString());
```

2021-08-17 13:26 UTC, jonkoops commented on src/identity-providers/add/DescriptorSettings.tsx
> +                  <SelectOption key={5} value="DSA_SHA1" />
I don't think it's needed to give these `SelectOption` a `key` prop, as they are statically populated.
```suggestion
                  <SelectOption value="RSA_SHA1" />
                  <SelectOption value="RSA_SHA256" isPlaceholder />
                  <SelectOption value="RSA_SHA256_MGF1" />
                  <SelectOption value="RSA_SHA512" />
                  <SelectOption value="RSA_SHA512_MGF1" />
                  <SelectOption value="DSA_SHA1" />
```

2021-08-17 13:26 UTC, jonkoops commented on src/identity-providers/add/DescriptorSettings.tsx
> +                    onChange(value as string);
There is no need to cast this type as `SelectOptionObject` implements `toString()`.
```suggestion
                    onChange(value.toString());
```

2021-08-17 13:26 UTC, jonkoops commented on src/identity-providers/add/DescriptorSettings.tsx
> +                  }
There is no need to manage this state ourselves as the callback provides an argument for it.
```suggestion
                  onToggle={(isExpanded) =>
                    setSamlSignatureKeyNameDropdownOpen(isExpanded)
                  }
```

2021-08-17 13:26 UTC, jonkoops commented on src/identity-providers/add/DescriptorSettings.tsx
> +                  <SelectOption key={2} value={t("certSubject")} />
I don't think it's needed to give these `SelectOption` a `key` prop, as they are statically populated.

```suggestion
                  <SelectOption value="NONE" />
                  <SelectOption value={t("keyID")} isPlaceholder />
                  <SelectOption value={t("certSubject")} />
```

2021-08-17 13:26 UTC, jonkoops commented on src/identity-providers/add/DescriptorSettings.tsx
> +      {validateSignature === "true" && (
If the aforementioned changes are implemented to make this a boolean there is no need to compare this value to a string anymore.

```suggestion
      {validateSignature && (
```

2021-08-17 13:26 UTC, jonkoops commented on src/identity-providers/add/DescriptorSettings.tsx
> +        </>
There is no need to use a fragment here as there is only one root element.
```suggestion
        <TextField
          field="config.signingCertificate"
          label="validatingX509Certs"
          isReadOnly={readOnly}
        />
```

2021-08-17 13:26 UTC, jonkoops commented on src/identity-providers/add/DescriptorSettings.tsx
> +          onToggle={() => setIsExpanded(!isExpanded)}
```suggestion
          onToggle={(isOpen) => setIsExpanded(isOpen)}
```

2021-08-17 13:26 UTC, jonkoops commented on src/identity-providers/add/DescriptorSettings.tsx
> +  );
This could be a ternary expression, which also eliminates the need to use a fragment here.
```suggestion
  return readOnly ? (
    <ExpandableSection
      className="keycloak__discovery-settings__metadata"
      toggleText={isExpanded ? t("hideMetaData") : t("showMetaData")}
      onToggle={() => setIsExpanded(!isExpanded)}
      isExpanded={isExpanded}
    >
      <Fields readOnly={readOnly} />
    </ExpandableSection>
  ) : (
    <Fields readOnly={readOnly} />
  );
```

2021-08-17 17:51 UTC, mfrances17 commented on src/identity-providers/routes/IdentityProviderSaml.ts
> +  breadcrumb: (t) => t("identity-providers:addSamlProvider"),
Filed separate issue to handle the breadcrumbs of both identity providers:
https://github.com/keycloak/keycloak-admin-ui/issues/1016

2021-08-17 18:01 UTC, mfrances17 commented on src/identity-providers/add/SamlConnectSettings.tsx
> +};
this results in errors, as mentioned in the last comment

2021-08-17 20:36 UTC, mfrances17 commented on src/identity-providers/add/DescriptorSettings.tsx
> +      {validateSignature === "true" && (
I'm not changing these because they are stored as text in the API and changing them to booleans ruins the show/hide on load.

2021-08-17 20:59 UTC, mfrances17 commented
@edewit @jonkoops made most of the edits... filed separate issues when noted. some of the suggestions were not made, e.g. changing the switches to booleans, as they broke the UI (they are stored as strings in the API).

2021-08-18 12:38 UTC, mfrances17 commented on src/identity-providers/add/ReqAuthnConstraintsSettings.tsx
> +              selections={t(value)}
dunno... typo? removed

2021-08-18 12:38 UTC, mfrances17 commented on src/identity-providers/add/SamlConnectSettings.tsx
> +  const setupForm = (result: any) => {
done

2021-08-18 12:39 UTC, mfrances17 commented on src/identity-providers/add/SamlConnectSettings.tsx
> +    }
good suggestion, fixed

2021-08-18 12:39 UTC, mfrances17 commented on src/identity-providers/add/AddSamlConnect.tsx
> +    delete provider.discoveryEndpoint;
not needed, removed

2021-08-18 12:40 UTC, mfrances17 commented on src/identity-providers/add/DescriptorSettings.tsx
> +  const wantAuthnSigned = useWatch({
this resulted in errors with useWatch so i am keeping it as is

2021-08-18 12:41 UTC, mfrances17 commented on src/identity-providers/add/DescriptorSettings.tsx
> +      />
I'm not changing these because they are stored as text on the backend and changing them to booleans ruins the show/hide on load.

2021-08-18 12:42 UTC, mfrances17 commented on src/identity-providers/add/DescriptorSettings.tsx
> +                onChange(value as string);
yep, changed, ty

2021-08-18 12:42 UTC, mfrances17 commented on src/identity-providers/add/DescriptorSettings.tsx
> +      />
I'm not changing these because they are stored as text on the backend and changing them to booleans ruins the show/hide on load.

2021-08-18 12:42 UTC, mfrances17 commented on src/identity-providers/add/DescriptorSettings.tsx
> +      />
I'm not changing these because they are stored as text on the backend and changing them to booleans ruins the show/hide on load.

2021-08-18 12:43 UTC, mfrances17 commented on src/identity-providers/add/DescriptorSettings.tsx
> +              />
interesting, i thought it would throw a missing key prop without these, but it doesn't. i removed them, ty.

2021-08-18 12:43 UTC, mfrances17 commented on src/identity-providers/add/DescriptorSettings.tsx
> +          onToggle={() => setIsExpanded(!isExpanded)}
good suggestion, fixed

2021-08-18 12:44 UTC, mfrances17 commented on src/identity-providers/add/DescriptorSettings.tsx
> +        </>
you are correct, removed

2021-08-18 12:44 UTC, mfrances17 commented on src/identity-providers/add/DescriptorSettings.tsx
> +                  <SelectOption key={2} value={t("certSubject")} />
removed

2021-08-18 12:45 UTC, mfrances17 commented on src/identity-providers/add/DescriptorSettings.tsx
> +  const { register, control, errors } = useFormContext();
this did not work as expected, leaving as is for this iteration

2021-08-19 11:52 UTC, jonkoops commented
@mfrances17 There are some conflicts with `master`, could you resolve those?

2021-08-19 11:55 UTC, jonkoops requested changes
There are some review comments that have not been addressed yet, probably because Github hides reviews partially if there are too many. They can be found by clicking the following link:

![A link to show more of the thread](https://user-images.githubusercontent.com/695720/130064303-c10c4425-5964-414b-ac00-9995a800820a.png)

2021-08-19 13:29 UTC, jonkoops approved these changes

2021-08-19 13:55 UTC, mfrances17 commented on src/identity-providers/add/DescriptorSettings.tsx
> +                  }
fixed, ty

2021-08-19 13:56 UTC, mfrances17 commented on src/identity-providers/add/DescriptorSettings.tsx
> +                    onChange(value as string);
yep, this was fixed last iteration, ty

2021-08-19 13:56 UTC, mfrances17 commented on src/identity-providers/add/DescriptorSettings.tsx
> +                  <SelectOption key={5} value="DSA_SHA1" />
yep, this was fixed last iteration, ty

2021-08-19 13:57 UTC, mfrances17 commented on src/identity-providers/add/DescriptorSettings.tsx
> +                    onChange(value as string);
yep, all these were fixed last iteration, good catches

2021-08-19 13:58 UTC, mfrances17 commented on src/identity-providers/add/DescriptorSettings.tsx
> +                  }
fixed 👍

2021-08-19 13:58 UTC, mfrances17 commented on src/identity-providers/add/DescriptorSettings.tsx
> +      {wantAuthnSigned === "true" && (
did not implement as boolean because it is stored as string on backend

2021-08-19 13:59 UTC, mfrances17 commented on src/identity-providers/add/DescriptorSettings.tsx
> +              />
yep, all keys were removed last iteration, ty

2021-08-19 14:05 UTC, mfrances17 commented on src/identity-providers/add/DescriptorSettings.tsx
> +    control: control,
good suggestions: fixed

2021-08-19 14:05 UTC, mfrances17 commented on src/identity-providers/add/DescriptorSettings.tsx
> +    control: control,
good suggestions: fixed

2021-08-19 14:11 UTC, mfrances17 commented on src/identity-providers/add/SamlConnectSettings.tsx
> +  const fileUpload = async (obj: object) => {
Added an issue for this so it's not lost: https://github.com/keycloak/keycloak-admin-ui/issues/1024

2021-08-19 14:14 UTC, mfrances17 commented on src/identity-providers/add/SamlConnectSettings.tsx
> +  useEffect(() => {
Filed this as a separate issue so it doesn't get lost:
https://github.com/keycloak/keycloak-admin-ui/issues/1025

2021-08-19 14:41 UTC, merged