add priority attribute when dragging data list elements
keycloak/keycloak-admin-ui pull request #947
Opened 2021-08-06 18:36 UTC by jenny-s51

## Motivation

Closes #603 
## Brief Description

## Verification Steps

1. Go to Realm Settings -> Keys -> Providers list
2. Click and drag a provider to a new location
3. Inspect the network call and verify that the priority is changed based on the location in the providers list

## Checklist:

- [ ] Code has been tested locally by PR requester
- [ ] User-visible strings are using the react-i18next framework (useTranslation)
- [ ] Help has been implemented
- [ ] axe report has been run and resulting a11y issues have been resolved
- [ ] Unit tests have been created/updated

## Additional Notes

2021-08-06 22:17 UTC, jonkoops requested changes

2021-08-06 22:17 UTC, jonkoops commented on src/realm-settings/KeysProvidersTab.tsx
> +  const itemIds = components.map((component) => component.id);
This is probably one of those cases where a model from Keycloak is missing type information about whether the field is actually optional. You might be able to use a non-null assertion here to get rid of the undefined values.
```suggestion
  const itemIds = components.map((component) => component.id!);
```

2021-08-06 22:17 UTC, jonkoops commented on src/realm-settings/KeysProvidersTab.tsx
> +  const [itemOrder, setItemOrder] = useState<(string | undefined)[]>([]);
And thus
```suggestion
  const [itemOrder, setItemOrder] = useState<string[]>([]);
```

2021-08-06 22:17 UTC, jonkoops commented on src/realm-settings/KeysProvidersTab.tsx
> +    setItemOrder([...itemIds]);
If the value is already an array there should be no need to spread it.
```suggestion
    setItemOrder(itemIds);
```

2021-08-06 22:17 UTC, jonkoops commented on src/realm-settings/KeysProvidersTab.tsx
> +    setItemOrder([...itemOrder]);
Same here, I don't think this needs to be spread.
```suggestion
    setItemOrder(itemOrder);
```

2021-08-06 22:17 UTC, jonkoops commented on src/realm-settings/KeysProvidersTab.tsx
> +          providerType: "org.keycloak.keys.KeyProvider",
I am seeing this string a lot in the project, perhaps it's time to put in a constant in a shared file?

2021-08-06 22:17 UTC, jonkoops commented on src/realm-settings/KeysProvidersTab.tsx
> +          itemOrder={itemOrder as string[]}
If the aforementioned changes are applied this can be removed.
```suggestion
          itemOrder={itemOrder}
```

2021-08-18 21:17 UTC, mfrances17 requested changes
Code looks good with jon's suggestions. Drag and dropped worked well. 

Functionality does not seem to be working, though. When I drag and drop the keys in a different order in the Providers tab, it should change the order of keys by Provider in the Active keys list, but it doesn't. 

In the old console, I can go to Keys > Providers and assign different values to the priority, and when I go to the Active tab, the Algorithms are listed in order from high to low priority.

2021-08-19 15:16 UTC, jenny-s51 commented
@mfrances17 nice catch - updated based @edewit's suggestion to change all the element's priorities so they are sorted correctly

2021-08-19 16:07 UTC, edewit approved these changes
:+1: looks good

2021-08-19 16:07 UTC, edewit commented on src/realm-settings/KeysProvidersTab.tsx
> +      const componentToSave = { ...component };
this isn't necessary componentToSave === component

2021-08-19 16:07 UTC, edewit commented on src/realm-settings/KeysProvidersTab.tsx
> +      Promise.all(updateAll);
```suggestion
      await Promise.all(updateAll);
```

2021-08-19 16:07 UTC, edewit commented on src/realm-settings/KeysProvidersTab.tsx
> +      Promise.all(updateAll);
Don't we need a success message?

2021-08-19 16:08 UTC, jonkoops commented on src/realm-settings/KeysProvidersTab.tsx
> +      const componentToSave = { ...component };
I think this is to prevent `providerDescription` from getting changed in memory.

2021-08-19 16:48 UTC, jonkoops requested changes

2021-08-19 16:48 UTC, jonkoops commented on src/util.ts
> +export const KeyProviderType = "org.keycloak.keys.KeyProvider";
I think it's preferred to have our constants as screaming snake case (no joke this is what is called apparently). Otherwise it might be confused with a class or enum.
```suggestion
export const KEY_PROVIDER_TYPE = "org.keycloak.keys.KeyProvider";
```

2021-08-19 16:48 UTC, jonkoops commented on src/util.ts
> -    console.log(newKey);
Nice catch!

2021-08-19 16:48 UTC, jonkoops commented on src/realm-settings/RealmSettingsSection.tsx
> +  const sortByPriority = (components: ComponentRepresentation[]) => {
Looks like this function has no direct dependencies inside of the component, so it can be placed outside of it.

2021-08-19 16:48 UTC, jonkoops commented on src/realm-settings/RealmSettingsSection.tsx
> +    const sortedComponents = components?.sort(
According to the function signature the `components` argument is always defined, so there should be no need to use optional chaining here.
```suggestion
    const sortedComponents = components.sort(
```

2021-08-19 16:48 UTC, jonkoops commented on src/realm-settings/RealmSettingsSection.tsx
> +    const sortedComponents = components?.sort(
Be aware that `.sort()` uses an [in-place](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) algorithm, this means that the original array will be changes as well. You might want to create a new array before operating on it.

For example:
```suggestion
    const sortedComponents = [...components].sort(
```

Or
```suggestion
    const sortedComponents = Array.from(components).sort(
```

2021-08-19 16:48 UTC, jonkoops commented on src/realm-settings/RealmSettingsSection.tsx
> +      (a, b) => Number(b.config?.priority) - Number(a?.config?.priority || 0)
According to the type definition `priority` here can also be a `string[]`. In this case, or when passing in `undefined` into a `Number()` constructor this will result in a value of [`NaN`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN) (not a number).

Since it's not possible to do arithmetic on `NaN`, this code might be causing issues.

2021-08-19 16:48 UTC, jonkoops commented on src/realm-settings/RealmSettingsSection.tsx
> +  const kpComponentTypes = useServerInfo().componentTypes![KeyProviderType];
It might be better to use optional chaining with a default value here.
```suggestion
  const kpComponentTypes = useServerInfo().componentTypes?.[KeyProviderType] ?? [];
```

2021-08-19 16:48 UTC, jonkoops commented on src/realm-settings/JavaKeystoreModal.tsx
> +        config: { priority: ["0"] },
This line wasn't here before, is that intentional?

2021-08-19 16:48 UTC, jonkoops commented on src/realm-settings/KeysProvidersTab.tsx
> +  );
It might be better to use optional chaining with a default here in case the value is not set.
```suggestion
  const providerTypes = (
    serverInfo.componentTypes?.[KeyProviderType] ?? []
  ).map((item) => item.id);
```

2021-08-19 16:48 UTC, jonkoops commented on src/realm-settings/KeysProvidersTab.tsx
>    }, [components, searchVal]);
Be aware that `components` does not seem to be a stable value (by reference equality) between renders, meaning this effect might be triggered every time the parent component renders.

2021-08-19 16:48 UTC, jonkoops commented on src/realm-settings/KeysProvidersTab.tsx
> +  const itemIds = components.map((component) => component.id!);
Looks like `itemIds` is only used to in an effect to set `itemOrder`. Perhaps it can be included in that effect only so this code is not executed unnecessarily?

2021-08-19 16:48 UTC, jonkoops commented on src/realm-settings/KeysProvidersTab.tsx
> +      componentToSave.providerDescription = undefined;
An alternative approach for this could be:
```suggestion
      const componentToSave = { ...component, providerDescription: undefined };
```
Or
```suggestion
      const componentToSave = { ...component };
      delete componentToSave.providerDescription;
```

2021-08-19 16:48 UTC, jonkoops commented on src/realm-settings/KeysProvidersTab.tsx
> +          providerId: component?.providerId,
Are these fields not already provided by spreading `componentToSave`?

2021-08-19 16:48 UTC, jonkoops commented on src/realm-settings/KeysProvidersTab.tsx
> +                itemOrder.indexOf(component.id || "") +
I think this is one of those cases where `id` is always present but the types are not correct. You can use a non-null assertion here to fix that.
```suggestion
                itemOrder.indexOf(component.id!) +
```

2021-08-19 16:48 UTC, jonkoops commented on src/realm-settings/KeysProvidersTab.tsx
> +          ).map((component: ComponentData, idx: number) => (
The types can be inferred here from the value of the array we're mapping on, so the type annotations can be omitted.
```suggestion
          ).map((component, idx) => (
```

2021-08-19 16:48 UTC, jonkoops commented on src/realm-settings/KeysProvidersTab.tsx
>                <DataListItemRow key={idx} data-testid={"data-list-row"}>
The `key` prop here is not needed as these elements are static.
```suggestion
              <DataListItemRow data-testid={"data-list-row"}>
```

2021-08-19 16:48 UTC, jonkoops commented on src/realm-settings/KeysProvidersTab.tsx
> +                      aria-describedby="Press space or enter to begin dragging, and use the arrow keys to navigate up or down. Press enter to confirm the drag, or any other key to cancel the drag ope
Some of these ARIA attributes will need to be translated. It is also not needed to add an `aria-labelledby` attribute if an `aria-label` is already provided.

2021-08-19 16:48 UTC, jonkoops commented on src/realm-settings/RSAGeneratedModal.tsx
> +        config: { priority: ["0"] },
This line was not there before, is that intentional?

2021-08-19 16:48 UTC, jonkoops commented on src/realm-settings/RSAModal.tsx
> +          config: { priority: ["0"] },
This line was not there before, is that intentional?

2021-08-19 17:45 UTC, jenny-s51 commented on src/realm-settings/JavaKeystoreModal.tsx
> +        config: { priority: ["0"] },
Yes, the old console sets the default priority for every new provider to 0

2021-08-19 17:59 UTC, jenny-s51 commented on src/realm-settings/RealmSettingsSection.tsx
> +      (a, b) => Number(b.config?.priority) - Number(a?.config?.priority || 0)
Interesting - in the old console it's impossible to save a provider unless the priority field is set to be strictly an integer, therefore I didn't think `Number()` would cause any problems.

In the new console I updated the code to always set the default priority to `"0"` as it does in the old console. Could there still be instances when it is `undefined` or `string[]`?

2021-08-19 18:05 UTC, jenny-s51 commented on src/util.ts
> +export const KeyProviderType = "org.keycloak.keys.KeyProvider";
Great suggestion - also TIL 🐍

2021-08-19 18:08 UTC, jenny-s51 commented on src/realm-settings/KeysProvidersTab.tsx
> +      Promise.all(updateAll);
@edewit updated to include a success message

2021-08-19 18:24 UTC, jenny-s51 commented on src/realm-settings/KeysProvidersTab.tsx
> +  const itemIds = components.map((component) => component.id!);
good idea

2021-08-19 19:14 UTC, jenny-s51 commented on src/realm-settings/RSAModal.tsx
> +          config: { priority: ["0"] },
Yes, the old console sets the default priority for every new provider to 0

2021-08-19 19:14 UTC, jenny-s51 commented on src/realm-settings/RSAGeneratedModal.tsx
> +        config: { priority: ["0"] },
Yes, the old console sets the default priority for every new provider to 0

2021-08-19 20:07 UTC, jenny-s51 reviewed
@jonkoops thank you for your thorough review! Your feedback and suggestions are always helpful and much appreciated

2021-08-20 10:01 UTC, jonkoops requested changes
PR is looking good @jenny-s51, I think with this last change we can get it merged.

2021-08-20 10:01 UTC, jonkoops commented on src/realm-settings/RealmSettingsSection.tsx
> +  );
I think we can catch all the edge cases here by casting the values to a `number` first and then checking if those values are `NaN` (defaulting to 0 if they are). Since both `Number([])` and `Number(undefined)` will produce `NaN` only 'good' values will pass through here.

I think the type is actually wrong and this value specifically would always be of type `string`, but it's probably good to cover possible edge cases if we are not entirely sure.
```suggestion
  const sortedComponents = [...components].sort((a, b) => {
    const priorityA = Number(a.config?.priority);
    const priorityB = Number(b.config?.priority);

    return (
      (!isNaN(priorityB) ? priorityB : 0) - (!isNaN(priorityA) ? priorityA : 0)
    );
  });
```

2021-08-20 13:29 UTC, jenny-s51 commented on src/realm-settings/RealmSettingsSection.tsx
> +  );
defaulting to 0 here is a good idea - thank you @jonkoops

2021-08-20 14:26 UTC, jonkoops approved these changes
LGTM!

2021-08-20 16:13 UTC, mfrances17 approved these changes
LGTM, nice work. The ordering now works as expected. One thing I will mention, is that when you switch tabs to the Key list, the new ordering is not reflected unless you manually refresh. That may or may not be a problem we want to address at some point.

2021-08-20 16:15 UTC, merged