Empty state for a list
keycloak/keycloak-admin-ui pull request #95
Opened 2020-09-16 15:01 UTC by srambach

This adds an opinionated empty state to be used for a list. Based on mockup https://marvelapp.com/prototype/504f2fh/screen/72066304

Can be viewed in the storybook.

Fixes #35

2020-09-16 18:39 UTC, jenny-s51 reviewed
Code, styling, and storybook demo are looking good! I tested this in the groups section and was able to integrate the new component and customize the prop inputs without any issues. My only quibble here is the suggestion to rename the component to `EmptyListState` so it's a bit clearer that it's an empty state component. Otherwise LGTM :)

2020-09-16 20:11 UTC, ssilvert reviewed
We have adopted CamelCase convention for ts and tsx files.

`empty-list.tsx` file should be named `EmptyList.tsx`

2020-09-16 20:11 UTC, ssilvert commented on src/components/empty-list/empty-list.tsx
> +  primaryAction: any;
We want to avoid using `any`
```suggestion
  primaryAction: (event: React.MouseEvent<HTMLButtonElement>) => void;
```

2020-09-17 09:25 UTC, edewit requested changes
A cool new feature of this new storybook is to add meta data so you can play with the attributes of a component like this:
```javascript
import React from "react";
import { Meta, Story } from "@storybook/react";
import { Page } from "@patternfly/react-core";
import { EmptyList, EmptyListProps } from "../components/empty-list/empty-list";

export default {
  title: "Empty list",
  component: EmptyList,
} as Meta;

const Template: Story<EmptyListProps> = (args) => (
  <Page>
  <EmptyList {...args} />
  </Page>
);

export const View = Template.bind({});
View.args = {
  message:"No things",
  instructions:"You haven't created any things for this list.",
  primaryActionText:"Add a thing"
};
```
![storybook](https://user-images.githubusercontent.com/51133/93452209-718e5880-f8d8-11ea-98b6-5aeb12afa5ce.gif)

2020-09-17 09:25 UTC, edewit commented on src/components/empty-list/empty-list.tsx
> +  primaryAction: any;
Also I would recommend to name actions "on(action name)" so in this case `onPrimaryAction` that way you can also try them out in storybook
```suggestion
  onPrimaryAction: MouseEventHandler<HTMLButtonElement>;
```

2020-09-17 09:26 UTC, edewit commented
also rename the file `EmptyList.tsx`

2020-09-17 15:17 UTC, ssilvert commented
> A cool new feature of this new storybook is to add meta data so you can play with the attributes of a component like this:

That is cool indeed.  Gives a good reason for using storybook.

2020-09-18 17:44 UTC, srambach commented
Thank you @jenny-s51, @edewit, and @ssilvert for your helpful comments! I've updated everything and added a test, which is new to me so please let me know if that's ok or not.

2020-09-18 18:08 UTC, ssilvert approved these changes

2020-09-18 18:16 UTC, jenny-s51 approved these changes
LGTM 🚀

2020-09-19 18:05 UTC, merged