fixed breadcrumb for search and seach box distance
keycloak/keycloak-admin-ui pull request #998
Opened 2021-08-12 07:29 UTC by edewit

fixes: #692

2021-08-12 08:55 UTC, jonkoops requested changes

2021-08-12 08:55 UTC, jonkoops commented on src/components/bread-crumb/GroupBreadCrumbs.tsx
>              <BreadcrumbItem key={i} isActive={subGroups.length - 1 === i}>
Perhaps we can use the group id for the key instead?
```suggestion
            <BreadcrumbItem key={group.id} isActive={subGroups.length - 1 === i}>
```

2021-08-12 08:55 UTC, jonkoops commented on src/components/bread-crumb/GroupBreadCrumbs.tsx
>              <BreadcrumbItem key={i} isActive={subGroups.length - 1 === i}>
I think we can use the `isLastGroup()` function here as well.
```suggestion
            <BreadcrumbItem key={i} isActive={isLastGroup(i)}>
```

2021-08-12 08:55 UTC, jonkoops commented on src/components/bread-crumb/GroupBreadCrumbs.tsx
> +              {isLastGroup(i) && group.id === "search" && <>{group.name}</>}
There is no need to use a fragment here, as a string is also a valid JSX element. We can also use a ternary operation to reduce the amount of calls to `isLastGroup()`.

```suggestion
              {isLastGroup(i) &&
                (group.id === "search" ? group.name : t("groups:groupDetails"))}
```

2021-08-12 08:55 UTC, jonkoops commented on src/components/bread-crumb/GroupBreadCrumbs.tsx
> +  const isLastGroup = (index: number) => subGroups.length - 1 === index;
Instead of defining a function which we have to call every time we need a result, we can also define a variable in the function body of the `map()` over the subgroups to get the value once.

```tsx
{subGroups.map((group, i) => {
  const isLastGroup = i === subGroups.length - 1;

  return (
    <BreadcrumbItem key={group.id} isActive={isLastGroup}>
      ...
    </BreadcrumbItem>
  );
})}
```

2021-08-12 08:55 UTC, jonkoops commented on src/groups/SearchGroups.tsx
> +        to={`/${realm}/groups/search/${group.link}`}
Any chance we could use one of the link functions from the route definition here?

2021-08-12 08:55 UTC, jonkoops commented on src/groups/SearchGroups.tsx
> +          setSubGroups([{ name: t("searchGroups"), id: "search" }, group])
Interesting, we're setting an internal state that is derived from the URL state as well? Can't we only derive this state from the path entirely?

2021-08-12 08:55 UTC, jonkoops commented on src/groups/SearchGroups.tsx
> +            <>
Why do we need this fragment? Looks like there is only a single child element.

2021-08-12 09:31 UTC, edewit commented on src/groups/SearchGroups.tsx
> +            <>
otherwise it doesn't work, I don't know why

2021-08-12 09:41 UTC, edewit commented on src/groups/SearchGroups.tsx
> +          setSubGroups([{ name: t("searchGroups"), id: "search" }, group])
we could if we had a way to put the group name and it's ID on the url.

2021-08-12 09:51 UTC, edewit commented on src/groups/SearchGroups.tsx
> +        to={`/${realm}/groups/search/${group.link}`}
don't see how to do that quickly

2021-08-12 11:16 UTC, jonkoops commented on src/groups/SearchGroups.tsx
> +        to={`/${realm}/groups/search/${group.link}`}
Let's skip it for now then.

2021-08-12 11:16 UTC, jonkoops commented on src/groups/SearchGroups.tsx
> +          setSubGroups([{ name: t("searchGroups"), id: "search" }, group])
Yeah, this seems like an improvement we can do at a later point.

2021-08-12 11:20 UTC, jonkoops requested changes

2021-08-12 11:20 UTC, jonkoops commented on src/components/bread-crumb/GroupBreadCrumbs.tsx
> +              <BreadcrumbItem key={i} isActive={isLastGroup}>
Can we use the group id here for the key prop?
```suggestion
              <BreadcrumbItem key={group.id} isActive={isLastGroup}>
```

2021-08-16 08:19 UTC, yih-wang requested changes
1. Enter (on keyboard) doesn't work when I want to trigger the search
2. The search bar and the chips are next to each other. I think there should be an 8px (or around) space between them. I haven't found a code example in Patternfly, only a screenshot in the guidelines like this 
![image](https://user-images.githubusercontent.com/23331885/129533076-a7447dfd-c0ff-48df-afa2-7d47c16eea52.png)
3. The search bar should be left-aligned with the header (like the main page of the Groups)

2021-08-16 12:23 UTC, yih-wang approved these changes
LGTM

2021-08-16 12:35 UTC, jonkoops approved these changes

2021-08-16 12:35 UTC, merged